// Guard suite for the A2.2 Wortliste migration (Course Factory Wave 5, PR B).
// Mirrors tests/a2-1-wortliste.test.mjs (Wave 4 PR B / #84).
//
// migrations/2026-09-06-a2-2-wortliste.sql is generated by
// scripts/words-from-json.mjs from the reviewed addition/fix JSON — the same
// generic script behind the A1.1 (#69), A1.2 (#73) and A2.1 (#84) Wortliste migrations.
// This test parses the GENERATED SQL (not the source JSON) so a hand-edit that
// breaks the re-run contract — an INSERT missing its WHERE NOT EXISTS guard,
// an UPDATE missing its IS NOT DISTINCT FROM guard, a plural regression back
// to the literal string "null" — fails here even if the JSON inputs stay
// clean. It also pins VOCAB_WORD_COUNT against the new total (see
// tests/a1-1-wortliste.test.mjs for the article/plural display bug guard,
// which is level-agnostic and not repeated here).
//
// A2.2-specific: the fixes include 152 rows whose headword carried its own
// article ("der Bahnhof" + article "der"), 60 plurals carrying an article
// ("die Bahnhöfe") and 15 literal "null" plurals; the guards at the bottom pin
// that no INSERT or UPDATE re-introduces any of those shapes — the additions
// author's first draft wrote 85 plurals WITH the article, which is why the
// INSERT-plural guard exists here and not in the A2.1 twin.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { VOCAB_WORD_COUNT } from '../src/data/marketing.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const MIGRATION = 'migrations/2026-09-06-a2-2-wortliste.sql';

const sql = readFileSync(join(ROOT, MIGRATION), 'utf8');

// Statement blocks (string literals in the data can contain commas but never
// a bare ";" — see tests/a1-1-wortliste.test.mjs).
const insertBlocks = [...sql.matchAll(/INSERT INTO public\.words[\s\S]*?\n\);/g)].map((m) => m[0]);
const updateBlocks = [...sql.matchAll(/UPDATE public\.words SET[\s\S]*?;/g)].map((m) => m[0]);

test('the migration has exactly 171 INSERT statements', () => {
  assert.equal(insertBlocks.length, 171);
});

test('every INSERT targets level a2.2', () => {
  for (const block of insertBlocks) {
    assert.match(block, /SELECT 'a2\.2',/, `INSERT missing/wrong level literal:\n${block}`);
    assert.match(block, /AND level = 'a2\.2'/, `INSERT's guard missing level = 'a2.2':\n${block}`);
  }
});

test('no INSERT or UPDATE writes the literal string "null" as a value', () => {
  for (const block of insertBlocks) {
    assert.ok(!block.includes("'null'"), `INSERT carries the literal string 'null':\n${block}`);
  }
  for (const block of updateBlocks) {
    // Only the SET side: five fixes legitimately quote 'null' in their
    // IS NOT DISTINCT FROM guard because that IS the defect being repaired.
    const setSide = block.slice(0, block.indexOf('\nWHERE id ='));
    assert.ok(!setSide.includes("'null'"), `UPDATE writes the literal string 'null':\n${block}`);
  }
});

test('every INSERT is guarded by WHERE NOT EXISTS on (german, level, category)', () => {
  for (const block of insertBlocks) {
    assert.match(
      block,
      /WHERE NOT EXISTS \(\s*SELECT 1 FROM public\.words WHERE german = '.*?' AND level = 'a2\.2' AND category = '.*?'\s*\)/,
      `INSERT missing a proper WHERE NOT EXISTS guard:\n${block}`,
    );
  }
});

test('the migration has exactly 271 UPDATE statements', () => {
  assert.equal(updateBlocks.length, 271);
});

test('every UPDATE is guarded by an IS NOT DISTINCT FROM on the old value', () => {
  for (const block of updateBlocks) {
    assert.match(
      block,
      /WHERE id = '[0-9a-f-]{36}'::uuid AND \w+ IS NOT DISTINCT FROM /,
      `UPDATE missing an IS NOT DISTINCT FROM guard:\n${block}`,
    );
  }
});

test('no UPDATE writes an article-prefixed headword or plural', () => {
  // The whole point of 212 of the 271 fixes; a regenerated file that put the
  // article back would pass every structural guard above and still ship the
  // display bug ("der der Bahnhof") that tests/a1-1-wortliste.test.mjs describes.
  for (const block of updateBlocks) {
    const m = block.match(/SET (german|plural) = '((?:der|die|das) [^']*)'/);
    assert.equal(m, null, `UPDATE writes an article-prefixed value:\n${block}`);
  }
});

test('no INSERT bakes the article into the headword', () => {
  for (const block of insertBlocks) {
    const m = block.match(/SELECT 'a2\.2', '(?:der|die|das) /);
    assert.equal(m, null, `INSERT headword starts with an article:\n${block}`);
  }
});

test('no INSERT bakes the article into the plural', () => {
  // The additions author's first draft wrote 85 plurals as "die Charaktere" —
  // the exact defect class the fixes half of this migration removes.
  for (const block of insertBlocks) {
    const m = block.match(/'(?:der|die|das) [^']*'/g) || [];
    // the headword guard above already covers position 1; any remaining
    // article-prefixed literal in the VALUES is the plural
    const offenders = m.filter((lit) => !block.includes(`SELECT 'a2.2', ${lit}`));
    assert.equal(offenders.length, 0, `INSERT plural starts with an article: ${offenders.join(', ')}\n${block}`);
  }
});

test('the migration is wrapped in BEGIN/COMMIT', () => {
  assert.match(sql, /^BEGIN;/m);
  assert.match(sql, /^COMMIT;/m);
});

test('every addition category from the source JSON appears in the migration', () => {
  // Pinned literally (not re-read from the review scratchpad, which is
  // ephemeral) so a category typo in a future regeneration is caught even if
  // the JSON that produced it is gone.
  const categories = [
    'Personality & Character',
    'Transport & Travel Problems',
    'Learning & Exams',
    'Housing & Neighbours',
    'Household Chores',
    'Kitchen & Cooking',
    'Shopping & Payment',
    'Emergencies & Safety',
  ];
  for (const cat of categories) {
    assert.ok(sql.includes(`'${cat}'`), `Migration is missing category "${cat}"`);
  }
});

test('VOCAB_WORD_COUNT is the live 2390 plus this migration\'s 171 additions', () => {
  assert.equal(VOCAB_WORD_COUNT, 2390 + 171);
});
