// public/llms.txt and public/llms-full.txt are GENERATED by scripts/build-llms.mjs
// from pricing.js, marketing.js, the Leitfaden and exam registries and the grammar
// cache. Hand-typed, they had drifted to 64 of 84 topics, 4 of 8 guides, no exam
// hubs and no one-time courses. This pins "regenerate after a data change".
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { renderShort, renderFull } from '../scripts/build-llms.mjs';
import { GUIDES } from '../astro-site/src/data/guides/index.js';
import { EXAM_HUBS } from '../astro-site/src/data/exams/index.js';
import { GRAMMAR_TOPIC_COUNT } from '../src/data/marketing.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = (f) => readFileSync(join(ROOT, f), 'utf8');

test('committed llms files equal the generator output (run node scripts/build-llms.mjs)', () => {
  assert.equal(read('public/llms.txt'), renderShort(), 'public/llms.txt is stale');
  assert.equal(read('public/llms-full.txt'), renderFull(), 'public/llms-full.txt is stale');
});

test('llms-full lists every grammar topic, guide and exam hub', () => {
  const full = renderFull();
  const topicLinks = full.match(/https:\/\/deutsch-meister\.de\/grammar\/[ab]\d\.\d\/[\w-]+\//g) ?? [];
  assert.equal(new Set(topicLinks).size, GRAMMAR_TOPIC_COUNT);
  for (const g of GUIDES) assert.ok(full.includes(`/leitfaden/${g.slug}/`), `guide ${g.slug} missing`);
  for (const h of EXAM_HUBS) assert.ok(full.includes(`/pruefung/${h.slug}/`), `exam hub ${h.slug} missing`);
});
