// Guard suite for scripts/rule-card-overrides.mjs.
//
// The override file replaces generated rule cards WHOLE: the builder merges each
// entry over the card of the same slug, so a missing key does not fall through to
// the generated value, it disappears from the text
// `netlify/functions/explain-answer.mjs` puts in the prompt. That is the failure
// this suite exists for — it compares the shape of every override against the
// COMMITTED netlify/functions/_shared/ruleCards.mjs, which is the generated
// artefact the override has to stand in for.
//
// The content rules come from the second DaF review
// (docs/course-factory/a11-rebuild/REVIEW-daf-2-2026-09-12.md §D):
//   * no sound comparison to English ("sounds like", "like English") — that
//     framing is what the review rejected on `alphabet-pronunciation`, and the
//     item pool was already cleaned of it;
//   * no percentage sign — the unsourced genus split on `nouns-gender` is a
//     measure-before-you-claim violation, so the character is banned outright;
//   * no ordinal number anywhere on `time-and-dates` — the course defers the
//     date with ordinals to A1.2 in writing, and the generated card was the only
//     place in the repo that taught it anyway. Naming the deferral ("Das Datum
//     mit Ordnungszahlen kommt erst in A1.2") is allowed; an ordinal FORM is not;
//   * at most 120 German words in the main rule, because the card is read by a
//     learner who has just failed an item. The English support line is excluded
//     from that count — it is deliberately English, one line per card, and
//     required to exist so the L1 support is consistent rather than accidental.
//
// SINCE 2026-09-13 THE SUITE IS LEVEL-AGNOSTIC. It ran over the twelve A1.1
// slugs; A1.2 arrived as a validated curriculum draft with twelve more, and a
// per-level test list is exactly how the A1.1 cards stayed half pre-rebuild for
// four review rounds. Every content test now iterates the primary slugs of ALL
// curricula (`ALL_CURRICULA`, live and draft), so a new level's cards meet the
// same bar the day its curriculum lands. Two things are necessarily
// level-relative and are computed per curriculum: the cumulative Wortfeld a card
// may draw its examples from (a level inherits every earlier level's Wortfeld in
// full, plus its own up to that Lektion), and where the GENERATED card the
// override stands in for is found — `netlify/functions/_shared/ruleCards.mjs` is
// generated for a1.1 only, so for every other level the slug is checked against
// the `grammar-content-cache.json` rows that `build-lesson-pool.mjs <level>`
// will read. The remaining A1.1-specific tests (alphabet, nouns-gender, the
// clock, yes/no) stay named and single-slug: they pin findings of a particular
// review, not a rule of the genre.

import { readFileSync } from 'node:fs';
import { test } from 'node:test';
import assert from 'node:assert/strict';

import OVERRIDES, { RULE_CARD_OVERRIDE_SLUGS } from '../scripts/rule-card-overrides.mjs';
import { RULE_CARDS } from '../netlify/functions/_shared/ruleCards.mjs';
import { ALL_CURRICULA } from '../src/data/curricula/index.js';
import {
  META_NOUNS,
  CONSTRUCTION_PATTERNS,
  isMetaNoun,
  introducedAt as introducedIn,
} from '../src/data/curricula/constructions.js';

/** Level keys in course order — 'a1.1' before 'a1.2'; a later level inherits the earlier lexis. */
const LEVELS = Object.keys(ALL_CURRICULA).sort();

/** Every primary slug of every curriculum, with the level and Lektion it belongs to. */
const PRIMARIES = LEVELS.flatMap((level) =>
  ALL_CURRICULA[level].lektionen.map((l) => ({ level, nr: l.nr, slug: l.primarySlug })),
);
const PRIMARY_OF = new Map(PRIMARIES.map((p) => [p.slug, p]));
const ALL_PRIMARY_SLUGS = PRIMARIES.map((p) => p.slug);

/**
 * The generated cards an override has to stand in for. a1.1 has them committed
 * (`ruleCards.mjs`, generated by `build-lesson-pool.mjs a1.1`); every other level
 * does not yet, so its slugs are checked against the cache rows the generator
 * reads — `grammar-content-cache.json`, `topics.sub_level`. That is the same
 * source, one step earlier, and it is a real check rather than a skip.
 */
const CACHE = JSON.parse(readFileSync(new URL('../grammar-content-cache.json', import.meta.url), 'utf8'));
const cacheSlugsFor = (level) =>
  new Set(
    (CACHE.topics || [])
      .filter((t) => String(t.sub_level || '').toLowerCase() === level)
      .map((t) => String(t.slug || '').toLowerCase()),
  );
const CACHE_SLUGS = new Map(LEVELS.map((level) => [level, cacheSlugsFor(level)]));

/** The shape `writeRuleCards()` emits for every card (see scripts/build-lesson-pool.mjs). */
const CARD_SHAPE = ['commonMistakes', 'content', 'titleDe'];

const MAX_GERMAN_WORDS = 120;
const ENGLISH_LINE = /^English:/;

const germanWords = (content) =>
  content
    .split('\n')
    .filter((line) => !ENGLISH_LINE.test(line.trim()))
    .join(' ')
    .split(/\s+/)
    .filter(Boolean);

const sortedKeys = (obj) => Object.keys(obj).sort();

test('the exported slug list matches the override map', () => {
  assert.deepEqual(RULE_CARD_OVERRIDE_SLUGS, Object.keys(OVERRIDES));
  assert.ok(RULE_CARD_OVERRIDE_SLUGS.length > 0, 'no overrides declared');
});

test('every override replaces a slug that the generated cards actually carry', () => {
  for (const slug of RULE_CARD_OVERRIDE_SLUGS) {
    assert.equal(slug, slug.toLowerCase(), `${slug} must be lowercase: ruleCard() lowercases the lookup`);
    const level = (PRIMARY_OF.get(slug) || {}).level;
    assert.ok(level, `${slug} is not the primary slug of any Lektion — nothing would open this card`);
    if (Object.prototype.hasOwnProperty.call(RULE_CARDS, slug)) continue;
    // No generated card committed for this level yet (ruleCards.mjs is built for
    // a1.1 only). The slug must then exist in the cache the generator reads, or
    // the merge in writeRuleCards() would drop the override silently.
    assert.ok(
      CACHE_SLUGS.get(level).has(slug),
      `${slug} is neither a generated rule card nor a ${level.toUpperCase()} topic in grammar-content-cache.json — an override for it would never be merged`,
    );
  }
});

test('every override has exactly the keys of the generated card it replaces', () => {
  for (const card of Object.values(RULE_CARDS)) {
    assert.deepEqual(sortedKeys(card), CARD_SHAPE, 'the generated card shape moved — CARD_SHAPE is stale');
  }
  for (const slug of RULE_CARD_OVERRIDE_SLUGS) {
    assert.deepEqual(
      sortedKeys(OVERRIDES[slug]),
      RULE_CARDS[slug] ? sortedKeys(RULE_CARDS[slug]) : CARD_SHAPE,
      `${slug}: override keys diverge from the generated card`,
    );
  }
});

test('commonMistakes entries have the generated mistake shape', () => {
  const shape = ['correct', 'explanationDe', 'wrong'];
  for (const slug of RULE_CARD_OVERRIDE_SLUGS) {
    const mistakes = OVERRIDES[slug].commonMistakes;
    assert.ok(Array.isArray(mistakes), `${slug}: commonMistakes must be an array`);
    for (const [i, mistake] of mistakes.entries()) {
      assert.deepEqual(sortedKeys(mistake), shape, `${slug}: commonMistakes[${i}] has the wrong keys`);
      for (const key of shape) {
        assert.ok(mistake[key].trim().length > 0, `${slug}: commonMistakes[${i}].${key} is empty`);
      }
    }
  }
});

test('titleDe and content are non-empty German strings', () => {
  for (const slug of RULE_CARD_OVERRIDE_SLUGS) {
    const card = OVERRIDES[slug];
    assert.equal(typeof card.titleDe, 'string');
    assert.equal(typeof card.content, 'string');
    assert.ok(card.titleDe.trim().length > 0, `${slug}: titleDe is empty`);
    assert.ok(card.content.trim().length > 0, `${slug}: content is empty`);
  }
});

test('the main rule stays under the German word budget', () => {
  for (const slug of RULE_CARD_OVERRIDE_SLUGS) {
    const words = germanWords(OVERRIDES[slug].content);
    assert.ok(
      words.length <= MAX_GERMAN_WORDS,
      `${slug}: ${words.length} German words in content, budget is ${MAX_GERMAN_WORDS}`,
    );
  }
});

test('each card carries exactly one short English support line', () => {
  for (const slug of RULE_CARD_OVERRIDE_SLUGS) {
    const lines = OVERRIDES[slug].content.split('\n').map((l) => l.trim());
    const english = lines.filter((l) => ENGLISH_LINE.test(l));
    assert.equal(english.length, 1, `${slug}: expected one "English:" support line, found ${english.length}`);
    assert.ok(
      english[0].split(/\s+/).length <= 25,
      `${slug}: the English support line is a line, not a paragraph`,
    );
  }
});

test('no card compares German sounds to English', () => {
  const banned = [/sounds?\s+like/i, /like\s+English/i, /English\s+(Example|Sound)/i, /klingt\s+wie/i];
  for (const slug of RULE_CARD_OVERRIDE_SLUGS) {
    const card = OVERRIDES[slug];
    const haystack = [
      card.titleDe,
      card.content,
      ...card.commonMistakes.flatMap((m) => [m.wrong, m.correct, m.explanationDe]),
    ].join('\n');
    for (const pattern of banned) {
      assert.ok(!pattern.test(haystack), `${slug}: banned sound comparison ${pattern}`);
    }
  }
});

test('no card states a percentage', () => {
  for (const slug of RULE_CARD_OVERRIDE_SLUGS) {
    const card = OVERRIDES[slug];
    const haystack = [
      card.titleDe,
      card.content,
      ...card.commonMistakes.flatMap((m) => [m.wrong, m.correct, m.explanationDe]),
    ].join('\n');
    assert.ok(!haystack.includes('%'), `${slug}: a percentage has no source on an A1 rule card`);
    assert.ok(!/\bProzent\b/i.test(haystack), `${slug}: a percentage has no source on an A1 rule card`);
  }
});

test('nouns-gender teaches the gender-predicting endings instead of a share table', () => {
  const card = OVERRIDES['nouns-gender'];
  for (const ending of ['-ung', '-heit', '-keit', '-schaft', '-chen', '-lein', '-er']) {
    assert.ok(card.content.includes(ending), `nouns-gender: the ${ending} rule is missing`);
  }
});

test('time-and-dates carries the clock but no ordinal form', () => {
  const card = OVERRIDES['time-and-dates'];
  const haystack = [
    card.titleDe,
    card.content,
    ...card.commonMistakes.flatMap((m) => [m.wrong, m.correct, m.explanationDe]),
  ].join('\n');

  // Ordinal WORD forms (am fünften Mai) and ordinal DIGIT forms (am 5. Mai).
  const ordinalWord =
    /\b(erst|zweit|dritt|viert|fünft|sechst|siebt|acht|neunt|zehnt|elft|zwölft|zwanzigst|dreißigst)(e|en|er|es|em)\b/i;
  // A standalone "5." — the leading (^|\s) keeps clock times like 9:30. out of it.
  const ordinalDigit = /(?:^|\s)\d{1,2}\.(?=\s|$)/m;
  assert.ok(!ordinalWord.test(haystack), 'time-and-dates must not teach an ordinal form (A1.2)');
  assert.ok(!ordinalDigit.test(haystack), 'time-and-dates must not teach an ordinal date (A1.2)');

  // …but it must say the deferral out loud, and it must be about the clock.
  assert.match(card.content, /A1\.2/, 'time-and-dates must name the A1.2 deferral');
  assert.match(card.content, /acht Uhr dreißig/, 'time-and-dates must carry the official time');
  assert.match(card.content, /halb neun/, 'time-and-dates must carry the everyday time');
  assert.match(card.content, /Viertel nach/, 'time-and-dates must carry Viertel nach');
  assert.match(card.content, /Viertel vor/, 'time-and-dates must carry Viertel vor');
  for (const preposition of [/\bum\b/, /\bam\b/, /\bim\b/]) {
    assert.match(card.content, preposition, `time-and-dates must explain ${preposition}`);
  }

  const mistakes = card.commonMistakes.map((m) => `${m.wrong} ${m.correct} ${m.explanationDe}`).join('\n');
  assert.match(mistakes, /halb neun = 8:30, nicht 9:30/, 'the halb-neun mistake is pinned by the review');
  assert.match(mistakes, /um Montag → am Montag/, 'the um/am mistake is pinned by the review');
});

test('alphabet-pronunciation names the German letters', () => {
  const card = OVERRIDES['alphabet-pronunciation'];
  const names = [
    'A a',
    'B be',
    'C ce',
    'Q ku',
    'V Vau',
    'X ix',
    'Y Ypsilon',
    'Z Zett',
    'Ä a-Umlaut',
    'Ö o-Umlaut',
    'Ü u-Umlaut',
    'ß Eszett',
  ];
  for (const name of names) {
    assert.ok(card.content.includes(name), `alphabet-pronunciation: letter name "${name}" is missing`);
  }

  // Review #3 BLOCKER 3: the first version of this card spelled the names as
  // sound respellings ("C tse", "X iks", "Z tset"). A letter NAME is a word, not
  // a pronunciation hint, and the Lektion-1 items accept only the word.
  assert.ok(
    !/\b(tse|tset|iks)\b/.test(card.content),
    'alphabet-pronunciation: a sound respelling is back in the letter table',
  );
  assert.ok(!card.content.includes('Y ypsilon'), 'alphabet-pronunciation: Ypsilon is a name, capitalised');
  assert.ok(!card.content.includes('V vau'), 'alphabet-pronunciation: Vau is a name, capitalised');
  assert.match(card.content, /Wie schreibt man das\?/, 'the card must show how to ask for a spelling');
  assert.match(card.content, /A-N-A/, 'the card must show a spelled-out name');

  // 4–6 spelling examples drawn from the Lektion 1/2 Wortfeld.
  const examples = ['Chakiri', 'Ana', 'Tschüss', 'Entschuldigung', 'Vorname'];
  const present = examples.filter((word) => card.content.includes(word));
  assert.ok(present.length >= 4, `alphabet-pronunciation: only ${present.length} Lektion examples`);
  assert.ok(present.length <= 6, 'alphabet-pronunciation: keep the example list short');
});

// Review #3 BLOCKER 3: the card and the items of the SAME free Lektion disagreed
// on the letter names — the card taught "Z tset", the item accepted only "Zett",
// so a learner who read the explanation and followed it was marked wrong. This
// reads the shipped pools and pins the agreement rather than a hand-typed list.
const poolItems = (file) => {
  const parsed = JSON.parse(readFileSync(new URL(`../src/data/lessonPools/${file}`, import.meta.url), 'utf8'));
  return Array.isArray(parsed) ? parsed : parsed.items || [];
};

const LETTER_ITEM_RE = /Buchstabe\s+(\S+)\s+(?:auf Deutsch\?|heißt)/;

test('alphabet-pronunciation agrees with the letter names the Lektion 1 items accept', () => {
  const card = OVERRIDES['alphabet-pronunciation'];
  const items = [...poolItems('a11.json'), ...poolItems('a11.extra.json')].filter(
    (item) => item.topic === 'alphabet-pronunciation' && LETTER_ITEM_RE.test(item.questionDe || ''),
  );
  assert.ok(items.length > 0, 'no letter-name items found — the pin would be vacuous');

  for (const item of items) {
    const letter = LETTER_ITEM_RE.exec(item.questionDe)[1];
    const pair = `${letter} ${item.answer}`;
    assert.ok(
      card.content.includes(pair),
      `alphabet-pronunciation: item ${item.id} accepts "${item.answer}" for ${letter}, the card does not say "${pair}"`,
    );
  }

  const zMistake = card.commonMistakes.find((m) => /Buchstabe Z/.test(m.correct));
  assert.ok(zMistake, 'alphabet-pronunciation: the Z mistake is pinned by review #3');
  assert.match(zMistake.correct, /Zett/, 'the Z mistake must give the name the item accepts');
  assert.ok(
    !/tset/.test(`${zMistake.wrong} ${zMistake.correct} ${zMistake.explanationDe}`),
    'the Z mistake must not offer the respelling as an answer',
  );
});

// Review #3 MAJOR 1: "-er bei Personen → der" is refuted by the course itself —
// die Mutter, die Schwester and die Tochter are taught in Lektion 3.
test('nouns-gender does not claim -er marks every person noun as masculine', () => {
  const card = OVERRIDES['nouns-gender'];
  assert.ok(!/-er bei Personen/.test(card.content), 'nouns-gender: the refuted -er rule is back');
  for (const exception of ['die Mutter', 'die Schwester']) {
    assert.ok(card.content.includes(exception), `nouns-gender: the L3 counter-example ${exception} is missing`);
  }
  const mistakes = card.commonMistakes.map((m) => `${m.wrong} ${m.correct} ${m.explanationDe}`).join('\n');
  assert.ok(
    !/Personen auf -er sind der-Wörter/.test(mistakes),
    'nouns-gender: commonMistakes still teaches the refuted -er rule',
  );
});

test('yes-no-questions names the written-question rule and admits the spoken form', () => {
  const first = OVERRIDES['yes-no-questions'].commonMistakes[0];
  assert.match(
    first.explanationDe,
    /In der geschriebenen Frage steht das Verb auf Platz 1/,
    'commonMistakes[0] must state the written rule in those words',
  );
  assert.match(
    first.explanationDe,
    /[Gg]esprochen/,
    'commonMistakes[0] must acknowledge the spoken intonation question',
  );
});

// ─────────────────────────────────────────────────────────────────────────────
// REVIEW #4 (docs/course-factory/a11-rebuild/REVIEW-daf-4-2026-09-12.md, MAJOR 1
// and MAJOR 2). Round 3 overrode the four cards the review had named and left
// eight standing, seven of them the half-English pre-rebuild tables — the exact
// mechanism this repo has been rebuked for four rounds running: the finding is
// closed for the instances that were listed and stays open as a class. These
// four tests close it as a class: they run over EVERY slug that ANY curriculum
// marks primary (A1.1 and, since 2026-09-13, the A1.2 draft), so a thirteenth
// Lektion, a new level or a re-generated card cannot quietly arrive without an
// override that meets the same bar.
//
//   (a) every card carries at least two commonMistakes — `definite-articles`
//       shipped with an empty array, i.e. half the card was missing for L5;
//   (b) no English outside the single `English:` support line, measured with
//       `hasEnglish()` from src/data/lessonPools/quality.js — the same predicate
//       that gates the exercise pool, so card and item are held to one rule;
//   (c) no du-register anywhere (review #4 MAJOR 2: tasks and explanations use
//       Sie or impersonal `man`; only the dialogue duzt);
//   (d) every example noun stands in the Wortfeld the course has taught BY that
//       Lektion — the review's "die Karten reden über einen anderen Kurs".

import { DIALOG_NAMES as DIALOG_NAMES_A11 } from '../src/data/curricula/a11.js';
import { DIALOG_NAMES as DIALOG_NAMES_A12 } from '../src/data/curricula/a12.js';
// The FUNCTION_WORDS list itself is deliberately NOT imported any more (DaF review #10, MAJOR 3):
// it is a RULE 5 licence for dialogue INPUT, not a licence for what a rule card may teach. What the
// card guards may treat as free is the measured subset, and it lives with the lexicon that uses it.
import { FUNCTION_WORDS_FREE } from '../scripts/validate-curriculum.mjs';
// …and the levels' own lists, for ONE question only: „is this form a function word
// at all?“ — which is what tells a grammar-bearing determiner apart from a content
// word in guard (e) below. It is never again used as a licence.
import { FUNCTION_WORDS as FUNCTION_WORDS_A11 } from '../src/data/curricula/a11.js';
import { FUNCTION_WORDS as FUNCTION_WORDS_A12 } from '../src/data/curricula/a12.js';
import {
  hasEnglish,
  NEXT_LEVEL_RE,
  UNTAUGHT_ANSWER_FORMS,
} from '../src/data/lessonPools/quality.js';

const cardOf = (slug) => OVERRIDES[slug];
const contentLines = (card) => card.content.split('\n').map((l) => l.trim()).filter(Boolean);
const germanLines = (card) => contentLines(card).filter((l) => !ENGLISH_LINE.test(l));
const mistakeFields = (card) => card.commonMistakes.flatMap((m) => [m.wrong, m.correct, m.explanationDe]);

/** "a1.2 perfekt-intro (Lektion 12)" — every failure says which course it is about. */
const where = ({ level, slug, nr }) => `${level} ${slug} (Lektion ${nr})`;

test('every primary slug of every curriculum carries an override', () => {
  for (const level of LEVELS) {
    const slugs = ALL_CURRICULA[level].lektionen.map((l) => l.primarySlug);
    assert.equal(slugs.length, 12, `${level}: a rebuilt course has twelve Lektionen, each with one primary slug`);
    const missing = slugs.filter((slug) => !Object.prototype.hasOwnProperty.call(OVERRIDES, slug));
    assert.deepEqual(
      missing,
      [],
      `${level}: these primary slugs still ship the generated pre-rebuild card: ${missing.join(', ')}`,
    );
  }
  assert.equal(new Set(ALL_PRIMARY_SLUGS).size, ALL_PRIMARY_SLUGS.length, 'a slug is primary in one Lektion only');
});

// (a)
test('every card carries at least two commonMistakes', () => {
  for (const primary of PRIMARIES) {
    const mistakes = cardOf(primary.slug).commonMistakes;
    assert.ok(mistakes.length >= 2, `${where(primary)}: ${mistakes.length} commonMistakes — half the card is missing`);
  }
});

// (b)
// ONE collision, and it is not English: the German NAME of the letter W is
// *we*, and `ENGLISH_MARKERS` lists `we` as the English pronoun. The A1.1 L1 card
// has to spell the letter names out (that is the whole finding it answers), so the
// name is removed before the English check rather than the check being skipped.
const LETTER_NAME_COLLISION = /\bwe\b/gi;
const withoutLetterNames = (text) => String(text).replace(LETTER_NAME_COLLISION, ' ');

test('no card carries English outside its one English: support line', () => {
  for (const primary of PRIMARIES) {
    const card = cardOf(primary.slug);
    for (const line of germanLines(card)) {
      assert.ok(!hasEnglish(withoutLetterNames(line)), `${where(primary)}: English in a German content line — "${line}"`);
    }
    assert.ok(!hasEnglish(card.titleDe), `${where(primary)}: English in titleDe — "${card.titleDe}"`);
    for (const [i, field] of mistakeFields(card).entries()) {
      assert.ok(
        !hasEnglish(withoutLetterNames(field)),
        `${where(primary)}: English in commonMistakes field ${i} — "${field}"`,
      );
    }
  }
});

// (c) ── du-register.
//
// The banned forms are the ones review #4 quoted plus the du-imperatives the
// pool normaliser already removes. ONE exemption, deliberately narrow and
// mechanical: a PARADIGM LINE — a line that names the persons, i.e. one
// carrying both `ich` and `du` as standalone words ("ich bin, du bist, er ist",
// "ich komme, du kommst → Komm!"). There `du` and `dein` are the grammar being
// taught, not an address to the reader; anywhere else they are the register bug.
// Nothing weaker is allowed: a bare "Du bist müde." or "Antworte mit einem Satz"
// carries no `ich` and therefore fails.
const DU_REGISTER_RE = /\b(du|dir|dich|dein\w*|sagst|lerne|antworte|tippe|kannst)\b/i;
// A PERSONAL paradigm names the persons (`ich … du …`); a POSSESSIVE paradigm
// names the possessive articles (`mein … dein …`) and is the same thing one word
// class over — it is what A1.1 Lektion 12 and its notice TITLE are made of
// ("mein, dein, sein, ihr – Possessivartikel"), and a card whose title must equal
// its notice title cannot drop the `dein` out of that listing. Both forms are
// closed: two named forms on one line, never a bare `du`/`dein` addressed at the
// reader.
const isParadigmLine = (text) =>
  (/\bich\b/i.test(text) && /\bdu\b/i.test(text)) || (/\bmein\b/i.test(text) && /\bdein\b/i.test(text));

test('no card duzt outside a paradigm listing', () => {
  for (const primary of PRIMARIES) {
    const card = cardOf(primary.slug);
    const checked = [
      ['titleDe', card.titleDe],
      ...germanLines(card).map((line, i) => [`content line ${i + 1}`, line]),
      ...mistakeFields(card).map((field, i) => [`commonMistakes field ${i}`, field]),
    ];
    for (const [at, text] of checked) {
      if (isParadigmLine(text)) continue;
      const hit = DU_REGISTER_RE.exec(text);
      assert.equal(
        hit,
        null,
        `${where(primary)} ${at}: du-register "${hit && hit[0]}" outside a paradigm line — "${text}"`,
      );
    }
  }
});

// (d) ── example nouns against the cumulative Wortfeld.
//
// HOW A NOUN IS FOUND. German capitalises nouns, so a capitalised token that is
// NOT at the start of a sentence is a noun. "Start of a sentence" resets at the
// beginning of a line and after `.`, `?`, `!`, `:`, `—` or `→` — the colon
// matters because these cards are written as "Frage: Wie schreibt man das?", and
// the arrow because what follows one is a quoted FORM that starts its own
// sentence ("ich komme, du kommst → Komm!"). The arrow costs a little coverage —
// the one token after it is not checked against the Wortfeld — and the
// alternative was an open-ended allow-list of capitalised imperatives, which is
// the kind of list that quietly grows until it covers everything.
//
// HOW IT IS MATCHED. Against the `word` values of every Wortfeld entry the course
// has taught BY that Lektion — for a level after the first that means the WHOLE
// Wortfeld of every earlier level plus its own Lektion 1 … N — split into single
// words (so "Guten Tag" yields Tag and "Gäste einladen" yields Gäste). A token
// counts as covered when a Wortfeld form is a PREFIX of it (Buchstabe →
// Buchstaben, Heft → Hefte) or a SUFFIX of it (German compounds are head-final:
// Artikel → Possessivartikel). Umlaut plurals are deliberately NOT resolved —
// write "die Hefte", not "die Bücher", and the card stays inside the lexis it can
// point at.
//
// Everything a card may legitimately name beyond that lexis is listed below, by
// kind, and every list is closed.
// META_NOUNS, CONSTRUCTION_PATTERNS and isMetaNoun now live in
// `src/data/curricula/constructions.js` so that this guard and RULE 15b in
// `scripts/validate-curriculum.mjs` read ONE definition (DaF review #11, MAJOR 3).
// The list itself is unchanged; see that module for its per-entry history.

/** Letter NAMES, which the A1.1 L1 card must spell out — they are names, not lexis. */
const LETTER_NAMES = ['Jot', 'Vau', 'We', 'Ypsilon', 'Zett', 'Eszett', 'Umlaut', 'Zed'];

/** The polite Sie/Ihr paradigm, capitalised by rule rather than by word class. */
const POLITE_FORMS = ['Sie', 'Ihr', 'Ihre', 'Ihren', 'Ihrem', 'Ihnen'];

/** Proper nouns: people and places. Reuses the curricula's own lists. */
const PROPER_NAMES = [...DIALOG_NAMES_A11, ...DIALOG_NAMES_A12, 'Marokko', 'Schweiz', 'Meier'];

/**
 * The nouns-gender card demonstrates gender-PREDICTING ENDINGS. An ending is
 * shown on words that carry it, and A1.1's Wortfeld happens to contain exactly
 * one (-ung: die Entschuldigung). These five are the -heit/-keit/-schaft/-chen/
 * -lein demonstrations; they are the card's subject matter, not its situation.
 */
const GENDER_ENDING_EXAMPLES = ['Freiheit', 'Möglichkeit', 'Freundschaft', 'Mädchen', 'Brötchen'];

/**
 * Wortfeld words a card needs BEFORE the Lektion that teaches them. Kept to the
 * cases that exist: `im` governs month names, so the A1.1 L8 clock card cannot
 * state its own rule without naming a month, and A1.1 teaches Monat and Mai in
 * L12 — the A1.2 number card inherits the same pair for "der zwanzigste Mai".
 * Anything added here is a card reaching outside its own course-so-far and must
 * be argued, not assumed.
 */
const EARLY_USE = { 'time-and-dates': ['Monat', 'Mai', 'Datum'], 'numbers-counting': ['Mai'] };

const ALWAYS_ALLOWED = [...META_NOUNS, ...LETTER_NAMES, ...POLITE_FORMS, ...PROPER_NAMES, ...GENDER_ENDING_EXAMPLES];

const splitWords = (text) => String(text).split(/[^A-Za-zÄÖÜäöüß]+/).filter(Boolean);

/**
 * Every Wortfeld word the course has taught by Lektion `nr` of `level`: the full
 * Wortfeld of every earlier level, plus this level's Lektion 1 … nr. Lowercased
 * and split into single words.
 */
const cumulativeWortfeld = (level, nr) => {
  const forms = new Set();
  for (const lvl of LEVELS) {
    if (lvl > level) continue;
    for (const lektion of ALL_CURRICULA[lvl].lektionen) {
      if (lvl === level && lektion.nr > nr) continue;
      for (const entry of lektion.wortfeld) {
        for (const word of splitWords(entry.word)) forms.add(word.toLowerCase());
        // ROUND 18 (DaF review #17, MAJOR 2): a paired person noun whose Lektion is at its 25-slot
        // ceiling carries the masculine in its gloss — `die Marokkanerin` … `(m: der Marokkaner,
        // Pl. die Marokkaner)`. That form is taught on the Lektion's notice (tests/curricula.test.mjs
        // pins that every `(m: …)` gloss reaches an input surface), so a card may say it. Read
        // from the gloss, never typed: the licence ends where the gloss does.
        for (const m of String(entry.en || '').matchAll(/\(m:\s*(?:der|die|das)?\s*([A-Za-zÄÖÜäöüß]+)/g)) forms.add(m[1].toLowerCase());
      }
    }
  }
  return [...forms].filter((w) => w.length >= 3);
};

/** Capitalised tokens that are not sentence-initial — i.e. the nouns of the text. */
const nounTokens = (text) => {
  const found = [];
  let atSentenceStart = true;
  for (const token of String(text).split(/\s+/)) {
    const bare = token.replace(/^[^A-Za-zÄÖÜäöüß]+/, '').replace(/[^A-Za-zÄÖÜäöüß]+$/, '');
    if (bare && !atSentenceStart && /^[A-ZÄÖÜ][a-zäöüß]+$/.test(bare)) found.push(bare);
    if (bare) atSentenceStart = false;
    if (/[.?!:—→]$/.test(token)) atSentenceStart = true;
  }
  return found;
};

test('every example noun stands in the Wortfeld the course has taught by that Lektion', () => {
  for (const primary of PRIMARIES) {
    const forms = cumulativeWortfeld(primary.level, primary.nr);
    const allowed = new Set([...ALWAYS_ALLOWED, ...(EARLY_USE[primary.slug] || [])].map((w) => w.toLowerCase()));
    // Prefix/suffix matching applies to the allow-lists too: "Name" covers
    // "Namen", "Artikel" covers "Possessivartikel".
    const covered = (token) => {
      const low = token.toLowerCase();
      return [...allowed, ...forms].some((form) => low === form || low.startsWith(form) || low.endsWith(form));
    };

    const card = cardOf(primary.slug);
    const offenders = [...new Set(
      [...germanLines(card), ...mistakeFields(card)].flatMap(nounTokens).filter((t) => !covered(t)),
    )];
    assert.deepEqual(
      offenders,
      [],
      `${where(primary)}: nouns outside the Wortfeld taught by Lektion ${primary.nr}: ${offenders.join(', ')}`,
    );
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// ROUND 3 · THE A1.2 CARD CLASS
// (docs/course-factory/a12-rebuild/REVIEW-daf-2-2026-09-13.md, BLOCKER 2 and
// MAJOR 1/4/9/14.)
//
// WHAT WENT WRONG AND WHY A TEST IS THE ANSWER. Round 2 repaired the twelve A1.2
// `notice` texts and left the twelve cards at the round-1 state, so six of twelve
// cards contradicted their own Lektion: L3's card taught `keinen` while its notice
// defers that form to Lektion 4; L1's card carried "Neben der Apotheke ist die
// Bank", the line the review had just deleted from the dictation, plus a
// commonMistake built on it, and quoted "Danach kommt die Brücke", a line that no
// longer exists; L6's card said "Ihr Auge sieht gut" after the dialogue had been
// corrected to "sehen gut aus"; L10's card taught `gegen`, `um`, `teurer`,
// `größer` and `besser`, four forms its shortened notice had dropped and that
// occur nowhere in the Lektion. Every one of those is the same failure: an
// example sentence on the card that is nobody's line. The card is what
// `netlify/functions/explain-answer.mjs` hands a learner who is already stuck, so
// a sentence there that the Lektion never says is a second, divergent course.
//
// THE RULE THESE TESTS PIN. Four of them are round 3's; (e), at the bottom of
// the file, is round 10's answer to DaF review #9 MAJOR 5, which measured that
// (b) and (d) did not hold the class they were written for — (b) because the
// cumulative lexis carries the single letters of the alphabet Lektion and its
// matcher accepted any prefix or suffix, (d) because it can only guard a form
// some notice happened to write a deferral for. Both are rewritten below; the
// mutation tests at the end of the file break a card on purpose and watch each
// guard fire.
//   (a) EVERY EXAMPLE SENTENCE ON A CARD IS A LINE OF ITS OWN LEKTION. An example
//       sentence is a segment that ends in . ! or ?, carries at least three words
//       and a verb, and is not metalanguage (see META_SENTENCE below). It must
//       appear VERBATIM among that Lektion's dialogue lines, notice body, notice
//       examples, pretest model, or schreiben sample — or be listed in
//       EXAMPLE_ALLOW with a reason.
//   (b) NO WORD FROM OUTSIDE THE COURSE-SO-FAR. The noun check above is extended
//       to every token: a card may use the cumulative Wortfeld, the curricula's
//       own FUNCTION_WORDS, the metalanguage lists, and any word that the
//       Lektionen up to and including its own actually use.
//   (c) EVERY FORM THE NOTICE PUTS IN BOLD APPEARS ON THE CARD — the notice's
//       bold spans ARE the teaching points, so a card that omits one teaches less
//       than its Lektion.
//   (d) NO FORM THE NOTICE EXPLICITLY DEFERS IS TAUGHT. A notice that says
//       "… kommt in Lektion 4" or "… folgt in A1.2" has withdrawn that form; the
//       card may name the deferral and may not use the form anywhere else.
//   (e) NO FORM THE COURSE INTRODUCES LATER IS TAUGHT — the same question asked
//       of the LEVEL rather than of one notice: the untaught answer forms of
//       quality.js, the next-level regex, and every form a later Lektion's
//       notice puts in bold or names in its title.
//
// THERE IS NO BUDGET ANY MORE. These four rules were written for the A1.2 rebuild
// and the A1.1 cards predated them, so round 3 held a1.1 at its MEASURED numbers
// — 47 unsourced example sentences, 17 uncovered bold forms, 10 titles that
// differ from their notice — as a ratchet that could only fall. Round 9
// (REVIEW-daf-8-2026-09-12.md MAJOR 1) rewrote all twelve A1.1 cards from the
// Lektionen's own notices and dialogue lines and took all three to zero, so the
// ratchet is gone rather than set to 0: an allowance that exists is an allowance
// a future level asks for, and the whole finding class was "a1.1 was skipped".
// Every level now fails on the FIRST offending sentence, form or title.

const unbold = (text) => String(text).replace(/\*\*/g, '');

/**
 * Sentence segmentation for both sides of the comparison. Splits after . ! ?,
 * and ALSO at `:` and at `→`/`—`, because a card line is written as
 * "Rule: example." and a notice as "…zweiter Stelle: Sie gehen geradeaus." —
 * splitting there is what lets the example half match the notice half.
 */
const SEGMENT_SPLIT = /(?<=[.!?])\s+|:\s*|\s*→\s*|\s*—\s*/;
const segments = (text) =>
  unbold(text)
    .split(SEGMENT_SPLIT)
    .map((s) => s.trim())
    .filter(Boolean);

/** Every sentence the Lektion itself says — the set an example must come from. */
const lektionSentences = (lektion) => {
  const sources = [
    ...lektion.dialog.lines.map((line) => line.de),
    ...(lektion.notice.examples || []),
    lektion.notice.bodyDe,
    lektion.pretest.model,
    lektion.schreiben.sample || '',
    lektion.schreiben.taskDe || '',
  ];
  return new Set(sources.flatMap(segments));
};

// Metalanguage: a segment that talks ABOUT German rather than showing it. These
// two lists are how a rule statement is told from an example — a rule statement
// is not required to be a Lektion line, an example is.
const META_SENTENCE_NOUN = new RegExp(`\\b(${META_NOUNS.join('|')})n?\\b`);
const META_SENTENCE_VERB =
  /\b(steht|stehen|wird|werden|heißt|heißen|bekommt|bekommen|verneint|verlangt|verlangen|bleibt|bleiben|ändert|ändern|fällt|entsteht|endet|verschmelzen|schickt|schicken|lernt|liest|zeigt|gezeigt|fragt|schreibt|rutscht|ergibt|lautet|entscheidet|wiederholt|beginnt)\b/;

/**
 * "Contains a verb". A list fragment ("für den Bruder, ohne den Schal, durch das
 * Kaufhaus.") is not an example sentence and is not checked. The test is closed
 * and mechanical: a segment has a verb when it carries a lower-case word that is
 * not in this stoplist of articles, prepositions, pronouns and particles.
 */
const VERBLESS_STOP = new Set(
  ('der die das den dem des ein eine einen einem einer kein keine keinen mein meine meinen zum zur im am ' +
    'an auf in mit nach bei seit von zu aus für ohne durch und oder also nur auch hier da dann nicht bis ' +
    'als wie so man es sie er ich wir ihr du dich mir ihn ihre sein seine bitte gern noch schon sehr').split(' '),
);
const hasVerb = (segment) =>
  segment
    .split(/[^A-Za-zÄÖÜäöüß-]+/)
    .filter(Boolean)
    .some((w) => /^[a-zäöüß]/.test(w) && !VERBLESS_STOP.has(w.toLowerCase()));

/** Segments of a card's German content that count as example sentences. */
const exampleSentences = (card) =>
  segments(germanLines(card).join(' ')).filter(
    (s) =>
      /[.!?]$/.test(s) &&
      s.split(/\s+/).length >= 3 &&
      hasVerb(s) &&
      !META_SENTENCE_NOUN.test(s) &&
      !META_SENTENCE_VERB.test(s),
  );

/**
 * Example sentences a card may carry that are NOT a line of its Lektion, keyed by
 * slug, each with the reason it is allowed. Deliberately empty: all twenty-four
 * cards — the twelve A1.2 ones since round 3, the twelve A1.1 ones since round 9
 * — quote their own Lektion verbatim. An entry here is a card saying out loud
 * that it had to invent a sentence, which is the thing BLOCKER 2 was.
 */
const EXAMPLE_ALLOW = /** @type {Record<string, Array<{ sentence: string, why: string }>>} */ ({});

// (a)
test('every example sentence on a card is a line of its own Lektion', () => {
  for (const level of LEVELS) {
    const offenders = [];
    for (const lektion of ALL_CURRICULA[level].lektionen) {
      const card = cardOf(lektion.primarySlug);
      if (!card) continue;
      const known = lektionSentences(lektion);
      const allowed = new Set((EXAMPLE_ALLOW[lektion.primarySlug] || []).map((e) => e.sentence));
      for (const sentence of exampleSentences(card)) {
        if (known.has(sentence) || allowed.has(sentence)) continue;
        offenders.push(`L${lektion.nr} ${lektion.primarySlug}: "${sentence}"`);
      }
    }
    assert.deepEqual(
      offenders,
      [],
      `${level}: ${offenders.length} example sentences are nobody's line:\n  ${offenders.join('\n  ')}`,
    );
  }
});

// (b) — the noun check above, widened to every token.
//
// WHY IT IS REWRITTEN (DaF review #9, MAJOR 5). The first version of this guard
// did not bite. Its coverage test was
//   `token === form || token.startsWith(form) || token.endsWith(form) ||
//    form.startsWith(token) || commonPrefix(token, form) >= 4`
// and sixteen out-of-course forms were probed against the A1.1 state at Lektion
// 5: fifteen passed, including the Konjunktiv II (`hätte`, `wäre`, `müsste`,
// `dürfte`) and the Partizip II (`gegangen`, `geschwommen`) that neither A1.1 nor
// A1.2 teaches. MEASURED CAUSE, and it is one line: `cumulativeLexis()` did not
// drop short forms the way `cumulativeWortfeld()` does, and Lektion 1 is the
// ALPHABET — so the lexis set contains the single letters a, c, e, g, h, i, j, k,
// n, r, s, v, w, y, z, ß. With `endsWith`/`startsWith` against a one-character
// "form", every German word is covered: `gegangen` matched the letter `g`,
// `hätte` matched the letter `e`. The four-character tolerance did the rest
// (`unterschreibt` ~ `Unterschrift`).
//
// THE RULE NOW. A token is covered only by a form it SHARES A STEM WITH, and the
// stem has to be four characters long:
//   * the same word, or
//   * a prefix relation in either direction where what the longer side adds is
//     an ENDING and nothing else (`Buchstabe` → `Buchstaben`, `Tag` → `Tagen`,
//     `nehmen` → `nehme`; `unter` does NOT cover `unterschreibt`, because
//     `schreibt` is not an ending), or
//   * the same inflectional stem, i.e. the same word after one German suffix is
//     removed (`kaufen`/`kauft` → `kauf`, `fahren`/`fährst` is NOT the same stem
//     and is not covered).
// `endsWith` is gone — German compounds are head-final, so suffix matching is
// right for the NOUN check above and wrong here, where it licensed every verb
// and adjective in the language. The four-character prefix tolerance is gone
// with it.
//
// THE ALLOW-LIST IS METALANGUAGE ONLY. What a card may say beyond the lexis of
// its own course-so-far is the vocabulary it needs to talk ABOUT German: the
// grammar nouns (META_NOUNS, already closed and argued above), the verbs a rule
// statement is made of (read out of META_SENTENCE_VERB so the two cannot drift),
// and a closed list of grammatical qualifiers. The test below asserts that the
// list stays that: no entry may be a Wortfeld word of any curriculum, and none of
// the sixteen probe forms may be covered by it. An inflected content form
// ("kauft", "bestellt") is NOT allow-listed — it is covered by the stem rule or
// the card is rewritten.
/** The verbs a rule statement is made of — one source with META_SENTENCE_VERB. */
const META_VERBS = META_SENTENCE_VERB.source.replace(/\\b|[()]/g, '').split('|');

/**
 * Three more rule-statement words that are metalanguage but not segment markers,
 * so they do not belong in META_SENTENCE_VERB (a segment carrying one of those is
 * exempted from the example-sentence guard, and these three verbs appear in real
 * example sentences too): `gehört` ("Das Genus gehört zum Wort"), `gilt` ("In der
 * Familie gilt das nicht"), `fehlt` ("Ohne die Vorsilbe fehlt das halbe Verb"),
 * and `weg`, the separable particle of the rule verb `wegfallen` ("Der Artikel
 * fällt nicht weg").
 */
const META_VERBS_EXTRA = ['gehört', 'gilt', 'fehlt'];

/**
 * Grammatical qualifiers: words that name a CATEGORY of German, never a thing in
 * a situation. Closed, and asserted below to contain no Wortfeld word.
 *   * the genus and regularity words a rule card cannot avoid;
 *   * `richtig`/`falsch` — `ruleCardText()` renders every commonMistake as
 *     "Falsch: … — Richtig: …", so the two words are the card's own frame;
 *   * `feste` — "eine feste Wendung", "feste Endungen" is a grammatical
 *     category, and `Wendung` is already a META_NOUN. The bare `fest` is not
 *     here either: `das Fest` is A1.1 Lektion 12 vocabulary;
 *   * the position words a word-order rule needs to point with;
 *   * `geschrieben`/`gesprochen` — the written and the spoken form of a question
 *     are what A1.1 L10 is about;
 *   * the gender-predicting ENDINGS, which `nouns-gender` quotes with a leading
 *     hyphen ("-ung, -heit …") and which `splitWords` hands over bare.
 * The bare `bestimmt` is deliberately NOT here: it is the A1.1 Lektion 12
 * Wortfeld adverb ("Ja, bestimmt"), a different word from the attributive
 * `bestimmte` a rule card needs, and the assertion below would refuse it.
 */
const GRAMMAR_TERMS = [
  'feminin', 'feminine', 'femininen', 'maskulin', 'maskuline', 'männlich', 'männliche',
  'männlichen', 'neutrum', 'neutral', 'regelmäßig', 'regelmäßige', 'unregelmäßig',
  'trennbar', 'trennbare', 'bestimmte', 'bestimmtem', 'bestimmten',
  'unbestimmte', 'unbestimmtem', 'unbestimmten', 'höflich', 'höfliche',
  'einzeln', 'einzelne', 'auswendig',
  'richtig', 'falsch', 'feste',
  'direkt', 'dahinter', 'vorn', 'hinten',
  'geschrieben', 'geschriebene', 'geschriebenen', 'gesprochen',
  'ung', 'heit', 'keit', 'schaft', 'chen', 'lein',
];

/**
 * THE PREDICATION GLUE — five forms, and the argument for each is the same.
 *
 * A rule card is a sentence ABOUT German, and a German sentence about German has
 * to predicate („Ü **ist** ein Buchstabe mit Umlaut“, „Die Namen der Buchstaben
 * **sind** A a, B be, …“) and has to name feminine and plural forms with their
 * article („**die** Endung -st“). Since round 11 the lexis guard no longer takes
 * the whole FUNCTION_WORDS list as free (DaF review #10, MAJOR 3), and these are
 * the five forms that fell out — measured over all 24 shipped cards, all five on
 * the A1.1 Lektion 1 card and nowhere else, because by Lektion 2 the course has
 * said `ist`/`sind` itself, by L5 `die` and by L9 `haben`.
 *
 * They are safe to free in a way the rest of the list is not: none of them is a
 * deferral of this course. What A1.1 defers is `ein/eine/einen` (L6), the
 * accusative `den` (L4), the separable prefix (L11) and the possessives (L12) —
 * and each of those is now bound to its Lektion, with the construction guard (f)
 * below on top of it.
 */
const CARD_PREDICATION = ['ist', 'sind', 'hat', 'haben', 'die'];

/** The metalanguage a card may use on top of its own course-so-far. Closed. */
const CARD_METALANGUAGE = [
  ...META_NOUNS,
  ...META_VERBS,
  ...META_VERBS_EXTRA,
  ...GRAMMAR_TERMS,
  ...CARD_PREDICATION,
].map((w) => w.toLowerCase());

/**
 * Sixteen forms from outside both courses, the probe set of DaF review #9,
 * MAJOR 5: four Konjunktiv II, two Partizip II, three inflected verbs, two
 * adjectives, four compound nouns and one untaught possessive. The guard is run
 * against them below and must catch EVERY one — a guard that does not pass its
 * own counter-probe is not a rule.
 */
const OUT_OF_COURSE_PROBES = [
  'hätte', 'wäre', 'müsste', 'dürfte',
  'gegangen', 'geschwommen',
  'repariert', 'verhandelt', 'unterschreibt',
  'gewöhnlich', 'zuverlässig',
  'Schmetterling', 'Waschmaschine', 'Zahnarzt', 'Gewerkschaft',
  'deinen',
];

/** Every word the course has SAID by Lektion `nr` of `level` — not only its Wortfeld. */
const cumulativeLexis = (level, nr) => {
  const seen = new Set();
  for (const lvl of LEVELS) {
    if (lvl > level) continue;
    for (const lektion of ALL_CURRICULA[lvl].lektionen) {
      if (lvl === level && lektion.nr > nr) continue;
      const sources = [
        lektion.title,
        lektion.situation,
        lektion.notice.title,
        unbold(lektion.notice.bodyDe),
        ...(lektion.notice.examples || []),
        ...lektion.dialog.lines.map((line) => line.de),
        ...(lektion.canDo || []),
        ...lektion.wortfeld.map((w) => w.de),
        lektion.pretest.model,
        lektion.schreiben.sample || '',
        lektion.schreiben.taskDe || '',
      ];
      for (const text of sources) for (const word of splitWords(text)) seen.add(word.toLowerCase());
    }
  }
  return seen;
};

/**
 * THE FUNCTION WORDS A CARD MAY USE FREELY — and they are the only ones.
 *
 * This used to be the whole FUNCTION_WORDS list of the level (plus A1.1's at
 * A1.2), on the reasoning that a learner may MEET a function word before it is
 * taught. DaF review #10, MAJOR 3 measured what that licence costs on a TEACHING
 * surface: `ein und eine stehen bei einer Sache.` on the Lektion 5 card and
 * `Ich kaufe am Freitag ein.` on the Lektion 10 card both came back `lexis=[]
 * defer=0`, although `ein/eine` is Lektion 6 and the Satzklammer Lektion 11 —
 * „eine Prüfung, die dort misst, wo sie leicht zu messen ist“.
 *
 * A card is not a dialogue. What the course has SAID by this Lektion is already
 * in `cumulativeLexis` (it reads every dialogue line and every notice), so a
 * function word the learner has met is covered there, at the Lektion it was met.
 * On top of that only `FUNCTION_WORDS_FREE` — the numbers, the particles, the
 * question words, the subject pronouns and the two bare greetings, each entry
 * justified where the list is defined. Every article, determiner, possessive,
 * oblique pronoun, preposition and form of sein/haben is out: those are the word
 * class this course's deferrals are made of.
 */
const freeFunctionWords = () => FUNCTION_WORDS_FREE.map((w) => w.toLowerCase());

/**
 * The NOMINATIVE definite articles. Free like the list above, and for the reason
 * DaF review #10 gives when it splits FUNCTION_WORDS in two: what this course
 * defers is CASE and the indefinite/possessive paradigms, and `der`/`die`/`das`
 * in the nominative carry neither. The A1.1 Lektion 1 dialogue already says `der`
 * and `das`. `den`, `dem`, `des` are NOT here — they are the accusative and
 * dative forms the course introduces in Lektion 4 and defers to A1.2.
 */
const NOMINATIVE_ARTICLES = ['der', 'die', 'das'];

/**
 * THE DETERMINERS THIS COURSE DEFERS — derived from the two FUNCTION_WORDS lists,
 * not retyped: the article/determiner block minus the nominative definite
 * articles, which are free (see NOMINATIVE_ARTICLES).
 *
 * These are the forms for which „the course already said it somewhere“ is NOT an
 * answer. A learner MEETS `ein` in the Lektion 2 dialogue; Lektion 6 is where the
 * course TEACHES it, in bold, with a rule. A card before Lektion 6 that puts it
 * in a rule sentence is teaching Lektion 6 early, and that is what MAJOR 3
 * measured going through every guard.
 *
 * Two forms are deliberately out. Bare `sein` is the infinitive of the copula
 * (Lektion 2) as well as the possessive (Lektion 12), and bare `ihr` is the
 * Lektion 3 subject pronoun as well as the possessive — spelling alone cannot
 * tell them apart, so they are left to the possessive CONSTRUCTION pattern above
 * and to UNTAUGHT_ANSWER_FORMS below, both of which read the context.
 */
const DETERMINER_PREFIXES = /^(ein|kein|mein|dein|sein|ihr|unser|euer|eur|den|dem|des)/;
const DEFERRED_DETERMINERS = new Set(
  [...FUNCTION_WORDS_A11, ...FUNCTION_WORDS_A12]
    .map((w) => w.toLowerCase())
    .filter((w) => DETERMINER_PREFIXES.test(w))
    .filter((w) => !NOMINATIVE_ARTICLES.includes(w) && w !== 'sein' && w !== 'ihr' && w !== 'eins'),
);

/**
 * One German inflectional suffix, removed once. Only applied when at least four
 * characters remain, so `ist` → `ist` and `gegangen` → `gegang` (which no A1
 * stem matches) rather than collapsing to a syllable that matches everything.
 */
const INFLECTION_SUFFIX = /(?:en|em|er|es|et|st|te|e|n|t)$/;
const stemOf = (word) => {
  const stem = word.replace(INFLECTION_SUFFIX, '');
  return stem.length >= 4 ? stem : word;
};

/**
 * What a prefix relation is allowed to leave over. Without this the prefix rule
 * is nearly as loose as the `endsWith` it replaces: `unter` is a word of the
 * course and covered `unterschreibt` on its own. A longer word is an INFLECTION
 * of a shorter one only when what follows is an ending.
 */
const INFLECTION_TAIL = /^(?:e|en|em|er|es|et|st|t|n|s|ns|in|innen)?$/;

/** The noun heads a compound on this card may be built on. */
const compoundHeads = (primary) => [
  ...cumulativeLexis(primary.level, primary.nr),
  ...META_NOUNS.map((w) => w.toLowerCase()),
  ...ALWAYS_ALLOWED.map((w) => w.toLowerCase()),
];

/** The words a card at this Lektion may use, and nothing else. */
const cardVocabulary = (primary) => [
  ...cumulativeLexis(primary.level, primary.nr),
  ...freeFunctionWords(),
  ...CARD_METALANGUAGE,
  ...ALWAYS_ALLOWED.map((w) => w.toLowerCase()),
  ...(EARLY_USE[primary.slug] || []).map((w) => w.toLowerCase()),
];

/**
 * The tokens of a card that are checked: everything except the `wrong` fields.
 * Case is KEPT — German capitalises nouns, and the compound rule below applies
 * to nouns only.
 */
const cardTokens = (card) =>
  [card.titleDe, ...germanLines(card), ...card.commonMistakes.flatMap((m) => [m.correct, m.explanationDe])]
    .flatMap(splitWords)
    .filter((w) => w.length >= 3);

/**
 * The guard itself, as a function so the mutation tests below can call it on a
 * card fixture rather than on the shipped file. `wrong` fields are excluded —
 * they are deliberately malformed German and are the one place a non-word
 * belongs.
 */
const outsideLexis = (card, primary, vocabulary = cardVocabulary(primary)) => {
  const stems = new Set(vocabulary.map(stemOf));
  // German compounds are head-final, so a CAPITALISED token whose head is a word
  // of the course is a compound of it (Beruf + Namen → Berufsnamen). This is the
  // one suffix rule that survives, and it is restricted to nouns and to heads
  // that are real course words — never to the grammatical ENDINGS in
  // GRAMMAR_TERMS, which would turn "-schaft" into a licence for Gewerkschaft.
  const heads = compoundHeads(primary);
  const covered = (raw) => {
    const token = raw.toLowerCase();
    if (stems.has(stemOf(token))) return true;
    if (
      vocabulary.some(
        (form) =>
          token === form ||
          (form.length >= 3 && token.startsWith(form) && INFLECTION_TAIL.test(token.slice(form.length))) ||
          (token.length >= 3 && form.startsWith(token) && INFLECTION_TAIL.test(form.slice(token.length))),
      )
    ) {
      return true;
    }
    const stem = stemOf(token);
    return (
      /^[A-ZÄÖÜ]/.test(raw) &&
      heads.some((head) => head.length >= 4 && token !== head && (token.endsWith(head) || stem.endsWith(head)))
    );
  };
  return [...new Set(cardTokens(card).filter((token) => !covered(token)).map((w) => w.toLowerCase()))];
};

test('no card uses a word the course has not used by that Lektion', () => {
  // Reported for ALL 24 cards at once, not card by card: a per-card assert stops
  // at the first failure, and a repair round then fixes one card, re-runs, finds
  // the next — which is how a finding class gets closed as a list of instances
  // (DaF review #10's recurring rebuke). One run, the whole class.
  const failures = PRIMARIES.map((primary) => ({ primary, offenders: outsideLexis(cardOf(primary.slug), primary) }))
    .filter(({ offenders }) => offenders.length)
    .map(({ primary, offenders }) => `${where(primary)}: ${offenders.join(', ')}`);
  assert.deepEqual(failures, [], `cards using words the course has not used by their Lektion:\n  ${failures.join('\n  ')}`);
});

test('the card metalanguage list is metalanguage and nothing else', () => {
  const wortfeld = new Set(
    LEVELS.flatMap((level) =>
      ALL_CURRICULA[level].lektionen.flatMap((l) => l.wortfeld.flatMap((w) => splitWords(w.word))),
    ).map((w) => w.toLowerCase()),
  );
  for (const term of CARD_METALANGUAGE) {
    assert.equal(term, term.toLowerCase(), `${term}: the list is matched lower-cased`);
  }
  // META_NOUNS is the closed, argued list above and legitimately overlaps the
  // Wortfeld where the course teaches a grammar word as vocabulary (der
  // Buchstabe, die Uhr, der Name). The two HAND-WRITTEN additions may not: a
  // Wortfeld word there is a content form smuggled in as metalanguage.
  for (const term of [...META_VERBS_EXTRA, ...GRAMMAR_TERMS]) {
    assert.ok(
      !wortfeld.has(term),
      `${term} is a Wortfeld word of the course — a content form has no place in the metalanguage allow-list`,
    );
  }
  assert.ok(
    META_VERBS_EXTRA.length + GRAMMAR_TERMS.length <= 60,
    'the metalanguage allow-list is meant to stay small — argue an entry or rewrite the card',
  );
  // And it may not, on its own, license anything from outside the course.
  const covered = OUT_OF_COURSE_PROBES.map((w) => w.toLowerCase()).filter((probe) => {
    const stems = new Set(CARD_METALANGUAGE.map(stemOf));
    return (
      stems.has(stemOf(probe)) ||
      CARD_METALANGUAGE.some(
        (t) => probe === t || (t.length >= 4 && probe.startsWith(t) && INFLECTION_TAIL.test(probe.slice(t.length))),
      )
    );
  });
  assert.deepEqual(covered, [], `the metalanguage list licenses out-of-course forms: ${covered.join(', ')}`);
});

test('the lexis guard catches every out-of-course probe form', () => {
  // A1.1 Lektion 5 — the state review #9 measured the sixteen probes against.
  const primary = PRIMARIES.find((p) => p.level === 'a1.1' && p.nr === 5);
  const vocabulary = cardVocabulary(primary);
  const probed = OUT_OF_COURSE_PROBES.map((form) => {
    const fixture = {
      titleDe: cardOf(primary.slug).titleDe,
      content: `Der Artikel ${form} steht vor dem Nomen.\nEnglish: probe.`,
      commonMistakes: [{ wrong: 'x', correct: 'y', explanationDe: 'z' }],
    };
    return { form, caught: outsideLexis(fixture, primary, vocabulary).includes(form.toLowerCase()) };
  });
  assert.deepEqual(
    probed.filter((p) => !p.caught).map((p) => p.form),
    // `deinen` is a FUNCTION_WORD of both levels (CONTRACT §2: a learner may MEET
    // a function word early), so the lexis guard is the wrong guard for it — it
    // is caught by the level-scoped deferral guard below, which reads
    // UNTAUGHT_ANSWER_FORMS and knows no allow-list.
    ['deinen'],
    'a guard that does not pass its own counter-probe is not a rule',
  );
});

// (c)
/** The bold spans of a notice — the forms the Lektion actually teaches. */
const noticeForms = (lektion) => [
  ...new Set(
    [...lektion.notice.bodyDe.matchAll(/\*\*(.+?)\*\*/g)]
      .flatMap((m) => m[1].split('…'))
      .map((form) => form.trim())
      .filter(Boolean),
  ),
];

test('every form the notice puts in bold appears on the card', () => {
  for (const level of LEVELS) {
    const missing = [];
    for (const lektion of ALL_CURRICULA[level].lektionen) {
      const card = cardOf(lektion.primarySlug);
      if (!card) continue;
      const haystack = [card.content, ...card.commonMistakes.flatMap((m) => [m.wrong, m.correct, m.explanationDe])].join('\n');
      for (const form of noticeForms(lektion)) {
        if (haystack.includes(form)) continue;
        missing.push(`L${lektion.nr} ${lektion.primarySlug}: "${form}"`);
      }
    }
    assert.deepEqual(
      missing,
      [],
      `${level}: ${missing.length} bold notice forms are missing from their card:\n  ${missing.join('\n  ')}`,
    );
  }
});

test('the card title is the title of its notice', () => {
  for (const level of LEVELS) {
    const diverged = [];
    for (const lektion of ALL_CURRICULA[level].lektionen) {
      const card = cardOf(lektion.primarySlug);
      if (!card || card.titleDe === lektion.notice.title) continue;
      diverged.push(`L${lektion.nr} ${lektion.primarySlug}: card "${card.titleDe}" vs notice "${lektion.notice.title}"`);
    }
    assert.deepEqual(
      diverged,
      [],
      `${level}: ${diverged.length} card titles differ from their notice:\n  ${diverged.join('\n  ')}`,
    );
  }
});

// (d) — deferrals. "Die Form keinen kommt in Lektion 4 dazu." withdraws `keinen`
// from Lektion 3; the card may repeat the deferral and may not teach the form.
// The deferred token is read out of the notice rather than typed here, so a new
// deferral is guarded the moment it is written.
const DEFERRAL_RE = /(\S+)\s+(?:kommt|folgt)\s+(?:erst\s+)?(?:in\s+Lektion\s+\d+|in\s+A1\.\d)/g;
const NAMES_DEFERRAL = /(kommt|folgt)\s+(erst\s+)?in\s+(Lektion|A1\.)/;

const deferredForms = (lektion) =>
  [...unbold(lektion.notice.bodyDe).matchAll(DEFERRAL_RE)]
    .map((m) => m[1].replace(/[^A-Za-zÄÖÜäöüß-]/g, ''))
    // A deferral can be about a CONCEPT ("die Regel kommt in Lektion 11") rather
    // than a FORM; the metalanguage list is exactly how the two are told apart.
    .filter((form) => form.length >= 3 && !META_NOUNS.some((m) => m.toLowerCase() === form.toLowerCase()));

test('no card teaches a form its own notice defers to a later Lektion', () => {
  for (const primary of PRIMARIES) {
    const lektion = ALL_CURRICULA[primary.level].lektionen.find((l) => l.nr === primary.nr);
    const card = cardOf(primary.slug);
    for (const form of deferredForms(lektion)) {
      const pattern = new RegExp(`\\b${form}\\b`, 'i');
      const carriers = [card.content, ...card.commonMistakes.map((m) => m.correct)]
        .flatMap((text) => text.split(/\n|(?<=[.!?])\s+/))
        .filter((sentence) => pattern.test(sentence) && !NAMES_DEFERRAL.test(sentence));
      assert.deepEqual(
        carriers,
        [],
        `${where(primary)}: the notice defers "${form}", the card teaches it anyway:\n  ${carriers.join('\n  ')}`,
      );
    }
  }
});

// ─────────────────────────────────────────────────────────────────────────────
// (e) ── DEFERRALS, LEVEL-SCOPED (DaF review #9, MAJOR 5).
//
// WHY (d) IS NOT ENOUGH, MEASURED. Guard (d) above reads the DEFERRAL out of the
// card's own notice: "die Form keinen kommt in Lektion 4" withdraws `keinen`. Run
// over the twelve A1.1 notices, it has nothing to guard in ten of them — the
// regex reads the token immediately before "kommt/folgt", and in L4, L5, L9 and
// L11 that token is a bracketed metalanguage word ("(Akkusativ) kommt in A1.2"),
// which META_NOUNS filters away; in L9 the sentence does not say "kommt/folgt" at
// all. Exactly two forms survive and both are misfires (`eins`, `haben`). So a
// card could go on teaching the next Lektion's grammar as long as its own notice
// had not happened to write the deferral down.
//
// THE QUESTION THIS GUARD ASKS INSTEAD: does the card teach a form THE COURSE
// introduces later — whatever its own notice says? Three sources, all imported,
// none retyped here:
//   1. `UNTAUGHT_ANSWER_FORMS` (src/data/lessonPools/quality.js) — the possessive
//      paradigm beyond -e, which A1.1 never teaches. These are FUNCTION_WORDS of
//      both levels, so the lexis guard above cannot see them: `deinen` is covered
//      by `deine` there and is caught only here.
//   2. `NEXT_LEVEL_RE` (same file) — the card SAYING the next level out loud
//      ("Vorschau", "A1.2", and at A1.1 the case names, which no A1.1 notice
//      uses).
//   3. Every form a LATER Lektion's notice puts in bold — the notice's bold spans
//      are the teaching points (that is what guard (c) is built on), so a bold
//      form of a later Lektion is by definition introduced later.
// Both level-scoped lists apply to A1.1 only, exactly as quality.js scopes them:
// `meinen` is ordinary German at A1.2 and `Dativ` is A1.2 metalanguage.
//
// THE ONE EXEMPTION, and it is the same one guard (d) has: a sentence that POINTS
// AHEAD ("… kommt in A1.2", "Mehr dazu in Lektion 7", "gehört zu den Modalverben
// in A1.2") is naming the deferral, which is what a card is supposed to do. The
// exemption is a property of the SENTENCE, not of the card, so the rest of the
// card stays under the guard. A later bold form is also skipped when the
// course-so-far already says all of its words — then it is not introduced later,
// it is being re-taught.

/** A sentence that hands the form forward to a named Lektion or level. */
const POINTS_AHEAD = /\bin\s+(Lektion\s+\d+|A1\.\d)\b/;

const escapeRe = (text) => text.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

/** A Lektion's place in the whole course, so two of them can be compared across levels. */
const coursePosition = (level, nr) => LEVELS.indexOf(level) * 100 + nr;

/**
 * The forms every Lektion after this one puts in bold, with where they come from.
 *
 * EARLIEST BOLD WINS (round 11). The first cut read „the next Lektion that bolds
 * it“, and a form bolded twice was therefore deferred by its SECOND teaching:
 * A1.1 bolds `ein` in Lektion 6 (the indefinite article) and again in Lektion 11
 * (the separable prefix of `einkaufen` — a different word with the same letters),
 * so the Lektion 6 card, which IS the indefinite-article card, was reported for
 * teaching `ein` early. A form is introduced where it is introduced: the first
 * Lektion of the whole course that bolds it.
 */
const laterNoticeForms = (level, nr) => {
  const forms = new Map();
  const at = new Map();
  const here = coursePosition(level, nr);
  for (const lvl of LEVELS) {
    for (const lektion of ALL_CURRICULA[lvl].lektionen) {
      const pos = coursePosition(lvl, lektion.nr);
      // The bold spans AND the NOUNS of the notice title: A1.1 L11 names the
      // Satzklammer in its title and nowhere in bold, and the title is a teaching
      // point like any other (guard (c) holds every card title to it). Only the
      // capitalised words — a title also carries position words ("das Verb steht
      // vorn"), which name where, not what.
      const titleForms = splitWords(lektion.notice.title).filter(
        (w) => w.length >= 4 && /^[A-ZÄÖÜ]/.test(w),
      );
      for (const form of [...noticeForms(lektion), ...titleForms]) {
        if (at.has(form)) continue;                       // earliest bold wins
        at.set(form, pos);
        if (pos > here) forms.set(form, `${lvl} L${lektion.nr}`);
      }
    }
  }
  return forms;
};

/** The sentences of a card that are under this guard. */
const guardedSentences = (card) =>
  [card.titleDe, card.content, ...card.commonMistakes.flatMap((m) => [m.correct, m.explanationDe])]
    .flatMap((text) => String(text).split(/\n|(?<=[.!?])\s+/))
    .map((s) => unbold(s).replace(/\s+/g, ' ').trim())
    .filter(Boolean)
    .filter((s) => !ENGLISH_LINE.test(s))
    // A line that opens „Nicht: …“ is the card's negative example — the same
    // thing a `commonMistakes.wrong` field is, and `wrong` is excluded from every
    // guard here for the same reason: it is the one place a card SHOWS what not
    // to say. („Nicht: Ich bin ein Lehrer.“ on the A1.1 L2 card.)
    .filter((s) => !/^Nicht:/.test(s))
    .filter((s) => !POINTS_AHEAD.test(s));

/**
 * (f) ── THE CONSTRUCTIONS, not the words (DaF review #10, MAJOR 3).
 *
 * The guard above reads FORMS. A course defers CONSTRUCTIONS, and the three this
 * one defers are each spelled with words that are ordinary at every Lektion:
 * `ein`/`eine` before a noun is Lektion 6, a finite verb with its prefix at the
 * end of the sentence is Lektion 11, `mein`/`dein` before a noun is Lektion 12 —
 * and „ein und eine stehen bei einer Sache.“ on the L5 card came back clean from
 * all four earlier guards, because every single word in it is fine.
 *
 * The patterns themselves, their two narrowings and the rule that the
 * introducing Lektion is READ FROM THE CURRICULUM live in
 * `src/data/curricula/constructions.js`, because the same question has to be
 * answered the same way for the sentence the learner DICTATES or READS ALOUD —
 * RULE 15b in `scripts/validate-curriculum.mjs` (DaF review #11, MAJOR 3).
 * The exemption is the same one every guard here has: a sentence that POINTS
 * AHEAD names its own deferral and is allowed to.
 */

/** The Lektion of `level` whose primarySlug is `slug` — the curriculum's own answer. */
const introducedAt = (level, slug) => introducedIn(ALL_CURRICULA[level], slug);

/** True when every occurrence of `form` in the sentence is followed by a metalanguage noun. */
const beforeMetaNounOnly = (form, sentence) => {
  const hits = [...sentence.matchAll(new RegExp(`\\b${escapeRe(form)}\\b\\s*(\\S*)`, 'gi'))];
  return hits.length > 0 && hits.every((m) => isMetaNoun(m[1]));
};

const constructionOffenders = (sentences, primary) => {
  const out = [];
  for (const { slug, label, re, skip } of CONSTRUCTION_PATTERNS) {
    const taught = introducedAt(primary.level, slug);
    if (!taught || taught <= primary.nr) continue;
    for (const sentence of sentences) {
      for (const m of sentence.matchAll(new RegExp(re.source, re.flags))) {
        if (skip && skip(m, sentence)) continue;
        out.push(`Lektion ${taught} teaches ${label} — "${sentence}"`);
      }
    }
  }
  return out;
};

const levelDeferralOffenders = (card, primary) => {
  const lexis = cumulativeLexis(primary.level, primary.nr);
  const stems = new Set([...lexis].map(stemOf));
  const said = (word) => lexis.has(word.toLowerCase()) || stems.has(stemOf(word.toLowerCase()));
  const sentences = guardedSentences(card);
  const offenders = [...constructionOffenders(sentences, primary)];

  // FUNCTION_WORDS_FREE, not the whole function-word list. The old carve-out read
  // „a learner may MEET a function word before it is taught (CONTRACT §2)“ and
  // therefore exempted `ein`, `eine`, `einen`, `dem`, `meiner` — the exact word
  // class this course's deferrals are made of (DaF review #10, MAJOR 3). What a
  // learner has MET is `said()` above, measured on the dialogues; what may be
  // used without having been met is the small justified list and nothing else.
  // …plus CARD_PREDICATION, for the reason it exists: a card has to predicate and
  // has to name feminine forms with their article, and `ist`/`sind`/`hat`/
  // `haben`/`die` are bold in a later notice of every course precisely because
  // they are the course's own grammar. They are none of the three constructions
  // guard (f) above defers.
  const functionWords = new Set([...freeFunctionWords(), ...CARD_PREDICATION, ...NOMINATIVE_ARTICLES]);
  for (const [form, from] of laterNoticeForms(primary.level, primary.nr)) {
    if (form.length < 3) continue;
    const low = form.toLowerCase();
    const single = !/\s/.test(form);
    // A GRAMMAR-BEARING function form: a function word of this course that is in
    // neither free list, i.e. `ein`, `eine`, `einen`, `kein`, `den`, `dem`,
    // `meiner`, `um`, `am`. For these the „the course already says it, so it is
    // being re-taught“ escape below does NOT apply: an incidental use in a
    // dialogue line is the learner MEETING a form, and a later notice putting it
    // in bold is the course TEACHING it. A card may not do the second one early.
    // („ein und eine stehen bei einer Sache.“ on the Lektion 5 card is exactly
    // this: `ein` occurs in the Lektion 2 dialogue, and Lektion 6 is where it is
    // taught — DaF review #10, MAJOR 3.)
    const grammarBearing = single && DEFERRED_DETERMINERS.has(low) && from.startsWith(primary.level);
    if (!grammarBearing && splitWords(form).every(said)) continue;
    if (single && functionWords.has(low)) continue;
    const multiWord = /\s/.test(form);
    const pattern = new RegExp(multiWord ? escapeRe(form) : `\\b${escapeRe(form)}\\b`, 'i');
    for (const sentence of sentences) {
      if (!pattern.test(sentence)) continue;
      // A determiner in front of a METALANGUAGE noun is the card talking about
      // German („Jedes Nomen hat ein Genus“ — the A1.1 L4 notice title, which the
      // card title has to repeat), not the card putting a thing into the world
      // with an article. Same narrowing as the construction patterns above, and
      // for the same reason.
      if (grammarBearing && beforeMetaNounOnly(form, sentence)) continue;
      offenders.push(`${from} teaches "${form}" — "${sentence}"`);
    }
  }

  if (primary.level === 'a1.1') {
    for (const sentence of sentences) {
      const preview = NEXT_LEVEL_RE.exec(sentence);
      if (preview) offenders.push(`the card names the next level ("${preview[0]}") — "${sentence}"`);
      for (const word of splitWords(sentence)) {
        if (UNTAUGHT_ANSWER_FORMS.includes(word.toLowerCase())) {
          offenders.push(`"${word}" is an untaught answer form at ${primary.level} — "${sentence}"`);
        }
      }
    }
  }
  return [...new Set(offenders)];
};

test('no card teaches a form the course introduces after its own Lektion', () => {
  const failures = PRIMARIES.flatMap((primary) =>
    levelDeferralOffenders(cardOf(primary.slug), primary).map((o) => `${where(primary)}: ${o}`),
  );
  assert.deepEqual(failures, [], `${failures.length} forms the course introduces later:\n  ${failures.join('\n  ')}`);
});

// ─────────────────────────────────────────────────────────────────────────────
// MUTATION TESTS. The finding behind MAJOR 5 is that four guards passed the cards
// they were written for and would not have caught the class the cards came from.
// The only answer to that is to break a card on purpose and watch the guard fire.
// Each case injects ONE thing into a copy of a shipped card and asserts the guard
// that owns it reports it.

/** A shipped card with one sentence appended to `content`. */
const cardWith = (slug, sentence) => {
  const card = cardOf(slug);
  const lines = card.content.split('\n');
  const english = lines.findIndex((l) => ENGLISH_LINE.test(l.trim()));
  const injected = [...lines];
  injected.splice(english < 0 ? lines.length : english, 0, sentence);
  return { ...card, content: injected.join('\n') };
};

const A11_L5 = PRIMARIES.find((p) => p.level === 'a1.1' && p.nr === 5);
const A11_L10 = PRIMARIES.find((p) => p.level === 'a1.1' && p.nr === 10);

test('MUTATION: Konjunktiv II on a card is caught by the lexis guard', () => {
  const offenders = outsideLexis(cardWith(A11_L5.slug, 'Das hätte der Lehrer gesagt.'), A11_L5);
  assert.ok(offenders.includes('hätte'), `hätte went through: ${offenders.join(', ') || 'nothing reported'}`);
});

test('MUTATION: a Partizip II on a card is caught by the lexis guard', () => {
  const offenders = outsideLexis(cardWith(A11_L5.slug, 'Der Lehrer ist gegangen.'), A11_L5);
  assert.ok(offenders.includes('gegangen'), `gegangen went through: ${offenders.join(', ') || 'nothing reported'}`);
});

test('MUTATION: an untaught possessive is caught by the deferral guard', () => {
  // `deinen` is a FUNCTION_WORD, so the lexis guard cannot see it — this is
  // exactly the split the two guards exist for.
  const card = cardWith(A11_L5.slug, 'Der Artikel steht vor deinen Nomen.');
  assert.deepEqual(outsideLexis(card, A11_L5), [], 'the lexis guard is not the guard for a function word');
  const offenders = levelDeferralOffenders(card, A11_L5);
  assert.ok(
    offenders.some((o) => o.includes('deinen')),
    `deinen went through: ${offenders.join(' | ') || 'nothing reported'}`,
  );
});

test('MUTATION: A1.2 content on an A1.1 card is caught by the deferral guard', () => {
  // The Satzklammer is A1.1 Lektion 11's teaching point and `Satzklammer` is
  // METALANGUAGE (META_NOUNS), so the lexis guard passes it on the Lektion 10
  // card — the review's case (c) exactly. The deferral guard reads the notices.
  const card = cardWith(A11_L10.slug, 'Die Satzklammer hält den Satz zusammen.');
  const offenders = levelDeferralOffenders(card, A11_L10);
  assert.ok(
    offenders.some((o) => o.includes('Satzklammer')),
    `Satzklammer went through: ${offenders.join(' | ') || 'nothing reported'}`,
  );
});

/**
 * THE COUNTER-PROBE OF DaF REVIEW #10, MAJOR 3 — the six sentences the review
 * built by hand, injected into the shipped card of the Lektion it named, and
 * measured through all four guards of round 10: every one came back
 * `lexis=[] defer=0`. They are a FIXTURE, not prose in a comment, because the
 * finding the review keeps repeating is that a guard which has never been shot at
 * is not a guard. Every one of them must be reported now.
 *
 * `Das ist mein Buch.` is quoted by the review as reaching the Lektion 3 card
 * with only `buch` reported; the possessive is Lektion 12.
 */
const DEFERRED_CONSTRUCTION_PROBES = [
  { nr: 5, sentence: 'ein und eine stehen bei einer Sache.', why: 'ein/eine is Lektion 6' },
  { nr: 5, sentence: 'Man sagt ein Stuhl und eine Lampe.', why: 'the indefinite article is Lektion 6' },
  { nr: 5, sentence: 'Wir haben kein Buch.', why: 'kein is Lektion 6' },
  { nr: 10, sentence: 'Stehen Sie um sechs auf?', why: 'the Satzklammer is Lektion 11' },
  { nr: 10, sentence: 'Ich kaufe am Freitag ein.', why: 'the Satzklammer is Lektion 11' },
  { nr: 3, sentence: 'Das ist mein Buch.', why: 'the possessive article is Lektion 12' },
];

test('MUTATION: every deferred-construction probe of DaF review #10 is caught', () => {
  const missed = [];
  for (const { nr, sentence, why } of DEFERRED_CONSTRUCTION_PROBES) {
    const primary = PRIMARIES.find((p) => p.level === 'a1.1' && p.nr === nr);
    const offenders = levelDeferralOffenders(cardWith(primary.slug, sentence), primary);
    if (!offenders.some((o) => o.includes(sentence))) missed.push(`L${nr} "${sentence}" (${why})`);
  }
  assert.deepEqual(missed, [], `probes that still go through the deferral guard:\n  ${missed.join('\n  ')}`);
});

test('MUTATION: a deferral sentence may still name the construction it defers', () => {
  // The one exemption, and it is a property of the SENTENCE: a card that hands the
  // form forward is doing its job. Without this the guard would forbid the course
  // from telling the learner what comes next.
  const card = cardWith(A11_L5.slug, 'Die Formen ein und eine kommen in Lektion 6.');
  assert.deepEqual(
    levelDeferralOffenders(card, A11_L5).filter((o) => o.includes('Lektion 6.')),
    [],
    'a card must be able to name what it defers',
  );
});

test('MUTATION: naming the next level outside a deferral sentence is caught', () => {
  const card = cardWith(A11_L5.slug, 'Der Artikel steht im Akkusativ.');
  const offenders = levelDeferralOffenders(card, A11_L5);
  assert.ok(
    offenders.some((o) => o.includes('Akkusativ')),
    `Akkusativ went through: ${offenders.join(' | ') || 'nothing reported'}`,
  );
  // …and the same word inside a sentence that names the deferral is allowed.
  const deferring = cardWith(A11_L5.slug, 'Die Regel dazu (Akkusativ) kommt in A1.2.');
  assert.deepEqual(
    levelDeferralOffenders(deferring, A11_L5).filter((o) => o.includes('Akkusativ')),
    [],
    'a card must be able to name what it defers',
  );
});
