# -*- coding: utf-8 -*-
"""Build S/wave4/grammar/modal-verbs-past.json (CREATE shape)."""
import json, os

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'grammar', 'modal-verbs-past.json')

def rule(rule_type, title_en, title_de, content, order_index,
         common_mistakes=None, memory_trick_en=None, memory_trick_de=None,
         formal_note_en=None, formal_note_de=None, key_insight_en=None, key_insight_de=None):
    return {
        "rule_type": rule_type,
        "title_en": title_en,
        "title_de": title_de,
        "content": content,
        "order_index": order_index,
        "common_mistakes": common_mistakes,
        "memory_trick_en": memory_trick_en,
        "memory_trick_de": memory_trick_de,
        "formal_note_en": formal_note_en,
        "formal_note_de": formal_note_de,
        "key_insight_en": key_insight_en,
        "key_insight_de": key_insight_de,
    }

topic = {
    "sub_level": "A2.1",
    "topic_order": 11,
    "title_en": "Modal Verbs in the Past",
    "title_de": "Modalverben im Präteritum",
    "slug": "modal-verbs-past",
    "description_en": "Say what you could, had to, wanted to or were allowed to do: konnte, musste, wollte, durfte, sollte, mochte. The modal takes position 2 and the infinitive stays at the end. Goethe A2 needs these forms in Schreiben Teil 1 (the SMS apology) and Sprechen Teil 2.",
    "description_de": "Lerne das Präteritum bei den sechs Modalverben. Das Modalverb steht auf Position 2, der Infinitiv am Ende. Du brauchst das im Goethe A2: Schreiben Teil 1, Sprechen Teil 2.",
    "estimated_time": 22,
    "difficulty": "intermediate",
    "icon": "⏳",
    "is_published": True,
    "prerequisite_slugs": ["modal-verbs-intro", "perfect-tense-haben"],
    "related_slugs": ["perfect-tense-sein", "imperative-mood", "temporal-prepositions"],
}

rules = [
    rule(
        "introduction", "Modal Verbs in the Past: Introduction", "Einführung: Modalverben im Präteritum",
        {
            "hook_de": "Ich konnte gestern nicht kommen. Ich musste zum Arzt gehen.",
            "hook_en": "I couldn't come yesterday. I had to go to the doctor. German says both with one past modal form.",
            "scenario_en": "Cancelling an appointment, explaining an absence, telling a friend what you had to do.",
            "preview_note_en": "Six modal verbs, six past forms — and not one umlaut among them.",
            "preview_highlight": "konnte, musste, wollte, durfte, sollte, mochte",
            "preview_example_de": "Wir konnten gestern nicht kommen.",
            "preview_example_en": "We couldn't come yesterday.",
            "why_it_matters_en": "Goethe A2 Schreiben Teil 1 is often a short SMS: you cancel and say why. Sprechen Teil 2 (telling about yourself) and Hören Teil 1 (phone messages) use the same forms.",
            "german_difference_en": "German keeps one word where English needs two or three: musste = had to, durfte = was allowed to.",
            "english_comparison_en": "English swaps the word (can → could, must → had to). German keeps the modal, drops the umlaut and adds -te: können → konnte.",
        },
        -1,
    ),
    rule(
        "table", "The Six Modal Verbs in the Präteritum", "Die sechs Modalverben im Präteritum",
        {
            "type": "case_table",
            "headers": ["Person", "können", "müssen", "wollen", "dürfen", "sollen", "mögen"],
            "rows": [
                ["ich", "konnte", "musste", "wollte", "durfte", "sollte", "mochte"],
                ["du", "konntest", "musstest", "wolltest", "durftest", "solltest", "mochtest"],
                ["er/sie/es", "konnte", "musste", "wollte", "durfte", "sollte", "mochte"],
                ["wir", "konnten", "mussten", "wollten", "durften", "sollten", "mochten"],
                ["ihr", "konntet", "musstet", "wolltet", "durftet", "solltet", "mochtet"],
                ["sie/Sie", "konnten", "mussten", "wollten", "durften", "sollten", "mochten"],
            ],
            "highlight_row": -1,
            "description_de": "ich und er/sie/es haben keine Endung. Das kennst du von war und hatte.",
            "description_en": "ich and er/sie/es share one form, exactly like war and hatte. All six modals lose the umlaut, and mögen also swaps g for ch: mochte.",
        },
        1,
        memory_trick_en="No umlaut in the past — that is the fastest check: konnte, musste, durfte, mochte.",
        memory_trick_de="Kein Umlaut im Präteritum: konnte, musste, durfte, mochte.",
        key_insight_en="möchte has no past form of its own. Use wollte for it.",
        key_insight_de="möchte hat kein Präteritum. Nimm dafür wollte.",
    ),
    rule(
        "pattern", "How to Build the Präteritum", "So bildest du das Präteritum",
        {
            "type": "steps",
            "steps": [
                {
                    "step": 1,
                    "title_de": "Nimm den Infinitiv ohne -en.",
                    "title_en": "Take the infinitive without -en.",
                    "detail_de": "können → könn-, müssen → müss-, wollen → woll-.",
                    "detail_en": "Start from the infinitive and cut the -en: können → könn-, müssen → müss-, wollen → woll-.",
                },
                {
                    "step": 2,
                    "title_de": "Streiche den Umlaut.",
                    "title_en": "Drop the umlaut.",
                    "detail_de": "könn- → konn-, müss- → muss-, dürf- → durf-. wollen und sollen haben keinen Umlaut.",
                    "detail_en": "könn- → konn-, müss- → muss-, dürf- → durf-. wollen and sollen have no umlaut to lose, and mögen goes one step further: mög- → moch-.",
                },
                {
                    "step": 3,
                    "title_de": "Hänge -te an.",
                    "title_en": "Add -te.",
                    "detail_de": "konn + te = konnte. muss + te = musste. moch + te = mochte.",
                    "detail_en": "konn + te = konnte, muss + te = musste, moch + te = mochte. This -te is the past signal.",
                },
                {
                    "step": 4,
                    "title_de": "Setze die Endung an.",
                    "title_en": "Add the personal ending.",
                    "detail_de": "ich/er konnte, du konntest, wir/sie konnten, ihr konntet.",
                    "detail_en": "ich/er konnte, du konntest, wir/sie konnten, ihr konntet — the same endings hatte takes.",
                },
            ],
            "description_de": "Vier Schritte, immer gleich. Nur mögen ändert g zu ch.",
            "description_en": "Four steps, always in the same order. Only mögen changes g to ch (mochte).",
        },
        2,
        key_insight_en="hatte is the model: hatte / hattest / hatten / hattet — konnte works identically.",
        key_insight_de="hatte ist das Muster: hatte, hattest, hatten, hattet. konnte funktioniert genauso.",
    ),
    rule(
        "table", "Präsens and Präteritum: the Satzklammer Stays", "Präsens und Präteritum: die Satzklammer bleibt",
        {
            "type": "case_table",
            "headers": ["Präsens", "Präteritum", "English"],
            "rows": [
                ["Ich muss arbeiten.", "Ich musste arbeiten.", "I have to work. / I had to work."],
                ["Wir können nicht kommen.", "Wir konnten nicht kommen.", "We can't come. / We couldn't come."],
                ["Darfst du mitkommen?", "Durftest du mitkommen?", "Are you allowed to come along? / Were you allowed to come along?"],
                ["Ihr sollt hier warten.", "Ihr solltet hier warten.", "You are / were supposed to wait here."],
                ["Ich will Deutsch lernen.", "Ich wollte Deutsch lernen.", "I want / wanted to learn German."],
                ["Ich möchte einen Termin haben.", "Ich wollte einen Termin haben.", "I would like to have an appointment. / I wanted to have an appointment."],
            ],
            "highlight_row": -1,
            "description_de": "Nur das Modalverb ändert sich. Der Infinitiv bleibt am Ende.",
            "description_en": "Only the modal changes shape. Position 2 holds the modal, the infinitive closes the bracket at the end — the same Satzklammer you already use in the present.",
        },
        3,
        key_insight_en="A modal can stand without an infinitive when the action is obvious: Ich musste zum Arzt. (gehen is understood.)",
        key_insight_de="Ohne Infinitiv geht auch: Ich musste zum Arzt. Das Verb gehen fehlt hier.",
    ),
    rule(
        "explanation_comparison", "What Each Past Modal Means", "Die Bedeutungen im Präteritum",
        {
            "type": "case_table",
            "headers": ["Form", "English meaning", "Beispiel"],
            "rows": [
                ["konnte", "was able to, could", "Ich konnte gestern nicht arbeiten."],
                ["musste", "had to", "Wir mussten lange warten."],
                ["durfte", "was allowed to", "Ihr durftet hier nicht parken."],
                ["wollte", "wanted to", "Sie wollte nach Hause."],
                ["sollte", "was supposed to", "Ich sollte um acht Uhr da sein."],
                ["mochte", "liked", "Früher mochte er keinen Käse."],
                ["wollte (für möchte)", "wanted (to have)", "Ich wollte einen Termin haben."],
            ],
            "highlight_row": -1,
            "description_de": "musste: es war nötig. durfte: es war erlaubt. wollte: das war dein Plan.",
            "description_en": "musste = necessity, durfte = permission, wollte = your own plan, sollte = someone else's instruction, mochte = what you liked.",
        },
        4,
        key_insight_en="mochte and möchte look alike but are different tenses: mochte is past, möchte is present.",
        key_insight_de="mochte ist Präteritum. möchte ist Gegenwart. Nur ein Buchstabe, zwei Zeiten.",
    ),
    rule(
        "tip", "war, hatte and Why Modals Skip the Perfekt", "war, hatte und kein Perfekt",
        {
            "content_de": "war und hatte kennst du schon. Sie passen gut zu den Modalverben. Ich war krank. Ich konnte nicht arbeiten. Für Modalverben nimmst du im Alltag das Präteritum. Das Perfekt von Modalverben lernst du später.",
            "content_en": "You already know war and hatte, and they pair naturally with the past modals: Ich war krank. Ich konnte nicht arbeiten. For modal verbs, everyday German uses the Präteritum rather than the Perfekt; the Perfekt form of a modal waits until B1.",
        },
        5,
        formal_note_en="In the Goethe A2 SMS (Schreiben Teil 1) this pair does most of the work: one sentence with war or hatte, one with a past modal.",
        formal_note_de="In einer SMS schreibst du: Ich war krank. Ich konnte nicht kommen.",
        key_insight_en="In everyday German you simply say Ich musste; the Perfekt of a modal waits until B1.",
        key_insight_de="Im Alltag sagst du einfach: Ich musste.",
    ),
    rule(
        "dialogue", "Dialogue: Calling the Office", "Dialog: eine Absage am Telefon",
        {
            "speakers": ["Frau Klein", "Herr Bauer"],
            "exchanges": [
                {
                    "speaker": "Frau Klein",
                    "text_de": "Guten Morgen, Herr Bauer. Ich konnte gestern nicht kommen.",
                    "text_en": "Good morning, Herr Bauer. I couldn't come yesterday.",
                    "grammar_note": "konnte — können im Präteritum, Infinitiv am Ende",
                },
                {
                    "speaker": "Herr Bauer",
                    "text_de": "Kein Problem. Waren Sie krank?",
                    "text_en": "No problem. Were you ill?",
                    "grammar_note": "waren — sein im Präteritum",
                },
                {
                    "speaker": "Frau Klein",
                    "text_de": "Ja, ich hatte Fieber. Ich musste zum Arzt.",
                    "text_en": "Yes, I had a fever. I had to go to the doctor.",
                    "grammar_note": "musste — müssen ohne Infinitiv (gehen fehlt)",
                },
                {
                    "speaker": "Herr Bauer",
                    "text_de": "Und der Termin? Sie wollten mit Frau Meier sprechen.",
                    "text_en": "And the appointment? You wanted to speak to Frau Meier.",
                    "grammar_note": "wollten — wollen im Präteritum, Sie-Form",
                },
                {
                    "speaker": "Frau Klein",
                    "text_de": "Ja, ich konnte sie leider nicht anrufen.",
                    "text_en": "Yes, unfortunately I couldn't call her.",
                    "grammar_note": "konnte + anrufen: der Infinitiv steht am Ende",
                },
                {
                    "speaker": "Herr Bauer",
                    "text_de": "Alles gut. Ich konnte ihr alles sagen.",
                    "text_en": "All fine. I was able to tell her everything.",
                    "grammar_note": "konnte — hier ohne nicht, mit Dativpronomen ihr",
                },
            ],
            "context_de": "Frau Klein ruft im Büro an. Sie war gestern krank.",
            "context_en": "Frau Klein phones the office. She was ill yesterday.",
            "grammar_focus_en": "Every past modal here (konnte, musste, wollten) sits in position 2, with the infinitive at the very end — or with no infinitive at all: Ich musste zum Arzt. Hören Teil 1 of the Goethe A2 exam plays exactly this kind of short phone message.",
        },
        6,
        key_insight_en="Hören Teil 1 plays short phone messages just like this one; Sprechen Teil 2 asks you to tell the same story yourself.",
        key_insight_de="So klingt Hören Teil 1: eine Nachricht am Telefon.",
    ),
    rule(
        "common_mistakes", "Six Mistakes to Avoid", "Sechs Fehler im Präteritum",
        {
            "content_de": "Diese sechs Fehler kommen oft. Lies die Beispiele langsam.",
            "content_en": "These six come up again and again. Read the pairs slowly and compare them.",
        },
        7,
        common_mistakes=[
            {
                "wrong": "Ich könnte gestern nicht kommen.",
                "correct": "Ich konnte gestern nicht kommen.",
                "explanation_de": "Das Präteritum hat keinen Umlaut. Es heißt konnte, nicht könnte.",
                "explanation_en": "The past form has no umlaut: konnte, not könnte.",
            },
            {
                "wrong": "Ich musste gestern gearbeitet.",
                "correct": "Ich musste gestern arbeiten.",
                "explanation_de": "Nach dem Modalverb steht der Infinitiv. Kein Partizip II.",
                "explanation_en": "A modal takes an infinitive (arbeiten), never a participle (gearbeitet).",
            },
            {
                "wrong": "Wir wollten gehen nach Hause.",
                "correct": "Wir wollten nach Hause gehen.",
                "explanation_de": "Der Infinitiv steht ganz am Ende. Das ist die Satzklammer.",
                "explanation_en": "The infinitive closes the bracket at the very end of the sentence.",
            },
            {
                "wrong": "Du konntst nicht kommen.",
                "correct": "Du konntest nicht kommen.",
                "explanation_de": "Bei du kommt nach -te noch ein -st: konntest, musstest.",
                "explanation_en": "The du-form adds -st after the -te: konntest, musstest, wolltest.",
            },
            {
                "wrong": "Ich habe gestern gemusst arbeiten.",
                "correct": "Ich musste gestern arbeiten.",
                "explanation_de": "Diese Form gibt es nicht. Nimm das Präteritum: musste.",
                "explanation_en": "That form does not exist. Use the Präteritum: musste.",
            },
            {
                "wrong": "Früher möchte ich keinen Tee.",
                "correct": "Früher mochte ich keinen Tee.",
                "explanation_de": "möchte ist Gegenwart. Das Präteritum von mögen ist mochte.",
                "explanation_en": "möchte is present. The past of mögen is mochte.",
            },
        ],
    ),
    rule(
        "summary", "Quick Reference", "Kurzübersicht",
        {
            "points": [
                "Präteritum: Infinitiv ohne -en, ohne Umlaut, plus -te. können → konnte.",
                "Endungen: ich/er konnte, du konntest, wir/sie konnten, ihr konntet.",
                "Die sechs Formen: konnte, musste, wollte, durfte, sollte, mochte.",
                "mögen ändert g zu ch: mochte.",
                "möchte hat kein Präteritum. Nimm wollte.",
                "Das Modalverb steht auf Position 2. Der Infinitiv steht am Ende.",
                "Ohne Infinitiv geht auch: Ich musste zum Arzt.",
                "war und hatte passen dazu: Ich war krank. Ich konnte nicht kommen.",
                "Für Modalverben nimmst du das Präteritum, nicht das Perfekt.",
                "Prüfung: Schreiben Teil 1 (SMS), Sprechen Teil 2, Hören Teil 1.",
            ]
        },
        99,
    ),
]

def ex(order_index, sentence_de, sentence_en, highlight, expl_en, expl_de, breakdown, difficulty, category):
    return {
        "sentence_de": sentence_de,
        "sentence_en": sentence_en,
        "grammar_highlight": highlight,
        "explanation_en": expl_en,
        "explanation_de": expl_de,
        "word_breakdown": breakdown,
        "difficulty": difficulty,
        "category": category,
        "order_index": order_index,
        "audio_url": None,
    }

examples = [
    ex(1, "Ich konnte gestern nicht kommen.", "I couldn't come yesterday.", "konnte",
       "konnte is the Präteritum of können: no umlaut, plus -te. The infinitive kommen closes the sentence.",
       "konnte ist das Präteritum von können. Der Infinitiv kommen steht am Ende.",
       {"Ich": "I", "konnte": "could, was able to (können, Präteritum)", "gestern": "yesterday",
        "nicht": "not", "kommen": "to come (infinitive)"}, 1, "basic"),
    ex(2, "Ich musste zum Arzt gehen.", "I had to go to the doctor.", "musste",
       "musste is the Präteritum of müssen. zum Arzt uses the dative preposition zu you already know.",
       "musste ist das Präteritum von müssen. Der Infinitiv gehen steht am Ende.",
       {"Ich": "I", "musste": "had to (müssen, Präteritum)", "zum": "to the (zu + dem)",
        "Arzt": "doctor", "gehen": "to go (infinitive)"}, 1, "basic"),
    ex(3, "Wir wollten am Samstag Fußball spielen.", "We wanted to play football on Saturday.", "wollten",
       "wollen has no umlaut, so only -te plus the wir-ending -n is added: wollten.",
       "wollen hat keinen Umlaut. Du hängst nur -te und die Endung an.",
       {"Wir": "we", "wollten": "wanted to (wollen, Präteritum)", "am": "on (an + dem)",
        "Samstag": "Saturday", "Fußball": "football, soccer", "spielen": "to play (infinitive)"}, 1, "basic"),
    ex(4, "Durftet ihr im Unterricht telefonieren?", "Were you allowed to make phone calls in class?", "Durftet",
       "In a question the modal comes first: Durftet ihr …? The ihr-ending is -t.",
       "In der Frage steht das Modalverb zuerst. Die ihr-Endung ist -t.",
       {"Durftet": "were allowed to (dürfen, Präteritum, ihr)", "ihr": "you (plural)",
        "im": "in the (in + dem)", "Unterricht": "class, lesson", "telefonieren": "to make a phone call"},
       2, "intermediate"),
    ex(5, "Ich sollte um acht Uhr im Büro sein.", "I was supposed to be at the office at eight.", "sollte",
       "sollte means somebody else set the plan. sein stays as an infinitive at the end.",
       "sollte heißt: eine andere Person sagt das. Der Infinitiv sein steht am Ende.",
       {"Ich": "I", "sollte": "was supposed to (sollen, Präteritum)", "um": "at",
        "acht": "eight", "Uhr": "o'clock", "im": "in the (in + dem)", "Büro": "office",
        "sein": "to be (infinitive)"}, 2, "intermediate"),
    ex(6, "Früher mochte ich keinen Kaffee.", "I didn't like coffee back then.", "mochte",
       "mögen changes g to ch: mochte. Früher in position 1 pushes ich behind the verb.",
       "mögen ändert g zu ch: mochte. Nach Früher steht das Verb, dann ich.",
       {"Früher": "back then, in the past", "mochte": "liked (mögen, Präteritum)", "ich": "I",
        "keinen": "no, not any (Akkusativ, maskulin)", "Kaffee": "coffee"}, 2, "intermediate"),
    ex(7, "Musstest du gestern lange arbeiten?", "Did you have to work a long time yesterday?", "Musstest",
       "The du-form adds -st after -te: musstest. In a yes/no question the modal opens the sentence.",
       "Bei du kommt nach -te noch ein -st: musstest. In der Frage steht das Verb zuerst.",
       {"Musstest": "did you have to (müssen, Präteritum, du)", "du": "you", "gestern": "yesterday",
        "lange": "for a long time", "arbeiten": "to work (infinitive)"}, 2, "intermediate"),
    ex(8, "Ich hatte keine Zeit. Ich musste arbeiten.", "I had no time. I had to work.", "musste",
       "hatte and a past modal are the standard pair in a Goethe A2 SMS (Schreiben Teil 1).",
       "hatte und ein Modalverb im Präteritum passen gut zusammen. Das brauchst du in der SMS.",
       {"Ich": "I", "hatte": "had (haben, Präteritum)", "keine": "no, not any (feminine)",
        "Zeit": "time", "musste": "had to (müssen, Präteritum)", "arbeiten": "to work (infinitive)"},
       2, "exam"),
    ex(9, "Sie wollte nach Hause.", "She wanted to go home.", "wollte",
       "No infinitive is needed here: gehen is obvious from nach Hause.",
       "Hier fehlt der Infinitiv. Bei nach Hause versteht man gehen.",
       {"Sie": "she", "wollte": "wanted to (wollen, Präteritum)", "nach": "to",
        "Hause": "home (nach Hause = home, with movement)"}, 3, "complex"),
    ex(10, "Wir konnten die Wohnung nicht bezahlen.", "We couldn't pay for the apartment.", "konnten",
       "The wir-form ends in -n: konnten. nicht stands before the infinitive at the end.",
       "Die wir-Form endet auf -n: konnten. nicht steht vor dem Infinitiv.",
       {"Wir": "we", "konnten": "could, were able to (können, Präteritum, wir)", "die": "the (feminine)",
        "Wohnung": "apartment, flat", "nicht": "not", "bezahlen": "to pay (infinitive)"}, 3, "complex"),
]

def fb(stage, oi, q_de, q_en, answer, accept, expl_en, expl_de, why_en, why_de, diff):
    return {
        "exercise_type": "fill_blank", "question_de": q_de, "question_en": q_en, "options": None,
        "correct_answer": answer, "acceptable_answers": accept,
        "explanation_en": expl_en, "explanation_de": expl_de, "hint": None,
        "why_correct_en": why_en, "why_correct_de": why_de,
        "difficulty": diff, "stage": stage, "order_index": oi, "related_rule_title": None,
    }

def mc(stage, oi, q_de, q_en, options, answer, expl_en, expl_de, why_en, why_de, diff):
    return {
        "exercise_type": "multiple_choice", "question_de": q_de, "question_en": q_en,
        "options": options, "correct_answer": answer, "acceptable_answers": None,
        "explanation_en": expl_en, "explanation_de": expl_de, "hint": None,
        "why_correct_en": why_en, "why_correct_de": why_de,
        "difficulty": diff, "stage": stage, "order_index": oi, "related_rule_title": None,
    }

def typed(kind, stage, oi, q_de, q_en, answer, accept, expl_en, expl_de, why_en, why_de, diff):
    return {
        "exercise_type": kind, "question_de": q_de, "question_en": q_en, "options": None,
        "correct_answer": answer, "acceptable_answers": accept,
        "explanation_en": expl_en, "explanation_de": expl_de, "hint": None,
        "why_correct_en": why_en, "why_correct_de": why_de,
        "difficulty": diff, "stage": stage, "order_index": oi, "related_rule_title": None,
    }

def both(s):
    """sentence with and without its final punctuation."""
    out = [s]
    if s and s[-1] in '.?!':
        out.append(s[:-1])
    return out

exercises = []

# ---------------------------------------------------------------- stage 4 ---
exercises.append(fb(4, 1,
    "Ich ___ dich gestern nicht anrufen. (können, Präteritum, ich)",
    "Fill in the past modal: I couldn't call you yesterday. (verb: können, Präteritum, ich)",
    "konnte", ["konnte"],
    "können → konn- (no umlaut) + -te → konnte. ich takes no extra ending.",
    "können → konn- ohne Umlaut, plus -te: konnte. ich hat keine Endung.",
    "The infinitive of the separable verb anrufen stays whole and closes the sentence.",
    "Der Infinitiv anrufen bleibt ein Wort und steht am Ende.", 1))
exercises.append(fb(4, 2,
    "___ du gestern früh aufstehen? (müssen, Präteritum, du)",
    "Fill in the past modal at the start of the question: Did you have to get up early yesterday? (verb: müssen, Präteritum, du)",
    "Musstest", ["Musstest", "musstest"],
    "müssen → muss- + -te + du-ending -st → musstest. In a question it opens the sentence.",
    "müssen → muss- plus -te, dann bei du noch ein -st: musstest.",
    "The du-form is musstest; aufstehen stays an infinitive at the end.",
    "Die du-Form heißt musstest. Der Infinitiv aufstehen steht am Ende.", 1))
exercises.append(fb(4, 3,
    "Er ___ am Samstag Fußball spielen. (wollen, Präteritum, er)",
    "Fill in the past modal: He wanted to play football on Saturday. (verb: wollen, Präteritum, er)",
    "wollte", ["wollte"],
    "wollen has no umlaut: woll- + -te → wollte. er/sie/es takes no extra ending.",
    "wollen hat keinen Umlaut: woll- plus -te. er/sie/es hat keine Endung.",
    "The er-form and the ich-form are always identical: wollte.",
    "Die er-Form und die ich-Form sind immer gleich: wollte.", 1))
exercises.append(fb(4, 4,
    "Ihr ___ nicht mit dem Auto kommen. (dürfen, Präteritum, ihr)",
    "Fill in the past modal: You were not allowed to come by car. (verb: dürfen, Präteritum, ihr)",
    "durftet", ["durftet"],
    "dürfen → durf- (umlaut gone) + -te + ihr-ending -t → durftet.",
    "dürfen → durf- ohne Umlaut, plus -te und die ihr-Endung -t: durftet.",
    "The ihr-form ends in -t: durftet, konntet, musstet.",
    "Die ihr-Form endet auf -t: durftet, konntet, musstet.", 2))
exercises.append(fb(4, 5,
    "Wir ___ um neun Uhr im Kurs sein. (sollen, Präteritum, wir)",
    "Fill in the past modal: We were supposed to be in class at nine. (verb: sollen, Präteritum, wir)",
    "sollten", ["sollten"],
    "sollen has no umlaut: soll- + -te + -n → sollten. sein stays at the end.",
    "sollen hat keinen Umlaut: soll- plus -te und -n. Der Infinitiv sein steht am Ende.",
    "sollten means somebody else set the time — a plan, not your own wish.",
    "sollten heißt: eine andere Person macht den Plan.", 2))
exercises.append(fb(4, 6,
    "Wir ___ den Film sehr. (mögen, Präteritum, wir)",
    "Fill in the past modal: We liked the film a lot. (verb: mögen, Präteritum, wir)",
    "mochten", ["mochten"],
    "mögen is the only modal that swaps a consonant: mög- → moch-, then -te plus the wir-ending -n.",
    "Bei mögen wird g zu ch: moch-. Dazu kommen -te und die wir-Endung -n.",
    "mochten needs no infinitive here: mögen takes a plain object, den Film.",
    "mochten braucht hier keinen Infinitiv. mögen nimmt ein Objekt: den Film.", 2))
exercises.append(mc(4, 7,
    "Ich ___ das Fenster nicht öffnen. (können, Präteritum, ich)",
    "Which form is correct? I couldn't open the window. (verb: können, Präteritum, ich)",
    ["könnte", "konnt", "konnte", "gekonnt"], "konnte",
    "The Präteritum drops the umlaut and adds -te: konnte.",
    "Das Präteritum hat keinen Umlaut und endet auf -te: konnte.",
    "konnt is missing the -te, gekonnt is a participle, and könnte carries an umlaut the Präteritum never has.",
    "konnt hat kein -te. gekonnt ist ein Partizip. könnte hat einen Umlaut.", 2))
exercises.append(mc(4, 8,
    "Wann ___ du nach Hause? (müssen, Präteritum, du)",
    "Which form is correct? When did you have to go home? (verb: müssen, Präteritum, du)",
    ["musstest", "müsstest", "musste", "mustest"], "musstest",
    "The du-form of müssen in the Präteritum is musstest — two s, then -test.",
    "Die du-Form von müssen heißt musstest. Zwei s, dann -test.",
    "musste is the ich/er-form, müsstest keeps an umlaut, and mustest is missing an s.",
    "musste ist die ich-Form. müsstest hat einen Umlaut. mustest hat nur ein s.", 2))
exercises.append(fb(4, 9,
    "Ich ___ gestern krank. Ich konnte nicht kommen. (sein, Präteritum, ich)",
    "Fill in the past of sein: I was ill yesterday. I couldn't come. (verb: sein, Präteritum, ich)",
    "war", ["war"],
    "war is the Präteritum of sein and the natural partner of a past modal.",
    "war ist das Präteritum von sein. Es passt gut zu einem Modalverb.",
    "Reason first, then the modal: Ich war krank. Ich konnte nicht kommen.",
    "Zuerst der Grund, dann das Modalverb: Ich war krank. Ich konnte nicht kommen.", 1))
exercises.append(fb(4, 10,
    "Wir ___ keine Zeit. Wir mussten arbeiten. (haben, Präteritum, wir)",
    "Fill in the past of haben: We had no time. We had to work. (verb: haben, Präteritum, wir)",
    "hatten", ["hatten"],
    "hatten is the wir-form of the Präteritum of haben — the same endings the modals take.",
    "hatten ist die wir-Form von haben im Präteritum. Die Endungen sind gleich.",
    "hatte, hattest, hatten, hattet — konnte follows exactly this pattern.",
    "Die Endungen von hatte und konnte sind gleich.", 2))
exercises.append(typed("error_correction", 4, 11,
    "Finde den Fehler: Sie musste gestern eingekauft.",
    "Correct the sentence. A modal needs an infinitive, not a participle. (She had to do the shopping yesterday.)",
    "Sie musste gestern einkaufen.",
    both("Sie musste gestern einkaufen.") + both("Gestern musste sie einkaufen."),
    "After a modal verb German uses the infinitive: einkaufen, not eingekauft.",
    "Nach dem Modalverb steht der Infinitiv: einkaufen, nicht eingekauft.",
    "musste + einkaufen builds the bracket; eingekauft belongs to the Perfekt with haben.",
    "musste und einkaufen bilden die Satzklammer. eingekauft gehört zum Perfekt.", 2))
exercises.append(typed("error_correction", 4, 12,
    "Finde den Fehler: Er musste kaufen eine Fahrkarte.",
    "Correct the word order. Keep the opener Er and move only the infinitive. (He had to buy a ticket.)",
    "Er musste eine Fahrkarte kaufen.",
    both("Er musste eine Fahrkarte kaufen."),
    "The infinitive stands at the very end: Er musste eine Fahrkarte kaufen.",
    "Der Infinitiv steht ganz am Ende: Er musste eine Fahrkarte kaufen.",
    "Only the infinitive moves — the task fixes the opener Er, so no other order is tested here.",
    "Der Satzanfang bleibt gleich. Nur der Infinitiv geht ans Ende.", 3))
exercises.append(mc(4, 13,
    "___ ihr die Wohnung? (mögen, Präteritum, ihr)",
    "Which form is correct? Did you like the apartment? (verb: mögen, Präteritum, ihr)",
    ["Möchtet", "Mochtet", "Mochtetet", "Gemocht"], "Mochtet",
    "In the Präteritum of mögen, g becomes ch and ihr adds -t: mochtet.",
    "Bei mögen wird g zu ch. Die ihr-Endung ist -t: mochtet.",
    "Möchtet is present, Mochtetet does not exist, Gemocht is a participle.",
    "Möchtet ist Gegenwart. Mochtetet gibt es nicht. Gemocht ist ein Partizip.", 2))

# ---------------------------------------------------------------- stage 5 ---
exercises.append(typed("sentence_building", 5, 1,
    "Schreib den Satz: [ich / gestern Abend / nicht kommen / können]",
    "Write the sentence in the Präteritum: I couldn't come yesterday evening. (können, ich; start with Ich or Gestern Abend)",
    "Ich konnte gestern Abend nicht kommen.",
    both("Ich konnte gestern Abend nicht kommen.") + both("Gestern Abend konnte ich nicht kommen."),
    "können → konnte in position 2, kommen at the end. Gestern Abend may also open the sentence.",
    "Aus können wird konnte. Position 2 für das Modalverb, kommen am Ende.",
    "Both orders are correct: position 1 is free, and the verb keeps position 2.",
    "Beide Sätze sind richtig. Position 1 ist frei, das Verb bleibt auf Position 2.", 2))
exercises.append(typed("sentence_building", 5, 2,
    "Schreib den Satz: [wir / am Sonntag / ins Kino gehen / wollen]",
    "Write the sentence in the Präteritum: We wanted to go to the cinema on Sunday. (wollen, wir)",
    "Wir wollten am Sonntag ins Kino gehen.",
    both("Wir wollten am Sonntag ins Kino gehen.") + both("Am Sonntag wollten wir ins Kino gehen."),
    "wollen → wollten. The infinitive gehen closes the sentence after ins Kino.",
    "Aus wollen wird wollten. Der Infinitiv gehen steht am Ende, nach ins Kino.",
    "Am Sonntag may stand in position 1; then wollten still follows immediately.",
    "Am Sonntag kann auf Position 1 stehen. Dann kommt wollten direkt danach.", 2))
exercises.append(typed("sentence_building", 5, 3,
    "Schreib die Frage: [du / gestern / zum Arzt gehen / müssen]",
    "Write the yes/no question in the Präteritum: Did you have to go to the doctor yesterday? (müssen, du; start with the verb)",
    "Musstest du gestern zum Arzt gehen?",
    both("Musstest du gestern zum Arzt gehen?"),
    "In a yes/no question the modal opens the sentence: Musstest du …?",
    "In der Ja/Nein-Frage steht das Modalverb zuerst: Musstest du …?",
    "The du-form is musstest; gehen still closes the bracket at the end.",
    "Die du-Form heißt musstest. gehen steht am Ende.", 2))
exercises.append(typed("sentence_building", 5, 4,
    "Schreib die Frage: [ihr / im Museum / fotografieren / dürfen]",
    "Write the yes/no question in the Präteritum: Were you allowed to take photos in the museum? (dürfen, ihr; start with the verb)",
    "Durftet ihr im Museum fotografieren?",
    both("Durftet ihr im Museum fotografieren?"),
    "dürfen → durftet for ihr. The question starts with the modal, the infinitive ends it.",
    "Aus dürfen wird bei ihr durftet. Die Frage beginnt mit dem Modalverb.",
    "The ihr-ending is -t: durftet — and it is capitalised because it starts the question.",
    "Die ihr-Endung ist -t: durftet. Am Satzanfang schreibst du es groß.", 2))
exercises.append(typed("sentence_building", 5, 5,
    "Schreib den Satz: [ich / um sieben Uhr / zu Hause sein / sollen]",
    "Write the sentence in the Präteritum: I was supposed to be home at seven. (sollen, ich)",
    "Ich sollte um sieben Uhr zu Hause sein.",
    both("Ich sollte um sieben Uhr zu Hause sein.") + both("Um sieben Uhr sollte ich zu Hause sein."),
    "sollen → sollte. sein is an infinitive here and stands at the end.",
    "Aus sollen wird sollte. sein ist hier ein Infinitiv und steht am Ende.",
    "Um sieben Uhr may open the sentence; sollte then keeps position 2.",
    "Um sieben Uhr kann auf Position 1 stehen. sollte bleibt auf Position 2.", 3))
exercises.append(typed("sentence_building", 5, 6,
    "Schreib den Satz: [ich / das Buch / sehr / mögen]",
    "Write the sentence in the Präteritum: I liked the book a lot. (mögen, ich)",
    "Ich mochte das Buch sehr.",
    both("Ich mochte das Buch sehr.") + both("Das Buch mochte ich sehr."),
    "mögen → mochte. Here mögen takes an object and needs no infinitive.",
    "Aus mögen wird mochte. Hier braucht mögen keinen Infinitiv, nur ein Objekt.",
    "The object Das Buch may open the sentence instead of ich; mochte keeps position 2 either way.",
    "Auch Das Buch kann auf Position 1 stehen. mochte bleibt auf Position 2.", 3))
exercises.append(typed("sentence_building", 5, 7,
    "Schreib den Satz: [wir / das Zimmer / nicht finden / können]",
    "Write the sentence in the Präteritum: We couldn't find the room. (können, wir)",
    "Wir konnten das Zimmer nicht finden.",
    both("Wir konnten das Zimmer nicht finden.") + both("Das Zimmer konnten wir nicht finden."),
    "können → konnten. nicht stands directly before the infinitive finden.",
    "Aus können wird konnten. nicht steht direkt vor dem Infinitiv finden.",
    "The object Das Zimmer may also open the sentence; konnten then still holds position 2.",
    "Auch Das Zimmer kann auf Position 1 stehen. konnten bleibt auf Position 2.", 3))
exercises.append(typed("sentence_building", 5, 8,
    "Schreib im Präteritum: Ich möchte einen Termin haben.",
    "Rewrite in the Präteritum: I would like to have an appointment. → I wanted to have an appointment. (möchte has no past form of its own)",
    "Ich wollte einen Termin haben.",
    both("Ich wollte einen Termin haben.") + both("Ich wollte einen Termin."),
    "möchte has no Präteritum, so wollte takes over: Ich wollte einen Termin haben. Dropping haben (Ich wollte einen Termin.) is just as correct.",
    "möchte hat kein Präteritum. Dafür nimmst du wollte.",
    "mochte would mean liked; the polite wish möchte becomes wollte in the past. The short form without haben counts too.",
    "mochte heißt: du hattest etwas gern. Aus möchte wird im Präteritum wollte.", 3))
exercises.append(typed("sentence_building", 5, 9,
    "Schreib im Präteritum: Sie muss lange warten.",
    "Rewrite in the Präteritum: She has to wait a long time. → She had to wait a long time. (müssen, sie)",
    "Sie musste lange warten.",
    both("Sie musste lange warten."),
    "muss → musste. Only the modal changes; warten stays at the end.",
    "Aus muss wird musste. Nur das Modalverb ändert sich, warten bleibt am Ende.",
    "sie musste has no extra ending — the same form as ich musste.",
    "sie musste hat keine Endung. Die ich-Form ist gleich.", 2))
exercises.append(typed("sentence_building", 5, 10,
    "Schreib im Präteritum: Wir dürfen hier nicht parken.",
    "Rewrite in the Präteritum: We are not allowed to park here. → We were not allowed to park here. (dürfen, wir)",
    "Wir durften hier nicht parken.",
    both("Wir durften hier nicht parken."),
    "dürfen → durften: the umlaut disappears, -te plus -n is added.",
    "Aus dürfen wird durften: der Umlaut fällt weg, dann -te und -n.",
    "Word order does not move at all — only dürfen becomes durften.",
    "Der Satz bleibt gleich. Nur aus dürfen wird durften.", 2))
exercises.append(typed("error_correction", 5, 11,
    "Finde den Fehler: Ihr habt gestern gewollt telefonieren.",
    "Correct the sentence. Modal verbs use the Präteritum, not this form. (You wanted to make a phone call yesterday.)",
    "Ihr wolltet gestern telefonieren.",
    both("Ihr wolltet gestern telefonieren.") + both("Gestern wolltet ihr telefonieren."),
    "There is no habt gewollt telefonieren. Everyday German uses the Präteritum: Ihr wolltet telefonieren.",
    "Die Form habt gewollt telefonieren gibt es nicht. Nimm das Präteritum: Ihr wolltet telefonieren.",
    "One past modal replaces the whole Perfekt here: wolltet in position 2, telefonieren at the end.",
    "Ein Modalverb im Präteritum reicht: wolltet auf Position 2, telefonieren am Ende.", 3))
exercises.append(mc(5, 12,
    "Welcher Satz ist richtig?",
    "Which sentence has the correct word order for: I had to work a long time on Monday.",
    ["Ich musste lange arbeiten am Montag.", "Ich am Montag musste lange arbeiten.",
     "Ich musste am Montag arbeiten lange.", "Ich musste am Montag lange arbeiten."],
    "Ich musste am Montag lange arbeiten.",
    "The modal takes position 2 and the infinitive the very end: Ich musste am Montag lange arbeiten.",
    "Das Modalverb steht auf Position 2, der Infinitiv am Ende.",
    "am Montag and lange stand inside the bracket, between musste and arbeiten.",
    "am Montag und lange stehen in der Satzklammer, zwischen musste und arbeiten.", 2))
exercises.append(typed("sentence_building", 5, 13,
    "Schreib eine SMS: [ich / gestern / krank sein] + [ich / nicht zum Kurs kommen können]",
    "Write the two-sentence apology for Schreiben Teil 1: I was ill yesterday. I couldn't come to the class. (sein and können, Präteritum, ich)",
    "Ich war gestern krank. Ich konnte nicht zum Kurs kommen.",
    both("Ich war gestern krank. Ich konnte nicht zum Kurs kommen.")
    + both("Gestern war ich krank. Ich konnte nicht zum Kurs kommen."),
    "war gives the reason, the past modal gives the result — the standard SMS pair.",
    "war nennt den Grund, das Modalverb die Folge. So schreibst du eine SMS.",
    "Both sentences keep the verb in position 2; gestern may also open the first one.",
    "In beiden Sätzen steht das Verb auf Position 2. gestern kann auch vorn stehen.", 3))

doc = {"topic": topic, "rules": rules, "examples": examples, "exercises": exercises}

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, 'w', encoding='utf-8') as f:
    json.dump(doc, f, ensure_ascii=False, indent=2)
    f.write('\n')
print('wrote', OUT, 'rules', len(rules), 'examples', len(examples), 'exercises', len(exercises))
