# -*- coding: utf-8 -*-
# Wave 4 PR A2 - author E1, round 2 (rebuilt after review-E1-1.md)
import json, os
OUT = "/tmp/claude-0/-home-user-deutschmeister/c2792a5e-db22-5773-87d6-2f95d17dddab/scratchpad/wave4/extend/typed-a2.1"

def ex(t, qde, qen, ca, acc, exen, exde, wcen, wcde, diff, stage, oi, hint=None):
    return {"exercise_type": t, "question_de": qde, "question_en": qen, "options": None,
            "correct_answer": ca, "acceptable_answers": acc, "explanation_en": exen,
            "explanation_de": exde, "hint": hint, "why_correct_en": wcen, "why_correct_de": wcde,
            "difficulty": diff, "stage": stage, "order_index": oi, "related_rule_title": None}

def sb(*sents):
    """statement variants: with and without the final period"""
    out = []
    for s in sents:
        out += [s, s.rstrip(".")]
    return out

def imp(*sents):
    """imperative variants: '.', '!' and bare, for each accepted word order"""
    out = []
    for s in sents:
        base = s.rstrip(".!")
        out += [base + ".", base + "!", base]
    return out

def qu(*sents):
    out = []
    for s in sents:
        base = s.rstrip("?")
        out += [base + "?", base]
    return out

def write(slug, sub, exercises):
    doc = {"extend": {"slug": slug, "sub_level": sub}, "exercises": exercises}
    p = os.path.join(OUT, slug + ".json")
    with open(p, "w", encoding="utf-8") as f:
        json.dump(doc, f, ensure_ascii=False, indent=2); f.write("\n")
    print(p, len(exercises))

# ---------------------------------------------------------------- dative-case
dat = [
ex("fill_blank",
   "Der Koffer gehört ___ Onkel. (mein Onkel)",
   "The suitcase belongs to my uncle. Type the possessive: gehören takes the dative, masculine 'mein'.",
   "meinem", ["meinem"],
   "gehören always takes a dative object, and in the masculine dative mein becomes meinem.",
   "gehören hat immer ein Dativobjekt. Maskulin: mein → meinem.",
   "Wem gehört der Koffer? Meinem Onkel. Masculine dative: mein → meinem.",
   "Wem gehört der Koffer? Meinem Onkel. Maskulin Dativ: mein → meinem.",
   1, 4, 16),
ex("fill_blank",
   "Der Kuchen schmeckt ___ Schwester. (meine Schwester)",
   "The cake tastes good to my sister. Type the possessive: schmecken takes the dative, feminine 'meine'.",
   "meiner", ["meiner"],
   "schmecken takes a dative object, and in the feminine dative meine becomes meiner.",
   "schmecken hat ein Dativobjekt. Feminin: meine → meiner.",
   "Wem schmeckt der Kuchen? Meiner Schwester. Feminine dative: meine → meiner.",
   "Wem schmeckt der Kuchen? Meiner Schwester. Feminin Dativ: meine → meiner.",
   1, 4, 17),
ex("fill_blank",
   "Ich kaufe ___ Kind ein Eis. (ein Kind)",
   "I am buying a child an ice cream. Type the indefinite article: neuter dative for the person who gets it.",
   "einem", ["einem"],
   "Kind is the person who receives, so it stands in the dative: ein becomes einem.",
   "Kind ist hier das Dativobjekt. Neutrum: ein → einem.",
   "Wem kaufe ich ein Eis? Einem Kind. Neuter dative: ein → einem.",
   "Wem kaufe ich ein Eis? Einem Kind. Neutrum Dativ: ein → einem.",
   2, 4, 18),
ex("fill_blank",
   "Die Wohnung gefällt ___ sehr gut. (wir)",
   "We like the flat a lot. Type the dative pronoun for 'wir'.",
   "uns", ["uns"],
   "gefallen takes a dative object, so wir becomes the dative pronoun uns.",
   "gefallen hat ein Dativobjekt. wir wird im Dativ zu uns.",
   "Wem gefällt die Wohnung? Uns. The dative form of wir is uns.",
   "Wem gefällt die Wohnung? Uns. Die Dativform von wir ist uns.",
   2, 4, 19),
ex("sentence_building",
   "Schreib den Satz: [wir / helfen / unsere Nachbarin]",
   "Write the sentence: We help our neighbour (female). Verb helfen, subject wir; the object goes into the dative.",
   "Wir helfen unserer Nachbarin.", sb("Wir helfen unserer Nachbarin."),
   "helfen never takes an accusative object; its object is always dative.",
   "helfen hat nie ein Akkusativobjekt. Das Objekt steht immer im Dativ.",
   "Wem helfen wir? Unserer Nachbarin. Feminine dative: unsere → unserer.",
   "Wem helfen wir? Unserer Nachbarin. Feminin Dativ: unsere → unserer.",
   2, 5, 20),
ex("sentence_building",
   "Schreib den Satz: [der Mantel / gehören / die Lehrerin]",
   "Write the sentence: The coat belongs to the teacher (female). Start with 'Der Mantel'; gehören takes the dative.",
   "Der Mantel gehört der Lehrerin.", sb("Der Mantel gehört der Lehrerin."),
   "The subject der Mantel stays nominative; die Lehrerin becomes der Lehrerin in the dative.",
   "Das Subjekt der Mantel bleibt Nominativ. die Lehrerin wird zu der Lehrerin.",
   "Wem gehört der Mantel? Der Lehrerin. Feminine dative: die → der.",
   "Wem gehört der Mantel? Der Lehrerin. Feminin Dativ: die → der.",
   2, 5, 21),
ex("sentence_building",
   "Schreib den Satz: [wir / schenken / unsere Eltern / eine Reise]",
   "Write the sentence: We give our parents a trip as a present. Start with 'Wir'; dative object before accusative object.",
   "Wir schenken unseren Eltern eine Reise.", sb("Wir schenken unseren Eltern eine Reise."),
   "The person who receives is dative and comes first; the thing given is accusative.",
   "Die Person im Dativ kommt zuerst, die Sache im Akkusativ danach.",
   "The possessive shows the dative plural here: unsere → unseren, and dative comes before accusative.",
   "Im Dativ Plural: unsere → unseren. Dativ steht vor Akkusativ.",
   3, 5, 22, "Wem? zuerst, was? danach."),
ex("sentence_building",
   "Schreib den Satz: [ich / zeigen / mein Freund / die Fotos]",
   "Write the sentence: I show my friend the photos. Start with 'Ich'; dative person first, accusative thing second.",
   "Ich zeige meinem Freund die Fotos.", sb("Ich zeige meinem Freund die Fotos."),
   "mein Freund is the person who receives (dative); die Fotos is the direct object (accusative).",
   "mein Freund ist das Dativobjekt. die Fotos ist das Akkusativobjekt.",
   "Wem zeige ich? Meinem Freund. Was zeige ich? Die Fotos. Plural die stays die.",
   "Wem zeige ich? Meinem Freund. Was zeige ich? Die Fotos. Plural die bleibt die.",
   3, 5, 23, "Wem? → meinem Freund."),
ex("error_correction",
   "Korrigiere den Satz: „Die Jacke passt mich nicht.“",
   "Correct the sentence: passen takes a dative pronoun, not an accusative one. Write the whole sentence.",
   "Die Jacke passt mir nicht.", sb("Die Jacke passt mir nicht."),
   "mich is accusative; passen needs the dative pronoun mir.",
   "mich ist Akkusativ. passen braucht das Dativpronomen mir.",
   "Wem passt die Jacke nicht? Mir. The dative of ich is mir.",
   "Wem passt die Jacke nicht? Mir. Der Dativ von ich ist mir.",
   2, 5, 24),
ex("error_correction",
   "Korrigiere den Satz: „Ich schreibe meine Schwester eine E-Mail.“",
   "Correct the sentence: the person who receives the e-mail must be dative. Write the whole sentence.",
   "Ich schreibe meiner Schwester eine E-Mail.", sb("Ich schreibe meiner Schwester eine E-Mail."),
   "meine Schwester is the person who receives, so it takes the dative: meiner Schwester.",
   "meine Schwester bekommt die E-Mail. Das ist der Dativ: meiner Schwester.",
   "Wem schreibe ich? Meiner Schwester. Was schreibe ich? Eine E-Mail.",
   "Wem schreibe ich? Meiner Schwester. Was schreibe ich? Eine E-Mail.",
   2, 5, 25),
ex("error_correction",
   "Korrigiere den Satz: „Wir helfen die Kinder.“",
   "Correct the sentence: helfen takes the dative, and the dative plural also needs an -n on the noun. Write the whole sentence.",
   "Wir helfen den Kindern.", sb("Wir helfen den Kindern."),
   "In the dative plural the article becomes den and the noun itself adds -n.",
   "Im Dativ Plural wird der Artikel zu den. Das Nomen bekommt auch ein -n.",
   "Wem helfen wir? Den Kindern. Dative plural: die Kinder → den Kindern.",
   "Wem helfen wir? Den Kindern. Dativ Plural: die Kinder → den Kindern.",
   3, 5, 26, "Der Dativ Plural endet auf -n."),
ex("error_correction",
   "Korrigiere den Satz: „Der Kellner bringt die Frau die Rechnung.“",
   "Correct the sentence: the person who receives must be dative. Write the whole sentence.",
   "Der Kellner bringt der Frau die Rechnung.",
   sb("Der Kellner bringt der Frau die Rechnung.", "Der Kellner bringt die Rechnung der Frau."),
   "die Frau receives the bill, so it takes the dative: der Frau. die Rechnung stays accusative.",
   "die Frau bekommt die Rechnung. Sie steht im Dativ: der Frau.",
   "Wem bringt der Kellner? Der Frau. Was? Die Rechnung. Dative comes first.",
   "Wem bringt der Kellner? Der Frau. Was? Die Rechnung. Der Dativ kommt zuerst.",
   3, 5, 27),
]
write("dative-case", "A2.1", dat)

# -------------------------------------------------------- prepositions-dative
prep = [
ex("fill_blank",
   "Ich spreche oft mit ___ Nachbarin. (die Nachbarin)",
   "I often talk to the neighbour (female). Type the article: mit always takes the dative, feminine.",
   "der", ["der"],
   "mit is a dative preposition, so die Nachbarin becomes der Nachbarin.",
   "mit ist eine Dativpräposition. Feminin: die → der.",
   "mit + Dativ: die Nachbarin → der Nachbarin.",
   "mit + Dativ: die Nachbarin → der Nachbarin.",
   1, 4, 16),
ex("fill_blank",
   "Nach ___ Arbeit gehe ich einkaufen. (die Arbeit)",
   "After work I go shopping. Type the article: here nach is a time preposition and takes the dative.",
   "der", ["der"],
   "nach is a dative preposition, so die Arbeit becomes der Arbeit.",
   "nach ist eine Dativpräposition. die Arbeit wird zu der Arbeit.",
   "nach + Dativ: die Arbeit → der Arbeit. The verb stays in position two.",
   "nach + Dativ: die Arbeit → der Arbeit. Das Verb bleibt auf Position zwei.",
   2, 4, 17),
ex("fill_blank",
   "Wir wohnen seit ___ Monat in Berlin. (ein Monat)",
   "We have been living in Berlin for a month. Type the article: seit takes the dative, masculine.",
   "einem", ["einem"],
   "seit is a dative preposition, so ein Monat becomes einem Monat.",
   "seit ist eine Dativpräposition. Maskulin: ein → einem.",
   "seit + Dativ: ein Monat → einem Monat, and German uses the present tense here.",
   "seit + Dativ: ein Monat → einem Monat. Deutsch benutzt hier das Präsens.",
   2, 4, 18),
ex("fill_blank",
   "Am Samstag fahre ich ___ Flughafen. (zu + dem)",
   "On Saturday I drive to the airport. Type the short form of zu + dem (the long form counts too).",
   "zum", ["zum", "zu dem"],
   "zu takes the dative, and out of zu + dem you normally make zum.",
   "zu steht mit Dativ. Aus zu + dem macht man normalerweise zum.",
   "zu dem Flughafen → zum Flughafen. The short form is the everyday one.",
   "zu dem Flughafen → zum Flughafen. Die Kurzform ist die Alltagsform.",
   1, 4, 19),
ex("sentence_building",
   "Schreib den Satz: [ich / fahren / mit / mein Fahrrad / zu / die Arbeit]",
   "Write the sentence: I ride my bike to work. Both prepositions take the dative; either word order counts.",
   "Ich fahre mit meinem Fahrrad zur Arbeit.",
   sb("Ich fahre mit meinem Fahrrad zur Arbeit.", "Mit meinem Fahrrad fahre ich zur Arbeit."),
   "mit + Dativ gives meinem Fahrrad; zu + der Arbeit becomes zur Arbeit.",
   "mit + Dativ: meinem Fahrrad. zu + der Arbeit wird zur Arbeit.",
   "mein → meinem after mit; zu der Arbeit → zur Arbeit.",
   "mein → meinem nach mit. zu der Arbeit → zur Arbeit.",
   2, 5, 20),
ex("sentence_building",
   "Schreib den Satz: [ich / arbeiten / seit / drei Monate / in Hamburg]",
   "Write the sentence: I have been working in Hamburg for three months. Start with 'Ich'; seit takes the dative plural.",
   "Ich arbeite seit drei Monaten in Hamburg.", sb("Ich arbeite seit drei Monaten in Hamburg."),
   "seit takes the dative, and the dative plural adds -n: drei Monate → drei Monaten.",
   "seit steht mit Dativ. Der Dativ Plural bekommt -n: drei Monate → drei Monaten.",
   "German uses the present tense with seit, and the dative plural ends in -n.",
   "Deutsch benutzt mit seit das Präsens. Der Dativ Plural endet auf -n.",
   3, 5, 21, "Der Dativ Plural endet auf -n."),
ex("sentence_building",
   "Schreib den Satz: [nach / das Abendessen / ich / anrufen / meine Freundin]",
   "Write the sentence: After dinner I call my friend (female). Start with 'Nach'; anrufen is separable.",
   "Nach dem Abendessen rufe ich meine Freundin an.",
   sb("Nach dem Abendessen rufe ich meine Freundin an."),
   "nach + dem Abendessen fills position one, so the verb comes second and ich follows it.",
   "nach + dem Abendessen steht auf Position eins. Das Verb kommt auf Position zwei.",
   "Time phrase first means inversion: rufe ich; the prefix an goes to the end.",
   "Zeitangabe zuerst bedeutet Inversion: rufe ich. Das Präfix an steht am Ende.",
   3, 5, 22, "Das Verb steht auf Position zwei."),
ex("sentence_building",
   "Schreib den Satz: [ich / fahren / heute / zu / der Arzt]",
   "Write the sentence: I drive to the doctor today. Start with 'Ich'; the short form is the everyday one.",
   "Ich fahre heute zum Arzt.",
   sb("Ich fahre heute zum Arzt.", "Ich fahre heute zu dem Arzt."),
   "zu takes the dative: der Arzt → dem Arzt, normally shortened to zum Arzt.",
   "zu steht mit Dativ: der Arzt → dem Arzt. Meistens sagt man zum Arzt.",
   "Both zum Arzt and zu dem Arzt are correct; zum is the everyday form.",
   "zum Arzt und zu dem Arzt sind beide richtig. zum ist die Alltagsform.",
   2, 5, 23),
ex("error_correction",
   "Korrigiere den Satz: „Heute Abend gehe ich bei meinen Freunden.“",
   "Correct the sentence: bei says where you are, but this sentence says where you are going. Write the whole sentence.",
   "Heute Abend gehe ich zu meinen Freunden.", sb("Heute Abend gehe ich zu meinen Freunden."),
   "bei answers wo? (Ich bin bei Freunden); for the direction you need zu + Dativ.",
   "bei antwortet auf wo?: Ich bin bei Freunden. Für die Richtung braucht man zu.",
   "gehen shows a direction, so zu meinen Freunden is right; both keep the dative.",
   "gehen zeigt eine Richtung, deshalb passt zu meinen Freunden. Beide stehen mit Dativ.",
   3, 5, 24, "Wohin? → zu."),
ex("error_correction",
   "Korrigiere den Satz: „Ich arbeite bei eine Firma.“",
   "Correct the sentence: bei takes the dative. Write the whole sentence.",
   "Ich arbeite bei einer Firma.", sb("Ich arbeite bei einer Firma."),
   "bei is a dative preposition, so eine Firma becomes einer Firma.",
   "bei ist eine Dativpräposition. Feminin: eine → einer.",
   "bei + Dativ: eine Firma → einer Firma.",
   "bei + Dativ: eine Firma → einer Firma.",
   2, 5, 25),
ex("error_correction",
   "Korrigiere den Satz: „Seit einem Monat habe ich jeden Tag Gitarre gespielt.“",
   "Correct the sentence: the activity is still going on every day, and with seit German then uses the present tense. Start with 'Seit einem Monat'.",
   "Seit einem Monat spiele ich jeden Tag Gitarre.",
   sb("Seit einem Monat spiele ich jeden Tag Gitarre."),
   "seit plus something that still happens every day needs the present tense, not the Perfekt.",
   "seit und etwas, das jeden Tag weiterläuft: Da steht das Präsens, nicht das Perfekt.",
   "Seit einem Monat spiele ich jeden Tag: it still goes on today, so present tense.",
   "Seit einem Monat spiele ich jeden Tag: Es läuft noch heute, also Präsens.",
   3, 5, 26, "seit + Präsens."),
ex("error_correction",
   "Korrigiere den Satz: „Die Apotheke ist gegenüber der Supermarkt.“",
   "Correct the sentence: gegenüber takes the dative, masculine. Write the whole sentence (gegenüber may also stand after the noun).",
   "Die Apotheke ist gegenüber dem Supermarkt.",
   sb("Die Apotheke ist gegenüber dem Supermarkt.", "Die Apotheke ist dem Supermarkt gegenüber."),
   "gegenüber is a dative preposition, so der Supermarkt becomes dem Supermarkt.",
   "gegenüber ist eine Dativpräposition. der Supermarkt wird zu dem Supermarkt.",
   "gegenüber + Dativ: der → dem. gegenüber may stand before or after the noun.",
   "gegenüber + Dativ: der → dem. gegenüber kann vor oder nach dem Nomen stehen.",
   3, 5, 27),
]
write("prepositions-dative", "A2.1", prep)

# ------------------------------------------------------- two-way-prepositions
two = [
ex("fill_blank",
   "Die Kinder spielen ___ Garten. (in + dem, wo?)",
   "The children are playing in the garden. Type the short form of in + dem (the long form counts too).",
   "im", ["im", "in dem"],
   "The question is wo?, so in takes the dative, and in + dem gives im.",
   "Die Frage ist wo?, deshalb steht in mit Dativ. in + dem wird im.",
   "Wo spielen die Kinder? Im Garten. Location means dative.",
   "Wo spielen die Kinder? Im Garten. Position bedeutet Dativ.",
   1, 4, 16),
ex("fill_blank",
   "Stell die Flasche bitte auf ___ Tisch. (wohin? der Tisch)",
   "Please put the bottle on the table. Type the article: stellen answers wohin?, so accusative, masculine.",
   "den", ["den"],
   "stellen describes movement to a place, so auf takes the accusative.",
   "stellen beschreibt eine Bewegung zu einem Ort, deshalb steht auf mit Akkusativ.",
   "Wohin stelle ich die Flasche? Auf den Tisch. Movement means accusative.",
   "Wohin stelle ich die Flasche? Auf den Tisch. Bewegung bedeutet Akkusativ.",
   2, 4, 17),
ex("fill_blank",
   "Das Auto steht vor ___ Haus. (wo? das Haus)",
   "The car is parked in front of the house. Type the article: stehen answers wo?, so dative, neuter.",
   "dem", ["dem"],
   "stehen describes a position, so vor takes the dative.",
   "stehen beschreibt eine Position, deshalb steht vor mit Dativ.",
   "Wo steht das Auto? Vor dem Haus. Neuter dative: das → dem.",
   "Wo steht das Auto? Vor dem Haus. Neutrum Dativ: das → dem.",
   2, 4, 18),
ex("fill_blank",
   "Wir warten ___ Bahnhof. (an + dem, wo?)",
   "We are waiting at the station. Type the short form of an + dem (the long form counts too).",
   "am", ["am", "an dem"],
   "warten describes a position, so an takes the dative, and an + dem gives am.",
   "warten beschreibt eine Position, deshalb steht an mit Dativ. an + dem wird am.",
   "Wo warten wir? Am Bahnhof. Location means dative, not accusative.",
   "Wo warten wir? Am Bahnhof. Position bedeutet Dativ, nicht Akkusativ.",
   2, 4, 19),
ex("sentence_building",
   "Schreib den Satz: [ich / stellen / die Lampe / neben / das Sofa]",
   "Write the sentence: I put the lamp next to the sofa. Start with 'Ich'; stellen answers wohin?.",
   "Ich stelle die Lampe neben das Sofa.", sb("Ich stelle die Lampe neben das Sofa."),
   "stellen means movement to a place, so neben takes the accusative.",
   "stellen bedeutet Bewegung zu einem Ort, deshalb steht neben mit Akkusativ.",
   "Wohin stelle ich die Lampe? Neben das Sofa. Neuter das stays das in the accusative.",
   "Wohin stelle ich die Lampe? Neben das Sofa. Neutrum: das bleibt im Akkusativ das.",
   2, 5, 20),
ex("sentence_building",
   "Schreib den Satz: [die Schuhe / stehen / hinter / die Tür]",
   "Write the sentence: The shoes are behind the door. Start with 'Die Schuhe'; stehen answers wo?.",
   "Die Schuhe stehen hinter der Tür.", sb("Die Schuhe stehen hinter der Tür."),
   "stehen describes a position, so hinter takes the dative: die Tür → der Tür.",
   "stehen beschreibt eine Position, deshalb steht hinter mit Dativ: die Tür → der Tür.",
   "Wo stehen die Schuhe? Hinter der Tür. Position verb, so dative.",
   "Wo stehen die Schuhe? Hinter der Tür. Positionsverb, also Dativ.",
   2, 5, 21),
ex("sentence_building",
   "Schreib den Satz: [wir / fahren / am Sonntag / an / das Meer]",
   "Write the sentence: On Sunday we drive to the sea. Start with 'Wir'; fahren answers wohin?.",
   "Wir fahren am Sonntag ans Meer.",
   sb("Wir fahren am Sonntag ans Meer.", "Wir fahren am Sonntag an das Meer."),
   "fahren means movement, so an takes the accusative, and an + das gives ans.",
   "fahren bedeutet Bewegung, deshalb steht an mit Akkusativ. an + das wird ans.",
   "Wohin fahren wir? Ans Meer. Both ans and an das are correct.",
   "Wohin fahren wir? Ans Meer. ans und an das sind beide richtig.",
   3, 5, 22),
ex("sentence_building",
   "Schreib den Satz: [der Schlüssel / liegen / zwischen / die Bücher]",
   "Write the sentence: The key is lying between the books. Start with 'Der Schlüssel'; liegen answers wo?.",
   "Der Schlüssel liegt zwischen den Büchern.", sb("Der Schlüssel liegt zwischen den Büchern."),
   "liegen describes a position, so zwischen takes the dative; the dative plural adds -n.",
   "liegen beschreibt eine Position, deshalb steht zwischen mit Dativ. Der Dativ Plural bekommt -n.",
   "Wo liegt der Schlüssel? Zwischen den Büchern. Dative plural: die Bücher → den Büchern.",
   "Wo liegt der Schlüssel? Zwischen den Büchern. Dativ Plural: die Bücher → den Büchern.",
   3, 5, 23, "Der Dativ Plural endet auf -n."),
ex("error_correction",
   "Korrigiere den Satz: „Leg den Brief bitte in dem Briefkasten.“",
   "Correct the sentence: legen answers wohin?, so the case after in is wrong. Write the whole sentence.",
   "Leg den Brief bitte in den Briefkasten.",
   imp("Leg den Brief bitte in den Briefkasten.", "Lege den Brief bitte in den Briefkasten.",
       "Bitte leg den Brief in den Briefkasten.", "Bitte lege den Brief in den Briefkasten."),
   "legen is a movement verb, so in needs the accusative den Briefkasten.",
   "legen ist ein Bewegungsverb, deshalb braucht in den Akkusativ den Briefkasten.",
   "Wohin lege ich den Brief? In den Briefkasten. legen → Akkusativ, liegen → Dativ.",
   "Wohin lege ich den Brief? In den Briefkasten. legen → Akkusativ, liegen → Dativ.",
   2, 5, 24),
ex("error_correction",
   "Korrigiere den Satz: „Das Kind sitzt auf den Stuhl.“",
   "Correct the sentence: sitzen answers wo?, so the case after auf is wrong. Write the whole sentence.",
   "Das Kind sitzt auf dem Stuhl.", sb("Das Kind sitzt auf dem Stuhl."),
   "sitzen describes a position, so auf needs the dative dem Stuhl.",
   "sitzen beschreibt eine Position, deshalb braucht auf den Dativ dem Stuhl.",
   "Wo sitzt das Kind? Auf dem Stuhl. sitzen → Dativ, setzen → Akkusativ.",
   "Wo sitzt das Kind? Auf dem Stuhl. sitzen → Dativ, setzen → Akkusativ.",
   2, 5, 25),
ex("error_correction",
   "Korrigiere den Satz: „Hängen Sie das Bild bitte über dem Sofa.“",
   "Correct the sentence: here hängen means putting the picture up, so it answers wohin?. Write the whole sentence.",
   "Hängen Sie das Bild bitte über das Sofa.",
   imp("Hängen Sie das Bild bitte über das Sofa.", "Hängen Sie bitte das Bild über das Sofa."),
   "With a direct object, hängen describes movement, so über takes the accusative.",
   "Mit einem Akkusativobjekt beschreibt hängen eine Bewegung. über steht mit Akkusativ.",
   "Wohin hängen Sie das Bild? Über das Sofa. The picture moves to a new place.",
   "Wohin hängen Sie das Bild? Über das Sofa. Es gibt hier eine Bewegung.",
   3, 5, 26, "Es gibt hier ein Akkusativobjekt: das Bild."),
ex("error_correction",
   "Korrigiere den Satz: „Ich warte vor die Schule.“",
   "Correct the sentence: warten answers wo?, so the case after vor is wrong. Write the whole sentence.",
   "Ich warte vor der Schule.", sb("Ich warte vor der Schule."),
   "warten describes a position, so vor needs the dative der Schule.",
   "warten beschreibt eine Position, deshalb braucht vor den Dativ der Schule.",
   "Wo warte ich? Vor der Schule. No movement, so dative.",
   "Wo warte ich? Vor der Schule. Keine Bewegung, also Dativ.",
   3, 5, 27),
]
write("two-way-prepositions", "A2.1", two)

# ------------------------------------------------------------ separable-verbs
sep = [
ex("fill_blank",
   "Ich ___ am Wochenende mein Zimmer auf. (aufräumen, ich)",
   "I tidy my room at the weekend. Type the conjugated verb for 'ich'; the prefix auf already stands at the end.",
   "räume", ["räume"],
   "In a main clause the prefix auf goes to the end, and you conjugate only räumen.",
   "Im Hauptsatz geht das Präfix auf ans Ende. Du konjugierst nur räumen.",
   "aufräumen splits: ich räume … auf. The stem takes the ich ending -e.",
   "Bei aufräumen steht auf am Ende: ich räume … auf. Der Stamm bekommt -e.",
   1, 4, 16),
ex("fill_blank",
   "Ich hole meine Tochter um vier Uhr ___. (abholen)",
   "I pick my daughter up at four o'clock. Type the separated prefix at the end of the sentence.",
   "ab", ["ab"],
   "abholen splits in a main clause; the prefix ab stands at the very end.",
   "abholen ist trennbar. Im Hauptsatz steht das Präfix ab ganz am Ende.",
   "Ich hole … ab. The prefix always closes the main clause.",
   "Ich hole … ab. Das Präfix geht immer ans Satzende.",
   1, 4, 17),
ex("fill_blank",
   "Wir ___ am Samstag mit Freunden aus. (ausgehen, wir)",
   "We go out with friends on Saturday. Type the conjugated verb for 'wir'; the prefix aus already stands at the end.",
   "gehen", ["gehen"],
   "You conjugate only the base verb gehen; the prefix aus stays at the end.",
   "Du konjugierst nur das Grundverb gehen. Das Präfix aus bleibt am Ende.",
   "ausgehen splits: wir gehen … aus. The wir form of gehen is gehen.",
   "Bei ausgehen steht aus am Ende: wir gehen … aus. Die wir-Form ist gehen.",
   2, 4, 18),
ex("fill_blank",
   "Kannst du bitte das Fenster ___? (aufmachen, mit Modalverb)",
   "Can you please open the window? Type the verb form used after a modal verb.",
   "aufmachen", ["aufmachen"],
   "After a modal verb the separable verb stays together in the infinitive at the end.",
   "Nach einem Modalverb bleibt das Verb im Infinitiv am Ende zusammen.",
   "With können the prefix stays on the verb: Kannst du … aufmachen?",
   "Mit können bleibt das Verb zusammen: Kannst du … aufmachen?",
   2, 4, 19),
ex("sentence_building",
   "Schreib den Satz: [am Freitag / ich / einladen / meine Freunde]",
   "Write the sentence: On Friday I invite my friends. Start with 'Am Freitag', so the verb comes second.",
   "Am Freitag lade ich meine Freunde ein.", sb("Am Freitag lade ich meine Freunde ein."),
   "The time phrase takes position one, the conjugated verb position two, and the prefix ein goes last.",
   "Die Zeitangabe steht auf Position eins, das Verb auf Position zwei. Das Präfix ein steht am Ende.",
   "Am Freitag lade ich … ein: inversion plus the separated prefix at the end.",
   "Am Freitag lade ich … ein: Inversion und das Präfix am Ende.",
   2, 5, 20),
ex("sentence_building",
   "Schreib den Satz: [er / mitnehmen / der Regenschirm]",
   "Write the sentence: He takes the umbrella with him. Start with 'Er'; nehmen changes its vowel in the er form.",
   "Er nimmt den Regenschirm mit.", sb("Er nimmt den Regenschirm mit."),
   "mitnehmen splits, and the stem nehmen changes e to i in the er/sie/es form.",
   "Bei mitnehmen steht mit am Ende. Der Stamm nehmen ändert e zu i bei er/sie/es.",
   "Er nimmt … mit: vowel change, accusative den Regenschirm, prefix mit at the end.",
   "Er nimmt … mit: Vokalwechsel, Akkusativ den Regenschirm, Präfix mit am Ende.",
   2, 5, 21, "nehmen: er nimmt."),
ex("sentence_building",
   "Schreib den Satz: [du / müssen / dein Pass / mitbringen]",
   "Write the sentence: You have to bring your passport. Start with 'Du'; after a modal verb the separable verb stays whole.",
   "Du musst deinen Pass mitbringen.", sb("Du musst deinen Pass mitbringen."),
   "The modal verb stands in position two; mitbringen stays whole at the end.",
   "Das Modalverb steht auf Position zwei. mitbringen bleibt am Ende ganz.",
   "dein Pass is the accusative object: deinen Pass. The infinitive mitbringen closes the sentence.",
   "dein Pass ist das Akkusativobjekt: deinen Pass. Der Infinitiv mitbringen steht am Ende.",
   2, 5, 22),
ex("sentence_building",
   "Schreib den Satz im Perfekt: [gestern / ich / einkaufen]",
   "Write the sentence in the perfect tense: Yesterday I did the shopping. Start with 'Gestern'; einkaufen takes haben.",
   "Gestern habe ich eingekauft.", sb("Gestern habe ich eingekauft."),
   "In the participle of a separable verb ge- sits between the prefix and the stem: eingekauft.",
   "Im Partizip steht ge- zwischen Präfix und Stamm: eingekauft.",
   "Gestern habe ich eingekauft: haben in position two, the participle at the end.",
   "Gestern habe ich eingekauft: haben auf Position zwei, das Partizip am Ende.",
   3, 5, 23, "ein + ge + kauft."),
ex("error_correction",
   "Korrigiere die Frage: „Wann kommt zurück dein Bruder?“",
   "Correct the question: the separated prefix is in the wrong place. Write the whole question.",
   "Wann kommt dein Bruder zurück?", qu("Wann kommt dein Bruder zurück?"),
   "The prefix zurück belongs at the very end of the question.",
   "Das Präfix zurück gehört ganz ans Ende der Frage.",
   "Wann kommt dein Bruder zurück? The prefix always closes the sentence bracket.",
   "Wann kommt dein Bruder zurück? Das Präfix schließt immer die Satzklammer.",
   3, 5, 24),
ex("error_correction",
   "Korrigiere den Satz: „Das Konzert hat um acht Uhr angefangt.“",
   "Correct the sentence: the participle of anfangen is irregular. Write the whole sentence.",
   "Das Konzert hat um acht Uhr angefangen.", sb("Das Konzert hat um acht Uhr angefangen."),
   "anfangen has an irregular participle, so it ends in -en: angefangen.",
   "Das Partizip von anfangen ist unregelmäßig. Es endet auf -en: angefangen.",
   "an + ge + fangen = angefangen, not angefangt.",
   "an + ge + fangen = angefangen, nicht angefangt.",
   3, 5, 25),
ex("error_correction",
   "Korrigiere den Satz: „Meine Freundin ist gestern spät ankommen.“",
   "Correct the sentence: the participle of ankommen is missing its ge-. Write the whole sentence.",
   "Meine Freundin ist gestern spät angekommen.", sb("Meine Freundin ist gestern spät angekommen."),
   "In the participle of a separable verb ge- stands between the prefix and the stem.",
   "Im Partizip steht ge- zwischen Präfix und Stamm.",
   "an + ge + kommen = angekommen. ankommen takes sein in the perfect tense.",
   "an + ge + kommen = angekommen. ankommen bildet das Perfekt mit sein.",
   3, 5, 26, "an + ge + kommen."),
ex("error_correction",
   "Korrigiere den Satz: „Ruf bitte an deine Schwester.“",
   "Correct the imperative: the separated prefix must come last. Write the whole sentence.",
   "Ruf bitte deine Schwester an.",
   imp("Ruf bitte deine Schwester an.", "Rufe bitte deine Schwester an.",
       "Bitte ruf deine Schwester an.", "Bitte rufe deine Schwester an."),
   "In the imperative the verb comes first and the prefix an goes to the end.",
   "Im Imperativ steht das Verb zuerst, das Präfix an am Ende.",
   "Ruf bitte deine Schwester an: object first, separated prefix last.",
   "Ruf bitte deine Schwester an: zuerst das Objekt, am Ende das Präfix.",
   2, 5, 27),
]
write("separable-verbs", "A2.1", sep)
