-- a1.2 reading: 8 rewritten lessons get auto-checkable
-- "checks" items (Richtig/Falsch and exam-style choice) plus 2 brand-new
-- exam-format lessons. Course Factory content pipeline.
--
-- Generated by scripts/reading-from-json.mjs from the reviewed JSON — do not
-- hand-edit; regenerate instead. Idempotent: every UPDATE is guarded by
-- `AND checks IS NULL` (a no-op once applied) and every INSERT by
-- `WHERE NOT EXISTS` on (level, title_de).
--
-- How to test: apply by hand in the Supabase SQL editor, then:
--   SELECT id, title_de, jsonb_array_length(checks) FROM public.reading_lessons
--   WHERE level = 'a1.2' ORDER BY order_index;
-- should show 10 rows, all with a non-null `checks` array (the rewrites keep
-- their reviewed check count, the new exam-format lessons carry theirs).
-- Rollback: `UPDATE public.reading_lessons SET checks = NULL WHERE id IN (...)`
-- for the 8 ids above, and `DELETE ... WHERE level = 'a1.2' AND title_de IN
-- ('Zwei kurze E-Mails (wie in der Prüfung, Teil 1)', 'Anzeigen zu Wohnen und Arbeit (wie in der Prüfung, Teil 2)')`
-- for the 2 inserts. The ADD COLUMN is left in place (a null column is inert).

BEGIN;

ALTER TABLE public.reading_lessons ADD COLUMN IF NOT EXISTS checks jsonb;

-- ---------------------------------------------------------------------------
-- Rewrites (8 rows, guarded by id + checks IS NULL)
-- ---------------------------------------------------------------------------

UPDATE public.reading_lessons SET
  title_de = 'Meine Hobbys',
  title_en = 'My Hobbies',
  content_de = 'Jeder Mensch braucht Hobbys. Ich habe viele Hobbys. Mein Lieblingshobby ist Fußball. Ich spiele seit zehn Jahren Fußball. Mein Verein trainiert am Dienstag und am Donnerstag. Am Samstag haben wir oft ein Spiel.

Ich lese gern. Ich lese jeden Abend ein Buch. Jetzt lese ich einen Krimi. Das Buch ist sehr spannend.

Musik ist auch wichtig für mich. Ich höre jeden Tag Musik. Ich spiele Gitarre. Ich lerne seit zwei Jahren Gitarre.

Am Wochenende treffe ich meine Freunde. Wir sehen zusammen einen Film. Letzte Woche haben wir zusammen gekocht. Das war sehr lustig.

Im Sommer fahre ich gern Fahrrad. Was sind eure Hobbys?',
  content_en = 'Every person needs hobbies. I have many hobbies. My favorite hobby is football. I have been playing football for ten years. My club trains on Tuesday and on Thursday. On Saturday we often have a match.

I like reading. I read a book every evening. Now I am reading a crime novel. The book is very exciting.

Music is also important to me. I listen to music every day. I play guitar. I have been learning guitar for two years.

On the weekend I meet my friends. We watch a film together. Last week we cooked together. That was a lot of fun.

In summer I like cycling. What are your hobbies?',
  key_vocabulary = '[{"de":"das Hobby, -s","en":"hobby"},{"de":"der Verein, -e","en":"club"},{"de":"trainieren","en":"to train"},{"de":"das Spiel, -e","en":"game, match"},{"de":"lesen","en":"to read"},{"de":"das Buch, Bücher","en":"book"},{"de":"spannend","en":"exciting"},{"de":"die Musik","en":"music"},{"de":"Gitarre spielen","en":"to play guitar"},{"de":"treffen","en":"to meet"}]'::jsonb,
  questions = '[{"question_de":"Wie lange spielt die Person schon Fußball?","question_en":"How long has the person been playing football?","answer_de":"Sie spielt seit zehn Jahren Fußball.","answer_en":"She has been playing football for ten years."},{"question_de":"Wann trainiert der Verein?","question_en":"When does the club train?","answer_de":"Der Verein trainiert am Dienstag und am Donnerstag.","answer_en":"The club trains on Tuesday and Thursday."},{"question_de":"Wie lange lernt die Person schon Gitarre?","question_en":"How long has the person been learning guitar?","answer_de":"Sie lernt seit zwei Jahren Gitarre.","answer_en":"She has been learning guitar for two years."},{"question_de":"Was haben die Freunde letzte Woche gemacht?","question_en":"What did the friends do last week?","answer_de":"Sie haben zusammen gekocht.","answer_en":"They cooked together."},{"question_de":"Was macht die Person im Sommer gern?","question_en":"What does the person like doing in summer?","answer_de":"Sie fährt gern Fahrrad.","answer_en":"She likes cycling."}]'::jsonb,
  checks = '[{"type":"rf","statement_de":"Der Verein trainiert am Montag und am Mittwoch.","statement_en":"The club trains on Monday and Wednesday.","answer":"falsch","explanation_de":"Der Verein trainiert am Dienstag und am Donnerstag."},{"type":"rf","statement_de":"Die Person liest jeden Abend eine Zeitung.","statement_en":"The person reads a newspaper every evening.","answer":"falsch","explanation_de":"Die Person liest jeden Abend ein Buch, keine Zeitung."},{"type":"rf","statement_de":"Die Person spielt seit zehn Jahren Fußball.","statement_en":"The person has been playing football for ten years.","answer":"richtig","explanation_de":"Der Text sagt: Ich spiele seit zehn Jahren Fußball."},{"type":"rf","statement_de":"Die Person lernt seit zwei Jahren Gitarre.","statement_en":"The person has been learning guitar for two years.","answer":"richtig","explanation_de":"Der Text sagt: Ich lerne seit zwei Jahren Gitarre."},{"type":"rf","statement_de":"Am Wochenende sieht die Person einen Film.","statement_en":"On the weekend the person watches a film.","answer":"richtig","explanation_de":"Der Text sagt: Wir sehen zusammen einen Film."},{"type":"choice","statement_de":"Was liest die Person gerade?","statement_en":"What is the person reading right now?","options":["einen Krimi","einen Comic"],"answer":"einen Krimi","explanation_de":"Der Text sagt: Jetzt lese ich einen Krimi."}]'::jsonb,
  word_count = 103,
  estimated_reading_time = 2
WHERE id = 'c2904e41-dca9-49ad-b902-ddfc5939079c'
  AND checks IS NULL; -- idempotency guard: a re-run after this migration has
                       -- already applied is a no-op

UPDATE public.reading_lessons SET
  title_de = 'Essen und Trinken',
  title_en = 'Food and Drink',
  content_de = 'Essen und Trinken sind sehr wichtig. Ich esse gern und koche auch gern.

Zum Frühstück esse ich Brot mit Butter und Käse. Ich trinke eine Tasse Kaffee. Ohne Kaffee geht es nicht!

Mittags esse ich oft bei der Arbeit. Ich esse gern Schnitzel mit Pommes. Das Gericht ist typisch deutsch.

Am Abend esse ich Brot mit Wurst. Das heißt Abendbrot.

Ich trinke jeden Tag zwei Liter Wasser. Wasser ist gesund!

Ich koche auch gern selbst. Mein Lieblingsgericht ist Spaghetti Bolognese. Ich kaufe die Zutaten im Supermarkt: Tomaten, Zwiebeln und Hackfleisch. Das Kochen dauert eine Stunde. Das Essen schmeckt fantastisch!

Ich esse auch gern Schokolade, aber nicht zu viel.',
  content_en = 'Food and drink are very important. I like eating and I also like cooking.

For breakfast I eat bread with butter and cheese. I drink a cup of coffee. Without coffee nothing works!

At noon I often eat at work. I like eating schnitzel with fries. The dish is typically German.

In the evening I eat bread with sausage. This is called Abendbrot.

I drink two liters of water every day. Water is healthy!

I also like cooking myself. My favorite dish is spaghetti Bolognese. I buy the ingredients at the supermarket: tomatoes, onions and minced meat. The cooking takes an hour. The food tastes fantastic!

I also like eating chocolate, but not too much.',
  key_vocabulary = '[{"de":"das Frühstück","en":"breakfast"},{"de":"das Abendbrot","en":"cold evening meal"},{"de":"die Tasse, -n","en":"cup"},{"de":"das Brot, -e","en":"bread"},{"de":"der Käse","en":"cheese"},{"de":"das Gericht, -e","en":"dish"},{"de":"kochen","en":"to cook"},{"de":"schmecken","en":"to taste"},{"de":"gesund","en":"healthy"},{"de":"die Zutat, -en","en":"ingredient"}]'::jsonb,
  questions = '[{"question_de":"Was isst die Person zum Frühstück?","question_en":"What does the person eat for breakfast?","answer_de":"Sie isst Brot mit Butter und Käse.","answer_en":"She eats bread with butter and cheese."},{"question_de":"Wo isst die Person mittags?","question_en":"Where does the person eat lunch?","answer_de":"Sie isst mittags oft bei der Arbeit.","answer_en":"She often eats at work at noon."},{"question_de":"Was ist Abendbrot?","question_en":"What is Abendbrot?","answer_de":"Abendbrot ist Brot mit Wurst am Abend.","answer_en":"Abendbrot is bread with sausage in the evening."},{"question_de":"Wie viel Wasser trinkt die Person jeden Tag?","question_en":"How much water does the person drink every day?","answer_de":"Sie trinkt jeden Tag zwei Liter Wasser.","answer_en":"She drinks two liters of water every day."},{"question_de":"Was ist das Lieblingsgericht der Person?","question_en":"What is the person''s favorite dish?","answer_de":"Das Lieblingsgericht ist Spaghetti Bolognese.","answer_en":"The favorite dish is spaghetti Bolognese."}]'::jsonb,
  checks = '[{"type":"rf","statement_de":"Die Person trinkt zum Frühstück Tee.","statement_en":"For breakfast the person drinks tea.","answer":"falsch","explanation_de":"Die Person trinkt zum Frühstück Kaffee, keinen Tee."},{"type":"rf","statement_de":"Zum Frühstück isst die Person Brot mit Butter und Käse.","statement_en":"For breakfast the person eats bread with butter and cheese.","answer":"richtig","explanation_de":"Der Text sagt: Zum Frühstück esse ich Brot mit Butter und Käse."},{"type":"rf","statement_de":"Die Person trinkt jeden Tag drei Liter Wasser.","statement_en":"The person drinks three liters of water every day.","answer":"falsch","explanation_de":"Die Person trinkt jeden Tag zwei Liter Wasser, nicht drei."},{"type":"rf","statement_de":"Das Lieblingsgericht ist Spaghetti Bolognese.","statement_en":"The favorite dish is spaghetti Bolognese.","answer":"richtig","explanation_de":"Der Text sagt: Mein Lieblingsgericht ist Spaghetti Bolognese."},{"type":"rf","statement_de":"Mittags isst die Person oft bei der Arbeit.","statement_en":"At noon the person often eats at work.","answer":"richtig","explanation_de":"Der Text sagt: Mittags esse ich oft bei der Arbeit."},{"type":"choice","statement_de":"Wo kauft die Person die Zutaten für Spaghetti Bolognese?","statement_en":"Where does the person buy the ingredients for spaghetti Bolognese?","options":["beim Bäcker","im Supermarkt"],"answer":"im Supermarkt","explanation_de":"Der Text sagt: Ich kaufe die Zutaten im Supermarkt."}]'::jsonb,
  word_count = 108,
  estimated_reading_time = 2
WHERE id = '3b8414a9-e36b-456b-a44f-012dea7e1cc3'
  AND checks IS NULL; -- idempotency guard: a re-run after this migration has
                       -- already applied is a no-op

UPDATE public.reading_lessons SET
  title_de = 'Einkaufen in Deutschland',
  title_en = 'Shopping in Germany',
  content_de = 'Ich kaufe jede Woche ein, besonders am Wochenende.

Für Lebensmittel gehe ich zum Supermarkt. Der Supermarkt ist von Montag bis Samstag offen. Am Sonntag ist er nicht offen. Ich kaufe dort einmal pro Woche ein.

Am Samstag gehe ich oft zum Wochenmarkt. Dort kaufe ich Obst und Gemüse von den Bauern. Ich kaufe auch Blumen für meine Wohnung.

Kleidung kaufe ich in der Stadt. Dort gibt es viele Geschäfte. Manchmal kaufe ich Kleidung nicht neu. Das ist gut für die Umwelt.

Ich kaufe auch viel online. Ich bestelle zu Hause. Dann kommt das Paket.

In Deutschland bezahlt man oft bar. Ich bezahle lieber mit meiner EC-Karte.

Ich kaufe nicht zu viel ein. Ich bringe immer meine Einkaufstasche mit.',
  content_en = 'I shop every week, especially on the weekend.

For groceries I go to the supermarket. The supermarket is open Monday to Saturday. On Sunday it is not open. I shop there once a week.

On Saturday I often go to the weekly market. There I buy fruit and vegetables from the farmers. I also buy flowers for my apartment.

I buy clothes in the city. There are many shops there. Sometimes I buy clothes that are not new. That is good for the environment.

I also buy a lot online. I order at home. Then the package arrives.

In Germany people often pay cash. I prefer paying with my debit card.

I don''t buy too much. I always bring my shopping bag.',
  key_vocabulary = '[{"de":"einkaufen","en":"to shop"},{"de":"das Geschäft, -e","en":"shop"},{"de":"der Supermarkt, -märkte","en":"supermarket"},{"de":"der Markt, Märkte","en":"market"},{"de":"bestellen","en":"to order"},{"de":"das Paket, -e","en":"package"},{"de":"bezahlen","en":"to pay"},{"de":"bar","en":"cash"},{"de":"die Einkaufstasche, -n","en":"shopping bag"},{"de":"die Kleidung","en":"clothes"}]'::jsonb,
  questions = '[{"question_de":"Wann ist der Supermarkt nicht offen?","question_en":"When is the supermarket not open?","answer_de":"Der Supermarkt ist am Sonntag nicht offen.","answer_en":"The supermarket is not open on Sunday."},{"question_de":"Wo kauft die Person Obst und Gemüse?","question_en":"Where does the person buy fruit and vegetables?","answer_de":"Sie kauft Obst und Gemüse von den Bauern.","answer_en":"She buys fruit and vegetables from the farmers."},{"question_de":"Wo kauft die Person Kleidung?","question_en":"Where does the person buy clothes?","answer_de":"Sie kauft Kleidung in der Stadt.","answer_en":"She buys clothes in the city."},{"question_de":"Wie bezahlt die Person lieber?","question_en":"How does the person prefer to pay?","answer_de":"Sie bezahlt lieber mit der EC-Karte.","answer_en":"She prefers to pay with her debit card."},{"question_de":"Was bringt die Person immer mit?","question_en":"What does the person always bring?","answer_de":"Sie bringt immer ihre Einkaufstasche mit.","answer_en":"She always brings her shopping bag."}]'::jsonb,
  checks = '[{"type":"rf","statement_de":"Die Person kauft nur einmal pro Monat ein.","statement_en":"The person only shops once a month.","answer":"falsch","explanation_de":"Die Person kauft einmal pro Woche ein, nicht einmal pro Monat."},{"type":"rf","statement_de":"Die Person kauft Kleidung in der Stadt.","statement_en":"The person buys clothes in the city.","answer":"richtig","explanation_de":"Der Text sagt: Kleidung kaufe ich in der Stadt."},{"type":"rf","statement_de":"Die Person kauft am Samstag Obst und Gemüse.","statement_en":"On Saturday the person buys fruit and vegetables.","answer":"richtig","explanation_de":"Der Text sagt: Am Samstag gehe ich oft zum Wochenmarkt. Dort kaufe ich Obst und Gemüse."},{"type":"rf","statement_de":"Die Person bezahlt lieber bar.","statement_en":"The person prefers to pay in cash.","answer":"falsch","explanation_de":"Die Person bezahlt lieber mit der EC-Karte, nicht bar."},{"type":"rf","statement_de":"Die Person bringt immer ihre Einkaufstasche mit.","statement_en":"The person always brings her shopping bag.","answer":"richtig","explanation_de":"Der Text sagt: Ich bringe immer meine Einkaufstasche mit."},{"type":"choice","statement_de":"Wann kann man dort nicht einkaufen?","statement_en":"When can you not shop there?","options":["am Sonntag","am Samstag"],"answer":"am Sonntag","explanation_de":"Der Text sagt: Am Sonntag ist er nicht offen."}]'::jsonb,
  word_count = 118,
  estimated_reading_time = 2
WHERE id = '635b1d9e-02b1-45e4-bcc6-e0eea5267c02'
  AND checks IS NULL; -- idempotency guard: a re-run after this migration has
                       -- already applied is a no-op

UPDATE public.reading_lessons SET
  title_de = 'Meine Wohnung',
  title_en = 'My Apartment',
  content_de = 'Ich habe eine Wohnung in Berlin. Ich wohne hier seit zwei Jahren. Die Wohnung ist klein, aber sie ist gemütlich.

Die Wohnung hat drei Zimmer, eine Küche und ein Badezimmer. Die Miete kostet 800 Euro pro Monat.

Das Wohnzimmer ist mein Lieblingsraum. Es ist groß und hell. Ich habe ein Sofa und einen Fernseher.

Das Schlafzimmer ist ruhig. Ich habe ein Bett und einen Kleiderschrank.

Die Küche ist klein, aber praktisch. Am Wochenende koche ich oft für meine Freunde.

Ich arbeite oft zu Hause. Ich habe ein Arbeitszimmer mit einem Schreibtisch und einem Bücherregal.

Der Balkon ist klein, aber schön. Im Sommer trinke ich dort gern Kaffee. Ich kann einen Park sehen!',
  content_en = 'I have an apartment in Berlin. I have been living here for two years. The apartment is small, but it is cozy.

The apartment has three rooms, a kitchen and a bathroom. The rent costs 800 euros per month.

The living room is my favorite room. It is big and bright. I have a sofa and a TV.

The bedroom is quiet. I have a bed and a wardrobe.

The kitchen is small but practical. On the weekend I often cook for my friends.

I often work at home. I have a study with a desk and a bookshelf.

The balcony is small but nice. In summer I like drinking coffee there. I can see a park!',
  key_vocabulary = '[{"de":"die Wohnung, -en","en":"apartment"},{"de":"das Zimmer, -","en":"room"},{"de":"das Wohnzimmer","en":"living room"},{"de":"das Schlafzimmer","en":"bedroom"},{"de":"die Küche, -n","en":"kitchen"},{"de":"der Balkon, -e","en":"balcony"},{"de":"die Miete, -n","en":"rent"},{"de":"der Schreibtisch, -e","en":"desk"},{"de":"das Bücherregal, -e","en":"bookshelf"},{"de":"praktisch","en":"practical"}]'::jsonb,
  questions = '[{"question_de":"Wie viele Zimmer hat die Wohnung?","question_en":"How many rooms does the apartment have?","answer_de":"Die Wohnung hat drei Zimmer, eine Küche und ein Badezimmer.","answer_en":"The apartment has three rooms, a kitchen and a bathroom."},{"question_de":"Was kostet die Miete?","question_en":"How much is the rent?","answer_de":"Die Miete kostet 800 Euro pro Monat.","answer_en":"The rent costs 800 euros per month."},{"question_de":"Was ist der Lieblingsraum der Person?","question_en":"What is the person''s favorite room?","answer_de":"Der Lieblingsraum ist das Wohnzimmer.","answer_en":"The favorite room is the living room."},{"question_de":"Was hat das Arbeitszimmer?","question_en":"What does the study have?","answer_de":"Es hat einen Schreibtisch und ein Bücherregal.","answer_en":"It has a desk and a bookshelf."},{"question_de":"Was kann die Person vom Balkon sehen?","question_en":"What can the person see from the balcony?","answer_de":"Sie kann einen Park sehen.","answer_en":"She can see a park."}]'::jsonb,
  checks = '[{"type":"rf","statement_de":"Die Miete kostet 500 Euro pro Monat.","statement_en":"The rent costs 500 euros per month.","answer":"falsch","explanation_de":"Die Miete kostet 800 Euro, nicht 500."},{"type":"rf","statement_de":"Die Wohnung hat drei Zimmer.","statement_en":"The apartment has three rooms.","answer":"richtig","explanation_de":"Der Text sagt: Die Wohnung hat drei Zimmer."},{"type":"rf","statement_de":"Das Wohnzimmer ist der Lieblingsraum.","statement_en":"The living room is the favorite room.","answer":"richtig","explanation_de":"Der Text sagt: Das Wohnzimmer ist mein Lieblingsraum."},{"type":"rf","statement_de":"Vom Balkon kann man einen Park sehen.","statement_en":"From the balcony you can see a park.","answer":"richtig","explanation_de":"Der Text sagt: Ich kann einen Park sehen."},{"type":"rf","statement_de":"Das Schlafzimmer hat einen Schreibtisch.","statement_en":"The bedroom has a desk.","answer":"falsch","explanation_de":"Das Arbeitszimmer hat den Schreibtisch, nicht das Schlafzimmer."},{"type":"choice","statement_de":"Wie lange wohnt die Person schon hier?","statement_en":"How long has the person been living here?","options":["seit drei Jahren","seit zwei Jahren"],"answer":"seit zwei Jahren","explanation_de":"Der Text sagt: Ich wohne hier seit zwei Jahren."}]'::jsonb,
  word_count = 112,
  estimated_reading_time = 2
WHERE id = '08cf277c-5b91-4777-979e-a3a82b8f39f0'
  AND checks IS NULL; -- idempotency guard: a re-run after this migration has
                       -- already applied is a no-op

UPDATE public.reading_lessons SET
  title_de = 'Eine E-Mail an eine Freundin',
  title_en = 'An Email to a Friend',
  content_de = 'Liebe Julia,

wie geht es dir? Mir geht es sehr gut, denn ich habe eine Wohnung in Köln! Sie ist klein, aber schön und hell. Das Viertel heißt Südstadt. Es gibt hier viele Cafés und einen Park.

Köln ist groß, und ich kenne noch niemanden. Ich mache einen Tanzkurs. Dort kann ich Leute treffen. Ich habe auch schon einen Job! Ich arbeite bei Buchhandlung Lang. Die Arbeit ist interessant, aber die Tage sind lang. Die Kollegen sind sehr nett.

Und jetzt meine Frage: Möchtest du mich besuchen? Du kannst am Wochenende kommen. Wir können zusammen die Stadt und den Dom sehen. Wann hast du Zeit? Schreib bald!

Viele Grüße
deine Emma',
  content_en = 'Dear Julia,

How are you? I am doing very well, because I have an apartment in Cologne! It is small, but nice and bright. The neighborhood is called Südstadt. There are lots of cafés here and a park.

Cologne is big, and I don''t know anyone yet. I am taking a dance class. There I can meet people. I also already have a job! I work at Buchhandlung Lang. The work is interesting, but the days are long. My colleagues are very nice.

And now my question: Would you like to visit me? You can come on the weekend. We can see the city and the cathedral together. When do you have time? Write soon!

Best wishes
your Emma',
  key_vocabulary = '[{"de":"die Wohnung, -en","en":"apartment"},{"de":"hell","en":"bright"},{"de":"das Viertel, -","en":"neighborhood"},{"de":"der Tanzkurs, -e","en":"dance class"},{"de":"treffen","en":"to meet"},{"de":"der Job, -s","en":"job"},{"de":"die Buchhandlung, -en","en":"bookshop"},{"de":"besuchen","en":"to visit"},{"de":"der Dom, -e","en":"cathedral"},{"de":"schreiben","en":"to write"}]'::jsonb,
  questions = '[{"question_de":"Warum geht es Emma sehr gut?","question_en":"Why is Emma doing very well?","answer_de":"Sie hat jetzt eine Wohnung in Köln.","answer_en":"She now has an apartment in Cologne."},{"question_de":"Wie ist Emmas Wohnung?","question_en":"What is Emma''s apartment like?","answer_de":"Die Wohnung ist klein, aber schön und hell.","answer_en":"The apartment is small, but nice and bright."},{"question_de":"Was macht Emma in Köln?","question_en":"What is Emma doing in Cologne?","answer_de":"Sie macht einen Tanzkurs.","answer_en":"She is taking a dance class."},{"question_de":"Wo arbeitet Emma?","question_en":"Where does Emma work?","answer_de":"Emma arbeitet bei Buchhandlung Lang.","answer_en":"Emma works at Buchhandlung Lang."},{"question_de":"Was können Emma und Julia am Wochenende machen?","question_en":"What can Emma and Julia do on the weekend?","answer_de":"Sie können die Stadt und den Dom sehen.","answer_en":"They can see the city and the cathedral."}]'::jsonb,
  checks = '[{"type":"rf","statement_de":"Emma hat jetzt eine Wohnung in Köln.","statement_en":"Emma now has an apartment in Cologne.","answer":"richtig","explanation_de":"Der Text sagt: Ich habe eine Wohnung in Köln."},{"type":"rf","statement_de":"Emma arbeitet bei Buchhandlung Lang.","statement_en":"Emma works at Buchhandlung Lang.","answer":"richtig","explanation_de":"Der Text sagt: Ich arbeite bei Buchhandlung Lang."},{"type":"rf","statement_de":"Emmas Viertel heißt Nordstadt.","statement_en":"Emma''s neighborhood is called Nordstadt.","answer":"falsch","explanation_de":"Das Viertel heißt Südstadt, nicht Nordstadt."},{"type":"rf","statement_de":"Julia kann am Wochenende kommen.","statement_en":"Julia can come on the weekend.","answer":"richtig","explanation_de":"Der Text sagt: Du kannst am Wochenende kommen."},{"type":"rf","statement_de":"Emma kennt schon viele Leute in Köln.","statement_en":"Emma already knows many people in Cologne.","answer":"falsch","explanation_de":"Emma kennt noch niemanden in Köln."},{"type":"choice","statement_de":"Was möchte Emma mit Julia machen?","statement_en":"What does Emma want to do with Julia?","options":["die Stadt und den Dom sehen","am Wochenende arbeiten"],"answer":"die Stadt und den Dom sehen","explanation_de":"Der Text sagt: Wir können zusammen die Stadt und den Dom sehen."}]'::jsonb,
  word_count = 111,
  estimated_reading_time = 2
WHERE id = 'dcc34a7f-10c6-4f9d-ab7b-192bc2b292e6'
  AND checks IS NULL; -- idempotency guard: a re-run after this migration has
                       -- already applied is a no-op

UPDATE public.reading_lessons SET
  title_de = 'Am Wochenende',
  title_en = 'On the Weekend',
  content_de = 'Endlich Freitag! Max und Sara planen das Wochenende. Am Samstagmorgen möchte Max lange schlafen. Aber Sara sagt: „Wir müssen früh aufstehen.“ Der Wochenmarkt beginnt um acht Uhr. Sie möchten Gemüse, Obst und Blumen kaufen.

Am Nachmittag möchte Max Fußball spielen. Sara möchte lieber schwimmen. Am Abend möchten beide einen Film sehen. Max möchte einen Actionfilm, aber Sara möchte eine Komödie. Vielleicht sehen sie beide Filme!

Am Sonntag müssen Max und Sara zu Hause viel machen. Max muss die Wohnung putzen, und Sara muss Wäsche waschen. Danach machen sie vielleicht eine Radtour. Um sechs Uhr kommen Freunde zum Abendessen. Sara möchte Lasagne kochen. Das Wochenende ist kurz, aber sie können viel machen!',
  content_en = 'Finally Friday! Max and Sara are planning the weekend. On Saturday morning Max would like to sleep in. But Sara says: "We have to get up early." The weekly market starts at eight o''clock. They want to buy vegetables, fruit and flowers.

In the afternoon Max wants to play football. Sara would rather swim. In the evening they both want to watch a film. Max wants an action film, but Sara wants a comedy. Maybe they will watch both films!

On Sunday Max and Sara have a lot to do at home. Max has to clean the apartment, and Sara has to do the laundry. Afterwards they will maybe go on a bike tour. At six o''clock friends are coming for dinner. Sara wants to cook lasagna. The weekend is short, but they can do a lot!',
  key_vocabulary = '[{"de":"planen","en":"to plan"},{"de":"aufstehen","en":"to get up"},{"de":"früh","en":"early"},{"de":"der Film, -e","en":"film"},{"de":"die Komödie, -n","en":"comedy"},{"de":"putzen","en":"to clean"},{"de":"die Wäsche","en":"laundry"},{"de":"waschen","en":"to wash"},{"de":"die Radtour, -en","en":"bike tour"},{"de":"kochen","en":"to cook"}]'::jsonb,
  questions = '[{"question_de":"Wann beginnt der Wochenmarkt am Samstag?","question_en":"When does the weekly market start on Saturday?","answer_de":"Der Wochenmarkt beginnt um acht Uhr.","answer_en":"The weekly market starts at eight o''clock."},{"question_de":"Was möchte Max am Nachmittag machen?","question_en":"What does Max want to do in the afternoon?","answer_de":"Er möchte Fußball spielen.","answer_en":"He wants to play football."},{"question_de":"Welchen Film möchte Sara sehen?","question_en":"Which film does Sara want to see?","answer_de":"Sie möchte eine Komödie sehen.","answer_en":"She wants to see a comedy."},{"question_de":"Was muss Max am Sonntag machen?","question_en":"What does Max have to do on Sunday?","answer_de":"Er muss die Wohnung putzen.","answer_en":"He has to clean the apartment."},{"question_de":"Wer kommt am Sonntag um sechs Uhr?","question_en":"Who is coming on Sunday at six o''clock?","answer_de":"Um sechs Uhr kommen Freunde zum Abendessen.","answer_en":"At six o''clock friends are coming for dinner."}]'::jsonb,
  checks = '[{"type":"rf","statement_de":"Der Wochenmarkt beginnt um acht Uhr.","statement_en":"The weekly market starts at eight o''clock.","answer":"richtig","explanation_de":"Der Text sagt: Der Wochenmarkt beginnt um acht Uhr."},{"type":"rf","statement_de":"Max möchte am Nachmittag schwimmen.","statement_en":"Max wants to swim in the afternoon.","answer":"falsch","explanation_de":"Max möchte Fußball spielen; Sara möchte schwimmen."},{"type":"rf","statement_de":"Max muss am Sonntag die Wohnung putzen.","statement_en":"Max has to clean the apartment on Sunday.","answer":"richtig","explanation_de":"Der Text sagt: Max muss die Wohnung putzen."},{"type":"rf","statement_de":"Am Sonntagabend kommen Freunde zu Besuch.","statement_en":"On Sunday evening friends are coming to visit.","answer":"richtig","explanation_de":"Der Text sagt: Um sechs Uhr kommen Freunde zum Abendessen."},{"type":"rf","statement_de":"Sara möchte einen Actionfilm sehen.","statement_en":"Sara wants to see an action film.","answer":"falsch","explanation_de":"Sara möchte eine Komödie sehen; Max möchte den Actionfilm."},{"type":"choice","statement_de":"Was möchte Sara zum Abendessen kochen?","statement_en":"What does Sara want to cook for dinner?","options":["Schnitzel","Lasagne"],"answer":"Lasagne","explanation_de":"Der Text sagt: Sara möchte Lasagne kochen."}]'::jsonb,
  word_count = 111,
  estimated_reading_time = 2
WHERE id = 'fd570bfa-06d1-4c2e-bd2a-aaeaa04d19bf'
  AND checks IS NULL; -- idempotency guard: a re-run after this migration has
                       -- already applied is a no-op

UPDATE public.reading_lessons SET
  title_de = 'Mit dem Zug durch Deutschland',
  title_en = 'Through Germany by Train',
  content_de = 'Tom möchte seine Schwester in München besuchen. Er wohnt in Hamburg. Die Reise ist lang: fast 800 Kilometer. Aber Tom fliegt nicht gern. Er fährt lieber mit dem Zug. Er kann dann lesen und arbeiten.

Tom kauft eine Fahrkarte. Die Fahrt mit dem ICE kostet 89 Euro. Das ist teuer! Aber Tom hat eine BahnCard. Mit der BahnCard bekommt er 25 Prozent Rabatt.

Tom sucht seinen Zug: ICE 787 nach München. Abfahrt ist um 10:40 Uhr, Gleis 14. Dann kommt eine Durchsage: „Der ICE 787 hat 20 Minuten Verspätung.“

Die Fahrt dauert sechs Stunden. Tom sieht Städte, Felder und Berge. Um 17 Uhr ist er in München. Seine Schwester wartet dort. „Willkommen in München!“, sagt sie.',
  content_en = 'Tom wants to visit his sister in Munich. He lives in Hamburg. The journey is long: almost 800 kilometers. But Tom does not like flying. He prefers going by train. He can then read and work.

Tom buys a ticket. The trip on the ICE costs 89 euros. That is expensive! But Tom has a BahnCard. With the BahnCard he gets a 25 percent discount.

Tom looks for his train: ICE 787 to Munich. Departure is at 10:40, platform 14. Then an announcement comes: "The ICE 787 is delayed by 20 minutes."

The journey takes six hours. Tom sees cities, fields and mountains. At 5 p.m. he is in Munich. His sister is waiting there. "Welcome to Munich!", she says.',
  key_vocabulary = '[{"de":"die Reise, -n","en":"trip"},{"de":"die Fahrkarte, -n","en":"ticket"},{"de":"teuer","en":"expensive"},{"de":"der Rabatt, -e","en":"discount"},{"de":"die Abfahrt, -en","en":"departure"},{"de":"das Gleis, -e","en":"platform"},{"de":"die Durchsage, -n","en":"announcement"},{"de":"die Verspätung, -en","en":"delay"},{"de":"die Fahrt, -en","en":"journey"},{"de":"besuchen","en":"to visit"}]'::jsonb,
  questions = '[{"question_de":"Warum fährt Tom lieber mit dem Zug?","question_en":"Why does Tom prefer to go by train?","answer_de":"Er kann dann lesen und arbeiten.","answer_en":"He can then read and work."},{"question_de":"Was kostet die Fahrt mit dem ICE?","question_en":"How much does the trip on the ICE cost?","answer_de":"Die Fahrt kostet 89 Euro.","answer_en":"The trip costs 89 euros."},{"question_de":"Wie viel Rabatt bekommt Tom mit der BahnCard?","question_en":"How much discount does Tom get with the BahnCard?","answer_de":"Er bekommt 25 Prozent Rabatt.","answer_en":"He gets a 25 percent discount."},{"question_de":"Wie viel Verspätung hat der ICE 787?","question_en":"How delayed is the ICE 787?","answer_de":"Der Zug hat 20 Minuten Verspätung.","answer_en":"The train is delayed by 20 minutes."},{"question_de":"Wie lange dauert die Fahrt nach München?","question_en":"How long does the journey to Munich take?","answer_de":"Die Fahrt dauert sechs Stunden.","answer_en":"The journey takes six hours."}]'::jsonb,
  checks = '[{"type":"rf","statement_de":"Die Fahrt mit dem ICE kostet 89 Euro.","statement_en":"The trip on the ICE costs 89 euros.","answer":"richtig","explanation_de":"Der Text sagt: Die Fahrt mit dem ICE kostet 89 Euro."},{"type":"rf","statement_de":"Der Zug fährt von Gleis 14.","statement_en":"The train leaves from platform 14.","answer":"richtig","explanation_de":"Der Text sagt: Gleis 14."},{"type":"rf","statement_de":"Tom fährt mit dem Bus nach München.","statement_en":"Tom travels to Munich by bus.","answer":"falsch","explanation_de":"Tom fährt mit dem Zug, nicht mit dem Bus."},{"type":"rf","statement_de":"Mit der BahnCard bekommt Tom 50 Prozent Rabatt.","statement_en":"With the BahnCard Tom gets a 50 percent discount.","answer":"falsch","explanation_de":"Tom bekommt 25 Prozent Rabatt, nicht 50."},{"type":"rf","statement_de":"Tom ist am Nachmittag in München.","statement_en":"Tom is in Munich in the afternoon.","answer":"richtig","explanation_de":"Der Text sagt: Um 17 Uhr ist er in München."},{"type":"choice","statement_de":"Was braucht Tom für den Rabatt?","statement_en":"What does Tom need for the discount?","options":["eine BahnCard","eine Fahrkarte"],"answer":"eine BahnCard","explanation_de":"Der Text sagt: Tom hat eine BahnCard. Mit der BahnCard bekommt er Rabatt."}]'::jsonb,
  word_count = 116,
  estimated_reading_time = 2
WHERE id = 'f26af6bf-6a1e-40c6-808e-b4b75b61d6d8'
  AND checks IS NULL; -- idempotency guard: a re-run after this migration has
                       -- already applied is a no-op

UPDATE public.reading_lessons SET
  title_de = 'Beim Bäcker',
  title_en = 'At the Bakery',
  content_de = 'Es ist Samstagmorgen, halb neun. Frau Schmidt geht zum Bäcker. Beim Bäcker Lang ist immer viel los. Sie wartet kurz.

Die Verkäuferin lächelt: „Guten Morgen! Was darf es sein?“ „Ich möchte sechs Brötchen, bitte“, sagt Frau Schmidt. „Mit Körnern oder ohne?“ „Vier ohne Körner und zwei mit Körnern, bitte.“

Der Apfelkuchen ist lecker. „Was kostet ein Stück Apfelkuchen?“ „Ein Stück kostet 3,20 Euro.“ „Gut, dann zwei Stück, bitte.“

Die Verkäuferin rechnet: „Sechs Brötchen kosten 3,60 Euro. Das macht zusammen 10,00 Euro.“ Frau Schmidt bezahlt bar. Sie gibt 15 Euro und bekommt 5,00 Euro Wechselgeld. „Schönes Wochenende!“, sagt die Verkäuferin. „Danke, gleichfalls!“

Zu Hause wartet schon die Familie. Brötchen am Samstag, das ist in Deutschland Tradition.',
  content_en = 'It is Saturday morning, half past eight. Mrs. Schmidt goes to the bakery. At Lang''s bakery there is always a lot going on. She waits briefly.

The saleswoman smiles: "Good morning! What can I get you?" "I would like six rolls, please," says Mrs. Schmidt. "With grains or without?" "Four without grains and two with grains, please."

The apple cake is delicious. "How much is one slice of apple cake?" "One slice costs 3.20 euros." "Good, then two slices, please."

The saleswoman adds it up: "Six rolls cost 3.60 euros. That comes to 10.00 euros altogether." Mrs. Schmidt pays in cash. She gives 15 euros and gets 5.00 euros change. "Have a nice weekend!" says the saleswoman. "Thanks, you too!"

At home the family is already waiting. Rolls on Saturday, that is a tradition in Germany.',
  key_vocabulary = '[{"de":"der Bäcker, -","en":"baker, bakery"},{"de":"die Verkäuferin, -nen","en":"saleswoman"},{"de":"lächeln","en":"to smile"},{"de":"der Apfelkuchen, -","en":"apple cake"},{"de":"das Stück, -e","en":"piece, slice"},{"de":"bar","en":"cash"},{"de":"das Wechselgeld","en":"change (money)"},{"de":"die Tradition, -en","en":"tradition"},{"de":"das Brötchen, -","en":"bread roll"}]'::jsonb,
  questions = '[{"question_de":"Wann geht Frau Schmidt zum Bäcker?","question_en":"When does Mrs. Schmidt go to the bakery?","answer_de":"Sie geht am Samstagmorgen um halb neun.","answer_en":"She goes on Saturday morning at half past eight."},{"question_de":"Wie viele Brötchen möchte Frau Schmidt?","question_en":"How many rolls does Mrs. Schmidt want?","answer_de":"Sie möchte sechs Brötchen.","answer_en":"She wants six rolls."},{"question_de":"Was kostet ein Stück Apfelkuchen?","question_en":"How much does a slice of apple cake cost?","answer_de":"Ein Stück kostet 3,20 Euro.","answer_en":"A slice costs 3.20 euros."},{"question_de":"Wie bezahlt Frau Schmidt?","question_en":"How does Mrs. Schmidt pay?","answer_de":"Sie bezahlt bar.","answer_en":"She pays in cash."},{"question_de":"Wie viel Wechselgeld bekommt Frau Schmidt?","question_en":"How much change does Mrs. Schmidt get?","answer_de":"Sie bekommt 5,00 Euro Wechselgeld.","answer_en":"She gets 5.00 euros change."}]'::jsonb,
  checks = '[{"type":"rf","statement_de":"Frau Schmidt geht am Samstagmorgen zum Bäcker.","statement_en":"Mrs. Schmidt goes to the bakery on Saturday morning.","answer":"richtig","explanation_de":"Der Text sagt: Es ist Samstagmorgen. Frau Schmidt geht zum Bäcker."},{"type":"rf","statement_de":"Frau Schmidt möchte acht Brötchen.","statement_en":"Mrs. Schmidt wants eight rolls.","answer":"falsch","explanation_de":"Frau Schmidt möchte sechs Brötchen, nicht acht."},{"type":"rf","statement_de":"Frau Schmidt bezahlt mit Karte.","statement_en":"Mrs. Schmidt pays by card.","answer":"falsch","explanation_de":"Frau Schmidt bezahlt bar, nicht mit Karte."},{"type":"rf","statement_de":"Ein Stück Apfelkuchen kostet 3,20 Euro.","statement_en":"A slice of apple cake costs 3.20 euros.","answer":"richtig","explanation_de":"Der Text sagt: Ein Stück kostet 3,20 Euro."},{"type":"rf","statement_de":"Frau Schmidt bezahlt zusammen 10,00 Euro.","statement_en":"Mrs. Schmidt pays 10.00 euros altogether.","answer":"richtig","explanation_de":"Der Text sagt: Das macht zusammen 10,00 Euro."},{"type":"choice","statement_de":"Wie viele Brötchen ohne Körner kauft Frau Schmidt?","statement_en":"How many rolls without grains does Mrs. Schmidt buy?","options":["zwei","vier"],"answer":"vier","explanation_de":"Der Text sagt: Vier ohne Körner und zwei mit Körnern, bitte."}]'::jsonb,
  word_count = 115,
  estimated_reading_time = 2
WHERE id = 'da67d132-0f15-4ef9-b6e8-5323ad741a37'
  AND checks IS NULL; -- idempotency guard: a re-run after this migration has
                       -- already applied is a no-op

-- ---------------------------------------------------------------------------
-- New exam-format lessons (2 rows, guarded by level + title_de)
-- ---------------------------------------------------------------------------

INSERT INTO public.reading_lessons
  (level, title_de, title_en, topic, content_de, content_en, key_vocabulary, questions, checks, word_count, difficulty, estimated_reading_time, order_index)
SELECT
  'a1.2', 'Zwei kurze E-Mails (wie in der Prüfung, Teil 1)', 'Two short emails (exam-style, part 1)', 'Prüfungsformat',
  'Lies die zwei E-Mails. Sind die Sätze richtig oder falsch?

E-Mail 1

Hallo Lisa,

wie geht''s? Am Samstag mache ich eine Grillparty. Kommst du mit? Die Party beginnt um 16 Uhr. Meine Adresse ist Gartenstraße 5. Bring bitte einen Salat mit! Meine Schwester kommt auch. Wir spielen vielleicht Fußball. Das ist bestimmt lustig!

Schreib bald!

Liebe Grüße
Anna

E-Mail 2

Sehr geehrter Herr Bauer,

meine Heizung funktioniert nicht. Es ist sehr kalt. Können Sie das bitte reparieren? Ich bin diese Woche jeden Tag zu Hause. Sie können auch am Wochenende kommen. Meine Wohnung hat die Nummer 12. Bitte rufen Sie mich an. Meine Telefonnummer ist 030 5566778. Vielen Dank für Ihre Hilfe.

Mit freundlichen Grüßen
Sabine Kern', 'Read the two emails. Are the sentences true or false?

Email 1

Hi Lisa,

how are you? On Saturday I''m having a barbecue party. Are you coming? The party starts at 4 p.m. My address is Gartenstraße 5. Please bring a salad! My sister is coming too. We might play football. That is bound to be fun!

Write soon!

Best wishes
Anna

Email 2

Dear Mr. Bauer,

my heating is not working. It is very cold. Could you please repair it? I am at home every day this week. You can also come on the weekend. My apartment is number 12. Please call me. My phone number is 030 5566778. Thank you very much for your help.

Kind regards
Sabine Kern',
  '[{"de":"die Grillparty, -s","en":"barbecue party"},{"de":"mitbringen","en":"to bring along"},{"de":"die Adresse, -n","en":"address"},{"de":"der Salat, -e","en":"salad"},{"de":"die Heizung, -en","en":"heating"},{"de":"kalt","en":"cold"},{"de":"funktionieren","en":"to function, work"},{"de":"reparieren","en":"to repair"},{"de":"die Telefonnummer, -n","en":"phone number"},{"de":"sehr geehrter / sehr geehrte","en":"dear (formal salutation)"},{"de":"mit freundlichen Grüßen","en":"kind regards (formal closing)"}]'::jsonb, '[]'::jsonb, '[{"type":"rf","statement_de":"Anna feiert am Samstag.","statement_en":"Anna is celebrating on Saturday.","answer":"richtig","explanation_de":"Anna schreibt: Am Samstag mache ich eine Grillparty."},{"type":"rf","statement_de":"Die Party beginnt um 18 Uhr.","statement_en":"The party starts at 6 p.m.","answer":"falsch","explanation_de":"Die Party beginnt um 16 Uhr, nicht um 18 Uhr."},{"type":"rf","statement_de":"Lisa soll einen Kuchen mitbringen.","statement_en":"Lisa should bring a cake.","answer":"falsch","explanation_de":"Anna bittet um einen Salat, nicht um einen Kuchen."},{"type":"rf","statement_de":"Frau Kern hat diese Woche viel Zeit zu Hause.","statement_en":"Mrs. Kern has a lot of time at home this week.","answer":"richtig","explanation_de":"Frau Kern schreibt: Ich bin diese Woche jeden Tag zu Hause. Sie können auch am Wochenende kommen."},{"type":"rf","statement_de":"Frau Kerns Wohnung hat die Nummer 12.","statement_en":"Mrs. Kern''s apartment is number 12.","answer":"richtig","explanation_de":"Frau Kern schreibt: Meine Wohnung hat die Nummer 12."},{"type":"rf","statement_de":"Frau Kern hat es zu warm.","statement_en":"Mrs. Kern''s place is too warm.","answer":"falsch","explanation_de":"Frau Kern schreibt: Es ist sehr kalt, nicht zu warm."}]'::jsonb,
  117, 2, 3, 9
WHERE NOT EXISTS (
  SELECT 1 FROM public.reading_lessons WHERE level = 'a1.2' AND title_de = 'Zwei kurze E-Mails (wie in der Prüfung, Teil 1)'
);

INSERT INTO public.reading_lessons
  (level, title_de, title_en, topic, content_de, content_en, key_vocabulary, questions, checks, word_count, difficulty, estimated_reading_time, order_index)
SELECT
  'a1.2', 'Anzeigen zu Wohnen und Arbeit (wie in der Prüfung, Teil 2)', 'Ads about housing and work (exam-style, part 2)', 'Prüfungsformat',
  'Lies die Situation und die zwei Anzeigen. Welche Anzeige passt: a oder b?

Situation 1: Du suchst eine Wohnung in Rostock für unter 500 Euro.

(a) Wohnung in Rostock, 50 m², 620 Euro warm, frei ab 15. Januar. Telefon: 0381 774411.

(b) Wohnung in Rostock, 45 m², 480 Euro warm, frei ab 15. Januar. Telefon: 0381 774422.

Situation 2: Du suchst eine Stelle als Verkäufer/in. Du kannst nur vormittags arbeiten.

(a) Buchladen sucht Aushilfe: Montag bis Freitag, 8 bis 13 Uhr, 10 Euro pro Stunde. Telefon: 0521 663344.

(b) Buchladen sucht Aushilfe: Montag bis Freitag, 14 bis 19 Uhr, 10 Euro pro Stunde. Telefon: 0521 663345.

Situation 3: Du suchst Mathe-Nachhilfe für deine Tochter.

(a) Nachhilfe Mathematik: Frau Weber, Erfahrung mit Kindern, 15 Euro pro Stunde. Telefon: 0711 445566.

(b) Nachhilfe Englisch: Herr Fischer, Erfahrung mit Erwachsenen, 20 Euro pro Stunde. Telefon: 0711 778899.

Situation 4: Du arbeitest tagsüber. Du suchst einen Deutschkurs am Abend.

(a) Deutschkurs, Dienstag und Freitag, 8 bis 10 Uhr, Sprachschule Süd. Anmeldung: 089 221144.

(b) Deutschkurs, Dienstag und Freitag, 19 bis 21 Uhr, Sprachschule Süd. Anmeldung: 089 221144.

Situation 5: Du fährst jeden Tag von Bremen nach Hamburg zur Arbeit.

(a) Fahrgemeinschaft gesucht: Bremen–Hamburg, täglich, Abfahrt 7 Uhr. Kontakt: 0421 665511.

(b) Fahrgemeinschaft gesucht: Hannover–Hamburg, täglich, Abfahrt 7 Uhr. Kontakt: 0511 665511.', 'Read the situation and the two ads. Which ad fits: a or b?

Situation 1: You are looking for an apartment in Rostock for under 500 euros.

(a) Apartment in Rostock, 50 m², 620 euros warm rent, available from January 15th. Phone: 0381 774411.

(b) Apartment in Rostock, 45 m², 480 euros warm rent, available from January 15th. Phone: 0381 774422.

Situation 2: You are looking for a position as a sales assistant. You can only work mornings.

(a) Bookshop looking for help: Monday to Friday, 8 a.m. to 1 p.m., 10 euros per hour. Phone: 0521 663344.

(b) Bookshop looking for help: Monday to Friday, 2 p.m. to 7 p.m., 10 euros per hour. Phone: 0521 663345.

Situation 3: You are looking for math tutoring for your daughter.

(a) Math tutoring: Mrs. Weber, experience with children, 15 euros per hour. Phone: 0711 445566.

(b) English tutoring: Mr. Fischer, experience with adults, 20 euros per hour. Phone: 0711 778899.

Situation 4: You work during the day. You are looking for a German course in the evening.

(a) German course, Tuesday and Friday, 8 to 10 a.m., Sprachschule Süd. Registration: 089 221144.

(b) German course, Tuesday and Friday, 7 to 9 p.m., Sprachschule Süd. Registration: 089 221144.

Situation 5: You drive from Bremen to Hamburg for work every day.

(a) Carpool wanted: Bremen–Hamburg, daily, departure 7 a.m. Contact: 0421 665511.

(b) Carpool wanted: Hannover–Hamburg, daily, departure 7 a.m. Contact: 0511 665511.',
  '[{"de":"die Wohnung, -en","en":"apartment"},{"de":"die Aushilfe, -n","en":"part-time helper"},{"de":"die Stelle, -n","en":"position, job"},{"de":"vormittags","en":"in the mornings"},{"de":"die Nachhilfe","en":"tutoring"},{"de":"die Erfahrung, -en","en":"experience"},{"de":"die Sprachschule, -n","en":"language school"},{"de":"die Anmeldung, -en","en":"registration"},{"de":"die Fahrgemeinschaft, -en","en":"carpool"},{"de":"täglich","en":"daily"}]'::jsonb, '[]'::jsonb, '[{"type":"choice","statement_de":"Situation 1: Wohnung in Rostock — welche Anzeige passt?","statement_en":"Situation 1: Apartment in Rostock — which ad fits?","options":["a","b"],"answer":"b","explanation_de":"Anzeige b kostet 480 Euro, unter 500 Euro. Anzeige a kostet 620 Euro."},{"type":"choice","statement_de":"Situation 2: Stelle am Vormittag — welche Anzeige passt?","statement_en":"Situation 2: Position in the morning — which ad fits?","options":["a","b"],"answer":"a","explanation_de":"Anzeige a ist am Vormittag. Anzeige b ist am Nachmittag und Abend."},{"type":"choice","statement_de":"Situation 3: Mathe-Nachhilfe — welche Anzeige passt?","statement_en":"Situation 3: Math tutoring — which ad fits?","options":["a","b"],"answer":"a","explanation_de":"Anzeige a ist für Mathematik. Anzeige b ist für Englisch."},{"type":"choice","statement_de":"Situation 4: Deutschkurs am Abend — welche Anzeige passt?","statement_en":"Situation 4: German course in the evening — which ad fits?","options":["a","b"],"answer":"b","explanation_de":"Anzeige b ist von 19 bis 21 Uhr. Anzeige a ist von 8 bis 10 Uhr."},{"type":"choice","statement_de":"Situation 5: Fahrgemeinschaft von Bremen — welche Anzeige passt?","statement_en":"Situation 5: Carpool from Bremen — which ad fits?","options":["a","b"],"answer":"a","explanation_de":"Anzeige a fährt von Bremen nach Hamburg. Anzeige b fährt von Hannover nach Hamburg."}]'::jsonb,
  217, 2, 3, 10
WHERE NOT EXISTS (
  SELECT 1 FROM public.reading_lessons WHERE level = 'a1.2' AND title_de = 'Anzeigen zu Wohnen und Arbeit (wie in der Prüfung, Teil 2)'
);

COMMIT;
