-- A1.2 Wortliste: adds 166 new vocabulary rows and fixes 54
-- defective live rows (Course Factory Wave 3, PR B).
--
-- What:
--   1. 166 INSERTs into public.words at level 'a1.2' across
--      9 categories: Travel & Transport (26), Places in Town (25), Health & Doctor (19), Furniture (20), Free Time & Hobbies (24), Money & Shopping (20), Numbers 100-1000 & Ordinals (18), Time Expressions (1), Weather (13).
--      See the source additions JSON and scratchpad vocab/notes.md for the
--      per-category rationale and the pre-existing dupes deliberately
--      skipped.
--   2. 54 guarded UPDATEs against live a1.2 rows, touching
--      german (12), english (4), article (2), plural (23), example_sentence (13)
--      — see the reason recorded against each id in the source fixes JSON
--      and (for each individual UPDATE) inline below.
--
-- Re-run contract: every INSERT is guarded by
--   WHERE NOT EXISTS (SELECT 1 FROM public.words WHERE german = ... AND level = ... AND category = ...)
-- (the table's live UNIQUE (german, level, category)); every UPDATE is
-- guarded by WHERE id = '<id>' AND <field> IS NOT DISTINCT FROM <old-value>,
-- so applying this file twice, or applying it after any of these rows were
-- already fixed by hand, is a no-op. `id` is left to the table's own
-- gen_random_uuid() default on every INSERT.
--
-- How to test: apply by hand in the Supabase SQL editor, then run the
-- verification SELECTs at the bottom of this file.
--
-- Rollback: fixes — re-run each UPDATE with SET and the guard value swapped
-- (old value in SET, new value in the IS NOT DISTINCT FROM guard) — the old
-- value for every fix is quoted verbatim in the source fixes JSON. Additions —
-- there is no id to key a rollback DELETE on before this runs; once applied,
-- words.id may already be referenced by vocab_srs_cards.word_id, so prefer
-- leaving additions in place over deleting by (german, level, category).
--
-- Generated by scripts/words-from-json.mjs on 2026-09-05T17:06:40.594Z.

BEGIN;

-- ===========================================================================
-- Additions: 166 new a1.2 words
-- ===========================================================================

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Bahnhof', 'train station', 'der', 'Bahnhöfe', 'Travel & Transport', 'Der Bahnhof ist in der Stadt.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Bahnhof' AND level = 'a1.2' AND category = 'Travel & Transport'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Zug', 'train', 'der', 'Züge', 'Travel & Transport', 'Der Zug fährt sehr schnell.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Zug' AND level = 'a1.2' AND category = 'Travel & Transport'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Bus', 'bus', 'der', 'Busse', 'Travel & Transport', 'Der Bus fährt sehr oft.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Bus' AND level = 'a1.2' AND category = 'Travel & Transport'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Straßenbahn', 'tram', 'die', 'Straßenbahnen', 'Travel & Transport', 'Die Straßenbahn ist immer pünktlich.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Straßenbahn' AND level = 'a1.2' AND category = 'Travel & Transport'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'U-Bahn', 'subway, metro', 'die', 'U-Bahnen', 'Travel & Transport', 'Ich fahre mit der U-Bahn.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'U-Bahn' AND level = 'a1.2' AND category = 'Travel & Transport'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Fahrkarte', 'ticket', 'die', 'Fahrkarten', 'Travel & Transport', 'Ich kaufe eine Fahrkarte für den Zug.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Fahrkarte' AND level = 'a1.2' AND category = 'Travel & Transport'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Gleis', 'platform, track', 'das', 'Gleise', 'Travel & Transport', 'Der Zug fährt von Gleis drei.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Gleis' AND level = 'a1.2' AND category = 'Travel & Transport'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Haltestelle', 'stop', 'die', 'Haltestellen', 'Travel & Transport', 'Die Haltestelle ist ganz nah.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Haltestelle' AND level = 'a1.2' AND category = 'Travel & Transport'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Flughafen', 'airport', 'der', 'Flughäfen', 'Travel & Transport', 'Der Flughafen ist sehr groß.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Flughafen' AND level = 'a1.2' AND category = 'Travel & Transport'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Flugzeug', 'airplane', 'das', 'Flugzeuge', 'Travel & Transport', 'Das Flugzeug fliegt nach Berlin.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Flugzeug' AND level = 'a1.2' AND category = 'Travel & Transport'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Fahrrad', 'bicycle', 'das', 'Fahrräder', 'Travel & Transport', 'Ich fahre jeden Tag Fahrrad.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Fahrrad' AND level = 'a1.2' AND category = 'Travel & Transport'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Auto', 'car', 'das', 'Autos', 'Travel & Transport', 'Das Auto ist neu und schnell.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Auto' AND level = 'a1.2' AND category = 'Travel & Transport'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Taxi', 'taxi', 'das', 'Taxis', 'Travel & Transport', 'Wir nehmen ein Taxi zum Bahnhof.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Taxi' AND level = 'a1.2' AND category = 'Travel & Transport'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'abfahren', 'to depart', NULL, NULL, 'Travel & Transport', 'Der Zug fährt um acht ab.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'abfahren' AND level = 'a1.2' AND category = 'Travel & Transport'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'ankommen', 'to arrive', NULL, NULL, 'Travel & Transport', 'Der Zug kommt um neun an.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'ankommen' AND level = 'a1.2' AND category = 'Travel & Transport'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'umsteigen', 'to change (trains/buses)', NULL, NULL, 'Travel & Transport', 'Ich steige in Köln um.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'umsteigen' AND level = 'a1.2' AND category = 'Travel & Transport'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'einsteigen', 'to board, get on', NULL, NULL, 'Travel & Transport', 'Bitte steigen Sie hier ein.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'einsteigen' AND level = 'a1.2' AND category = 'Travel & Transport'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'aussteigen', 'to get off', NULL, NULL, 'Travel & Transport', 'Wir steigen hier aus.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'aussteigen' AND level = 'a1.2' AND category = 'Travel & Transport'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Abfahrt', 'departure', 'die', 'Abfahrten', 'Travel & Transport', 'Die Abfahrt ist um sieben Uhr.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Abfahrt' AND level = 'a1.2' AND category = 'Travel & Transport'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Ankunft', 'arrival', 'die', 'Ankünfte', 'Travel & Transport', 'Die Ankunft ist am Nachmittag.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Ankunft' AND level = 'a1.2' AND category = 'Travel & Transport'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Reise', 'trip, journey', 'die', 'Reisen', 'Travel & Transport', 'Die Reise nach Berlin ist lang.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Reise' AND level = 'a1.2' AND category = 'Travel & Transport'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Koffer', 'suitcase', 'der', 'Koffer', 'Travel & Transport', 'Mein Koffer ist sehr schwer.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Koffer' AND level = 'a1.2' AND category = 'Travel & Transport'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Ticket', 'ticket (event, plane)', 'das', 'Tickets', 'Travel & Transport', 'Das Ticket für das Konzert kostet zehn Euro.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Ticket' AND level = 'a1.2' AND category = 'Travel & Transport'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Weg', 'way, path', 'der', 'Wege', 'Travel & Transport', 'Ich frage nach dem Weg.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Weg' AND level = 'a1.2' AND category = 'Travel & Transport'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Fahrplan', 'timetable, schedule', 'der', 'Fahrpläne', 'Travel & Transport', 'Ich lese den Fahrplan.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Fahrplan' AND level = 'a1.2' AND category = 'Travel & Transport'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'fliegen', 'to fly', NULL, NULL, 'Travel & Transport', 'Wir fliegen nach Berlin.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'fliegen' AND level = 'a1.2' AND category = 'Travel & Transport'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Post', 'post office', 'die', NULL, 'Places in Town', 'Ich gehe zur Post.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Post' AND level = 'a1.2' AND category = 'Places in Town'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Bank', 'bank', 'die', 'Banken', 'Places in Town', 'Die Bank ist um die Ecke.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Bank' AND level = 'a1.2' AND category = 'Places in Town'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Apotheke', 'pharmacy', 'die', 'Apotheken', 'Places in Town', 'Die Apotheke öffnet um acht Uhr.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Apotheke' AND level = 'a1.2' AND category = 'Places in Town'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Krankenhaus', 'hospital', 'das', 'Krankenhäuser', 'Places in Town', 'Das Krankenhaus ist sehr groß.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Krankenhaus' AND level = 'a1.2' AND category = 'Places in Town'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Schule', 'school', 'die', 'Schulen', 'Places in Town', 'Die Kinder sind in der Schule.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Schule' AND level = 'a1.2' AND category = 'Places in Town'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Kino', 'cinema', 'das', 'Kinos', 'Places in Town', 'Das Kino zeigt heute einen Film.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Kino' AND level = 'a1.2' AND category = 'Places in Town'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Restaurant', 'restaurant', 'das', 'Restaurants', 'Places in Town', 'Das Restaurant ist sehr gut.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Restaurant' AND level = 'a1.2' AND category = 'Places in Town'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Café', 'café', 'das', 'Cafés', 'Places in Town', 'Das Café ist sehr klein.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Café' AND level = 'a1.2' AND category = 'Places in Town'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Markt', 'market', 'der', 'Märkte', 'Places in Town', 'Wir besuchen den Markt am Samstag.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Markt' AND level = 'a1.2' AND category = 'Places in Town'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Park', 'park', 'der', 'Parks', 'Places in Town', 'Wir spielen im Park Fußball.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Park' AND level = 'a1.2' AND category = 'Places in Town'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Kirche', 'church', 'die', 'Kirchen', 'Places in Town', 'Die Kirche ist sehr alt.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Kirche' AND level = 'a1.2' AND category = 'Places in Town'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Rathaus', 'town hall', 'das', 'Rathäuser', 'Places in Town', 'Das Rathaus ist sehr schön.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Rathaus' AND level = 'a1.2' AND category = 'Places in Town'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Bibliothek', 'library', 'die', 'Bibliotheken', 'Places in Town', 'Die Bibliothek hat viele Bücher.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Bibliothek' AND level = 'a1.2' AND category = 'Places in Town'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Hotel', 'hotel', 'das', 'Hotels', 'Places in Town', 'Das Hotel ist groß und neu.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Hotel' AND level = 'a1.2' AND category = 'Places in Town'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Platz', 'square, place', 'der', 'Plätze', 'Places in Town', 'Der Platz ist in der Stadt.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Platz' AND level = 'a1.2' AND category = 'Places in Town'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Brücke', 'bridge', 'die', 'Brücken', 'Places in Town', 'Die Brücke ist sehr lang.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Brücke' AND level = 'a1.2' AND category = 'Places in Town'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Zentrum', 'center, downtown', 'das', 'Zentren', 'Places in Town', 'Das Zentrum ist nicht weit.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Zentrum' AND level = 'a1.2' AND category = 'Places in Town'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'links', 'left, on the left', NULL, NULL, 'Places in Town', 'Die Bank ist links.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'links' AND level = 'a1.2' AND category = 'Places in Town'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'rechts', 'right, on the right', NULL, NULL, 'Places in Town', 'Die Apotheke ist rechts.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'rechts' AND level = 'a1.2' AND category = 'Places in Town'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'geradeaus', 'straight ahead', NULL, NULL, 'Places in Town', 'Gehen Sie geradeaus, bitte.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'geradeaus' AND level = 'a1.2' AND category = 'Places in Town'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Ecke', 'corner', 'die', 'Ecken', 'Places in Town', 'Um die Ecke ist eine Bank.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Ecke' AND level = 'a1.2' AND category = 'Places in Town'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Supermarkt', 'supermarket', 'der', 'Supermärkte', 'Places in Town', 'Der Supermarkt schließt um acht Uhr.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Supermarkt' AND level = 'a1.2' AND category = 'Places in Town'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Stadt', 'city, town', 'die', 'Städte', 'Places in Town', 'Wir wohnen in der Stadt.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Stadt' AND level = 'a1.2' AND category = 'Places in Town'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Museum', 'museum', 'das', 'Museen', 'Places in Town', 'Das Museum ist alt.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Museum' AND level = 'a1.2' AND category = 'Places in Town'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Polizei', 'police', 'die', NULL, 'Places in Town', 'Die Polizei ist sehr schnell.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Polizei' AND level = 'a1.2' AND category = 'Places in Town'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Schmerz', 'pain', 'der', 'Schmerzen', 'Health & Doctor', 'Der Schmerz ist stark.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Schmerz' AND level = 'a1.2' AND category = 'Health & Doctor'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Kopfschmerzen', 'headache (Pl.)', 'die', NULL, 'Health & Doctor', 'Ich habe Kopfschmerzen.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Kopfschmerzen' AND level = 'a1.2' AND category = 'Health & Doctor'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Bauchschmerzen', 'stomach ache (Pl.)', 'die', NULL, 'Health & Doctor', 'Er hat Bauchschmerzen.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Bauchschmerzen' AND level = 'a1.2' AND category = 'Health & Doctor'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Halsschmerzen', 'sore throat (Pl.)', 'die', NULL, 'Health & Doctor', 'Sie hat Halsschmerzen.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Halsschmerzen' AND level = 'a1.2' AND category = 'Health & Doctor'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Fieber', 'fever', 'das', NULL, 'Health & Doctor', 'Das Kind hat Fieber.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Fieber' AND level = 'a1.2' AND category = 'Health & Doctor'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Husten', 'cough', 'der', NULL, 'Health & Doctor', 'Der Husten dauert drei Tage.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Husten' AND level = 'a1.2' AND category = 'Health & Doctor'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'gesund', 'healthy', NULL, NULL, 'Health & Doctor', 'Er ist wieder gesund.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'gesund' AND level = 'a1.2' AND category = 'Health & Doctor'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Medikament', 'medicine, medication', 'das', 'Medikamente', 'Health & Doctor', 'Ich nehme das Medikament jeden Tag.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Medikament' AND level = 'a1.2' AND category = 'Health & Doctor'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Tablette', 'pill, tablet', 'die', 'Tabletten', 'Health & Doctor', 'Ich nehme eine Tablette.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Tablette' AND level = 'a1.2' AND category = 'Health & Doctor'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Rezept', 'prescription', 'das', 'Rezepte', 'Health & Doctor', 'Der Arzt schreibt ein Rezept.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Rezept' AND level = 'a1.2' AND category = 'Health & Doctor'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Praxis', 'doctor’s office, practice', 'die', 'Praxen', 'Health & Doctor', 'Die Praxis öffnet um neun Uhr.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Praxis' AND level = 'a1.2' AND category = 'Health & Doctor'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Krankenkasse', 'health insurance (fund)', 'die', 'Krankenkassen', 'Health & Doctor', 'Die Krankenkasse bezahlt das Medikament.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Krankenkasse' AND level = 'a1.2' AND category = 'Health & Doctor'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Versichertenkarte', 'health insurance card', 'die', 'Versichertenkarten', 'Health & Doctor', 'Ich brauche meine Versichertenkarte.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Versichertenkarte' AND level = 'a1.2' AND category = 'Health & Doctor'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'wehtun', 'to hurt', NULL, NULL, 'Health & Doctor', 'Mein Kopf tut weh.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'wehtun' AND level = 'a1.2' AND category = 'Health & Doctor'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Erkältung', 'cold (illness)', 'die', 'Erkältungen', 'Health & Doctor', 'Ich habe eine Erkältung.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Erkältung' AND level = 'a1.2' AND category = 'Health & Doctor'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Grippe', 'flu', 'die', NULL, 'Health & Doctor', 'Sie hat die Grippe.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Grippe' AND level = 'a1.2' AND category = 'Health & Doctor'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'niesen', 'to sneeze', NULL, NULL, 'Health & Doctor', 'Ich niese sehr oft.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'niesen' AND level = 'a1.2' AND category = 'Health & Doctor'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Krankenwagen', 'ambulance', 'der', 'Krankenwagen', 'Health & Doctor', 'Der Krankenwagen kommt schnell.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Krankenwagen' AND level = 'a1.2' AND category = 'Health & Doctor'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Zahnarzt', 'dentist', 'der', 'Zahnärzte', 'Health & Doctor', 'Ich habe einen Termin beim Zahnarzt.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Zahnarzt' AND level = 'a1.2' AND category = 'Health & Doctor'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Bett', 'bed', 'das', 'Betten', 'Furniture', 'Das Bett ist sehr bequem.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Bett' AND level = 'a1.2' AND category = 'Furniture'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Sofa', 'sofa, couch', 'das', 'Sofas', 'Furniture', 'Das Sofa ist groß und bequem.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Sofa' AND level = 'a1.2' AND category = 'Furniture'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Schrank', 'wardrobe, cabinet', 'der', 'Schränke', 'Furniture', 'Der Schrank ist sehr groß.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Schrank' AND level = 'a1.2' AND category = 'Furniture'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Regal', 'shelf', 'das', 'Regale', 'Furniture', 'Das Regal ist voll mit Büchern.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Regal' AND level = 'a1.2' AND category = 'Furniture'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Fernseher', 'television', 'der', 'Fernseher', 'Furniture', 'Der Fernseher ist sehr neu.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Fernseher' AND level = 'a1.2' AND category = 'Furniture'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Kühlschrank', 'refrigerator', 'der', 'Kühlschränke', 'Furniture', 'Der Kühlschrank ist leer.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Kühlschrank' AND level = 'a1.2' AND category = 'Furniture'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Herd', 'stove', 'der', 'Herde', 'Furniture', 'Der Herd ist heiß.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Herd' AND level = 'a1.2' AND category = 'Furniture'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Waschmaschine', 'washing machine', 'die', 'Waschmaschinen', 'Furniture', 'Die Waschmaschine ist kaputt.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Waschmaschine' AND level = 'a1.2' AND category = 'Furniture'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Spiegel', 'mirror', 'der', 'Spiegel', 'Furniture', 'Der Spiegel ist sehr groß.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Spiegel' AND level = 'a1.2' AND category = 'Furniture'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Teppich', 'carpet, rug', 'der', 'Teppiche', 'Furniture', 'Der Teppich ist rot.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Teppich' AND level = 'a1.2' AND category = 'Furniture'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Miete', 'rent', 'die', NULL, 'Furniture', 'Die Miete ist dreihundert Euro.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Miete' AND level = 'a1.2' AND category = 'Furniture'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Vermieter', 'landlord', 'der', 'Vermieter', 'Furniture', 'Mein Vermieter ist sehr nett.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Vermieter' AND level = 'a1.2' AND category = 'Furniture'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Vermieterin', 'landlady', 'die', 'Vermieterinnen', 'Furniture', 'Die Vermieterin ist sehr freundlich.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Vermieterin' AND level = 'a1.2' AND category = 'Furniture'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Nachbar', 'neighbor (m)', 'der', 'Nachbarn', 'Furniture', 'Mein Nachbar ist sehr laut.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Nachbar' AND level = 'a1.2' AND category = 'Furniture'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Nachbarin', 'neighbor (f)', 'die', 'Nachbarinnen', 'Furniture', 'Meine Nachbarin hat zwei Kinder.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Nachbarin' AND level = 'a1.2' AND category = 'Furniture'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Kissen', 'pillow, cushion', 'das', 'Kissen', 'Furniture', 'Das Kissen ist sehr weich.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Kissen' AND level = 'a1.2' AND category = 'Furniture'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Bettdecke', 'duvet, blanket', 'die', 'Bettdecken', 'Furniture', 'Die Bettdecke ist warm und dick.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Bettdecke' AND level = 'a1.2' AND category = 'Furniture'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Vorhang', 'curtain', 'der', 'Vorhänge', 'Furniture', 'Der Vorhang ist blau.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Vorhang' AND level = 'a1.2' AND category = 'Furniture'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Möbel', 'furniture (Pl.)', NULL, NULL, 'Furniture', 'Die Möbel sind neu.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Möbel' AND level = 'a1.2' AND category = 'Furniture'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Steckdose', 'power outlet, socket', 'die', 'Steckdosen', 'Furniture', 'Die Steckdose ist kaputt.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Steckdose' AND level = 'a1.2' AND category = 'Furniture'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Hobby', 'hobby', 'das', 'Hobbys', 'Free Time & Hobbies', 'Mein Hobby ist Fußball.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Hobby' AND level = 'a1.2' AND category = 'Free Time & Hobbies'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Sport', 'sport, exercise', 'der', NULL, 'Free Time & Hobbies', 'Ich mache gern Sport.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Sport' AND level = 'a1.2' AND category = 'Free Time & Hobbies'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Fußball', 'soccer, football', 'der', NULL, 'Free Time & Hobbies', 'Wir spielen Fußball im Park.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Fußball' AND level = 'a1.2' AND category = 'Free Time & Hobbies'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'schwimmen', 'to swim', NULL, NULL, 'Free Time & Hobbies', 'Wir schwimmen im Sommer.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'schwimmen' AND level = 'a1.2' AND category = 'Free Time & Hobbies'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Musik', 'music', 'die', NULL, 'Free Time & Hobbies', 'Ich höre gern Musik.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Musik' AND level = 'a1.2' AND category = 'Free Time & Hobbies'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'tanzen', 'to dance', NULL, NULL, 'Free Time & Hobbies', 'Sie tanzt sehr gern.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'tanzen' AND level = 'a1.2' AND category = 'Free Time & Hobbies'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Konzert', 'concert', 'das', 'Konzerte', 'Free Time & Hobbies', 'Das Konzert ist heute Abend.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Konzert' AND level = 'a1.2' AND category = 'Free Time & Hobbies'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Film', 'movie, film', 'der', 'Filme', 'Free Time & Hobbies', 'Der Film beginnt um acht Uhr.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Film' AND level = 'a1.2' AND category = 'Free Time & Hobbies'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Spaziergang', 'walk, stroll', 'der', 'Spaziergänge', 'Free Time & Hobbies', 'Der Spaziergang ist sehr schön.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Spaziergang' AND level = 'a1.2' AND category = 'Free Time & Hobbies'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'spazieren gehen', 'to go for a walk', NULL, NULL, 'Free Time & Hobbies', 'Wir gehen am Sonntag spazieren.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'spazieren gehen' AND level = 'a1.2' AND category = 'Free Time & Hobbies'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'wandern', 'to hike', NULL, NULL, 'Free Time & Hobbies', 'Wir wandern jeden Sommer.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'wandern' AND level = 'a1.2' AND category = 'Free Time & Hobbies'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Rad fahren', 'to cycle', NULL, NULL, 'Free Time & Hobbies', 'Ich fahre gern Rad.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Rad fahren' AND level = 'a1.2' AND category = 'Free Time & Hobbies'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Party', 'party', 'die', 'Partys', 'Free Time & Hobbies', 'Die Party ist am Samstag.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Party' AND level = 'a1.2' AND category = 'Free Time & Hobbies'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Urlaub', 'vacation, holiday', 'der', NULL, 'Free Time & Hobbies', 'Der Urlaub beginnt bald.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Urlaub' AND level = 'a1.2' AND category = 'Free Time & Hobbies'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Ferien', 'school holidays (Pl.)', 'die', NULL, 'Free Time & Hobbies', 'Die Ferien sind sehr lang.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Ferien' AND level = 'a1.2' AND category = 'Free Time & Hobbies'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Verein', 'club, association', 'der', 'Vereine', 'Free Time & Hobbies', 'Der Verein spielt jeden Sonntag.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Verein' AND level = 'a1.2' AND category = 'Free Time & Hobbies'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Spiel', 'game', 'das', 'Spiele', 'Free Time & Hobbies', 'Das Spiel ist sehr lustig.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Spiel' AND level = 'a1.2' AND category = 'Free Time & Hobbies'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Karte', 'card', 'die', 'Karten', 'Free Time & Hobbies', 'Wir spielen Karten am Abend.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Karte' AND level = 'a1.2' AND category = 'Free Time & Hobbies'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'singen', 'to sing', NULL, NULL, 'Free Time & Hobbies', 'Ich singe jeden Tag.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'singen' AND level = 'a1.2' AND category = 'Free Time & Hobbies'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Ausflug', 'outing, excursion', 'der', 'Ausflüge', 'Free Time & Hobbies', 'Der Ausflug war sehr schön.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Ausflug' AND level = 'a1.2' AND category = 'Free Time & Hobbies'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'laufen', 'to run, walk', NULL, NULL, 'Free Time & Hobbies', 'Er läuft jeden Morgen.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'laufen' AND level = 'a1.2' AND category = 'Free Time & Hobbies'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'fernsehen', 'to watch TV', NULL, NULL, 'Free Time & Hobbies', 'Ich sehe abends fern.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'fernsehen' AND level = 'a1.2' AND category = 'Free Time & Hobbies'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Schwimmbad', 'swimming pool', 'das', 'Schwimmbäder', 'Free Time & Hobbies', 'Das Schwimmbad ist im Sommer offen.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Schwimmbad' AND level = 'a1.2' AND category = 'Free Time & Hobbies'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Foto', 'photo', 'das', 'Fotos', 'Free Time & Hobbies', 'Ich mache ein Foto.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Foto' AND level = 'a1.2' AND category = 'Free Time & Hobbies'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Geld', 'money', 'das', NULL, 'Money & Shopping', 'Ich habe kein Geld dabei.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Geld' AND level = 'a1.2' AND category = 'Money & Shopping'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Euro', 'euro', 'der', 'Euro', 'Money & Shopping', 'Ich brauche noch fünf Euro.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Euro' AND level = 'a1.2' AND category = 'Money & Shopping'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Cent', 'cent', 'der', 'Cent', 'Money & Shopping', 'Ein Apfel kostet vierzig Cent.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Cent' AND level = 'a1.2' AND category = 'Money & Shopping'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Preis', 'price', 'der', 'Preise', 'Money & Shopping', 'Der Preis ist sehr hoch.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Preis' AND level = 'a1.2' AND category = 'Money & Shopping'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'kosten', 'to cost', NULL, NULL, 'Money & Shopping', 'Wie viel kostet die Jacke?'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'kosten' AND level = 'a1.2' AND category = 'Money & Shopping'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'bezahlen', 'to pay', NULL, NULL, 'Money & Shopping', 'Ich bezahle mit der Kreditkarte.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'bezahlen' AND level = 'a1.2' AND category = 'Money & Shopping'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Kasse', 'checkout, cash register', 'die', 'Kassen', 'Money & Shopping', 'Ich bezahle an der Kasse.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Kasse' AND level = 'a1.2' AND category = 'Money & Shopping'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Rechnung', 'bill, invoice', 'die', 'Rechnungen', 'Money & Shopping', 'Die Rechnung ist vierzig Euro.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Rechnung' AND level = 'a1.2' AND category = 'Money & Shopping'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Kreditkarte', 'credit card', 'die', 'Kreditkarten', 'Money & Shopping', 'Meine Kreditkarte ist neu.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Kreditkarte' AND level = 'a1.2' AND category = 'Money & Shopping'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'bar', 'in cash', NULL, NULL, 'Money & Shopping', 'Ich bezahle lieber bar.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'bar' AND level = 'a1.2' AND category = 'Money & Shopping'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Angebot', 'offer, deal', 'das', 'Angebote', 'Money & Shopping', 'Das Angebot ist sehr gut.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Angebot' AND level = 'a1.2' AND category = 'Money & Shopping'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Rabatt', 'discount', 'der', 'Rabatte', 'Money & Shopping', 'Der Rabatt ist zwanzig Euro.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Rabatt' AND level = 'a1.2' AND category = 'Money & Shopping'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Quittung', 'receipt', 'die', 'Quittungen', 'Money & Shopping', 'Ich brauche die Quittung, bitte.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Quittung' AND level = 'a1.2' AND category = 'Money & Shopping'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Kunde', 'customer (m)', 'der', 'Kunden', 'Money & Shopping', 'Der Kunde wartet an der Kasse.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Kunde' AND level = 'a1.2' AND category = 'Money & Shopping'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Kundin', 'customer (f)', 'die', 'Kundinnen', 'Money & Shopping', 'Die Kundin bezahlt bar.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Kundin' AND level = 'a1.2' AND category = 'Money & Shopping'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Geschäft', 'shop, store', 'das', 'Geschäfte', 'Money & Shopping', 'Das Geschäft öffnet um neun Uhr.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Geschäft' AND level = 'a1.2' AND category = 'Money & Shopping'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Kaufhaus', 'department store', 'das', 'Kaufhäuser', 'Money & Shopping', 'Das Kaufhaus ist sehr groß.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Kaufhaus' AND level = 'a1.2' AND category = 'Money & Shopping'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'wechseln', 'to change, exchange', NULL, NULL, 'Money & Shopping', 'Ich möchte Geld wechseln.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'wechseln' AND level = 'a1.2' AND category = 'Money & Shopping'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Kilo', 'kilo(gram)', 'das', 'Kilo', 'Money & Shopping', 'Ich kaufe ein Kilo Tomaten.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Kilo' AND level = 'a1.2' AND category = 'Money & Shopping'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Stück', 'piece', 'das', 'Stück', 'Money & Shopping', 'Ich möchte ein Stück Kuchen.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Stück' AND level = 'a1.2' AND category = 'Money & Shopping'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'zweihundert', 'two hundred', NULL, NULL, 'Numbers 100-1000 & Ordinals', 'Das Dorf hat zweihundert Häuser.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'zweihundert' AND level = 'a1.2' AND category = 'Numbers 100-1000 & Ordinals'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'dreihundert', 'three hundred', NULL, NULL, 'Numbers 100-1000 & Ordinals', 'Die Stadt hat dreihundert Straßen.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'dreihundert' AND level = 'a1.2' AND category = 'Numbers 100-1000 & Ordinals'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'vierhundert', 'four hundred', NULL, NULL, 'Numbers 100-1000 & Ordinals', 'Die Firma hat vierhundert Autos.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'vierhundert' AND level = 'a1.2' AND category = 'Numbers 100-1000 & Ordinals'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'fünfhundert', 'five hundred', NULL, NULL, 'Numbers 100-1000 & Ordinals', 'Der Zug hat fünfhundert Plätze.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'fünfhundert' AND level = 'a1.2' AND category = 'Numbers 100-1000 & Ordinals'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'sechshundert', 'six hundred', NULL, NULL, 'Numbers 100-1000 & Ordinals', 'Die Schule hat sechshundert Schüler.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'sechshundert' AND level = 'a1.2' AND category = 'Numbers 100-1000 & Ordinals'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'siebenhundert', 'seven hundred', NULL, NULL, 'Numbers 100-1000 & Ordinals', 'Das Buch hat siebenhundert Seiten.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'siebenhundert' AND level = 'a1.2' AND category = 'Numbers 100-1000 & Ordinals'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'achthundert', 'eight hundred', NULL, NULL, 'Numbers 100-1000 & Ordinals', 'Das Hotel hat achthundert Betten.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'achthundert' AND level = 'a1.2' AND category = 'Numbers 100-1000 & Ordinals'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'neunhundert', 'nine hundred', NULL, NULL, 'Numbers 100-1000 & Ordinals', 'Der Berg ist neunhundert Meter hoch.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'neunhundert' AND level = 'a1.2' AND category = 'Numbers 100-1000 & Ordinals'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'tausend', 'thousand', NULL, NULL, 'Numbers 100-1000 & Ordinals', 'Die Stadt hat tausend Wohnungen.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'tausend' AND level = 'a1.2' AND category = 'Numbers 100-1000 & Ordinals'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'erste', 'first', NULL, NULL, 'Numbers 100-1000 & Ordinals', 'Er wohnt im ersten Stock.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'erste' AND level = 'a1.2' AND category = 'Numbers 100-1000 & Ordinals'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'zweite', 'second', NULL, NULL, 'Numbers 100-1000 & Ordinals', 'Die zweite Straße links, bitte.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'zweite' AND level = 'a1.2' AND category = 'Numbers 100-1000 & Ordinals'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'dritte', 'third', NULL, NULL, 'Numbers 100-1000 & Ordinals', 'Der Kurs beginnt am dritten März.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'dritte' AND level = 'a1.2' AND category = 'Numbers 100-1000 & Ordinals'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'vierte', 'fourth', NULL, NULL, 'Numbers 100-1000 & Ordinals', 'Mein Geburtstag ist am vierten Juli.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'vierte' AND level = 'a1.2' AND category = 'Numbers 100-1000 & Ordinals'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'fünfte', 'fifth', NULL, NULL, 'Numbers 100-1000 & Ordinals', 'Wir fahren am fünften August.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'fünfte' AND level = 'a1.2' AND category = 'Numbers 100-1000 & Ordinals'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'siebte', 'seventh', NULL, NULL, 'Numbers 100-1000 & Ordinals', 'Der siebte Tag ist Sonntag.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'siebte' AND level = 'a1.2' AND category = 'Numbers 100-1000 & Ordinals'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'achte', 'eighth', NULL, NULL, 'Numbers 100-1000 & Ordinals', 'Wir fahren am achten Juni.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'achte' AND level = 'a1.2' AND category = 'Numbers 100-1000 & Ordinals'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'zehnte', 'tenth', NULL, NULL, 'Numbers 100-1000 & Ordinals', 'Das Fest ist am zehnten September.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'zehnte' AND level = 'a1.2' AND category = 'Numbers 100-1000 & Ordinals'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'zwanzigste', 'twentieth', NULL, NULL, 'Numbers 100-1000 & Ordinals', 'Er kommt am zwanzigsten Oktober.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'zwanzigste' AND level = 'a1.2' AND category = 'Numbers 100-1000 & Ordinals'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'letzte', 'last', NULL, NULL, 'Time Expressions', 'Letzte Woche war ich krank.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'letzte' AND level = 'a1.2' AND category = 'Time Expressions'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Wetter', 'weather', 'das', NULL, 'Weather', 'Das Wetter ist heute gut.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Wetter' AND level = 'a1.2' AND category = 'Weather'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Regen', 'rain', 'der', NULL, 'Weather', 'Der Regen ist sehr stark.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Regen' AND level = 'a1.2' AND category = 'Weather'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'regnen', 'to rain', NULL, NULL, 'Weather', 'Es regnet heute wieder.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'regnen' AND level = 'a1.2' AND category = 'Weather'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Wind', 'wind', 'der', NULL, 'Weather', 'Der Wind ist sehr kalt.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Wind' AND level = 'a1.2' AND category = 'Weather'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'windig', 'windy', NULL, NULL, 'Weather', 'Es ist heute sehr windig.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'windig' AND level = 'a1.2' AND category = 'Weather'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Wolke', 'cloud', 'die', 'Wolken', 'Weather', 'Die Wolken sind grau.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Wolke' AND level = 'a1.2' AND category = 'Weather'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'wolkig', 'cloudy', NULL, NULL, 'Weather', 'Der Himmel ist wolkig.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'wolkig' AND level = 'a1.2' AND category = 'Weather'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Nebel', 'fog', 'der', NULL, 'Weather', 'Heute ist viel Nebel.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Nebel' AND level = 'a1.2' AND category = 'Weather'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Gewitter', 'thunderstorm', 'das', 'Gewitter', 'Weather', 'Das Gewitter ist sehr laut.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Gewitter' AND level = 'a1.2' AND category = 'Weather'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Grad', 'degree', 'der', 'Grad', 'Weather', 'Heute sind es zehn Grad.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Grad' AND level = 'a1.2' AND category = 'Weather'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'Temperatur', 'temperature', 'die', 'Temperaturen', 'Weather', 'Die Temperatur ist sehr hoch.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Temperatur' AND level = 'a1.2' AND category = 'Weather'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'sonnig', 'sunny', NULL, NULL, 'Weather', 'Der Tag ist sehr sonnig.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'sonnig' AND level = 'a1.2' AND category = 'Weather'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.2', 'schneien', 'to snow', NULL, NULL, 'Weather', 'Es schneit heute.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'schneien' AND level = 'a1.2' AND category = 'Weather'
);

-- ===========================================================================
-- Fixes: 54 guarded UPDATEs against defective live rows
-- ===========================================================================

-- german carries the article inside the string while the article field already holds it correctly (e.g. WordCard would be fine, but SrsTrainer.jsx prepends word.article unconditionally, so this currently renders as "das das Jahr" on the flashcard front/back) — same class of bug fixed in the A1.1 batch.
UPDATE public.words SET german = 'Wochenende'
WHERE id = 'dc6159e1-a846-48b5-8c0d-f2bfa25063a2'::uuid AND german IS NOT DISTINCT FROM 'das Wochenende';

-- german carries the article inside the string while the article field already holds it correctly (e.g. WordCard would be fine, but SrsTrainer.jsx prepends word.article unconditionally, so this currently renders as "das das Jahr" on the flashcard front/back) — same class of bug fixed in the A1.1 batch.
UPDATE public.words SET german = 'Abend'
WHERE id = '342c0ba4-ef8f-4029-99e9-bbeb116d6451'::uuid AND german IS NOT DISTINCT FROM 'der Abend';

-- german carries the article inside the string while the article field already holds it correctly (e.g. WordCard would be fine, but SrsTrainer.jsx prepends word.article unconditionally, so this currently renders as "das das Jahr" on the flashcard front/back) — same class of bug fixed in the A1.1 batch.
UPDATE public.words SET german = 'Mittag'
WHERE id = '3125d3a1-ee51-41b8-81f5-4797903a3d3b'::uuid AND german IS NOT DISTINCT FROM 'der Mittag';

-- german carries the article inside the string while the article field already holds it correctly (e.g. WordCard would be fine, but SrsTrainer.jsx prepends word.article unconditionally, so this currently renders as "das das Jahr" on the flashcard front/back) — same class of bug fixed in the A1.1 batch.
UPDATE public.words SET german = 'Morgen'
WHERE id = '9a345cf4-e390-4e9a-903e-05cbfd033b50'::uuid AND german IS NOT DISTINCT FROM 'der Morgen';

-- german carries the article inside the string while the article field already holds it correctly (e.g. WordCard would be fine, but SrsTrainer.jsx prepends word.article unconditionally, so this currently renders as "das das Jahr" on the flashcard front/back) — same class of bug fixed in the A1.1 batch.
UPDATE public.words SET german = 'Minute'
WHERE id = 'e3333a7e-6372-4006-a260-05f356b95ed0'::uuid AND german IS NOT DISTINCT FROM 'die Minute';

-- german carries the article inside the string while the article field already holds it correctly (e.g. WordCard would be fine, but SrsTrainer.jsx prepends word.article unconditionally, so this currently renders as "das das Jahr" on the flashcard front/back) — same class of bug fixed in the A1.1 batch.
UPDATE public.words SET german = 'Nacht'
WHERE id = '3722e56e-242e-4d88-b8a4-bc8608e2cc2c'::uuid AND german IS NOT DISTINCT FROM 'die Nacht';

-- german carries the article inside the string while the article field already holds it correctly (e.g. WordCard would be fine, but SrsTrainer.jsx prepends word.article unconditionally, so this currently renders as "das das Jahr" on the flashcard front/back) — same class of bug fixed in the A1.1 batch.
UPDATE public.words SET german = 'Stunde'
WHERE id = 'ad917256-a010-4a24-9fe2-8854985fb7eb'::uuid AND german IS NOT DISTINCT FROM 'die Stunde';

-- german carries the article inside the string while the article field already holds it correctly (e.g. WordCard would be fine, but SrsTrainer.jsx prepends word.article unconditionally, so this currently renders as "das das Jahr" on the flashcard front/back) — same class of bug fixed in the A1.1 batch.
UPDATE public.words SET german = 'Uhr'
WHERE id = '1b1f89d3-e928-44b9-953c-ea4657e1ccd1'::uuid AND german IS NOT DISTINCT FROM 'die Uhr';

-- german carries the article inside the string while the article field already holds it correctly (e.g. WordCard would be fine, but SrsTrainer.jsx prepends word.article unconditionally, so this currently renders as "das das Jahr" on the flashcard front/back) — same class of bug fixed in the A1.1 batch.
UPDATE public.words SET german = 'Woche'
WHERE id = '90e79e9c-70da-4650-a59c-5a22886665e6'::uuid AND german IS NOT DISTINCT FROM 'die Woche';

-- german carries the article inside the string while the article field already holds it correctly (e.g. WordCard would be fine, but SrsTrainer.jsx prepends word.article unconditionally, so this currently renders as "das das Jahr" on the flashcard front/back) — same class of bug fixed in the A1.1 batch. Also glossed apart from the pre-existing lowercase "morgen" (adverb, "tomorrow") it now sits beside in the same category/level, so the two cards read as clearly different words.
UPDATE public.words SET english = 'morning (noun)'
WHERE id = '9a345cf4-e390-4e9a-903e-05cbfd033b50'::uuid AND english IS NOT DISTINCT FROM 'morning';

-- stripping the article would duplicate the noun already live in Months & Seasons (Jahr das/Jahre; Monat der/Monate) -- the Monat case is worse, sharing that row's exact example sentence. No DELETE is available, so the row is repurposed into a genuinely missing Time Expressions adverb instead of being turned into a same-level duplicate.
UPDATE public.words SET german = 'bald'
WHERE id = 'c4e66eae-5ae1-4e92-94fe-7dba0a1c6269'::uuid AND german IS NOT DISTINCT FROM 'das Jahr';

-- stripping the article would duplicate the noun already live in Months & Seasons (Jahr das/Jahre; Monat der/Monate) -- the Monat case is worse, sharing that row's exact example sentence. No DELETE is available, so the row is repurposed into a genuinely missing Time Expressions adverb instead of being turned into a same-level duplicate.
UPDATE public.words SET article = NULL
WHERE id = 'c4e66eae-5ae1-4e92-94fe-7dba0a1c6269'::uuid AND article IS NOT DISTINCT FROM 'das';

-- stripping the article would duplicate the noun already live in Months & Seasons (Jahr das/Jahre; Monat der/Monate) -- the Monat case is worse, sharing that row's exact example sentence. No DELETE is available, so the row is repurposed into a genuinely missing Time Expressions adverb instead of being turned into a same-level duplicate.
UPDATE public.words SET plural = NULL
WHERE id = 'c4e66eae-5ae1-4e92-94fe-7dba0a1c6269'::uuid AND plural IS NOT DISTINCT FROM 'Jahre';

-- stripping the article would duplicate the noun already live in Months & Seasons (Jahr das/Jahre; Monat der/Monate) -- the Monat case is worse, sharing that row's exact example sentence. No DELETE is available, so the row is repurposed into a genuinely missing Time Expressions adverb instead of being turned into a same-level duplicate.
UPDATE public.words SET english = 'soon'
WHERE id = 'c4e66eae-5ae1-4e92-94fe-7dba0a1c6269'::uuid AND english IS NOT DISTINCT FROM 'year';

-- stripping the article would duplicate the noun already live in Months & Seasons (Jahr das/Jahre; Monat der/Monate) -- the Monat case is worse, sharing that row's exact example sentence. No DELETE is available, so the row is repurposed into a genuinely missing Time Expressions adverb instead of being turned into a same-level duplicate.
UPDATE public.words SET example_sentence = 'Der Bus kommt bald.'
WHERE id = 'c4e66eae-5ae1-4e92-94fe-7dba0a1c6269'::uuid AND example_sentence IS NOT DISTINCT FROM 'Ich bin seit zwei Jahren hier.';

-- stripping the article would duplicate the noun already live in Months & Seasons (Jahr das/Jahre; Monat der/Monate) -- the Monat case is worse, sharing that row's exact example sentence. No DELETE is available, so the row is repurposed into a genuinely missing Time Expressions adverb instead of being turned into a same-level duplicate.
UPDATE public.words SET german = 'wieder'
WHERE id = 'd7e01d71-6baf-425e-9b6c-8c9f0071dfc2'::uuid AND german IS NOT DISTINCT FROM 'der Monat';

-- stripping the article would duplicate the noun already live in Months & Seasons (Jahr das/Jahre; Monat der/Monate) -- the Monat case is worse, sharing that row's exact example sentence. No DELETE is available, so the row is repurposed into a genuinely missing Time Expressions adverb instead of being turned into a same-level duplicate.
UPDATE public.words SET article = NULL
WHERE id = 'd7e01d71-6baf-425e-9b6c-8c9f0071dfc2'::uuid AND article IS NOT DISTINCT FROM 'der';

-- stripping the article would duplicate the noun already live in Months & Seasons (Jahr das/Jahre; Monat der/Monate) -- the Monat case is worse, sharing that row's exact example sentence. No DELETE is available, so the row is repurposed into a genuinely missing Time Expressions adverb instead of being turned into a same-level duplicate.
UPDATE public.words SET plural = NULL
WHERE id = 'd7e01d71-6baf-425e-9b6c-8c9f0071dfc2'::uuid AND plural IS NOT DISTINCT FROM 'Monate';

-- stripping the article would duplicate the noun already live in Months & Seasons (Jahr das/Jahre; Monat der/Monate) -- the Monat case is worse, sharing that row's exact example sentence. No DELETE is available, so the row is repurposed into a genuinely missing Time Expressions adverb instead of being turned into a same-level duplicate.
UPDATE public.words SET english = 'again'
WHERE id = 'd7e01d71-6baf-425e-9b6c-8c9f0071dfc2'::uuid AND english IS NOT DISTINCT FROM 'month';

-- stripping the article would duplicate the noun already live in Months & Seasons (Jahr das/Jahre; Monat der/Monate) -- the Monat case is worse, sharing that row's exact example sentence. No DELETE is available, so the row is repurposed into a genuinely missing Time Expressions adverb instead of being turned into a same-level duplicate.
UPDATE public.words SET example_sentence = 'Ich komme morgen wieder.'
WHERE id = 'd7e01d71-6baf-425e-9b6c-8c9f0071dfc2'::uuid AND example_sentence IS NOT DISTINCT FROM 'Ein Jahr hat zwölf Monate.';

-- "der Verwandter" is ungrammatical (Verwandter is only correct article-less; the article form is "der Verwandte") and duplicates 59b49e32 "die Verwandte" in meaning -- exactly the adjectival-noun declension the level file bans. Repairing german to "Verwandte" would collide with 59b49e32 under UNIQUE(german,level,category), and no DELETE is available, so the row is repurposed into a plain noun genuinely missing from both live lists.
UPDATE public.words SET german = 'Schwiegersohn'
WHERE id = '85114110-0d07-4e1f-92f9-b65958e1c1db'::uuid AND german IS NOT DISTINCT FROM 'Verwandter';

-- "der Verwandter" is ungrammatical (Verwandter is only correct article-less; the article form is "der Verwandte") and duplicates 59b49e32 "die Verwandte" in meaning -- exactly the adjectival-noun declension the level file bans. Repairing german to "Verwandte" would collide with 59b49e32 under UNIQUE(german,level,category), and no DELETE is available, so the row is repurposed into a plain noun genuinely missing from both live lists.
UPDATE public.words SET plural = 'Schwiegersöhne'
WHERE id = '85114110-0d07-4e1f-92f9-b65958e1c1db'::uuid AND plural IS NOT DISTINCT FROM 'Verwandten';

-- "der Verwandter" is ungrammatical (Verwandter is only correct article-less; the article form is "der Verwandte") and duplicates 59b49e32 "die Verwandte" in meaning -- exactly the adjectival-noun declension the level file bans. Repairing german to "Verwandte" would collide with 59b49e32 under UNIQUE(german,level,category), and no DELETE is available, so the row is repurposed into a plain noun genuinely missing from both live lists.
UPDATE public.words SET english = 'son-in-law'
WHERE id = '85114110-0d07-4e1f-92f9-b65958e1c1db'::uuid AND english IS NOT DISTINCT FROM 'relative (male)';

-- "der Verwandter" is ungrammatical (Verwandter is only correct article-less; the article form is "der Verwandte") and duplicates 59b49e32 "die Verwandte" in meaning -- exactly the adjectival-noun declension the level file bans. Repairing german to "Verwandte" would collide with 59b49e32 under UNIQUE(german,level,category), and no DELETE is available, so the row is repurposed into a plain noun genuinely missing from both live lists.
UPDATE public.words SET example_sentence = 'Mein Schwiegersohn ist sehr nett.'
WHERE id = '85114110-0d07-4e1f-92f9-b65958e1c1db'::uuid AND example_sentence IS NOT DISTINCT FROM 'Ein Verwandter kommt zur Party.';

-- month names are not counted at A1 ("zwei Januare" is not idiomatic); Dezember/November/Oktober/September already correctly carry plural null, these eight do not.
UPDATE public.words SET plural = NULL
WHERE id = 'f0baa8fe-52af-4f89-9aad-7750a80912c0'::uuid AND plural IS NOT DISTINCT FROM 'Januare';

-- month names are not counted at A1 ("zwei Januare" is not idiomatic); Dezember/November/Oktober/September already correctly carry plural null, these eight do not.
UPDATE public.words SET plural = NULL
WHERE id = 'f7dea2f4-3cdc-4b39-9b46-fc79732e0f3a'::uuid AND plural IS NOT DISTINCT FROM 'Februare';

-- month names are not counted at A1 ("zwei Januare" is not idiomatic); Dezember/November/Oktober/September already correctly carry plural null, these eight do not.
UPDATE public.words SET plural = NULL
WHERE id = '95593970-f0d4-48a2-8e5c-85c6fdc86a37'::uuid AND plural IS NOT DISTINCT FROM 'Aprile';

-- month names are not counted at A1 ("zwei Januare" is not idiomatic); Dezember/November/Oktober/September already correctly carry plural null, these eight do not.
UPDATE public.words SET plural = NULL
WHERE id = 'dc7402bf-4793-49b8-86f0-432ad6db01e4'::uuid AND plural IS NOT DISTINCT FROM 'Maie';

-- month names are not counted at A1 ("zwei Januare" is not idiomatic); Dezember/November/Oktober/September already correctly carry plural null, these eight do not.
UPDATE public.words SET plural = NULL
WHERE id = '7d633b11-dc64-4f91-9e55-d6a91c32dd0e'::uuid AND plural IS NOT DISTINCT FROM 'Junis';

-- month names are not counted at A1 ("zwei Januare" is not idiomatic); Dezember/November/Oktober/September already correctly carry plural null, these eight do not.
UPDATE public.words SET plural = NULL
WHERE id = '4f493560-c6a0-4d66-b24c-36d104bd4422'::uuid AND plural IS NOT DISTINCT FROM 'Julis';

-- month names are not counted at A1 ("zwei Januare" is not idiomatic); Dezember/November/Oktober/September already correctly carry plural null, these eight do not.
UPDATE public.words SET plural = NULL
WHERE id = 'fe060adf-a7fb-40e0-9f04-e7d5f8d31bc9'::uuid AND plural IS NOT DISTINCT FROM 'Auguste';

-- month names are not counted at A1 ("zwei Januare" is not idiomatic); Dezember/November/Oktober/September already correctly carry plural null, these eight do not.
UPDATE public.words SET plural = NULL
WHERE id = 'cb58048f-f7a5-43d9-8888-9fc48948b12b'::uuid AND plural IS NOT DISTINCT FROM 'Märze';

-- Schokolade is a mass noun in ordinary use, same class as the nine Butter/Milch/Obst rows this batch fixes to null -- Schokoladen (varieties) is a technical/specialist plural.
UPDATE public.words SET plural = NULL
WHERE id = '9de2f04c-1958-45a5-9915-8fc00038f3eb'::uuid AND plural IS NOT DISTINCT FROM 'Schokoladen';

-- there is one sun; "Sonnen" is only used figuratively/astronomically, not at A1.
UPDATE public.words SET plural = NULL
WHERE id = '20981a4e-fbac-4dd7-af79-39ab73d40e2b'::uuid AND plural IS NOT DISTINCT FROM 'Sonnen';

-- Haut (skin) is uncountable in the A1 sense used here (die Haut ist gut für ...), matching the mass-noun treatment already applied to Milch/Obst/etc.
UPDATE public.words SET plural = NULL
WHERE id = 'a28a03d8-96fb-4605-9a7c-2dbcbb32f338'::uuid AND plural IS NOT DISTINCT FROM 'Häute';

-- "werden" is not in the A1.2 inventory (same issue already fixed on März in this batch); rewritten with the same ist + adjective pattern for consistency.
UPDATE public.words SET example_sentence = 'Im Frühling ist es warm.'
WHERE id = '2aff55ac-1ce9-4edf-a5d7-d331c7a5cd81'::uuid AND example_sentence IS NOT DISTINCT FROM 'Im Frühling wird es warm.';

-- plural stores the literal string "null" instead of JSON null; vocabularyService.js does `word.plural || ''` which does NOT catch the string "null", so the SRS card renders "Plural: null" for an uncountable mass noun — same bug class fixed in the A1.1 batch (Kreide). All eight/nine are genuinely uncountable in this sense, so real null is correct rather than a countable plural.
UPDATE public.words SET plural = NULL
WHERE id = 'c816d6bb-8778-458f-bc68-b4ee4ed5b00c'::uuid AND plural IS NOT DISTINCT FROM 'null';

-- plural stores the literal string "null" instead of JSON null; vocabularyService.js does `word.plural || ''` which does NOT catch the string "null", so the SRS card renders "Plural: null" for an uncountable mass noun — same bug class fixed in the A1.1 batch (Kreide). All eight/nine are genuinely uncountable in this sense, so real null is correct rather than a countable plural.
UPDATE public.words SET plural = NULL
WHERE id = '926c21fe-7efe-4643-bc04-f9971202b5bd'::uuid AND plural IS NOT DISTINCT FROM 'null';

-- plural stores the literal string "null" instead of JSON null; vocabularyService.js does `word.plural || ''` which does NOT catch the string "null", so the SRS card renders "Plural: null" for an uncountable mass noun — same bug class fixed in the A1.1 batch (Kreide). All eight/nine are genuinely uncountable in this sense, so real null is correct rather than a countable plural.
UPDATE public.words SET plural = NULL
WHERE id = 'd98a2b8c-d860-45d6-9f48-96754c44a124'::uuid AND plural IS NOT DISTINCT FROM 'null';

-- plural stores the literal string "null" instead of JSON null; vocabularyService.js does `word.plural || ''` which does NOT catch the string "null", so the SRS card renders "Plural: null" for an uncountable mass noun — same bug class fixed in the A1.1 batch (Kreide). All eight/nine are genuinely uncountable in this sense, so real null is correct rather than a countable plural.
UPDATE public.words SET plural = NULL
WHERE id = 'e375caea-4bd4-46f9-95b5-dd52bc001a18'::uuid AND plural IS NOT DISTINCT FROM 'null';

-- plural stores the literal string "null" instead of JSON null; vocabularyService.js does `word.plural || ''` which does NOT catch the string "null", so the SRS card renders "Plural: null" for an uncountable mass noun — same bug class fixed in the A1.1 batch (Kreide). All eight/nine are genuinely uncountable in this sense, so real null is correct rather than a countable plural.
UPDATE public.words SET plural = NULL
WHERE id = '5daed8d9-a6ba-4be5-90e7-6da8ffa2c0d0'::uuid AND plural IS NOT DISTINCT FROM 'null';

-- plural stores the literal string "null" instead of JSON null; vocabularyService.js does `word.plural || ''` which does NOT catch the string "null", so the SRS card renders "Plural: null" for an uncountable mass noun — same bug class fixed in the A1.1 batch (Kreide). All eight/nine are genuinely uncountable in this sense, so real null is correct rather than a countable plural.
UPDATE public.words SET plural = NULL
WHERE id = 'b09e72f3-0f09-4ef4-ba0c-72949f852061'::uuid AND plural IS NOT DISTINCT FROM 'null';

-- plural stores the literal string "null" instead of JSON null; vocabularyService.js does `word.plural || ''` which does NOT catch the string "null", so the SRS card renders "Plural: null" for an uncountable mass noun — same bug class fixed in the A1.1 batch (Kreide). All eight/nine are genuinely uncountable in this sense, so real null is correct rather than a countable plural.
UPDATE public.words SET plural = NULL
WHERE id = 'a63756b5-6a58-437f-bf30-0521ede79ef2'::uuid AND plural IS NOT DISTINCT FROM 'null';

-- plural stores the literal string "null" instead of JSON null; vocabularyService.js does `word.plural || ''` which does NOT catch the string "null", so the SRS card renders "Plural: null" for an uncountable mass noun — same bug class fixed in the A1.1 batch (Kreide). All eight/nine are genuinely uncountable in this sense, so real null is correct rather than a countable plural.
UPDATE public.words SET plural = NULL
WHERE id = 'e14cd229-6a6c-4b37-ac46-7af3cc053272'::uuid AND plural IS NOT DISTINCT FROM 'null';

-- plural stores the literal string "null" instead of JSON null; vocabularyService.js does `word.plural || ''` which does NOT catch the string "null", so the SRS card renders "Plural: null" for an uncountable mass noun — same bug class fixed in the A1.1 batch (Kreide). All eight/nine are genuinely uncountable in this sense, so real null is correct rather than a countable plural.
UPDATE public.words SET plural = NULL
WHERE id = 'e36f1a51-1c06-440b-8cc7-a5d98834dd0f'::uuid AND plural IS NOT DISTINCT FROM 'null';

-- attributive adjective ending after an indefinite article ("ein neues Handy") is banned at A1.2 — the level file requires the predicative form (Der Freund ist gut ✓ / ein guter Freund ✗); rewritten predicatively, still contains "neu".
UPDATE public.words SET example_sentence = 'Mein Handy ist neu.'
WHERE id = 'd765cd88-f043-41b7-af11-801806c075ef'::uuid AND example_sentence IS NOT DISTINCT FROM 'Ich habe ein neues Handy.';

-- attributive adjective ending after an indefinite article ("ein rotes Kleid") is banned at A1.2; rewritten predicatively in the same "ist X und Y" pattern already used elsewhere in Clothes (basic) (Die Hose ist blau und neu.).
UPDATE public.words SET example_sentence = 'Das Kleid ist rot und schön.'
WHERE id = 'f4bd3e60-96a3-4f29-9bf9-a3fe581f3fb9'::uuid AND example_sentence IS NOT DISTINCT FROM 'Sie trägt ein rotes Kleid heute.';

-- attributive adjective ending after an indefinite article ("einen leckeren Kuchen") is banned at A1.2; dropped the adjective rather than switching to predicative, since the verb is not a copula here.
UPDATE public.words SET example_sentence = 'Oma backt einen Kuchen.'
WHERE id = '5d8320e0-eddf-46ec-a151-b2ca754924d0'::uuid AND example_sentence IS NOT DISTINCT FROM 'Oma backt einen leckeren Kuchen.';

-- attributive adjective with a dative ending after the dative preposition "aus" ("aus braunem Leder") is banned at A1.2 — adjective endings are not taught in any case, dative included; rewritten predicatively, still contains "Gürtel".
UPDATE public.words SET example_sentence = 'Der Gürtel ist braun.'
WHERE id = '57ecb02c-ff07-4b09-b0d6-caf1c2c64537'::uuid AND example_sentence IS NOT DISTINCT FROM 'Der Gürtel ist aus braunem Leder.';

-- attributive adjective with a dative ending after "aus" ("aus weicher Baumwolle") is banned at A1.2; dropped the adjective and kept the frozen dative-preposition chunk, which needs no article before an uncountable noun.
UPDATE public.words SET example_sentence = 'Die Unterhose ist aus Baumwolle.'
WHERE id = 'a27518bc-3010-4370-9371-1eb4c0ab22ee'::uuid AND example_sentence IS NOT DISTINCT FROM 'Die Unterhose ist aus weicher Baumwolle.';

-- Partizip II used predicatively as an adjective ("gestrichen") is banned at A1.2 except the named headline fragments (gesucht/geschlossen/verboten on Schilder), and streichen is not on the Perfekt-verb allow-list either way; rewritten as a plain predicative-adjective sentence, still contains "Wand".
UPDATE public.words SET example_sentence = 'Die Wand ist weiß.'
WHERE id = '35a36571-e600-4077-9591-50d97a266bd5'::uuid AND example_sentence IS NOT DISTINCT FROM 'Die Wand ist weiß gestrichen.';

-- Perfekt of "sparen" is banned — sparen is not on the A1.2 Perfekt-verb allow-list (machen, kaufen, kochen, spielen, lernen, arbeiten, wohnen, hören, fragen, sagen, essen, trinken, sehen, lesen, schreiben, sprechen, nehmen, finden, schlafen, gehen, fahren, kommen, fliegen, bleiben, sein, anrufen, einkaufen, aufstehen); rewritten in the present tense, still contains "hundert".
UPDATE public.words SET example_sentence = 'Ich spare hundert Euro.'
WHERE id = 'eff90609-67d7-489d-8e78-6a0bf58d9123'::uuid AND example_sentence IS NOT DISTINCT FROM 'Ich habe hundert Euro gespart.';

-- comparative adjective form ("wärmer") is banned at A1.2 — only "mehr"/"lieber" as adverbs are allowed; rewritten with the positive form "warm", still contains "März".
UPDATE public.words SET example_sentence = 'Im März ist es schon warm.'
WHERE id = 'cb58048f-f7a5-43d9-8888-9fc48948b12b'::uuid AND example_sentence IS NOT DISTINCT FROM 'Im März wird es wärmer.';

-- sentence-final "nicht" negating a preceding noun phrase is a marked/non-standard negation placement that risks teaching wrong nicht-word-order; moved "nicht" directly before the negated element (Satznegation taught in topic 3), still contains "sechsunddreißig".
UPDATE public.words SET example_sentence = 'Das Jahr hat nicht sechsunddreißig Wochen.'
WHERE id = '3c20ce0e-67a2-45fb-a944-0dc64b730284'::uuid AND example_sentence IS NOT DISTINCT FROM 'Das Jahr hat sechsunddreißig Wochen nicht.';

COMMIT;

-- Verification (run after applying):
-- Count of new rows per category (should be >= the counts in this file's header):
--   SELECT count(*) FROM public.words WHERE level = 'a1.2' AND category = 'Travel & Transport'; -- expect >= 26
--   SELECT count(*) FROM public.words WHERE level = 'a1.2' AND category = 'Places in Town'; -- expect >= 25
--   SELECT count(*) FROM public.words WHERE level = 'a1.2' AND category = 'Health & Doctor'; -- expect >= 19
--   SELECT count(*) FROM public.words WHERE level = 'a1.2' AND category = 'Furniture'; -- expect >= 20
--   SELECT count(*) FROM public.words WHERE level = 'a1.2' AND category = 'Free Time & Hobbies'; -- expect >= 24
--   SELECT count(*) FROM public.words WHERE level = 'a1.2' AND category = 'Money & Shopping'; -- expect >= 20
--   SELECT count(*) FROM public.words WHERE level = 'a1.2' AND category = 'Numbers 100-1000 & Ordinals'; -- expect >= 18
--   SELECT count(*) FROM public.words WHERE level = 'a1.2' AND category = 'Time Expressions'; -- expect >= 1
--   SELECT count(*) FROM public.words WHERE level = 'a1.2' AND category = 'Weather'; -- expect >= 13
-- Literal-string "null" plurals at a1.2 (expect 0):
--   SELECT count(*) FROM public.words WHERE level = 'a1.2' AND plural = 'null';
-- Article baked into the german column at a1.2 (expect 0):
--   SELECT count(*) FROM public.words WHERE level = 'a1.2' AND (german LIKE 'der %' OR german LIKE 'die %' OR german LIKE 'das %');
