-- A1.1 Wortliste: adds 114 new vocabulary rows and fixes 51
-- defective live rows (Course Factory Wave 2, PR B).
--
-- What:
--   1. 114 INSERTs into public.words at level 'a1.1' across
--      6 categories: Countries & Languages (29), Jobs & Work (28), Forms & Registration (24), Drinks (11), Time & Appointments (21), Personal Pronouns (1).
--      Fills vocabulary gaps identified in review: countries/languages,
--      professions, registration-form words, drinks, and time/appointment
--      words — see scratchpad vocab/notes.md for the per-category rationale
--      and the pre-existing dupes deliberately skipped.
--   2. 51 guarded UPDATEs against live a1.1 rows, three defect
--      classes: (a) the article baked into `german` on top of the already-
--      correct `article` column (e.g. "der Tag" instead of "Tag") — this is
--      what SrsTrainer.jsx used to render as "der der Tag" because it
--      prepended word.article unconditionally (WordCard.jsx already guarded
--      against it; see src/utils/wordDisplay.js, added alongside this
--      migration); (b) `plural` holding the literal string "null" instead of
--      SQL NULL, which vocabularyService.js's `plural || ''` let through as
--      the word "null" on other surfaces; and (c) content fixes surfaced by
--      the adversarial review (Regenbogen's plural missing its umlaut,
--      "Mach's gut"'s missing apostrophe, silber/gold as predicate
--      adjectives, an out-of-level example, an uncountable noun's plural, and
--      stripping the article prefix from plural values for consistency with
--      the bare-form convention used by the majority of live a1.1 plurals).
--
-- Re-run contract: every INSERT is guarded by
--   WHERE NOT EXISTS (SELECT 1 FROM public.words WHERE german = ... AND level = ... AND category = ...)
-- (the table's live UNIQUE (german, level, category)); every UPDATE is
-- guarded by WHERE id = '<id>' AND <field> IS NOT DISTINCT FROM <old-value>,
-- so applying this file twice, or applying it after any of these rows were
-- already fixed by hand, is a no-op. `id` is left to the table's own
-- gen_random_uuid() default on every INSERT.
--
-- How to test: apply by hand in the Supabase SQL editor, then run the
-- verification SELECTs at the bottom of this file.
--
-- Rollback: fixes — re-run each UPDATE with SET and the guard value swapped
-- (old value in SET, new value in the IS NOT DISTINCT FROM guard) — the old
-- value for every fix is quoted verbatim in words-a1.1-fixes.json. Additions —
-- there is no id to key a rollback DELETE on before this runs; once applied,
-- words.id may already be referenced by vocab_srs_cards.word_id, so prefer
-- leaving additions in place over deleting by (german, level, category).
--
-- Generated by scripts/words-from-json.mjs on 2026-09-05T12:55:47.593Z.

BEGIN;

-- ===========================================================================
-- Additions: 114 new a1.1 words
-- ===========================================================================

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Deutschland', 'Germany', NULL, NULL, 'Countries & Languages', 'Ich wohne in Deutschland.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Deutschland' AND level = 'a1.1' AND category = 'Countries & Languages'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Land', 'country', 'das', 'Länder', 'Countries & Languages', 'Deutschland ist ein Land.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Land' AND level = 'a1.1' AND category = 'Countries & Languages'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Sprache', 'language', 'die', 'Sprachen', 'Countries & Languages', 'Deutsch ist eine Sprache.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Sprache' AND level = 'a1.1' AND category = 'Countries & Languages'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Deutsch', 'German (language)', NULL, NULL, 'Countries & Languages', 'Ich lerne Deutsch.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Deutsch' AND level = 'a1.1' AND category = 'Countries & Languages'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'kommen aus', 'to come from', NULL, NULL, 'Countries & Languages', 'Ich komme aus Syrien.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'kommen aus' AND level = 'a1.1' AND category = 'Countries & Languages'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Österreich', 'Austria', NULL, NULL, 'Countries & Languages', 'Wien liegt in Österreich.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Österreich' AND level = 'a1.1' AND category = 'Countries & Languages'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Schweiz', 'Switzerland', 'die', NULL, 'Countries & Languages', 'Ich komme aus der Schweiz.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Schweiz' AND level = 'a1.1' AND category = 'Countries & Languages'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Türkei', 'Turkey', 'die', NULL, 'Countries & Languages', 'Er kommt aus der Türkei.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Türkei' AND level = 'a1.1' AND category = 'Countries & Languages'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Türkisch', 'Turkish (language)', NULL, NULL, 'Countries & Languages', 'Zu Hause sprechen wir Türkisch.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Türkisch' AND level = 'a1.1' AND category = 'Countries & Languages'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Syrien', 'Syria', NULL, NULL, 'Countries & Languages', 'Er kommt aus Syrien.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Syrien' AND level = 'a1.1' AND category = 'Countries & Languages'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Arabisch', 'Arabic (language)', NULL, NULL, 'Countries & Languages', 'Wir sprechen Arabisch und Deutsch.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Arabisch' AND level = 'a1.1' AND category = 'Countries & Languages'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Marokko', 'Morocco', NULL, NULL, 'Countries & Languages', 'Sara kommt aus Marokko.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Marokko' AND level = 'a1.1' AND category = 'Countries & Languages'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Indien', 'India', NULL, NULL, 'Countries & Languages', 'Sie kommt aus Indien.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Indien' AND level = 'a1.1' AND category = 'Countries & Languages'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Pakistan', 'Pakistan', NULL, NULL, 'Countries & Languages', 'Ali kommt aus Pakistan.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Pakistan' AND level = 'a1.1' AND category = 'Countries & Languages'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Kosovo', 'Kosovo', 'der', NULL, 'Countries & Languages', 'Er kommt aus dem Kosovo.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Kosovo' AND level = 'a1.1' AND category = 'Countries & Languages'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Englisch', 'English (language)', NULL, NULL, 'Countries & Languages', 'Wir sprechen gut Englisch.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Englisch' AND level = 'a1.1' AND category = 'Countries & Languages'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Italien', 'Italy', NULL, NULL, 'Countries & Languages', 'Rom liegt in Italien.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Italien' AND level = 'a1.1' AND category = 'Countries & Languages'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Italienisch', 'Italian (language)', NULL, NULL, 'Countries & Languages', 'Wir sprechen zu Hause Italienisch.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Italienisch' AND level = 'a1.1' AND category = 'Countries & Languages'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Spanien', 'Spain', NULL, NULL, 'Countries & Languages', 'Ich fahre nach Spanien.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Spanien' AND level = 'a1.1' AND category = 'Countries & Languages'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Spanisch', 'Spanish (language)', NULL, NULL, 'Countries & Languages', 'Sie lernt Spanisch in der Schule.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Spanisch' AND level = 'a1.1' AND category = 'Countries & Languages'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Frankreich', 'France', NULL, NULL, 'Countries & Languages', 'Paris liegt in Frankreich.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Frankreich' AND level = 'a1.1' AND category = 'Countries & Languages'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Französisch', 'French (language)', NULL, NULL, 'Countries & Languages', 'Ich lerne Französisch in Frankreich.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Französisch' AND level = 'a1.1' AND category = 'Countries & Languages'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Polnisch', 'Polish (language)', NULL, NULL, 'Countries & Languages', 'Er lernt jetzt Polnisch.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Polnisch' AND level = 'a1.1' AND category = 'Countries & Languages'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Russisch', 'Russian (language)', NULL, NULL, 'Countries & Languages', 'Wir sprechen sehr gut Russisch.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Russisch' AND level = 'a1.1' AND category = 'Countries & Languages'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Russland', 'Russia', NULL, NULL, 'Countries & Languages', 'Er kommt aus Russland.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Russland' AND level = 'a1.1' AND category = 'Countries & Languages'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Polen', 'Poland', NULL, NULL, 'Countries & Languages', 'Ich komme aus Polen.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Polen' AND level = 'a1.1' AND category = 'Countries & Languages'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Iran', 'Iran', 'der', NULL, 'Countries & Languages', 'Sie kommt aus dem Iran.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Iran' AND level = 'a1.1' AND category = 'Countries & Languages'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Afghanistan', 'Afghanistan', NULL, NULL, 'Countries & Languages', 'Er kommt aus Afghanistan.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Afghanistan' AND level = 'a1.1' AND category = 'Countries & Languages'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Ukraine', 'Ukraine', 'die', NULL, 'Countries & Languages', 'Sie kommt aus der Ukraine.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Ukraine' AND level = 'a1.1' AND category = 'Countries & Languages'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Beruf', 'profession, job', 'der', 'Berufe', 'Jobs & Work', 'Das ist mein Beruf.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Beruf' AND level = 'a1.1' AND category = 'Jobs & Work'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'von Beruf', 'by profession', NULL, NULL, 'Jobs & Work', 'Ich bin Lehrer von Beruf.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'von Beruf' AND level = 'a1.1' AND category = 'Jobs & Work'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Arzt', 'doctor (m)', 'der', 'Ärzte', 'Jobs & Work', 'Mein Vater ist Arzt.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Arzt' AND level = 'a1.1' AND category = 'Jobs & Work'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Ärztin', 'doctor (f)', 'die', 'Ärztinnen', 'Jobs & Work', 'Die Ärztin arbeitet im Krankenhaus.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Ärztin' AND level = 'a1.1' AND category = 'Jobs & Work'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Lehrer', 'teacher (m)', 'der', 'Lehrer', 'Jobs & Work', 'Der Lehrer ist sehr nett.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Lehrer' AND level = 'a1.1' AND category = 'Jobs & Work'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Lehrerin', 'teacher (f)', 'die', 'Lehrerinnen', 'Jobs & Work', 'Die Lehrerin heißt Frau Klein.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Lehrerin' AND level = 'a1.1' AND category = 'Jobs & Work'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Student', 'student (m)', 'der', 'Studenten', 'Jobs & Work', 'Er ist Student in Berlin.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Student' AND level = 'a1.1' AND category = 'Jobs & Work'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Studentin', 'student (f)', 'die', 'Studentinnen', 'Jobs & Work', 'Die Studentin lernt Deutsch.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Studentin' AND level = 'a1.1' AND category = 'Jobs & Work'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Verkäufer', 'salesperson (m)', 'der', 'Verkäufer', 'Jobs & Work', 'Der Verkäufer ist freundlich.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Verkäufer' AND level = 'a1.1' AND category = 'Jobs & Work'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Verkäuferin', 'salesperson (f)', 'die', 'Verkäuferinnen', 'Jobs & Work', 'Die Verkäuferin arbeitet im Supermarkt.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Verkäuferin' AND level = 'a1.1' AND category = 'Jobs & Work'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Kellner', 'waiter', 'der', 'Kellner', 'Jobs & Work', 'Der Kellner bringt den Kaffee.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Kellner' AND level = 'a1.1' AND category = 'Jobs & Work'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Kellnerin', 'waitress', 'die', 'Kellnerinnen', 'Jobs & Work', 'Die Kellnerin ist sehr schnell.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Kellnerin' AND level = 'a1.1' AND category = 'Jobs & Work'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Ingenieur', 'engineer (m)', 'der', 'Ingenieure', 'Jobs & Work', 'Der Ingenieur arbeitet bei Siemens.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Ingenieur' AND level = 'a1.1' AND category = 'Jobs & Work'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Ingenieurin', 'engineer (f)', 'die', 'Ingenieurinnen', 'Jobs & Work', 'Die Ingenieurin baut Brücken.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Ingenieurin' AND level = 'a1.1' AND category = 'Jobs & Work'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Koch', 'cook (m)', 'der', 'Köche', 'Jobs & Work', 'Der Koch kocht sehr gut.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Koch' AND level = 'a1.1' AND category = 'Jobs & Work'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Köchin', 'cook (f)', 'die', 'Köchinnen', 'Jobs & Work', 'Die Köchin macht das Essen.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Köchin' AND level = 'a1.1' AND category = 'Jobs & Work'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Krankenschwester', 'nurse (f)', 'die', 'Krankenschwestern', 'Jobs & Work', 'Die Krankenschwester arbeitet im Krankenhaus.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Krankenschwester' AND level = 'a1.1' AND category = 'Jobs & Work'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Krankenpfleger', 'nurse (m)', 'der', 'Krankenpfleger', 'Jobs & Work', 'Der Krankenpfleger arbeitet in der Klinik.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Krankenpfleger' AND level = 'a1.1' AND category = 'Jobs & Work'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Fahrer', 'driver (m)', 'der', 'Fahrer', 'Jobs & Work', 'Der Fahrer ist sehr schnell.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Fahrer' AND level = 'a1.1' AND category = 'Jobs & Work'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Fahrerin', 'driver (f)', 'die', 'Fahrerinnen', 'Jobs & Work', 'Die Fahrerin kommt jeden Tag.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Fahrerin' AND level = 'a1.1' AND category = 'Jobs & Work'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Chef', 'boss (m)', 'der', 'Chefs', 'Jobs & Work', 'Mein Chef ist sehr streng.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Chef' AND level = 'a1.1' AND category = 'Jobs & Work'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Chefin', 'boss (f)', 'die', 'Chefinnen', 'Jobs & Work', 'Die Chefin ist heute krank.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Chefin' AND level = 'a1.1' AND category = 'Jobs & Work'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Firma', 'company', 'die', 'Firmen', 'Jobs & Work', 'Die Firma ist sehr groß.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Firma' AND level = 'a1.1' AND category = 'Jobs & Work'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Büro', 'office', 'das', 'Büros', 'Jobs & Work', 'Ich arbeite im Büro.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Büro' AND level = 'a1.1' AND category = 'Jobs & Work'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Arbeit', 'work', 'die', NULL, 'Jobs & Work', 'Die Arbeit macht mir Spaß.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Arbeit' AND level = 'a1.1' AND category = 'Jobs & Work'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'arbeitslos', 'unemployed', NULL, NULL, 'Jobs & Work', 'Mein Bruder ist arbeitslos.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'arbeitslos' AND level = 'a1.1' AND category = 'Jobs & Work'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Kollege', 'colleague (m)', 'der', 'Kollegen', 'Jobs & Work', 'Mein Kollege heißt Ahmed.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Kollege' AND level = 'a1.1' AND category = 'Jobs & Work'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Kollegin', 'colleague (f)', 'die', 'Kolleginnen', 'Jobs & Work', 'Meine Kollegin kommt aus Polen.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Kollegin' AND level = 'a1.1' AND category = 'Jobs & Work'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Vorname', 'first name', 'der', 'Vornamen', 'Forms & Registration', 'Mein Vorname ist Ahmed.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Vorname' AND level = 'a1.1' AND category = 'Forms & Registration'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Nachname', 'surname (= Familienname)', 'der', 'Nachnamen', 'Forms & Registration', 'Wie ist Ihr Nachname?'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Nachname' AND level = 'a1.1' AND category = 'Forms & Registration'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Familienname', 'family name', 'der', 'Familiennamen', 'Forms & Registration', 'Der Familienname steht hier oben.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Familienname' AND level = 'a1.1' AND category = 'Forms & Registration'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Adresse', 'address', 'die', 'Adressen', 'Forms & Registration', 'Ich brauche Ihre Adresse.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Adresse' AND level = 'a1.1' AND category = 'Forms & Registration'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Straße', 'street', 'die', 'Straßen', 'Forms & Registration', 'Die Straße ist sehr lang.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Straße' AND level = 'a1.1' AND category = 'Forms & Registration'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Hausnummer', 'house number', 'die', 'Hausnummern', 'Forms & Registration', 'Die Hausnummer ist zehn.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Hausnummer' AND level = 'a1.1' AND category = 'Forms & Registration'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Postleitzahl', 'postal code', 'die', 'Postleitzahlen', 'Forms & Registration', 'Wie ist die Postleitzahl?'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Postleitzahl' AND level = 'a1.1' AND category = 'Forms & Registration'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Wohnort', 'place of residence', 'der', 'Wohnorte', 'Forms & Registration', 'Mein Wohnort ist Berlin.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Wohnort' AND level = 'a1.1' AND category = 'Forms & Registration'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Geburtsdatum', 'date of birth', 'das', 'Geburtsdaten', 'Forms & Registration', 'Das Geburtsdatum steht im Formular.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Geburtsdatum' AND level = 'a1.1' AND category = 'Forms & Registration'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Geburtsort', 'place of birth', 'der', 'Geburtsorte', 'Forms & Registration', 'Mein Geburtsort ist Istanbul.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Geburtsort' AND level = 'a1.1' AND category = 'Forms & Registration'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Alter', 'age', 'das', NULL, 'Forms & Registration', 'Das Alter ist nicht wichtig.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Alter' AND level = 'a1.1' AND category = 'Forms & Registration'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Telefonnummer', 'phone number', 'die', 'Telefonnummern', 'Forms & Registration', 'Ich gebe dir meine Telefonnummer.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Telefonnummer' AND level = 'a1.1' AND category = 'Forms & Registration'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Handynummer', 'mobile number', 'die', 'Handynummern', 'Forms & Registration', 'Hast du eine Handynummer?'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Handynummer' AND level = 'a1.1' AND category = 'Forms & Registration'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'E-Mail-Adresse', 'email address', 'die', 'E-Mail-Adressen', 'Forms & Registration', 'Wie ist deine E-Mail-Adresse?'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'E-Mail-Adresse' AND level = 'a1.1' AND category = 'Forms & Registration'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Unterschrift', 'signature', 'die', 'Unterschriften', 'Forms & Registration', 'Die Unterschrift ist hier unten.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Unterschrift' AND level = 'a1.1' AND category = 'Forms & Registration'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Datum', 'date', 'das', 'Daten', 'Forms & Registration', 'Welches Datum ist heute?'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Datum' AND level = 'a1.1' AND category = 'Forms & Registration'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Staatsangehörigkeit', 'nationality', 'die', 'Staatsangehörigkeiten', 'Forms & Registration', 'Meine Staatsangehörigkeit ist syrisch.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Staatsangehörigkeit' AND level = 'a1.1' AND category = 'Forms & Registration'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'männlich', 'male', NULL, NULL, 'Forms & Registration', 'Er ist männlich.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'männlich' AND level = 'a1.1' AND category = 'Forms & Registration'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'weiblich', 'female', NULL, NULL, 'Forms & Registration', 'Sie ist weiblich.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'weiblich' AND level = 'a1.1' AND category = 'Forms & Registration'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'ledig', 'single, unmarried', NULL, NULL, 'Forms & Registration', 'Ich bin noch ledig.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'ledig' AND level = 'a1.1' AND category = 'Forms & Registration'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Formular', 'form', 'das', 'Formulare', 'Forms & Registration', 'Das Formular ist sehr lang.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Formular' AND level = 'a1.1' AND category = 'Forms & Registration'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'ausfüllen', 'to fill out', NULL, NULL, 'Forms & Registration', 'Ich fülle das Formular aus.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'ausfüllen' AND level = 'a1.1' AND category = 'Forms & Registration'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'unterschreiben', 'to sign', NULL, NULL, 'Forms & Registration', 'Ich unterschreibe hier unten.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'unterschreiben' AND level = 'a1.1' AND category = 'Forms & Registration'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'ankreuzen', 'to check, to tick', NULL, NULL, 'Forms & Registration', 'Ich kreuze die Antwort an.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'ankreuzen' AND level = 'a1.1' AND category = 'Forms & Registration'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Kaffee', 'coffee', 'der', 'Kaffees', 'Drinks', 'Ich trinke gern Kaffee.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Kaffee' AND level = 'a1.1' AND category = 'Drinks'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Tee', 'tea', 'der', 'Tees', 'Drinks', 'Der Tee ist noch heiß.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Tee' AND level = 'a1.1' AND category = 'Drinks'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Wasser', 'water', 'das', NULL, 'Drinks', 'Das Wasser ist sehr kalt.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Wasser' AND level = 'a1.1' AND category = 'Drinks'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Mineralwasser', 'mineral water', 'das', NULL, 'Drinks', 'Ein Mineralwasser, bitte.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Mineralwasser' AND level = 'a1.1' AND category = 'Drinks'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Orangensaft', 'orange juice', 'der', 'Orangensäfte', 'Drinks', 'Der Orangensaft ist frisch.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Orangensaft' AND level = 'a1.1' AND category = 'Drinks'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Bier', 'beer', 'das', 'Biere', 'Drinks', 'Das Bier ist kalt.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Bier' AND level = 'a1.1' AND category = 'Drinks'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Wein', 'wine', 'der', 'Weine', 'Drinks', 'Der Wein kommt aus Italien.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Wein' AND level = 'a1.1' AND category = 'Drinks'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Cola', 'cola', 'die', 'Colas', 'Drinks', 'Die Cola ist süß.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Cola' AND level = 'a1.1' AND category = 'Drinks'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Flasche', 'bottle', 'die', 'Flaschen', 'Drinks', 'Die Flasche ist leer.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Flasche' AND level = 'a1.1' AND category = 'Drinks'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Glas', 'glass', 'das', 'Gläser', 'Drinks', 'Das Glas ist voll.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Glas' AND level = 'a1.1' AND category = 'Drinks'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Tasse', 'cup', 'die', 'Tassen', 'Drinks', 'Die Tasse ist kaputt.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Tasse' AND level = 'a1.1' AND category = 'Drinks'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Uhrzeit', 'time (clock time)', 'die', 'Uhrzeiten', 'Time & Appointments', 'Die Uhrzeit ist sehr wichtig.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Uhrzeit' AND level = 'a1.1' AND category = 'Time & Appointments'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Sekunde', 'second', 'die', 'Sekunden', 'Time & Appointments', 'Eine Minute hat sechzig Sekunden.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Sekunde' AND level = 'a1.1' AND category = 'Time & Appointments'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Viertel', 'quarter', 'das', 'Viertel', 'Time & Appointments', 'Es ist Viertel nach acht.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Viertel' AND level = 'a1.1' AND category = 'Time & Appointments'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Termin', 'appointment', 'der', 'Termine', 'Time & Appointments', 'Ich habe einen Termin heute.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Termin' AND level = 'a1.1' AND category = 'Time & Appointments'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'pünktlich', 'punctual, on time', NULL, NULL, 'Time & Appointments', 'Der Zug ist pünktlich.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'pünktlich' AND level = 'a1.1' AND category = 'Time & Appointments'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Vormittag', 'morning (before noon)', 'der', 'Vormittage', 'Time & Appointments', 'Der Vormittag ist sehr lang.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Vormittag' AND level = 'a1.1' AND category = 'Time & Appointments'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Nachmittag', 'afternoon', 'der', 'Nachmittage', 'Time & Appointments', 'Am Nachmittag spiele ich Fußball.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Nachmittag' AND level = 'a1.1' AND category = 'Time & Appointments'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Geburtstag', 'birthday', 'der', 'Geburtstage', 'Time & Appointments', 'Mein Geburtstag ist im Mai.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Geburtstag' AND level = 'a1.1' AND category = 'Time & Appointments'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Wecker', 'alarm clock', 'der', 'Wecker', 'Time & Appointments', 'Der Wecker klingelt um sieben.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Wecker' AND level = 'a1.1' AND category = 'Time & Appointments'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'aufwachen', 'to wake up', NULL, NULL, 'Time & Appointments', 'Ich wache um sechs auf.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'aufwachen' AND level = 'a1.1' AND category = 'Time & Appointments'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'aufstehen', 'to get up', NULL, NULL, 'Time & Appointments', 'Er steht um sieben auf.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'aufstehen' AND level = 'a1.1' AND category = 'Time & Appointments'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Verabredung', 'appointment, date', 'die', 'Verabredungen', 'Time & Appointments', 'Ich habe eine Verabredung heute.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Verabredung' AND level = 'a1.1' AND category = 'Time & Appointments'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Pause', 'break', 'die', 'Pausen', 'Time & Appointments', 'Die Pause dauert zehn Minuten.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Pause' AND level = 'a1.1' AND category = 'Time & Appointments'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Verspätung', 'delay', 'die', 'Verspätungen', 'Time & Appointments', 'Der Zug hat zehn Minuten Verspätung.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Verspätung' AND level = 'a1.1' AND category = 'Time & Appointments'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'verspätet', 'delayed, late', NULL, NULL, 'Time & Appointments', 'Der Bus ist heute verspätet.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'verspätet' AND level = 'a1.1' AND category = 'Time & Appointments'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Zeit', 'time', 'die', 'Zeiten', 'Time & Appointments', 'Ich habe keine Zeit.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Zeit' AND level = 'a1.1' AND category = 'Time & Appointments'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'morgens', 'in the morning(s)', NULL, NULL, 'Time & Appointments', 'Morgens trinke ich Kaffee.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'morgens' AND level = 'a1.1' AND category = 'Time & Appointments'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'nachmittags', 'in the afternoon(s)', NULL, NULL, 'Time & Appointments', 'Nachmittags spiele ich Fußball.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'nachmittags' AND level = 'a1.1' AND category = 'Time & Appointments'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'abends', 'in the evening(s)', NULL, NULL, 'Time & Appointments', 'Abends bin ich müde.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'abends' AND level = 'a1.1' AND category = 'Time & Appointments'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'rechtzeitig', 'in time, on time', NULL, NULL, 'Time & Appointments', 'Ich komme immer rechtzeitig.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'rechtzeitig' AND level = 'a1.1' AND category = 'Time & Appointments'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'zu spät', 'too late', NULL, NULL, 'Time & Appointments', 'Der Bus ist zu spät.'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'zu spät' AND level = 'a1.1' AND category = 'Time & Appointments'
);

INSERT INTO public.words (level, german, english, article, plural, category, example_sentence)
SELECT 'a1.1', 'Sie', 'you (formal)', NULL, NULL, 'Personal Pronouns', 'Woher kommen Sie?'
WHERE NOT EXISTS (
  SELECT 1 FROM public.words WHERE german = 'Sie' AND level = 'a1.1' AND category = 'Personal Pronouns'
);

-- ===========================================================================
-- Fixes: 51 guarded UPDATEs against defective live rows
-- ===========================================================================

-- german carries the article inside the string while the article field already holds it correctly (e.g. WordCard would be fine, but SrsTrainer.jsx prepends word.article unconditionally, so this currently renders as "die die Zahl" on the flashcard front/back).
UPDATE public.words SET german = 'Zahl'
WHERE id = '06d1f81f-3ec8-4ef4-a4c6-ebaa02ee3969'::uuid AND german IS NOT DISTINCT FROM 'die Zahl';

-- german carries the article inside the string while the article field already holds it correctly (e.g. WordCard would be fine, but SrsTrainer.jsx prepends word.article unconditionally, so this currently renders as "die die Zahl" on the flashcard front/back).
UPDATE public.words SET german = 'Antwort'
WHERE id = '0fabdd9c-85fd-429a-880e-59bb75826e72'::uuid AND german IS NOT DISTINCT FROM 'die Antwort';

-- german carries the article inside the string while the article field already holds it correctly (e.g. WordCard would be fine, but SrsTrainer.jsx prepends word.article unconditionally, so this currently renders as "die die Zahl" on the flashcard front/back).
UPDATE public.words SET german = 'Woche'
WHERE id = '19bd209f-6a41-4f0f-9f58-9735dbb8809c'::uuid AND german IS NOT DISTINCT FROM 'die Woche';

-- german carries the article inside the string while the article field already holds it correctly (e.g. WordCard would be fine, but SrsTrainer.jsx prepends word.article unconditionally, so this currently renders as "die die Zahl" on the flashcard front/back).
UPDATE public.words SET german = 'Wochentag'
WHERE id = '2df94b7e-3050-431d-af30-d7617a5868ee'::uuid AND german IS NOT DISTINCT FROM 'der Wochentag';

-- german carries the article inside the string while the article field already holds it correctly (e.g. WordCard would be fine, but SrsTrainer.jsx prepends word.article unconditionally, so this currently renders as "die die Zahl" on the flashcard front/back).
UPDATE public.words SET german = 'Dienstag'
WHERE id = '34b1bf45-b514-4590-ba20-4a83f93f47f9'::uuid AND german IS NOT DISTINCT FROM 'der Dienstag';

-- german carries the article inside the string while the article field already holds it correctly (e.g. WordCard would be fine, but SrsTrainer.jsx prepends word.article unconditionally, so this currently renders as "die die Zahl" on the flashcard front/back).
UPDATE public.words SET german = 'Freitag'
WHERE id = '34c2e1e6-005c-4d2f-93d9-c4c285529878'::uuid AND german IS NOT DISTINCT FROM 'der Freitag';

-- german carries the article inside the string while the article field already holds it correctly (e.g. WordCard would be fine, but SrsTrainer.jsx prepends word.article unconditionally, so this currently renders as "die die Zahl" on the flashcard front/back).
UPDATE public.words SET german = 'Sonnabend'
WHERE id = '3940231c-deac-420d-a24e-e820781cd7b9'::uuid AND german IS NOT DISTINCT FROM 'der Sonnabend';

-- german carries the article inside the string while the article field already holds it correctly (e.g. WordCard would be fine, but SrsTrainer.jsx prepends word.article unconditionally, so this currently renders as "die die Zahl" on the flashcard front/back).
UPDATE public.words SET german = 'Tag'
WHERE id = '4442348b-1623-4a81-947e-04361d4a6c1e'::uuid AND german IS NOT DISTINCT FROM 'der Tag';

-- german carries the article inside the string while the article field already holds it correctly (e.g. WordCard would be fine, but SrsTrainer.jsx prepends word.article unconditionally, so this currently renders as "die die Zahl" on the flashcard front/back).
UPDATE public.words SET german = 'Sonntag'
WHERE id = '4b76a3f6-59ae-4e0d-bbe7-b3c9728b814f'::uuid AND german IS NOT DISTINCT FROM 'der Sonntag';

-- german carries the article inside the string while the article field already holds it correctly (e.g. WordCard would be fine, but SrsTrainer.jsx prepends word.article unconditionally, so this currently renders as "die die Zahl" on the flashcard front/back).
UPDATE public.words SET german = 'Donnerstag'
WHERE id = '4bd005d5-2b4e-4de7-b6c9-061f11e41675'::uuid AND german IS NOT DISTINCT FROM 'der Donnerstag';

-- german carries the article inside the string while the article field already holds it correctly (e.g. WordCard would be fine, but SrsTrainer.jsx prepends word.article unconditionally, so this currently renders as "die die Zahl" on the flashcard front/back).
UPDATE public.words SET german = 'Kalender'
WHERE id = '507555cd-b476-46ed-b463-6ffe65aecf12'::uuid AND german IS NOT DISTINCT FROM 'der Kalender';

-- german carries the article inside the string while the article field already holds it correctly (e.g. WordCard would be fine, but SrsTrainer.jsx prepends word.article unconditionally, so this currently renders as "die die Zahl" on the flashcard front/back).
UPDATE public.words SET german = 'Mittwoch'
WHERE id = '683072dd-e46c-4a9e-bae7-e2bbc67678ad'::uuid AND german IS NOT DISTINCT FROM 'der Mittwoch';

-- german carries the article inside the string while the article field already holds it correctly (e.g. WordCard would be fine, but SrsTrainer.jsx prepends word.article unconditionally, so this currently renders as "die die Zahl" on the flashcard front/back).
UPDATE public.words SET german = 'Montag'
WHERE id = '74232a41-8578-4826-af22-5c1235360cd9'::uuid AND german IS NOT DISTINCT FROM 'der Montag';

-- german carries the article inside the string while the article field already holds it correctly (e.g. WordCard would be fine, but SrsTrainer.jsx prepends word.article unconditionally, so this currently renders as "die die Zahl" on the flashcard front/back).
UPDATE public.words SET german = 'Nummer'
WHERE id = '83a14b7b-33f9-4972-9001-72c42442f14d'::uuid AND german IS NOT DISTINCT FROM 'die Nummer';

-- german carries the article inside the string while the article field already holds it correctly (e.g. WordCard would be fine, but SrsTrainer.jsx prepends word.article unconditionally, so this currently renders as "die die Zahl" on the flashcard front/back).
UPDATE public.words SET german = 'Farbe'
WHERE id = '9a35fe92-fc2d-42af-a718-7c6cf48a9984'::uuid AND german IS NOT DISTINCT FROM 'die Farbe';

-- german carries the article inside the string while the article field already holds it correctly (e.g. WordCard would be fine, but SrsTrainer.jsx prepends word.article unconditionally, so this currently renders as "die die Zahl" on the flashcard front/back).
UPDATE public.words SET german = 'Wochenende'
WHERE id = 'b5a36d15-71c0-4e81-9113-eeffcde1d9b7'::uuid AND german IS NOT DISTINCT FROM 'das Wochenende';

-- german carries the article inside the string while the article field already holds it correctly (e.g. WordCard would be fine, but SrsTrainer.jsx prepends word.article unconditionally, so this currently renders as "die die Zahl" on the flashcard front/back).
UPDATE public.words SET german = 'Regenbogen'
WHERE id = 'baf6828a-ae02-4217-8ec7-bedfbc57bd5b'::uuid AND german IS NOT DISTINCT FROM 'der Regenbogen';

-- german carries the article inside the string while the article field already holds it correctly (e.g. WordCard would be fine, but SrsTrainer.jsx prepends word.article unconditionally, so this currently renders as "die die Zahl" on the flashcard front/back).
UPDATE public.words SET german = 'Frage'
WHERE id = 'e14b8c64-8774-46fb-bb93-30550e16bb59'::uuid AND german IS NOT DISTINCT FROM 'die Frage';

-- german carries the article inside the string while the article field already holds it correctly (e.g. WordCard would be fine, but SrsTrainer.jsx prepends word.article unconditionally, so this currently renders as "die die Zahl" on the flashcard front/back).
UPDATE public.words SET german = 'Gruß'
WHERE id = 'e3b63654-5c07-412f-b209-1ea0ec0d140a'::uuid AND german IS NOT DISTINCT FROM 'der Gruß';

-- german carries the article inside the string while the article field already holds it correctly (e.g. WordCard would be fine, but SrsTrainer.jsx prepends word.article unconditionally, so this currently renders as "die die Zahl" on the flashcard front/back).
UPDATE public.words SET german = 'Samstag'
WHERE id = 'f975c09d-d4f8-4d3c-b00f-44d1c5c1cef5'::uuid AND german IS NOT DISTINCT FROM 'der Samstag';

-- Durst is uncountable; plural is stored as the literal string "null" instead of JSON null. SrsTrainer.jsx guards against the literal string ('plural !== \'null\'') but mapDbWordToApp/vocabularyService.js does not, so other surfaces can render the word "null" as the plural.
UPDATE public.words SET plural = NULL
WHERE id = '2676efa7-e91b-4171-b65b-7c92216fc982'::uuid AND plural IS NOT DISTINCT FROM 'null';

-- Zuhause is uncountable; plural is stored as the literal string "null" instead of JSON null. SrsTrainer.jsx guards against the literal string ('plural !== \'null\'') but mapDbWordToApp/vocabularyService.js does not, so other surfaces can render the word "null" as the plural.
UPDATE public.words SET plural = NULL
WHERE id = 'b09adebf-9767-4079-b1ee-b639aec4a733'::uuid AND plural IS NOT DISTINCT FROM 'null';

-- Hunger is uncountable; plural is stored as the literal string "null" instead of JSON null. SrsTrainer.jsx guards against the literal string ('plural !== \'null\'') but mapDbWordToApp/vocabularyService.js does not, so other surfaces can render the word "null" as the plural.
UPDATE public.words SET plural = NULL
WHERE id = 'c24eeb7f-d9d0-433c-9144-8ea52ba10732'::uuid AND plural IS NOT DISTINCT FROM 'null';

-- Uses the modal verb "kann"; A1.1 examples must be simple present tense without modal verbs.
UPDATE public.words SET example_sentence = 'Ich zähle bis zwanzig.'
WHERE id = '0bf9838a-2535-4035-baad-10646e997a7b'::uuid AND example_sentence IS NOT DISTINCT FROM 'Ich kann bis zwanzig zählen.';

-- Uses Präteritum "war"; replacement stays in present tense while keeping "gestern" meaningful.
UPDATE public.words SET example_sentence = 'Heute ist Montag, nicht gestern.'
WHERE id = '12fba7c9-bdd2-46e9-90d9-02c2ddd0bba5'::uuid AND example_sentence IS NOT DISTINCT FROM 'Gestern war Sonntag.';

-- Uses Präteritum "war"; replaced with a verb-less elliptical phrase (same pattern as other short-phrase entries in this list, e.g. "immer" -> "Ja, immer!").
UPDATE public.words SET example_sentence = 'Letzte Woche, nicht diese Woche.'
WHERE id = '1f732f26-b03d-44cc-848f-368727f687d9'::uuid AND example_sentence IS NOT DISTINCT FROM 'Letzte Woche war gut.';

-- Uses the modal verb "muss"; A1.1 examples must avoid modal verbs.
UPDATE public.words SET example_sentence = 'Bis später, ich gehe jetzt.'
WHERE id = 'ce5e11f5-b263-4d6f-b381-a190493db09a'::uuid AND example_sentence IS NOT DISTINCT FROM 'Bis später, ich muss gehen.';

-- Plural was both full-article-form and missing the umlaut; correct plural of Regenbogen is Regenbögen (bare form).
UPDATE public.words SET plural = 'Regenbögen'
WHERE id = 'baf6828a-ae02-4217-8ec7-bedfbc57bd5b'::uuid AND plural IS NOT DISTINCT FROM 'die Regenbogen';

-- Missing apostrophe: "Mach's gut" (mach es gut), not "Machs gut".
UPDATE public.words SET german = 'Mach''s gut'
WHERE id = '8751ef96-cac1-43ae-9e11-1dfba1e32d41'::uuid AND german IS NOT DISTINCT FROM 'Machs gut';

-- Same missing-apostrophe typo as the german field.
UPDATE public.words SET example_sentence = 'Mach''s gut, wir sehen uns!'
WHERE id = '8751ef96-cac1-43ae-9e11-1dfba1e32d41'::uuid AND example_sentence IS NOT DISTINCT FROM 'Machs gut, wir sehen uns!';

-- "silber" as a predicate adjective is colloquial; "silbern" is the grammatically correct adjective form.
UPDATE public.words SET example_sentence = 'Das Auto ist silbern.'
WHERE id = '9c7b7d80-df16-433e-8367-9ded5f200dbf'::uuid AND example_sentence IS NOT DISTINCT FROM 'Das Auto ist silber.';

-- "gold" as a predicate adjective is colloquial; "golden" is the grammatically correct adjective form.
UPDATE public.words SET example_sentence = 'Der Ring ist golden.'
WHERE id = '52baa979-7825-4b36-9af6-a14e3ab234a2'::uuid AND example_sentence IS NOT DISTINCT FROM 'Der Ring ist gold.';

-- Clearer, more concrete example of "es hat" + accusative object for an A1.1 learner.
UPDATE public.words SET example_sentence = 'Es hat vier Räder.'
WHERE id = '13ac8214-e530-4b5d-91e7-c7dd9e36d526'::uuid AND example_sentence IS NOT DISTINCT FROM 'Es hat Platz.';

-- Kreide (chalk) is normally an uncountable mass noun in this context; plural set to null rather than the rarely-used "Kreiden".
UPDATE public.words SET plural = NULL
WHERE id = '6964b56e-a4fc-43c5-b441-391d72e6227f'::uuid AND plural IS NOT DISTINCT FROM 'Kreiden';

-- Plural stored in full-article form (die X); stripped to the bare form used by 72% of existing A1.1 plurals.
UPDATE public.words SET plural = 'Zahlen'
WHERE id = '06d1f81f-3ec8-4ef4-a4c6-ebaa02ee3969'::uuid AND plural IS NOT DISTINCT FROM 'die Zahlen';

-- Plural stored in full-article form (die X); stripped to the bare form used by 72% of existing A1.1 plurals.
UPDATE public.words SET plural = 'Wochen'
WHERE id = '19bd209f-6a41-4f0f-9f58-9735dbb8809c'::uuid AND plural IS NOT DISTINCT FROM 'die Wochen';

-- Plural stored in full-article form (die X); stripped to the bare form used by 72% of existing A1.1 plurals.
UPDATE public.words SET plural = 'Wochentage'
WHERE id = '2df94b7e-3050-431d-af30-d7617a5868ee'::uuid AND plural IS NOT DISTINCT FROM 'die Wochentage';

-- Plural stored in full-article form (die X); stripped to the bare form used by 72% of existing A1.1 plurals.
UPDATE public.words SET plural = 'Dienstage'
WHERE id = '34b1bf45-b514-4590-ba20-4a83f93f47f9'::uuid AND plural IS NOT DISTINCT FROM 'die Dienstage';

-- Plural stored in full-article form (die X); stripped to the bare form used by 72% of existing A1.1 plurals.
UPDATE public.words SET plural = 'Freitage'
WHERE id = '34c2e1e6-005c-4d2f-93d9-c4c285529878'::uuid AND plural IS NOT DISTINCT FROM 'die Freitage';

-- Plural stored in full-article form (die X); stripped to the bare form used by 72% of existing A1.1 plurals.
UPDATE public.words SET plural = 'Sonnabende'
WHERE id = '3940231c-deac-420d-a24e-e820781cd7b9'::uuid AND plural IS NOT DISTINCT FROM 'die Sonnabende';

-- Plural stored in full-article form (die X); stripped to the bare form used by 72% of existing A1.1 plurals.
UPDATE public.words SET plural = 'Tage'
WHERE id = '4442348b-1623-4a81-947e-04361d4a6c1e'::uuid AND plural IS NOT DISTINCT FROM 'die Tage';

-- Plural stored in full-article form (die X); stripped to the bare form used by 72% of existing A1.1 plurals.
UPDATE public.words SET plural = 'Sonntage'
WHERE id = '4b76a3f6-59ae-4e0d-bbe7-b3c9728b814f'::uuid AND plural IS NOT DISTINCT FROM 'die Sonntage';

-- Plural stored in full-article form (die X); stripped to the bare form used by 72% of existing A1.1 plurals.
UPDATE public.words SET plural = 'Donnerstage'
WHERE id = '4bd005d5-2b4e-4de7-b6c9-061f11e41675'::uuid AND plural IS NOT DISTINCT FROM 'die Donnerstage';

-- Plural stored in full-article form (die X); stripped to the bare form used by 72% of existing A1.1 plurals.
UPDATE public.words SET plural = 'Kalender'
WHERE id = '507555cd-b476-46ed-b463-6ffe65aecf12'::uuid AND plural IS NOT DISTINCT FROM 'die Kalender';

-- Plural stored in full-article form (die X); stripped to the bare form used by 72% of existing A1.1 plurals.
UPDATE public.words SET plural = 'Mittwoche'
WHERE id = '683072dd-e46c-4a9e-bae7-e2bbc67678ad'::uuid AND plural IS NOT DISTINCT FROM 'die Mittwoche';

-- Plural stored in full-article form (die X); stripped to the bare form used by 72% of existing A1.1 plurals.
UPDATE public.words SET plural = 'Montage'
WHERE id = '74232a41-8578-4826-af22-5c1235360cd9'::uuid AND plural IS NOT DISTINCT FROM 'die Montage';

-- Plural stored in full-article form (die X); stripped to the bare form used by 72% of existing A1.1 plurals.
UPDATE public.words SET plural = 'Nummern'
WHERE id = '83a14b7b-33f9-4972-9001-72c42442f14d'::uuid AND plural IS NOT DISTINCT FROM 'die Nummern';

-- Plural stored in full-article form (die X); stripped to the bare form used by 72% of existing A1.1 plurals.
UPDATE public.words SET plural = 'Farben'
WHERE id = '9a35fe92-fc2d-42af-a718-7c6cf48a9984'::uuid AND plural IS NOT DISTINCT FROM 'die Farben';

-- Plural stored in full-article form (die X); stripped to the bare form used by 72% of existing A1.1 plurals.
UPDATE public.words SET plural = 'Wochenenden'
WHERE id = 'b5a36d15-71c0-4e81-9113-eeffcde1d9b7'::uuid AND plural IS NOT DISTINCT FROM 'die Wochenenden';

-- Plural stored in full-article form (die X); stripped to the bare form used by 72% of existing A1.1 plurals.
UPDATE public.words SET plural = 'Grüße'
WHERE id = 'e3b63654-5c07-412f-b209-1ea0ec0d140a'::uuid AND plural IS NOT DISTINCT FROM 'die Grüße';

-- Plural stored in full-article form (die X); stripped to the bare form used by 72% of existing A1.1 plurals.
UPDATE public.words SET plural = 'Samstage'
WHERE id = 'f975c09d-d4f8-4d3c-b00f-44d1c5c1cef5'::uuid AND plural IS NOT DISTINCT FROM 'die Samstage';

COMMIT;

-- Verification (run after applying):
-- Count of new rows per category (should be >= the counts in this file's header):
--   SELECT count(*) FROM public.words WHERE level = 'a1.1' AND category = 'Countries & Languages'; -- expect >= 29
--   SELECT count(*) FROM public.words WHERE level = 'a1.1' AND category = 'Jobs & Work'; -- expect >= 28
--   SELECT count(*) FROM public.words WHERE level = 'a1.1' AND category = 'Forms & Registration'; -- expect >= 24
--   SELECT count(*) FROM public.words WHERE level = 'a1.1' AND category = 'Drinks'; -- expect >= 11
--   SELECT count(*) FROM public.words WHERE level = 'a1.1' AND category = 'Time & Appointments'; -- expect >= 21
--   SELECT count(*) FROM public.words WHERE level = 'a1.1' AND category = 'Personal Pronouns'; -- expect >= 1
-- Literal-string "null" plurals at a1.1 (expect 0):
--   SELECT count(*) FROM public.words WHERE level = 'a1.1' AND plural = 'null';
-- Article baked into the german column at a1.1 (expect 0):
--   SELECT count(*) FROM public.words WHERE level = 'a1.1' AND (german LIKE 'der %' OR german LIKE 'die %' OR german LIKE 'das %');
