// Course v2 — the chrome strings of the v2 renderers (StepView, StartView, ItemView and their parts).
//
// The chrome language follows the learner's existing lesson preference (`useLessonLang`,
// localStorage `dm_lesson_lang`, English by default, „Deutsch-Modus" on the toggle) so the
// legacy course and the v2 course never disagree about which language the buttons speak.
// Content (prompts, dialogues, explanations' `de`) is German whatever the chrome says.
//
// Register: every German string addresses the learner with „Sie" (BLUEPRINT §1.6; the
// register scan in tests/course-player.test.mjs reads the same rule for both chromes).
//
// Legal wording (BLUEPRINT §4.5, §1.6): an AI result is always labelled
// „automatisierte Übungsbewertung" — in BOTH chrome languages the German label is shown,
// because it is the fixed label the claims rules name — and it is never a pass verdict,
// never a percentage and never a teacher's correction.

import { useLessonLang } from '../../lib/lesson/strings.js';

export const SCORE_LABEL_DE = 'automatisierte Übungsbewertung';
export const SCORE_NOTICE_DE =
  'Automatische KI-Auswertung — keine Korrektur durch eine Lehrkraft, kein Prüfungsergebnis. Richtwert.';

const EN = {
  'item.check': 'Check',
  'item.next': 'Continue',
  'item.retry': 'Try again',
  'item.showSolution': 'Show solution',
  'item.yourAnswer': 'Your answer',
  'item.typoRetry': 'Almost — check the spelling and try once more.',
  'item.caseRetry': 'Almost — check the capital letters and try once more.',
  'item.numberOnlyRetry': 'Almost — write only the number and try once more.',
  'item.wordOnlyRetry': 'Almost — write only the missing word and try once more.',
  'item.of': 'Question {n} of {total}',
  'item.repeat': '+1 repetition',
  'item.noMatch': 'None fits ({key})',
  'item.choose': 'Choose …',
  'item.gap': 'Gap {n}',
  'item.hint': 'Tip: {hint}',
  'item.listenAndType': 'Listen and write what you hear.',
  'item.listenAndChoose': 'Listen and choose.',
  'item.notes': 'Listen and take notes.',

  'fb.correct': 'Correct',
  'fb.typo': 'Correct — with a small slip',
  'fb.wrong': 'Not quite',
  'fb.revealed': 'Here is the solution',
  'fb.solution': 'Solution:',
  'fb.yours': 'Your answer:',
  // the bottom sheet of the one-item screen (FeedbackSheetV2.jsx)
  'fb.praise1': 'Great!',
  'fb.praise2': 'Nice!',
  'fb.praise3': 'Correct!',
  'fb.praise4': 'Exactly!',
  'fb.almost': 'Almost!',
  'fb.rightIs': 'Correct answer:',
  'fb.repeatSame': 'This one comes back in a moment.',
  'fb.repeatSimilar': 'A similar one comes back in a moment.',
  'fb.gotIt': 'Got it',

  // the instruction heading of a one-item screen, by item type (ItemView.jsx)
  'ask.choose': 'Choose the right answer',
  'ask.fill': 'Complete the sentence',
  'ask.tf': 'True or false?',
  'item.gapBlank': 'gap',
  'item.srRight': 'right',
  'item.srWrong': 'wrong',
  'item.srSolution': 'solution',
  'item.srSelected': 'selected',

  // the game layer (gamify.js): XP, combo, streak
  'game.xp': '+{n} XP',
  'game.combo': '{n} right in a row',
  'game.sessionXp': '{n} XP in this session',
  'game.streak': '{n} days in a row!',
  'game.streakOne': 'Day 1 — your streak begins!',
  'game.streakNone': 'Finish a step today to start a streak.',
  'game.week': 'This week',
  'game.today': 'today, still open',
  'game.dayOpen': 'no step',
  'game.wd0': 'Mo',
  'game.wd1': 'Tu',
  'game.wd2': 'We',
  'game.wd3': 'Th',
  'game.wd4': 'Fr',
  'game.wd5': 'Sa',
  'game.wd6': 'Su',

  // the step celebration (StepCelebration.jsx)
  'cel.title': 'Step complete!',
  'cel.did': 'You finished „{title}".',
  'cel.xp': 'XP',
  'cel.right': 'Correct',
  'cel.time': 'Time',

  'tiles.instructions': 'Tap the tiles in the right order.',
  'tiles.yourSentence': 'Your sentence',
  'tiles.bank': 'Tiles',
  'tiles.remove': 'Remove „{word}"',
  'match.instructions': 'Tap a word on the left, then its partner on the right.',
  'match.left': 'Left {n}',
  'match.right': 'Right {n}',

  'audio.play': 'Listen',
  'audio.playAgain': 'Listen again',
  'audio.playing': 'Playing …',
  'audio.slow': 'Slower',
  'audio.synthetic': 'Computer voice',
  'audio.none': 'Audio is not available in this browser — read the text instead.',
  'audio.playsLeft': '{n}× left',
  'audio.playsUsed': 'No more plays — as in the exam.',
  'audio.playsRule': 'In the exam you hear this text {n}×.',

  'input.listenFirst': 'Listen first — the text appears after the first listen.',
  'input.readFirst': 'Read the text.',
  'input.showText': 'Show text',
  'input.hideText': 'Hide text',
  'input.translationOn': 'Show English',
  'input.translationOff': 'Hide English',
  'input.glossHint': 'Dotted words: tap for the meaning.',

  'seg.warmup': 'Warm-up',
  'seg.input': 'Listen & read',
  'seg.inputItems': 'Understanding',
  'seg.form': 'Form',
  'seg.practice': 'Practice',
  'seg.aussprache': 'Pronunciation',
  'seg.micro': 'Your turn',
  'seg.exit': 'Wrap-up',
  'seg.exam': 'Exam training',
  'seg.sprache': 'Language',
  'seg.cloze': 'Cloze',
  'seg.redemittel': 'Useful phrases',
  'seg.step': 'Step {n}',

  'rule.title': 'Grammar',
  'rule.model': 'Model sentence',
  'rule.table': 'Overview',
  'rule.fillTable': 'Complete the table from the text.',
  'rule.missing': 'The rule card is not loaded yet.',
  'rule.repairLead': 'This came up twice — here is the rule again.',

  'aus.focus': 'Focus',
  'aus.readAloud': 'Read the sentence aloud.',

  'mo.plan': 'Plan ({s} s)',
  'mo.planLead': 'Think for a moment: what will you say or write?',
  'mo.planSkip': 'I am ready',
  'mo.write': 'Your text',
  'mo.words': '{n} words · target {min}–{max}',
  'mo.submit': 'Submit',
  'mo.submitting': 'Assessing …',
  'mo.speakStart': 'Start speaking',
  'mo.speakLead': 'Speak for {min}–{max} seconds. The AI listens and gives an automated practice assessment.',
  'mo.revise': 'Revise once',
  'mo.skip': 'Continue without an assessment',
  'mo.register': 'Form of address: {r}',
  'mo.model': 'Model answer',

  'ai.label': 'automated practice assessment',
  'ai.points': '{p} of {max} points (guide value)',
  'ai.notAuto': 'not assessed automatically',
  'ai.criteria': 'Criteria',
  'ai.selfCheck': 'Check these places yourself',
  'ai.leitpunkte': 'Content points',
  'ai.covered': 'covered',
  'ai.notCovered': 'not found',
  'ai.rules': 'Rules applied',
  'ai.nextStep': 'Next step',
  'ai.remaining': '{n} assessments left for this task.',
  'ai.signIn': 'Sign in to get an automated practice assessment.',
  'ai.access': 'This task is part of the course. With access to the course you get an automated practice assessment.',
  'ai.limit': 'Your AI assessments for this task are used up.',
  'ai.unavailable': 'The assessment is not available right now. Please try again later.',
  'ai.offline': 'No connection. Your text is saved on this device — try again when you are online.',
  'ai.failed': 'The assessment could not be created. Please try again.',
  'ai.slow': 'The assessment takes a little longer …',
  'ai.signInTitle': 'Free account: AI feedback on speaking and writing',
  'ai.signInLead': 'With a free account you get an automated practice assessment from the AI on your speaking and writing tasks, and your progress is saved in your account from then on — on every device.',
  'ai.signInBack': 'With an existing account you come straight back here after signing in.',
  'ai.signInCta': 'Sign in or create a free account',

  'w.task': 'Task',
  'w.points': 'Cover these points',
  'w.yourText': 'Your text',
  'w.words': '{n} words',
  'w.target': 'target {min}–{max}',
  'w.minSubmit': 'At least {n} words to submit.',
  'w.checklist': 'Checklist',
  'w.formcheck': 'Form check: this only looks at the form (length, points, greeting) — no assessment yet.',
  'w.cueFound': 'a hint of this point is there',
  'w.cueAi': 'the AI checks this',
  'w.anrede': 'Greeting at the start',
  'w.gruss': 'Closing at the end',
  'w.submit': 'Submit',
  'w.revise': 'Revise',
  'w.reviseLead': 'Look at the marked places, correct your text and submit it again.',
  'w.submitRevision': 'Submit revision',
  'w.reviseLater': 'You revise this text in the next step („Überarbeiten") on your next learning day.',
  'w.model': 'Model text',
  'w.modelAfter': 'The model text appears after your revision.',
  'w.done': 'Continue',
  'w.form': 'Fill in the form',
  'w.formCheck': 'Check form',
  'w.draftSaved': 'Draft saved on this device.',
  'w.noDraft': 'No earlier draft on this device — write your text here.',
  'w.previous': 'Your first version',

  'sp.task': 'Task',
  'sp.yourCards': 'Your cards',
  'sp.partnerCards': 'Your partner has cards too',
  'sp.slides': 'Your presentation',
  'sp.stimulus': 'Material',
  'sp.topics': 'Choose {pick} of {from} topics',
  'sp.hintWords': 'Helpful words',
  'sp.prep': 'Preparation',
  'sp.prepTimer': 'Preparation: {mm}:{ss}',
  'sp.prepExam': 'In the exam: {n} min. preparation',
  'sp.prepStart': 'Start preparation',
  'sp.prepSkip': 'Start now',
  'sp.notes': 'Your notes (only for you)',
  'sp.planning': 'Planning round ({n} min.)',
  'sp.start': 'Start the conversation',
  'sp.starting': 'Starting …',
  'sp.partner': 'Your partner: {name}',
  'sp.aiRole': 'You talk to an AI in the role of {name}.',
  'sp.examiner': 'Conversation lead (AI)',
  'sp.model': 'Model conversation',
  'sp.modelAfter': 'The model conversation appears after your attempt.',
  'sp.noMic': 'Continue without a microphone',
  'sp.noMicLead': 'Without a microphone: read the model conversation aloud for yourself. This attempt is not assessed.',
  'sp.selfLead': 'Without an assessment: read the model conversation aloud for yourself.',
  'sp.taskAgain': 'Show the task again',
  'sp.again': 'One more attempt',
  'sp.learner': 'You',
  'sp.partnerLabel': 'Partner',
  'sp.moves': 'Moves: {list}',

  'exam.lern': 'Learning mode',
  'exam.lernLead': 'Learning mode: you see after each answer whether it is right. The exam mode comes later.',
  'exam.strategy': 'Strategy',
  'exam.texts': 'Texts',
  'exam.transcript': 'Transcript',
  'exam.transcriptAfter': 'The transcript appears after you have answered.',
  'exam.items': 'Tasks',
  'exam.score': '{c} of {t} correct',
  'exam.choices': 'Choices',
  'exam.origin': 'From: {label}',
  'exam.start': 'Start',
  'exam.tip': 'Tip',
  'exam.showEn': 'Show in English',
  'exam.hideEn': 'Hide the English',
  'exam.count': '{n} tasks',
  'exam.countOne': '1 task',
  'exam.reduced': 'shortened',
  'exam.mini': 'mini',
  'exam.readFirst': 'Read the text first.',
  'exam.readAll': 'Read the texts first.',
  'exam.showText': 'Show text',
  'exam.hideText': 'Hide text',
  'exam.showWhole': 'Show the whole text',
  'exam.hideWhole': 'Hide the whole text',
  'exam.showChoices': 'Show texts {from}–{to}',
  'exam.hideChoices': 'Hide the texts',
  'exam.playsRule': 'In the exam you hear each text {n}×.',

  'check.title': 'Chapter test',
  'check.lead': '{n} short tasks. No AI — every answer is checked the same way.',
  'check.earlier': 'From earlier chapters',
  'check.proofs': 'Proofs',
  'check.canDo': 'I can do this',
  'check.proofItem': 'shown in the check',
  'check.proofOpen': 'still open',
  'check.itemOpen': 'the question in the check is still open',
  'check.proofAufgabe': 'shown in the {task} task',
  'check.aufgabeSprechen': 'speaking',
  'check.aufgabeSchreiben': 'writing',
  'check.aufgabeOpen': 'the {task} task is still open',
  'check.proofMicro': 'shown in your own answer',
  'check.microOpen': 'your own short answer is still open',
  'check.rueckschau': 'Grammar review',
  'check.portrait': 'Portrait',
  'check.story': 'How does it go on?',
  'check.result': '{c} of {t} correct',
  'check.repeatSuggest': 'Below 60 %: repeat one step if you like — you can also go on.',
  'check.done': 'Finish the chapter',

  'start.goals': 'Your goals in this chapter',
  'start.examFocus': 'Exam focus',
  'start.episode': 'Episode',
  'start.recap': 'Previously',
  'start.begin': 'Start',
  'start.testOut': 'I can do this already',
  'start.testOutLead': 'Take the chapter test. From 80 % the practice steps count as done; speaking and writing stay open.',
  'start.minutes': '≈ {n} min. (planned)',
  'start.today': 'Today you learn',
  'start.steps': '{n} steps',
  'start.perStep': 'about {n} min. each',
  'start.skipTest': 'Take the test and skip ahead',
  'start.bonus': 'Bonus: want to try it already?',
  'start.bonusLead': 'Optional — no pressure, you can skip it.',
  'start.bonusBubble': 'Now you know the episode. The steps start next!',
  'start.toSteps': 'On to the steps',

  'step.done': 'Step complete!',
  'step.result': '{c} of {t} correct at the first try',
  'step.next': 'Continue',
  'step.unknown': 'This step type is not supported yet.',
  'step.back': 'Back',
  'step.ueberarbeiten': 'Revise',

  // The unit player's own chrome (src/pages/course-v2/UnitPlayerPage.jsx)
  'player.home': 'Course overview',
  'player.progress': 'Progress in this chapter',
  'player.progressStep': 'Progress in this step',
  'player.unitBonus': 'Chapter bonus',
  'player.nextTeaser': 'Coming up in chapter {n}',
  'player.welcomeTitle': 'Welcome back!',
  'player.loading': 'Loading the chapter …',
  'player.unit': 'Chapter {n}',
  'player.goals': 'Goals',
  'player.doneMark': 'done',
  'player.minutes': '≈ {n} min. (planned)',
  'player.welcomeBack': 'Welcome back. {d} of {t} steps are done.',
  'player.resumeAt': 'Continue with step {n}: {title}',
  'player.startAgain': 'See the unit start again',
  'player.stepOf': 'Step {n} of {t}',
  'player.testOutNote': 'The practice steps are credited. Speaking and writing are still open.',
  'player.toPlateau': 'Continue to Plateau {n}',
  'player.toUnit': 'Continue with chapter {n}',
  'player.complete': 'Chapter complete!',
  'player.almost': 'Almost there',
  'player.open': 'Still open',
  'player.openStep': 'Step {n}: {title} →',
  'player.repeatTip': 'Tip: repeat a step before you move on — or carry straight on, if you prefer.',
  'player.canNow': 'What you can do now',
  'player.goalsUnit': 'Goals of this chapter',
  'player.words': '{n} new words are now in your review.',
  'player.nextUp': 'Next up:',
  'player.soonTitle': 'This chapter is coming soon',
  'player.soonBody': 'It is still being written. You will find every finished chapter in the course overview.',
  // round 3 — one thing per screen: the story screen, the welcome-back, the opt-in guide, the recap (UnitPlayerPage.jsx, UnitIntro.jsx)
  'flow.go': 'Let’s go',
  'flow.testOut': 'I know this already – take the test',
  'flow.welcome': 'Welcome back!',
  'flow.nextPart': 'Let’s carry on with part {l}: {title}',
  'flow.nextName': 'Next up: {name}',
  'flow.nextSummary': 'Everything is done – here is your summary.',
  'flow.overview': 'Chapter overview',
  'flow.guideTitle': 'Chapter {n} at a glance',
  'flow.close': 'Close the overview',
  'flow.openLeft': '{n} parts are still open.',
  'flow.openLeftOne': '1 part is still open.',
  'flow.repeat': 'Repeat a step',
  // step kinds as the player's step list and recap name them (the renderer's own
  // headings: seg.exam, check.title, step.ueberarbeiten; Sprechen/Schreiben stay German)
  'kind.situation': 'Situation',
  'kind.text': 'Text',
  'kind.sprache': 'Language',
  'kind.pruefung': 'Exam training',
  'kind.sprechen': 'Speaking task',
  'kind.schreiben': 'Writing task',
  'kind.ueberarbeiten': 'Revise',
  'kind.check': 'Chapter test',

  // the Kapitel page — the unit's front page, textbook style (UnitIntro.jsx, kapitel.js)
  'kap.chapter': 'Chapter',
  'kap.module': 'Module {m}',
  'kap.goals': 'In this chapter you learn',
  'kap.contents': 'Contents',
  'kap.intro': 'Opener',
  'kap.episode': 'Episode {n}',
  'kap.introLine': 'Listen to the episode, then one question',
  'kap.part': 'Part {l}',
  'kap.tasks': '{n} tasks',
  'kap.now': 'Now',
  'kap.pruefung': 'Exam practice',
  'kap.sprechen': 'Speaking (with AI)',
  'kap.schreiben': 'Writing (AI-corrected)',
  'kap.schreibenForm': 'Writing (form)',
  'kap.ueberarbeiten': 'Revising',
  'kap.test': 'Chapter test',
  'kap.testLine': 'Check your {n} goals',
  'kap.exam': 'Exam: {teile}',
  'kap.start': 'Start the chapter',
  'kap.continuePart': 'Continue with part {l}',
  'kap.continueWith': 'Continue: {name}',
  'kap.toSummary': 'See the summary',
  'kap.parts': '{n} parts',
  'kap.minutes': '≈ {n} min.',
  'kap.progress': '{d} of {t} parts done',
  'kap.reference': 'To look up',
  'kap.rules': '{n} rules',
  'kap.wordCount': '{n} words',
  'kap.wordOne': '1 word',
  'kap.phrases': '{n} phrases',
  'kap.moreWords': 'More words',
  'kap.allGrammar': 'All grammar of {level}',
  'kap.allWords': 'All words of {level}',
  'kap.loadingWords': 'Loading the words …',
  'kap.noWords': 'The word list of this chapter is not ready yet.',
  'kap.sg': 'sing. only',
  'kap.pl': 'plural only',
  'kap.hear': 'Listen: {w}',
  'kap.overview': 'Chapter overview',

  // the stages of a step: the section strip and the numbered exercise headings (StepView.jsx)
  'stage.aria': 'Parts of this step',
  'stage.words': 'New words',
  'stage.wordsLead': 'These words come up in a moment. Tap a word to see an example.',
  'stage.warmup': 'Warm-up',
  'stage.questions': 'Questions on the text',
  'stage.formPractice': 'Practise the form',
  'stage.table': 'Complete the table',
  'stage.yourTurn': 'Your turn',
  'stage.exit': 'Wrap-up',

  // one thing per screen inside a Lernschritt (StepView.jsx, StepScreen.jsx, WordCards.jsx,
  // StoryInput.jsx, RuleCardView.jsx RuleCardSteps)
  'card.newWord': 'New word',
  'card.wordOf': 'Word {n} of {total}',
  'card.plural': 'plural: {p}',
  'card.pluralOnly': 'plural only',
  'card.singularOnly': 'no plural',
  'card.example': 'Example',
  'card.hearExample': 'Listen to the example',
  'card.listen': 'Listen',
  'card.listenLead': 'Listen to the whole text first. Then you read it line by line.',
  'card.readAlong': 'Read along',
  'card.read': 'Read',
  'card.listenAll': 'Listen to everything',
  'card.tip': 'Grammar tip',
  'card.table': 'At a glance',
  'card.hearModel': 'Listen to the model sentence',
  'card.phrases': 'Useful phrases',
  'card.phraseOf': 'Phrase {n} of {total}',
  'card.pronounce': 'Listen closely',
  'card.hearFocus': 'Listen to the sounds',
  'card.sayIt': 'Say it',
  'card.yourTurn': 'Your turn!',

  // the level reference pages: /course/:level/grammatik and /course/:level/wortschatz
  'ref.grammarTitle': 'Grammar · {level}',
  'ref.grammarLead': 'Every rule of the course, chapter by chapter: model sentence, rule and table.',
  'ref.wordsTitle': 'Vocabulary · {level}',
  'ref.wordsLead': 'All {n} words of the course, chapter by chapter. Tap a word to see an example.',
  'ref.search': 'Search a word',
  'ref.searchHint': 'German or English',
  'ref.results': '{n} words found',
  'ref.resultOne': '1 word found',
  'ref.noResults': 'No word found. Try another spelling.',
  'ref.jump': 'Jump to a chapter',
  'ref.more': 'More grammar',
  'ref.moreWords': 'More words',
  'ref.seeAlso': 'Also practised here: {name}, see chapter {n}',
  'ref.loading': 'Loading …',
  'ref.soon': 'The reference for this level is coming soon.',
  'ref.toChapter': 'Open chapter {n}',

  // Plateau and closing block (src/pages/course-v2/AssessmentPlayer.jsx; BLUEPRINT §5.2, §5.3)
  'as.loading': 'Loading …',
  'as.plateau': 'Plateau {n}',
  // the SCHEMA kind stays 'halbtest' (a data key); the learner-facing name is Abschlusstest, as on the path
  'as.halbtest': 'Abschlusstest',
  'as.closingChip': 'Course finale',
  'as.plateauLead': 'The Plateau closes a module: a review of its chapters, exam parts in the exam format, one speaking or writing task, and something to read or hear.',
  'as.closingLead': 'Every part of the {exam} exam, in small. You see after each answer whether it is right. At the end, your exam-part map shows where each part continues in {next}. No mark and no exam result.',
  'as.start': 'Start the Plateau',
  'as.startClosing': 'Start the Abschlusstest',
  'as.resumeAt': 'Continue with part {n}: {title}',
  'as.sectionOf': 'Part {n} of {t}',
  'as.sections': 'Parts',
  'as.itemsCount': '{n} tasks',
  'as.progress': 'Progress',
  'as.review': 'Review',
  'as.reviewLead': '{n} tasks from chapters {from} to {to}. You see after each answer whether it is right.',
  'as.productiveSpeaking': 'Speaking task',
  'as.productiveWriting': 'Writing task',
  'as.productiveLead': 'The same kind of task you practised a few weeks ago — now again.',
  'as.rewardLead': 'Not graded — something to read or hear, just for you.',
  'as.rewardProjekt': 'Project',
  'as.rewardScene': 'Scene',
  'as.rewardSkip': 'Skip',
  'as.textAgain': 'See the text again',
  'as.rewardDone': 'Done',
  'as.optional': 'optional',
  'as.resultsDone': 'Plateau {n} submitted',
  'as.closingDone': 'Abschlusstest submitted',
  'as.almost': 'Almost there',
  'as.resultsLead': 'Your results per part — practice values in learning mode, not an exam result.',
  'as.open': 'Still open',
  'as.openSection': 'Part {n}: {title} →',
  'as.submitted': 'submitted',
  'as.notSubmitted': 'not submitted yet',
  'as.notDone': 'not done yet',
  'as.repairTitle': 'Worth repeating',
  'as.repairStep': 'Chapter {u}, part {s}: {m} of {t} not right',
  'as.repairTeil': '{teil}: {c} of {t} — practise it again in chapter {u}',
  'as.allRight': 'Every review task was right — nothing to repeat.',
  'as.toClosing': 'Continue to the Abschlusstest',
  'as.soonPlateau': 'Plateau {n} is coming soon',
  'as.soonClosing': 'The course finale is coming soon',
  'as.soonBody': 'It is still being written. You will find every finished part in the course overview.',
  'as.etappe': 'This stage',
  'kk.title': 'Your exam-part map',
  'kk.lead': 'Every part of the {exam} exam: what you practised in {level} and where it continues. No total and no pass mark.',
  'kk.miniature': 'practised in small',
  'kk.full': 'practised at full length (learning mode)',
  'kk.open': 'still open',
  'kk.next': 'comes in {level}, chapter {n}',
  'kk.nextLevel': 'comes in {level}',

  // the course home's first-visit welcome (home/Welcome.jsx, pathModel.welcomeModel/paceTile):
  // the chrome follows dm_lesson_lang like the player — the promise and the can-dos stay German
  'welcome.title': 'Welcome to the {code} course',
  'welcome.stepOf': 'Screen {n} of {t}',
  'welcome.skip': 'Skip',
  'welcome.next': 'Continue',
  'welcome.go': 'Let’s go',
  'welcome.outcomes': 'What you will learn in {code}',
  'welcome.chapters': '{n} chapters',
  'welcome.chapterOne': '1 chapter',
  'welcome.modules': '{n} modules',
  'welcome.moduleOne': '1 module',
  // the end of the path (CourseFinish.jsx, pathModel.courseFinish): every Kapitel done
  'finish.courseTitle': '{code} complete!',
  'finish.courseBody': 'All {n} chapters and the Abschlusstest are done.',
  'finish.nextNotYet': '{next} is not released yet. Until then, you can repeat any chapter and look up every word in the word list.',
  'finish.chaptersTitle': 'All {n} chapters done!',
  'finish.closingLeft': 'One thing is left: the Abschlusstest — every exam part, in small.',
  'finish.closingSoon': 'The Abschlusstest is coming soon. Until then, you can repeat any chapter and look up every word in the word list.',
  'finish.resumeClosing': 'Continue the Abschlusstest',
  'finish.toWords': 'Open the word list',
  'welcome.finalTest': 'Abschlusstest',
  'welcome.free': 'Free',
  'welcome.lane': 'On the way to the {exam}',
  'welcome.tempo': 'How much time do you have per day?',
  'welcome.tempoLegend': 'Your pace',
  'welcome.paceLeicht': 'Light',
  'welcome.paceStandard': 'Standard',
  'welcome.paceIntensiv': 'Intensive',
  'welcome.minutes': '{n} minutes',
  'welcome.days': 'on {n} days a week',
  'welcome.finish': 'done around {date}',
};

const DE = {
  'item.check': 'Prüfen',
  'item.next': 'Weiter',
  'item.retry': 'Nochmal versuchen',
  'item.showSolution': 'Lösung zeigen',
  'item.yourAnswer': 'Ihre Antwort',
  'item.typoRetry': 'Fast richtig – prüfen Sie die Schreibung und versuchen Sie es noch einmal.',
  'item.caseRetry': 'Fast richtig – achten Sie auf Groß- und Kleinschreibung und versuchen Sie es noch einmal.',
  'item.numberOnlyRetry': 'Fast richtig – schreiben Sie nur die Zahl und versuchen Sie es noch einmal.',
  'item.wordOnlyRetry': 'Fast richtig – schreiben Sie nur das fehlende Wort und versuchen Sie es noch einmal.',
  'item.of': 'Aufgabe {n} von {total}',
  'item.repeat': '+1 Wiederholung',
  'item.noMatch': 'Keine passt ({key})',
  'item.choose': 'Wählen Sie …',
  'item.gap': 'Lücke {n}',
  'item.hint': 'Tipp: {hint}',
  'item.listenAndType': 'Hören Sie und schreiben Sie, was Sie hören.',
  'item.listenAndChoose': 'Hören Sie und wählen Sie.',
  'item.notes': 'Hören Sie und notieren Sie.',

  'fb.correct': 'Richtig',
  'fb.typo': 'Richtig – mit einem kleinen Fehler',
  'fb.wrong': 'Noch nicht richtig',
  'fb.revealed': 'Hier ist die Lösung',
  'fb.solution': 'Lösung:',
  'fb.yours': 'Ihre Antwort:',
  'fb.praise1': 'Super!',
  'fb.praise2': 'Klasse!',
  'fb.praise3': 'Richtig!',
  'fb.praise4': 'Genau!',
  'fb.almost': 'Fast!',
  'fb.rightIs': 'Richtig ist:',
  'fb.repeatSame': 'Diese Aufgabe kommt gleich noch einmal.',
  'fb.repeatSimilar': 'Gleich kommt eine ähnliche Aufgabe noch einmal.',
  'fb.gotIt': 'Verstanden',

  'ask.choose': 'Wählen Sie die richtige Antwort',
  'ask.fill': 'Ergänzen Sie den Satz',
  'ask.tf': 'Richtig oder falsch?',
  'item.gapBlank': 'Lücke',
  'item.srRight': 'richtig',
  'item.srWrong': 'falsch',
  'item.srSolution': 'Lösung',
  'item.srSelected': 'ausgewählt',

  'game.xp': '+{n} XP',
  'game.combo': '{n} richtig in Folge',
  'game.sessionXp': '{n} XP in dieser Sitzung',
  'game.streak': '{n} Tage in Folge!',
  'game.streakOne': 'Tag 1 – Ihre Serie beginnt!',
  'game.streakNone': 'Schaffen Sie heute einen Lernschritt, dann beginnt Ihre Serie.',
  'game.week': 'Diese Woche',
  'game.today': 'heute, noch offen',
  'game.dayOpen': 'kein Lernschritt',
  'game.wd0': 'Mo',
  'game.wd1': 'Di',
  'game.wd2': 'Mi',
  'game.wd3': 'Do',
  'game.wd4': 'Fr',
  'game.wd5': 'Sa',
  'game.wd6': 'So',

  'cel.title': 'Lernschritt geschafft!',
  'cel.did': 'Sie haben „{title}" geschafft.',
  'cel.xp': 'XP',
  'cel.right': 'Richtig',
  'cel.time': 'Zeit',

  'tiles.instructions': 'Tippen Sie die Wörter in der richtigen Reihenfolge an.',
  'tiles.yourSentence': 'Ihr Satz',
  'tiles.bank': 'Wörter',
  'tiles.remove': '„{word}" entfernen',
  'match.instructions': 'Tippen Sie links ein Wort an, dann rechts den Partner.',
  'match.left': 'Links {n}',
  'match.right': 'Rechts {n}',

  'audio.play': 'Anhören',
  'audio.playAgain': 'Nochmal hören',
  'audio.playing': 'Läuft …',
  'audio.slow': 'Langsamer',
  'audio.synthetic': 'Computerstimme',
  'audio.none': 'Audio ist in diesem Browser nicht verfügbar – lesen Sie den Text.',
  'audio.playsLeft': 'noch {n}×',
  'audio.playsUsed': 'Keine Wiederholung mehr – wie in der Prüfung.',
  'audio.playsRule': 'In der Prüfung hören Sie diesen Text {n}×.',

  'input.listenFirst': 'Hören Sie zuerst – der Text erscheint nach dem ersten Hören.',
  'input.readFirst': 'Lesen Sie den Text.',
  'input.showText': 'Text zeigen',
  'input.hideText': 'Text ausblenden',
  'input.translationOn': 'Englisch zeigen',
  'input.translationOff': 'Englisch ausblenden',
  'input.glossHint': 'Gepunktete Wörter: Tippen Sie für die Bedeutung.',

  'seg.warmup': 'Aufwärmen',
  'seg.input': 'Hören & Lesen',
  'seg.inputItems': 'Verstehen',
  'seg.form': 'Form',
  'seg.practice': 'Üben',
  'seg.aussprache': 'Aussprache',
  'seg.micro': 'Ihre Mini-Aufgabe',
  'seg.exit': 'Abschluss',
  'seg.exam': 'Prüfungstraining',
  'seg.sprache': 'Sprache',
  'seg.cloze': 'Lückentext',
  'seg.redemittel': 'Redemittel',
  'seg.step': 'Lernschritt {n}',

  'rule.title': 'Grammatik',
  'rule.model': 'Mustersatz',
  'rule.table': 'Übersicht',
  'rule.fillTable': 'Ergänzen Sie die Tabelle mit dem Text.',
  'rule.missing': 'Die Regelkarte ist noch nicht geladen.',
  'rule.repairLead': 'Das war zweimal schwierig – hier noch einmal die Regel.',

  'aus.focus': 'Fokus',
  'aus.readAloud': 'Lesen Sie den Satz laut vor.',

  'mo.plan': 'Planen ({s} s)',
  'mo.planLead': 'Überlegen Sie kurz: Was sagen oder schreiben Sie?',
  'mo.planSkip': 'Ich bin bereit',
  'mo.write': 'Ihr Text',
  'mo.words': '{n} Wörter · Ziel {min}–{max}',
  'mo.submit': 'Abgeben',
  'mo.submitting': 'Wird ausgewertet …',
  'mo.speakStart': 'Sprechen starten',
  'mo.speakLead': 'Sprechen Sie {min}–{max} Sekunden. Die KI hört zu und gibt eine automatisierte Übungsbewertung.',
  'mo.revise': 'Einmal überarbeiten',
  'mo.skip': 'Ohne Auswertung weiter',
  'mo.register': 'Anrede: {r}',
  'mo.model': 'Musterantwort',

  'ai.label': SCORE_LABEL_DE,
  'ai.points': '{p} von {max} Punkten (Richtwert)',
  'ai.notAuto': 'nicht automatisch bewertet',
  'ai.criteria': 'Kriterien',
  'ai.selfCheck': 'Prüfen Sie diese Stellen selbst',
  'ai.leitpunkte': 'Inhaltspunkte',
  'ai.covered': 'behandelt',
  'ai.notCovered': 'nicht gefunden',
  'ai.rules': 'Angewandte Regeln',
  'ai.nextStep': 'Nächster Schritt',
  'ai.remaining': 'Noch {n} Auswertungen für diese Aufgabe.',
  'ai.signIn': 'Melden Sie sich an, um eine automatisierte Übungsbewertung zu bekommen.',
  'ai.access': 'Diese Aufgabe gehört zum Kurs. Mit Zugang zum Kurs bekommen Sie eine automatisierte Übungsbewertung.',
  'ai.limit': 'Ihre KI-Auswertungen für diese Aufgabe sind aufgebraucht.',
  'ai.unavailable': 'Die Auswertung ist gerade nicht verfügbar. Bitte versuchen Sie es später noch einmal.',
  'ai.offline': 'Keine Verbindung. Ihr Text ist auf diesem Gerät gespeichert – versuchen Sie es wieder, wenn Sie online sind.',
  'ai.failed': 'Die Auswertung konnte nicht erstellt werden. Bitte versuchen Sie es noch einmal.',
  'ai.slow': 'Die Auswertung dauert etwas länger …',
  'ai.signInTitle': 'Kostenloses Konto: KI-Feedback zu Sprechen und Schreiben',
  'ai.signInLead': 'Mit einem kostenlosen Konto bekommen Sie zu Ihren Sprech- und Schreibaufgaben eine automatisierte Übungsbewertung der KI, und Ihr Lernfortschritt wird ab dann in Ihrem Konto gespeichert – auf jedem Gerät.',
  'ai.signInBack': 'Mit einem bestehenden Konto kommen Sie nach der Anmeldung direkt hierher zurück.',
  'ai.signInCta': 'Anmelden oder kostenlos registrieren',

  'w.task': 'Aufgabe',
  'w.points': 'Schreiben Sie zu diesen Punkten',
  'w.yourText': 'Ihr Text',
  'w.words': '{n} Wörter',
  'w.target': 'Ziel {min}–{max}',
  'w.minSubmit': 'Mindestens {n} Wörter zum Abgeben.',
  'w.checklist': 'Checkliste',
  'w.formcheck': 'Formcheck: nur die Form (Länge, Punkte, Anrede und Gruß), noch keine Bewertung.',
  'w.cueFound': 'ein Hinweis auf diesen Punkt ist da',
  'w.cueAi': 'prüft die KI',
  'w.anrede': 'Anrede am Anfang',
  'w.gruss': 'Gruß am Ende',
  'w.submit': 'Abgeben',
  'w.revise': 'Überarbeiten',
  'w.reviseLead': 'Sehen Sie sich die markierten Stellen an, korrigieren Sie Ihren Text und geben Sie ihn noch einmal ab.',
  'w.submitRevision': 'Überarbeitung abgeben',
  'w.reviseLater': 'Sie überarbeiten diesen Text im nächsten Schritt („Überarbeiten") an Ihrem nächsten Lerntag.',
  'w.model': 'Mustertext',
  'w.modelAfter': 'Der Mustertext erscheint nach Ihrer Überarbeitung.',
  'w.done': 'Weiter',
  'w.form': 'Füllen Sie das Formular aus',
  'w.formCheck': 'Formular prüfen',
  'w.draftSaved': 'Entwurf auf diesem Gerät gespeichert.',
  'w.noDraft': 'Auf diesem Gerät gibt es keinen früheren Entwurf – schreiben Sie Ihren Text hier.',
  'w.previous': 'Ihre erste Fassung',

  'sp.task': 'Aufgabe',
  'sp.yourCards': 'Ihre Karten',
  'sp.partnerCards': 'Ihre Partnerin oder Ihr Partner hat auch Karten',
  'sp.slides': 'Ihre Präsentation',
  'sp.stimulus': 'Material',
  'sp.topics': 'Wählen Sie {pick} von {from} Themen',
  'sp.hintWords': 'Hilfreiche Wörter',
  'sp.prep': 'Vorbereitung',
  'sp.prepTimer': 'Vorbereitung: {mm}:{ss}',
  'sp.prepExam': 'In der Prüfung: {n} Min. Vorbereitung',
  'sp.prepStart': 'Vorbereitung starten',
  'sp.prepSkip': 'Jetzt beginnen',
  'sp.notes': 'Ihre Notizen (nur für Sie)',
  'sp.planning': 'Planungsrunde ({n} Min.)',
  'sp.start': 'Gespräch starten',
  'sp.starting': 'Wird gestartet …',
  'sp.partner': 'Ihr Gegenüber: {name}',
  'sp.aiRole': 'Sie sprechen mit einer KI in der Rolle von {name}.',
  'sp.examiner': 'Gesprächsleitung (KI)',
  'sp.model': 'Mustergespräch',
  'sp.modelAfter': 'Das Mustergespräch erscheint nach Ihrem Versuch.',
  'sp.noMic': 'Ohne Mikrofon weiter',
  'sp.noMicLead': 'Ohne Mikrofon: Lesen Sie das Mustergespräch für sich laut. Dieser Versuch wird nicht ausgewertet.',
  'sp.selfLead': 'Ohne Auswertung: Lesen Sie das Mustergespräch für sich laut.',
  'sp.taskAgain': 'Aufgabe noch einmal ansehen',
  'sp.again': 'Noch ein Versuch',
  'sp.learner': 'Sie',
  'sp.partnerLabel': 'Gegenüber',
  'sp.moves': 'Schritte: {list}',

  'exam.lern': 'Lernmodus',
  'exam.lernLead': 'Lernmodus: Nach jeder Antwort sehen Sie, ob sie richtig ist. Den Prüfungsmodus üben Sie später.',
  'exam.strategy': 'Strategie',
  'exam.texts': 'Texte',
  'exam.transcript': 'Transkript',
  'exam.transcriptAfter': 'Das Transkript erscheint, wenn Sie geantwortet haben.',
  'exam.items': 'Aufgaben',
  'exam.score': '{c} von {t} richtig',
  'exam.choices': 'Auswahl',
  'exam.origin': 'Aus: {label}',
  'exam.start': 'Los geht’s',
  'exam.tip': 'Tipp',
  'exam.showEn': 'Auf Englisch zeigen',
  'exam.hideEn': 'Englisch ausblenden',
  'exam.count': '{n} Aufgaben',
  'exam.countOne': '1 Aufgabe',
  'exam.reduced': 'verkürzt',
  'exam.mini': 'Mini',
  'exam.readFirst': 'Lesen Sie zuerst den Text.',
  'exam.readAll': 'Lesen Sie zuerst die Texte.',
  'exam.showText': 'Text anzeigen',
  'exam.hideText': 'Text ausblenden',
  'exam.showWhole': 'Ganzen Text anzeigen',
  'exam.hideWhole': 'Ganzen Text ausblenden',
  'exam.showChoices': 'Texte {from}–{to} anzeigen',
  'exam.hideChoices': 'Texte ausblenden',
  'exam.playsRule': 'In der Prüfung hören Sie jeden Text {n}×.',

  'check.title': 'Kapiteltest',
  'check.lead': '{n} kurze Aufgaben. Ohne KI – jede Antwort wird gleich geprüft.',
  'check.earlier': 'Aus früheren Kapiteln',
  'check.proofs': 'Nachweise',
  'check.canDo': 'Das kann ich',
  'check.proofItem': 'im Check gezeigt',
  'check.proofOpen': 'noch offen',
  'check.itemOpen': 'die Frage im Check ist noch offen',
  'check.proofAufgabe': 'in der Aufgabe {task} gezeigt',
  'check.aufgabeSprechen': 'Sprechen',
  'check.aufgabeSchreiben': 'Schreiben',
  'check.aufgabeOpen': 'die Aufgabe {task} ist noch offen',
  'check.proofMicro': 'in Ihrer eigenen Antwort gezeigt',
  'check.microOpen': 'Ihre eigene kurze Antwort ist noch offen',
  'check.rueckschau': 'Grammatik-Rückschau',
  'check.portrait': 'Porträt',
  'check.story': 'Wie geht es weiter?',
  'check.result': '{c} von {t} richtig',
  'check.repeatSuggest': 'Unter 60 %: Wiederholen Sie gern einen Lernschritt – Sie können aber auch weitermachen.',
  'check.done': 'Kapitel abschließen',

  'start.goals': 'Ihre Ziele in diesem Kapitel',
  'start.examFocus': 'Prüfungsfokus',
  'start.episode': 'Folge',
  'start.recap': 'Was bisher geschah',
  'start.begin': 'Los geht’s',
  'start.testOut': 'Ich kann das schon',
  'start.testOutLead': 'Machen Sie den Kapiteltest. Ab 80 % zählen die Übungsschritte als erledigt; Sprechen und Schreiben bleiben offen.',
  'start.minutes': '≈ {n} Min. (geplant)',
  'start.today': 'Heute lernen Sie',
  'start.steps': '{n} Lernschritte',
  'start.perStep': 'je etwa {n} Min.',
  'start.skipTest': 'Test machen und überspringen',
  'start.bonus': 'Bonus: Schon mal probieren?',
  'start.bonusLead': 'Freiwillig – ganz ohne Druck, Sie können es auch überspringen.',
  'start.bonusBubble': 'Jetzt kennen Sie die Folge. Gleich geht es mit den Lernschritten los!',
  'start.toSteps': 'Zu den Lernschritten',

  'step.done': 'Lernschritt geschafft!',
  'step.result': '{c} von {t} im ersten Versuch richtig',
  'step.next': 'Weiter',
  'step.unknown': 'Dieser Lernschritt wird noch nicht unterstützt.',
  'step.back': 'Zurück',
  'step.ueberarbeiten': 'Überarbeiten',

  'player.home': 'Zur Kursübersicht',
  'player.progress': 'Fortschritt in diesem Kapitel',
  'player.progressStep': 'Fortschritt in diesem Lernschritt',
  'player.unitBonus': 'Kapitelbonus',
  'player.nextTeaser': 'Gleich in Kapitel {n}',
  'player.welcomeTitle': 'Schön, dass Sie wieder da sind!',
  'player.loading': 'Kapitel wird geladen …',
  'player.unit': 'Kapitel {n}',
  'player.goals': 'Lernziele',
  'player.doneMark': 'erledigt',
  'player.minutes': '≈ {n} Min. (geplant)',
  'player.welcomeBack': 'Willkommen zurück. {d} von {t} Schritten sind erledigt.',
  'player.resumeAt': 'Weiter bei Schritt {n}: {title}',
  'player.startAgain': 'Einstieg noch einmal ansehen',
  'player.stepOf': 'Schritt {n} von {t}',
  'player.testOutNote': 'Die Übungsschritte sind angerechnet. Offen sind noch Sprechen und Schreiben.',
  'player.toPlateau': 'Weiter zum Plateau {n}',
  'player.toUnit': 'Weiter mit Kapitel {n}',
  'player.complete': 'Kapitel geschafft!',
  'player.almost': 'Fast geschafft',
  'player.open': 'Noch offen',
  'player.openStep': 'Schritt {n}: {title} →',
  'player.repeatTip': 'Tipp: Wiederholen Sie einen Lernschritt, bevor Sie weitergehen – Sie können aber auch direkt weitermachen.',
  'player.canNow': 'Das können Sie jetzt',
  'player.goalsUnit': 'Ziele dieses Kapitels',
  'player.words': '{n} neue Wörter sind jetzt in Ihrer Wiederholung.',
  'player.nextUp': 'Als Nächstes:',
  'player.soonTitle': 'Dieses Kapitel kommt bald',
  'player.soonBody': 'Es ist noch in Arbeit. Alle fertigen Kapitel finden Sie in der Kursübersicht.',
  'flow.go': 'Los geht’s',
  'flow.testOut': 'Ich kann das schon – Test machen',
  'flow.welcome': 'Willkommen zurück!',
  'flow.nextPart': 'Weiter geht’s mit Teil {l}: {title}',
  'flow.nextName': 'Als Nächstes: {name}',
  'flow.nextSummary': 'Alles erledigt – hier ist Ihre Zusammenfassung.',
  'flow.overview': 'Kapitel im Überblick',
  'flow.guideTitle': 'Kapitel {n} im Überblick',
  'flow.close': 'Überblick schließen',
  'flow.openLeft': 'Noch {n} Teile sind offen.',
  'flow.openLeftOne': 'Noch 1 Teil ist offen.',
  'flow.repeat': 'Einen Lernschritt wiederholen',
  'kind.situation': 'Situation',
  'kind.text': 'Text',
  'kind.sprache': 'Sprache',
  'kind.pruefung': 'Prüfungstraining',
  'kind.sprechen': 'Sprechen',
  'kind.schreiben': 'Schreiben',
  'kind.ueberarbeiten': 'Überarbeiten',
  'kind.check': 'Kapiteltest',

  'kap.chapter': 'Kapitel',
  'kap.module': 'Modul {m}',
  'kap.goals': 'In diesem Kapitel lernen Sie',
  'kap.contents': 'Inhalt',
  'kap.intro': 'Einstieg',
  'kap.episode': 'Folge {n}',
  'kap.introLine': 'Die Folge hören, dann eine Frage',
  'kap.part': 'Teil {l}',
  'kap.tasks': '{n} Aufgaben',
  'kap.now': 'Jetzt',
  'kap.pruefung': 'Prüfungstraining',
  'kap.sprechen': 'Sprechen (mit KI)',
  'kap.schreiben': 'Schreiben (mit KI-Korrektur)',
  'kap.schreibenForm': 'Schreiben (Formular)',
  'kap.ueberarbeiten': 'Überarbeiten',
  'kap.test': 'Kapiteltest',
  'kap.testLine': 'Prüfen Sie Ihre {n} Lernziele',
  'kap.exam': 'Prüfung: {teile}',
  'kap.start': 'Kapitel starten',
  'kap.continuePart': 'Weiter mit Teil {l}',
  'kap.continueWith': 'Weiter: {name}',
  'kap.toSummary': 'Zur Zusammenfassung',
  'kap.parts': '{n} Teile',
  'kap.minutes': '≈ {n} Min.',
  'kap.progress': '{d} von {t} Teilen geschafft',
  'kap.reference': 'Zum Nachschlagen',
  'kap.rules': '{n} Regeln',
  'kap.wordCount': '{n} Wörter',
  'kap.wordOne': '1 Wort',
  'kap.phrases': '{n} Sätze',
  'kap.moreWords': 'Weitere Wörter',
  'kap.allGrammar': 'Alle Grammatik von {level}',
  'kap.allWords': 'Alle Wörter von {level}',
  'kap.loadingWords': 'Wörter werden geladen …',
  'kap.noWords': 'Die Wortliste dieses Kapitels ist noch nicht fertig.',
  'kap.sg': 'nur Sg.',
  'kap.pl': 'nur Pl.',
  'kap.hear': 'Anhören: {w}',
  'kap.overview': 'Kapitelübersicht',

  'stage.aria': 'Teile dieses Lernschritts',
  'stage.words': 'Neue Wörter',
  'stage.wordsLead': 'Diese Wörter kommen gleich vor. Tippen Sie auf ein Wort für ein Beispiel.',
  'stage.warmup': 'Wiederholen',
  'stage.questions': 'Fragen zum Text',
  'stage.formPractice': 'Die Form üben',
  'stage.table': 'Die Tabelle ergänzen',
  'stage.yourTurn': 'Jetzt Sie',
  'stage.exit': 'Abschluss',

  // one thing per screen inside a Lernschritt (StepView.jsx, StepScreen.jsx, WordCards.jsx,
  // StoryInput.jsx, RuleCardView.jsx RuleCardSteps)
  'card.newWord': 'Neues Wort',
  'card.wordOf': 'Wort {n} von {total}',
  'card.plural': 'Plural: {p}',
  'card.pluralOnly': 'nur Plural',
  'card.singularOnly': 'kein Plural',
  'card.example': 'Beispiel',
  'card.hearExample': 'Beispiel anhören',
  'card.listen': 'Hören Sie zu',
  'card.listenLead': 'Hören Sie zuerst den ganzen Text. Dann lesen Sie ihn Zeile für Zeile.',
  'card.readAlong': 'Lesen Sie mit',
  'card.read': 'Lesen Sie',
  'card.listenAll': 'Alles anhören',
  'card.tip': 'Grammatik-Tipp',
  'card.table': 'Auf einen Blick',
  'card.hearModel': 'Mustersatz anhören',
  'card.phrases': 'Nützliche Sätze',
  'card.phraseOf': 'Satz {n} von {total}',
  'card.pronounce': 'Genau hinhören',
  'card.hearFocus': 'Die Laute anhören',
  'card.sayIt': 'Sprechen Sie nach',
  'card.yourTurn': 'Jetzt Sie!',

  'ref.grammarTitle': 'Grammatik · {level}',
  'ref.grammarLead': 'Alle Regeln des Kurses, Kapitel für Kapitel: Mustersatz, Regel und Tabelle.',
  'ref.wordsTitle': 'Wortschatz · {level}',
  'ref.wordsLead': 'Alle {n} Wörter des Kurses, Kapitel für Kapitel. Tippen Sie auf ein Wort für ein Beispiel.',
  'ref.search': 'Wort suchen',
  'ref.searchHint': 'Deutsch oder Englisch',
  'ref.results': '{n} Wörter gefunden',
  'ref.resultOne': '1 Wort gefunden',
  'ref.noResults': 'Kein Wort gefunden. Versuchen Sie eine andere Schreibung.',
  'ref.jump': 'Zu einem Kapitel springen',
  'ref.more': 'Weitere Grammatik',
  'ref.moreWords': 'Weitere Wörter',
  'ref.seeAlso': 'Hier auch geübt: {name}, siehe Kapitel {n}',
  'ref.loading': 'Wird geladen …',
  'ref.soon': 'Das Nachschlagen für dieses Niveau kommt bald.',
  'ref.toChapter': 'Kapitel {n} öffnen',

  'as.loading': 'Wird geladen …',
  'as.plateau': 'Plateau {n}',
  'as.halbtest': 'Abschlusstest',
  'as.closingChip': 'Abschluss des Kurses',
  'as.plateauLead': 'Das Plateau schließt ein Modul ab: eine Wiederholung aus seinen Kapiteln, Prüfungsteile im Prüfungsformat, eine Aufgabe zum Sprechen oder Schreiben und etwas zum Lesen oder Hören.',
  'as.closingLead': 'Jeder Teil der Prüfung {exam}, im Kleinen. Nach jeder Antwort sehen Sie, ob sie richtig ist. Am Ende zeigt Ihre Teil-Karte, wo jeder Teil in {next} weitergeht. Keine Note und kein Prüfungsergebnis.',
  'as.start': 'Plateau starten',
  'as.startClosing': 'Abschlusstest starten',
  'as.resumeAt': 'Weiter bei Teil {n}: {title}',
  'as.sectionOf': 'Teil {n} von {t}',
  'as.sections': 'Teile',
  'as.itemsCount': '{n} Aufgaben',
  'as.progress': 'Fortschritt',
  'as.review': 'Wiederholung',
  'as.reviewLead': '{n} Aufgaben aus den Kapiteln {from} bis {to}. Nach jeder Antwort sehen Sie, ob sie richtig ist.',
  'as.productiveSpeaking': 'Aufgabe: Sprechen',
  'as.productiveWriting': 'Aufgabe: Schreiben',
  'as.productiveLead': 'Diese Art von Aufgabe haben Sie vor ein paar Wochen geübt – jetzt noch einmal.',
  'as.rewardLead': 'Ohne Bewertung – etwas zum Lesen oder Hören, nur für Sie.',
  'as.rewardProjekt': 'Projekt',
  'as.rewardScene': 'Szene',
  'as.rewardSkip': 'Überspringen',
  'as.textAgain': 'Text noch einmal ansehen',
  'as.rewardDone': 'Fertig',
  'as.optional': 'freiwillig',
  'as.resultsDone': 'Plateau {n} abgegeben',
  'as.closingDone': 'Abschlusstest abgegeben',
  'as.almost': 'Fast geschafft',
  'as.resultsLead': 'Ihre Ergebnisse pro Teil – Übungswerte im Lernmodus, kein Prüfungsergebnis.',
  'as.open': 'Noch offen',
  'as.openSection': 'Teil {n}: {title} →',
  'as.submitted': 'abgegeben',
  'as.notSubmitted': 'noch nicht abgegeben',
  'as.notDone': 'noch nicht gemacht',
  'as.repairTitle': 'Das lohnt sich zu wiederholen',
  'as.repairStep': 'Kapitel {u}, Teil {s}: {m} von {t} nicht richtig',
  'as.repairTeil': '{teil}: {c} von {t} – üben Sie ihn noch einmal in Kapitel {u}',
  'as.allRight': 'Alle Aufgaben der Wiederholung waren richtig – nichts zu wiederholen.',
  'as.toClosing': 'Weiter zum Abschlusstest',
  'as.soonPlateau': 'Plateau {n} kommt bald',
  'as.soonClosing': 'Der Abschluss des Kurses kommt bald',
  'as.soonBody': 'Dieser Teil ist noch in Arbeit. Alle fertigen Teile finden Sie in der Kursübersicht.',
  'as.etappe': 'Diese Etappe',
  'kk.title': 'Ihre Teil-Karte',
  'kk.lead': 'Jeder Teil der Prüfung {exam}: was Sie in {level} geübt haben und wo er weitergeht. Keine Gesamtpunktzahl und keine Bestehensgrenze.',
  'kk.miniature': 'im Kleinen geübt',
  'kk.full': 'in voller Länge geübt (Lernmodus)',
  'kk.open': 'noch offen',
  'kk.next': 'kommt in {level}, Kapitel {n}',
  'kk.nextLevel': 'kommt in {level}',

  'welcome.title': 'Willkommen im Kurs {code}',
  'welcome.stepOf': 'Schritt {n} von {t}',
  'welcome.skip': 'Überspringen',
  'welcome.next': 'Weiter',
  'welcome.go': 'Los geht’s',
  'welcome.outcomes': 'Das lernen Sie in {code}',
  'welcome.chapters': '{n} Kapitel',
  'welcome.chapterOne': '1 Kapitel',
  'welcome.modules': '{n} Module',
  'welcome.moduleOne': '1 Modul',
  'finish.courseTitle': '{code} geschafft!',
  'finish.courseBody': 'Alle {n} Kapitel und der Abschlusstest sind geschafft.',
  'finish.nextNotYet': '{next} ist noch nicht freigeschaltet. Bis dahin können Sie jedes Kapitel wiederholen und jedes Wort in der Wortliste nachschlagen.',
  'finish.chaptersTitle': 'Alle {n} Kapitel geschafft!',
  'finish.closingLeft': 'Jetzt fehlt nur noch der Abschlusstest – jeder Prüfungsteil im Kleinen.',
  'finish.closingSoon': 'Der Abschlusstest kommt bald. Bis dahin können Sie jedes Kapitel wiederholen und jedes Wort in der Wortliste nachschlagen.',
  'finish.resumeClosing': 'Weiter mit dem Abschlusstest',
  'finish.toWords': 'Zur Wortliste',
  'welcome.finalTest': 'Abschlusstest',
  'welcome.free': 'Kostenlos',
  'welcome.lane': 'Auf dem Weg zum {exam}',
  'welcome.tempo': 'Wie viel Zeit haben Sie pro Tag?',
  'welcome.tempoLegend': 'Ihr Tempo',
  'welcome.paceLeicht': 'Leicht',
  'welcome.paceStandard': 'Standard',
  'welcome.paceIntensiv': 'Intensiv',
  'welcome.minutes': '{n} Minuten',
  'welcome.days': 'an {n} Tagen pro Woche',
  'welcome.finish': 'fertig etwa am {date}',
};

export const V2_STRINGS = { en: EN, de: DE };

/** One chrome string in `lang` ('en' | 'de'), `{name}` placeholders filled from `vars`. */
export function tv(key, lang = 'en', vars = null) {
  const table = V2_STRINGS[lang] || EN;
  let s = table[key] ?? EN[key] ?? key;
  if (vars) {
    for (const [k, v] of Object.entries(vars)) s = s.split(`{${k}}`).join(String(v));
  }
  return s;
}

/** [lang, t] — the chrome language and a bound translator. */
export function useV2Strings() {
  const [lang] = useLessonLang();
  const t = (key, vars) => tv(key, lang, vars);
  return [lang, t];
}

/** The explanation in the chrome language plus its twin (LText = { de, en }). */
export function ltext(value, lang) {
  if (!value) return { main: null, other: null };
  if (typeof value === 'string') return { main: value, other: null };
  const de = value.de || null;
  const en = value.en || null;
  return lang === 'de' ? { main: de || en, other: de ? en : null } : { main: en || de, other: en ? de : null };
}
