# -*- coding: utf-8 -*-
"""Build S/wave4/listening/questions-a2.1-additions.json (78 rows, q11-23 on 6 exercises)."""
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))
EX = {
    1: "1c6c1cec-b3ef-45cb-a7e6-51b9d16956e0",
    2: "369a41e4-edb8-4f7a-bda8-20a54fcfb11d",
    3: "d1552ee8-0a2e-4bf5-8f18-39da155f42dd",
    4: "fbd6e61e-b9a8-4a6d-bdff-ad3366b95a50",
    5: "7cb40bfe-01b4-4634-9953-897c0776fd4b",
    6: "e2266843-2135-4a89-ab44-dde935e31595",
}

def mc(d, n, text, opts, key, expl):
    return dict(dialogue_number=d, question_number=n, question_text=text,
                question_type="multiple_choice", options=opts, correct_answer=key,
                acceptable_answers=None, explanation=expl)

def rf(d, n, text, key, expl):
    return dict(dialogue_number=d, question_number=n, question_text=text,
                question_type="richtig_falsch", options=["Richtig", "Falsch"],
                correct_answer=key, acceptable_answers=None, explanation=expl)

def di(d, n, text, ans, acc, expl):
    return dict(dialogue_number=d, question_number=n, question_text=text,
                question_type="dictation", options=None, correct_answer=ans,
                acceptable_answers=acc, explanation=expl)

DATA = {}

DATA[1] = [
    mc(1, 11, "Was verschreibt die Ärztin gegen die Erkältung?",
       ["a) Nasenspray und Schmerztabletten", "b) Ein Antibiotikum", "c) Nasentropfen und Tee"], "a",
       'Die Ärztin sagt "Ich verschreibe Ihnen Nasenspray und Schmerztabletten".'),
    rf(2, 12, "Der Mann mit den Rückenschmerzen arbeitet am Computer.", "Richtig",
       'Er sagt "ich arbeite den ganzen Tag am Computer".'),
    mc(3, 13, "Wann niest der Patient besonders oft?",
       ["a) Nur im Winter", "b) Das ganze Jahr", "c) Im Frühling und Sommer"], "c",
       'Er sagt "Hauptsächlich im Frühling und Sommer".'),
    rf(4, 14, "Der Patient mit dem hohen Blutdruck bekommt sofort Medikamente.", "Falsch",
       'Die Ärztin sagt "Noch nicht".'),
    mc(5, 15, "In welchen Arm bekommt der Mann die Impfung?",
       ["a) Ins Bein", "b) In den linken Oberarm", "c) In den rechten Oberarm"], "b",
       'Die Ärztin sagt "Die Impfung ist in den linken Oberarm".'),
    rf(6, 16, "Die Frau war am Samstag im Restaurant.", "Falsch",
       'Sie sagt "Am Sonntag war ich in einem Restaurant".'),
    mc(7, 17, "Wann soll der Mann zur Blutabnahme kommen?",
       ["a) Nächste Woche", "b) Heute", "c) In drei Monaten"], "a",
       'Die Ärztin sagt "kommen Sie nächste Woche nüchtern zur Blutabnahme".'),
    rf(8, 18, "Der kranke Sohn hat auch Halsschmerzen.", "Richtig",
       'Die Mutter sagt "Er hat auch Halsschmerzen".'),
    mc(9, 19, "Wo ist die Radiologie?",
       ["a) Im ersten Stock", "b) Im Keller", "c) Im Erdgeschoss"], "c",
       'Die Ärztin sagt "Im Erdgeschoss".'),
    rf(10, 20, "Die Frau nimmt fast jeden Tag Schmerzmittel.", "Richtig",
       'Sie sagt "Ja, fast jeden Tag".'),
    di(8, 21, "Wie hoch ist das Fieber von ihrem Sohn? Schreiben Sie die Zahl.", "39,8",
       ["39,8", "39.8", "39,8 Grad", "39.8 Grad", "39,8 °C",
        "neununddreißig Komma acht", "neununddreißig Komma acht Grad"],
       'Die Mutter sagt "Neununddreißig Komma acht".'),
    di(2, 22, "Wie oft darf der Mann die Tabletten pro Tag nehmen?", "dreimal",
       ["dreimal", "3", "drei", "3x", "3 x", "3 mal", "3-mal", "drei Mal", "3x täglich",
        "3 mal täglich", "dreimal täglich", "dreimal am Tag", "maximal dreimal"],
       'Die Ärztin sagt "Nehmen Sie diese Tabletten, maximal dreimal täglich".'),
    di(4, 23, "In wie vielen Wochen kommt der Mann zur Kontrolle?", "4",
       ["4", "4 Wochen", "vier", "vier Wochen", "in 4 Wochen", "in vier Wochen"],
       'Die Ärztin sagt "Kommen Sie in vier Wochen wieder zur Kontrolle".'),
]

DATA[2] = [
    mc(1, 11, "Für wie viele Personen braucht der Gast einen Tisch?",
       ["a) Für zwei Personen", "b) Für vier Personen", "c) Für sechs Personen"], "b",
       'Er fragt "haben Sie einen Tisch für vier Personen?".'),
    rf(2, 12, "Das Tagesgericht ist Hähnchen mit Kartoffeln.", "Falsch",
       'Der Kellner sagt "Heute haben wir Lachsfilet mit Kartoffeln und Gemüse".'),
    mc(3, 13, "Was ist in der Gemüselasagne?",
       ["a) Zucchini, Auberginen und Tomaten", "b) Fleisch und Reis", "c) Kokosmilch und Curry"], "a",
       'Die Kellnerin sagt "Mit Zucchini, Auberginen und Tomaten".'),
    rf(4, 14, "Der Kellner notiert die Allergie für die Küche.", "Richtig",
       'Er sagt "Ich notiere das für die Küche".'),
    mc(5, 15, "Wie lange muss der Gast auf das Steak warten?",
       ["a) Fünf Minuten", "b) Zwanzig Minuten", "c) Etwa zehn Minuten"], "c",
       'Die Kellnerin sagt "Es dauert etwa zehn Minuten".'),
    rf(6, 16, "Der Kellner empfiehlt einen schweren Weißwein.", "Falsch",
       'Er sagt "Dann empfehle ich einen leichten Rotwein".'),
    mc(7, 17, "Was bestellt die Frau für ihren Mann?",
       ["a) Schokoladenkuchen", "b) Tiramisu", "c) Nur einen Espresso"], "b",
       'Sie sagt "Und für meinen Mann das Tiramisu".'),
    rf(8, 18, "Der Gast nimmt den Rest nicht mit.", "Falsch",
       'Der Kellner sagt "Ich packe es Ihnen ein".'),
    mc(9, 19, "Wie möchte der zweite Gast bezahlen?",
       ["a) Mit Karte", "b) Bar", "c) Zusammen mit dem Mann"], "a",
       'Der Gast fragt "Kann ich mit Karte zahlen?".'),
    rf(10, 20, "Dem Gast hat besonders der Fisch geschmeckt.", "Richtig",
       'Er sagt "Besonders der Fisch war perfekt".'),
    di(9, 21, "Wie viel kostet die Pasta mit dem Wein?", "22",
       ["22", "22 €", "22 Euro", "22,00", "22,00 Euro", "zweiundzwanzig", "zweiundzwanzig Euro"],
       'Die Kellnerin sagt "Das macht zweiundzwanzig Euro".'),
    di(7, 22, "Wie viele Espresso bestellt die Frau?", "2",
       ["2", "zwei", "2 Espresso", "zwei Espresso", "zwei Stück"],
       'Sie sagt "Ja, zwei Espresso bitte".'),
    di(6, 23, "Wie heißt der Wein aus der Pfalz?", "Spätburgunder",
       ["Spätburgunder", "Spaetburgunder", "Der Spätburgunder"],
       'Der Kellner sagt "Der Spätburgunder aus der Pfalz ist sehr gut".'),
]

DATA[3] = [
    mc(1, 11, "Wie viel kostet die Fahrkarte nach Frankfurt?",
       ["a) 29 Euro", "b) 49 Euro", "c) 39 Euro"], "c",
       'Die Frau sagt "Die Fahrkarte kostet neununddreißig Euro".'),
    rf(2, 12, "Der Zug nach München fährt ohne Umsteigen.", "Richtig",
       'Der Mann sagt "das ist eine Direktverbindung".'),
    mc(3, 13, "Was kostet ein Koffer extra?",
       ["a) 23 Euro", "b) 25 Euro", "c) 15 Euro"], "b",
       'Die Mitarbeiterin sagt "ein Koffer bis dreiundzwanzig Kilo kostet fünfundzwanzig Euro extra".'),
    rf(4, 14, "Das Servicecenter ist neben dem Kiosk.", "Falsch",
       'Die Frau sagt "Gleich hier vorne links, neben der Buchhandlung".'),
    mc(5, 15, "Für wie viele Tage bekommt Herr Müller das Auto?",
       ["a) Für fünf Tage", "b) Für drei Tage", "c) Für zehn Tage"], "a",
       'Die Mitarbeiterin sagt "Ein VW Golf für fünf Tage".'),
    rf(6, 16, "Die Fahrt zum Flughafen dauert etwa vierzig Minuten.", "Richtig",
       'Der Mann sagt "Ungefähr vierzig Minuten".'),
    mc(7, 17, "In welchem Wagen reserviert der Mann einen Platz?",
       ["a) Im Abteil", "b) Im Speisewagen", "c) Im Großraumwagen"], "c",
       'Er sagt "Großraumwagen ist okay".'),
    rf(8, 18, "Die Frau bekommt einen Platz in Reihe zwanzig.", "Falsch",
       'Der Mitarbeiter sagt "Reihe zwölf ist noch frei".'),
    mc(9, 19, "Wo wartet der Mann auf das Taxi?",
       ["a) Am Hauptbahnhof", "b) Im Hotel Kaiserhof", "c) In der Bahnhofstraße"], "b",
       'Er sagt "Hotel Kaiserhof, Berliner Straße fünfzehn".'),
    rf(10, 20, "Der Flug nach Rom dauert zwei Stunden.", "Falsch",
       'Die Durchsage sagt "eine Stunde und fünfundvierzig Minuten".'),
    di(2, 21, "Wann fährt der erste ICE nach München?", "5:53",
       ["5:53", "05:53", "5.53", "5:53 Uhr", "5 Uhr 53", "fünf Uhr dreiundfünfzig",
        "um fünf Uhr dreiundfünfzig"],
       'Der Mann sagt "Der erste ICE fährt um fünf Uhr dreiundfünfzig".'),
    di(7, 22, "Welchen Platz bekommt der Mann im Zug?", "42",
       ["42", "Platz 42", "Sitzplatz 42", "zweiundvierzig", "Platz zweiundvierzig"],
       'Die Mitarbeiterin sagt "Ich habe Wagen sieben, Platz zweiundvierzig".'),
    di(3, 23, "Wann geht der Flug nach Barcelona? Schreiben Sie die Uhrzeit.", "9:15",
       ["9:15", "09:15", "9.15", "9:15 Uhr", "9 Uhr 15", "neun Uhr fünfzehn",
        "um neun Uhr fünfzehn"],
       'Die Mitarbeiterin sagt "Ich habe einen Flug um neun Uhr fünfzehn".'),
]

DATA[4] = [
    mc(1, 11, "Wie lange dauert der Haarschnitt für Herren?",
       ["a) Etwa 30 Minuten", "b) Etwa 60 Minuten", "c) Etwa 15 Minuten"], "a",
       'Die Mitarbeiterin sagt "Für Herrenschnitt etwa dreißig Minuten".'),
    rf(2, 12, "Die Frau mit Zahnschmerzen kommt morgen um sechzehn Uhr.", "Falsch",
       'Der Mitarbeiter sagt "Können Sie heute um sechzehn Uhr kommen?".'),
    mc(3, 13, "Warum verschiebt Frau Schmidt den Termin?",
       ["a) Sie ist krank", "b) Sie hat eine Besprechung", "c) Sie ist im Urlaub"], "b",
       'Sie sagt "Ich habe eine wichtige Besprechung".'),
    rf(4, 14, "Die Freunde gehen am Sonntag ins Museum.", "Richtig",
       'Sie sagt "Aber Sonntag geht" und "Wir könnten ins Museum gehen".'),
    mc(5, 15, "An welchem Tag ist der neue Termin?",
       ["a) Am Montag", "b) Am Freitag", "c) Am Mittwoch"], "c",
       'Sie sagt "Mittwoch passt gut".'),
    rf(6, 16, "Die Frau kann das Auto nachmittags abholen.", "Richtig",
       'Der Mitarbeiter sagt "Sie können das Auto morgens bringen und nachmittags abholen".'),
    mc(7, 17, "Wann fängt die Geburtstagsparty an?",
       ["a) Um 20 Uhr", "b) Um 19 Uhr", "c) Um 21 Uhr"], "a",
       'Sie sagt "Um zwanzig Uhr. Bei mir zu Hause".'),
    rf(8, 18, "Die Frau mit der kaputten Heizung arbeitet zu Hause.", "Richtig",
       'Sie sagt "Ich arbeite von zu Hause. Ich bin immer da".'),
    mc(9, 19, "Wie lange können die beiden Tennis spielen?",
       ["a) Zwei Stunden", "b) Eine Stunde", "c) Eine halbe Stunde"], "b",
       'Er sagt "Eine Stunde. Danach ist der Platz leider besetzt".'),
    rf(10, 20, "Der Elternabend ist in der Turnhalle.", "Falsch",
       'Sie sagt "In der Aula".'),
    di(10, 21, "Wann beginnt der Elternabend? Schreiben Sie die Uhrzeit.", "19:30",
       ["19:30", "19.30", "19:30 Uhr", "1930", "19 Uhr 30", "neunzehn Uhr dreißig",
        "um neunzehn Uhr dreißig"],
       'Sie sagt "Um neunzehn Uhr dreißig".'),
    di(8, 22, "In welchem Stock wohnt die Frau? Schreiben Sie die Zahl.", "3",
       ["3", "3.", "drei", "dritter", "dritten", "3. Stock", "3.Stock", "3 Stock",
        "im 3. Stock", "dritter Stock", "im dritten Stock"],
       'Sie sagt "Bachstraße zwölf, dritter Stock".'),
    di(5, 23, "Um wie viel Uhr ist der Termin mit Peter?", "18:00",
       ["18:00", "18.00", "18 Uhr", "18", "um 18 Uhr", "achtzehn", "achtzehn Uhr",
        "um achtzehn Uhr"],
       'Er sagt "Ja, um achtzehn Uhr. Bis dann und alles Gute!".'),
]

DATA[5] = [
    mc(1, 11, "Wie möchte der Mann das Brot haben?",
       ["a) Am Stück", "b) Ohne Kruste", "c) Geschnitten"], "c",
       'Er sagt "Geschnitten, bitte".'),
    rf(2, 12, "Die Tomaten kommen aus der Region.", "Richtig",
       'Die Verkäuferin sagt "Die sind aus der Region, ganz frisch".'),
    mc(3, 13, "Wie lange hält der Akku von den Kopfhörern?",
       ["a) Acht Stunden", "b) Zehn Stunden", "c) Vier Stunden"], "a",
       'Die Verkäuferin sagt "der Akku hält acht Stunden".'),
    rf(4, 14, "Der Mann hat die Hose mit Karte bezahlt.", "Richtig",
       'Er sagt "Mit Karte".'),
    mc(5, 15, "Welcher Autor schreibt Thriller aus Berlin?",
       ["a) Sebastian Schmidt", "b) Sebastian Fitzek", "c) Stefan Fitzek"], "b",
       'Der Verkäufer sagt "das könnte Sebastian Fitzek sein. Er schreibt Thriller, die in Berlin spielen".'),
    rf(6, 16, "Die Sonnencreme steht in Gang fünf.", "Falsch",
       'Die Verkäuferin sagt "Die Sonnenpflege ist in Gang drei, links".'),
    mc(7, 17, "Welche Blumen mag die Mutter am liebsten?",
       ["a) Rosen in Gelb", "b) Rosen in Weiß", "c) Rosen in Rosa"], "c",
       'Der Sohn sagt "Sie liebt Rosen. Am liebsten in Rosa".'),
    rf(8, 18, "Der Mann läuft zwanzig Kilometer pro Woche.", "Falsch",
       'Er sagt "Im Moment etwa vierzig Kilometer".'),
    mc(9, 19, "Wann hat die Frau den Föhn gekauft?",
       ["a) Vor zwei Wochen", "b) Vor zwei Monaten", "c) Vor einem Jahr"], "a",
       'Sie sagt "Ich habe ihn erst vor zwei Wochen gekauft".'),
    rf(10, 20, "Der Kunde kann die Sachen im Geschäft anprobieren.", "Richtig",
       'Die Verkäuferin sagt "Möchten Sie alles anprobieren? Die Kabinen sind dort hinten".'),
    di(8, 21, "Welche Schuhgröße hat der Mann? Schreiben Sie die Zahl.", "43",
       ["43", "Größe 43", "Schuhgröße 43", "dreiundvierzig", "Größe dreiundvierzig"],
       'Er sagt "Dreiundvierzig".'),
    di(2, 22, "Wie viel bezahlt der Mann auf dem Wochenmarkt?", "5,49",
       ["5,49", "5.49", "5,49 €", "5,49 Euro", "5 Euro 49", "fünf Euro neunundvierzig"],
       'Die Verkäuferin sagt "Das macht dann fünf Euro neunundvierzig zusammen".'),
    di(1, 23, "Wie viele Brötchen kauft der Mann? Schreiben Sie die Zahl.", "4",
       ["4", "vier", "4 Brötchen", "vier Brötchen", "4 Stück", "vier Stück"],
       'Er sagt "Ich hätte gerne vier Brötchen und ein Vollkornbrot".'),
]

DATA[6] = [
    mc(1, 11, "Wie hoch sind die Temperaturen heute?",
       ["a) Zwanzig Grad", "b) Fünfzehn Grad", "c) Zehn Grad"], "b",
       'Die Sprecherin sagt "Die Temperaturen liegen bei maximal fünfzehn Grad".'),
    rf(2, 12, "Der Grund für die Verspätung ist ein Unfall.", "Falsch",
       'Die Durchsage sagt "Grund ist eine technische Störung".'),
    mc(3, 13, "Wie viel Rabatt gibt es auf Tiefkühlpizzen?",
       ["a) 20 Prozent", "b) 30 Prozent", "c) 50 Prozent"], "c",
       'Der Sprecher sagt "alle Tiefkühlpizzen sind heute fünfzig Prozent reduziert".'),
    rf(4, 14, "Das Boarding nach Barcelona endet in zehn Minuten.", "Falsch",
       'Die Durchsage sagt "Das Boarding endet in fünf Minuten".'),
    mc(5, 15, "Wie lange dauert die Verzögerung auf der A3?",
       ["a) 30 Minuten", "b) 15 Minuten", "c) 45 Minuten"], "a",
       'Der Sprecher sagt "Autofahrer müssen mit dreißig Minuten Verzögerung rechnen".'),
    rf(6, 16, "Die Führung im Museum kostet nichts.", "Richtig",
       'Die Durchsage sagt "in fünfzehn Minuten beginnt unsere kostenlose Führung".'),
    mc(3, 17, "Wie lange gelten die Angebote im Supermarkt?",
       ["a) Bis Freitag", "b) Nur heute", "c) Die ganze Woche"], "b",
       'Der Sprecher sagt "Die Angebote gelten nur heute und nur solange der Vorrat reicht".'),
    rf(8, 18, "Im Kino muss man das Handy ausschalten.", "Richtig",
       'Die Durchsage sagt "dass während des Films Handys ausgeschaltet sein müssen".'),
    mc(9, 19, "Wer hat das Tor für Dortmund geschossen?",
       ["a) Müller", "b) Sané", "c) Reus"], "c",
       'Der Sprecher sagt "Dortmund traf in der achtzigsten Minute durch Reus".'),
    rf(10, 20, "Der Eintritt beim Stadtfest kostet zehn Euro.", "Falsch",
       'Die Sprecherin sagt "Der Eintritt ist frei".'),
    di(7, 21, "Wann beginnt die Sprechzeit am Morgen? Schreiben Sie die Uhrzeit.", "8:00",
       ["8:00", "08:00", "8.00", "8 Uhr", "8", "um 8 Uhr", "acht", "acht Uhr", "um acht Uhr"],
       'Die Ansage sagt "Montag bis Freitag von acht bis zwölf Uhr".'),
    di(7, 22, "Wann beginnt die Sprechzeit am Nachmittag? Schreiben Sie die Uhrzeit.", "15:00",
       ["15:00", "15.00", "15 Uhr", "15", "um 15 Uhr", "fünfzehn", "fünfzehn Uhr",
        "um fünfzehn Uhr"],
       'Die Ansage sagt "zusätzlich von fünfzehn bis achtzehn Uhr".'),
    di(5, 23, "Auf welcher Autobahn gibt es keinen Stau mehr?", "A1",
       ["A1", "A 1", "A-1", "A eins", "Autobahn 1"],
       'Der Sprecher sagt "Auf der A eins Richtung Dortmund fließt der Verkehr wieder normal".'),
]

rows = []
for n in sorted(DATA):
    for r in DATA[n]:
        rows.append(dict(exercise_id=EX[n], exercise_number=n, **r))

out = os.path.join(HERE, "questions-a2.1-additions.json")
with open(out, "w", encoding="utf-8") as f:
    json.dump(rows, f, ensure_ascii=False, indent=2)
    f.write("\n")
print("wrote", len(rows), "rows ->", out)
