// Course v2 compiler v0 — deterministic, idempotent (SCHEMA §13).
//
// For one level it reads content/course-v2/** (registries shared, the level's own files) and
// produces, after a clean SCH-01/REF-01/KEY-01 check:
//
//   <out>/<level>/units/uNN.json      the unit chunk the player lazy-loads: learner-invisible fields
//                                     stripped, generated fields added (poolItems in the live
//                                     lessonPools shape, generated-item ids, line seconds,
//                                     minutesPlanned, reviewCards, contentHash)
//   <out>/<level>/plateaus/pN.json, closing/<id>.json   the same treatment for Plateau/closing files
//   <out>/<level>/manifest.json       course manifest: units with titles, can-dos, grammar, Prüfungsfokus,
//                                     minutes and counts (syllabus rows), Etappen, completion, review,
//                                     pace, counts for copy, contentHash
//   <out>/<level>/ids.ledger.json     every live id of the level + tombstones of removed ids (ID-01)
//   <banks>/<level>.banks.json        writing + speaking bank: every WritingTask / SpeakingTask /
//                                     MicroOutput keyed by bankKey (grader input only)
//
// Nothing here reads a clock, the environment or the network: the same content gives the same bytes.
import fs from 'node:fs';
import path from 'node:path';
import { loadTree, rel, REPO_ROOT } from './tree.mjs';
import { buildIndex } from './refindex.mjs';
import { checkLoaded } from './checker.mjs';
import { formatError } from './schema.mjs';
import { contentHash } from './hash.mjs';
import { PATTERNS, LANE_EXAM_KEY, prefixOfLevel } from './ids.mjs';

export const GENERATED_MARK = 'generated by scripts/course-v2/compile.mjs from content/course-v2 — do not edit';
export const DEFAULT_OUT = path.join(REPO_ROOT, 'src/data/course-v2');
export const DEFAULT_BANKS = path.join(REPO_ROOT, 'netlify/functions/_shared/course-v2');

const MODULE_LABEL = { hoeren: 'Hören', lesen: 'Lesen', sprachbausteine: 'Sprachbausteine', schreiben: 'Schreiben', sprechen: 'Sprechen' };
// Fields no learner sees: reviewer rationale, authoring provenance, validator flags.
const STRIP_ITEM_KEYS = ['origin', 'reviewerConfirmed', 'acceptedWhy', 'intentionalError', 'perceptionOnly'];
const STRIP_SPEC_KEYS = ['lehrwerk', 'deviation', 'source'];
const STRIP_TOP_KEYS = ['$schema', 'version', 'status', 'reviewedIn'];
const WORDS_PER_SECOND = 2.5; // line-length estimate (150 words/min) until the audio run measures it

const json = (x) => `${JSON.stringify(x, null, 2)}\n`;
const round1 = (x) => Math.round(x * 10) / 10;
const pad2 = (n) => String(n).padStart(2, '0');
const isObj = (x) => x !== null && typeof x === 'object' && !Array.isArray(x);
const isItem = (x) => isObj(x) && typeof x.id === 'string' && typeof x.type === 'string' && typeof x.role === 'string' && PATTERNS.item.test(x.id);
const isLine = (x) => isObj(x) && typeof x.id === 'string' && typeof x.speaker === 'string' && PATTERNS.line.test(x.id);

function levelOfDoc({ doc, kind }) {
  if (!doc) return null;
  switch (kind) {
    case 'course':
    case 'unit':
    case 'lexicon':
    case 'rulecards':
    case 'plateau':
    case 'closing':
    case 'mockmodule':
      return typeof doc.level === 'string' ? doc.level : null;
    case 'lanepack':
      return typeof doc.unit === 'string' ? doc.unit.split('-')[0] : null;
    default:
      return null; // registries, casts, stubs: shared by every level
  }
}

/** Visit every object/array in document order. */
function eachNode(root, fn) {
  const visit = (x, parent) => {
    if (Array.isArray(x)) {
      x.forEach((y) => visit(y, x));
      return;
    }
    if (!isObj(x)) return;
    fn(x, parent);
    for (const v of Object.values(x)) visit(v, x);
  };
  visit(root, null);
}

// ── pool shape (SCHEMA §3.1, last paragraph) ────────────────────────────────────────────
/** An authored Item in the live lessonPools shape read by check.js, requeue.js, mastery.js, reviewGrading. */
export function toPoolItem(item, minLektion) {
  const questionDe =
    item.type === 'sentence_building' && Array.isArray(item.tiles)
      ? `${item.promptDe.replace(/\.$/, ':')} [${item.tiles.join(' / ')}]`
      : item.promptDe;
  const out = {
    id: item.id,
    topic: item.topic,
    type: item.type,
    questionDe,
    questionEn: item.promptEn ?? null,
    options: item.options ?? null,
    answer: item.answer,
    accepted: item.accepted,
    caseSensitive: item.caseSensitive === true,
    explanationDe: item.explanation.de,
    explanationEn: item.explanation.en,
    hint: item.hint ? item.hint.de : null,
    minLektion,
  };
  if (item.exact) out.exact = item.exact; // passed to checkAnswer() by checkOptionsFor() once E1 extends it
  // renderer inputs of the new item types, carried only when the item has them
  for (const k of ['pairs', 'audioLineRef', 'textRef', 'noMatch']) if (item[k] !== undefined) out[k] = item[k];
  return out;
}

// ── generated ids, stripping, line seconds ──────────────────────────────────────────────
/** Give every GeneratorSpec of a step its compiler-assigned item ids (STEP-gNN, in document order). */
function assignGeneratedIds(step) {
  let n = 0;
  const assigned = [];
  eachNode(step, (x) => {
    if (typeof x.generator === 'string' && Number.isInteger(x.count)) {
      x.ids = [];
      for (let i = 0; i < x.count; i++) x.ids.push(`${step.id}-g${pad2(++n)}`);
      assigned.push(...x.ids);
    }
  });
  return assigned;
}

function estimateSeconds(line) {
  const words = String(line.say || line.de).trim().split(/\s+/).filter(Boolean).length;
  return round1(words / WORDS_PER_SECOND);
}

/** Learner-facing copy of an authored file (deep clone; the input is not touched). */
function learnerCopy(doc) {
  const c = structuredClone(doc);
  for (const k of STRIP_TOP_KEYS) delete c[k];
  if (isObj(c.spec)) for (const k of STRIP_SPEC_KEYS) delete c.spec[k];
  eachNode(c, (x) => {
    if (isItem(x)) for (const k of STRIP_ITEM_KEYS) delete x[k];
    if (isLine(x) && x.seconds === undefined) x.seconds = estimateSeconds(x);
    if (typeof x.claimDe === 'string' && PATTERNS.fact.test(x.id || '')) delete x.notes;
  });
  return c;
}

// ── ids (ID-01 ledger) ──────────────────────────────────────────────────────────────────
const ID_KINDS = ['UNIT', 'STEP', 'item', 'line', 'block', 'mo', 'rm', 'fact', 'fokus', 'plateau'];
function collectIds(doc, into, errors, where) {
  const add = (id, kind) => {
    if (into.has(id)) errors.push(`${where}: ID-01 duplicate id "${id}" (also ${into.get(id).where})`);
    else into.set(id, { kind, where });
  };
  eachNode(doc, (x) => {
    if (typeof x.id === 'string') {
      const kind = ID_KINDS.find((k) => PATTERNS[k].test(x.id));
      if (kind) add(x.id, kind === 'UNIT' ? 'unit' : kind === 'STEP' ? 'step' : kind);
    }
    if (Array.isArray(x.ids) && typeof x.generator === 'string') x.ids.forEach((id) => add(id, 'item-generated'));
  });
}

// ── banks ───────────────────────────────────────────────────────────────────────────────
function withHash(entry) {
  return { ...entry, contentHash: contentHash(entry) };
}
const pick = (src, keys) => {
  const o = {};
  for (const k of keys) if (src[k] !== undefined) o[k] = src[k];
  return o;
};

function writingEntry(t, level, owner) {
  return withHash({
    level,
    ...owner,
    lane: t.lane,
    template: t.template,
    examKey: t.examKey,
    profile: t.profile,
    register: t.register,
    address: t.address,
    situationDe: t.situationDe,
    taskDe: t.taskDe,
    leitpunkte: t.leitpunkte.map((lp) => ({ id: lp.id, de: lp.de })), // cues stay in the unit chunk
    ...pick(t, ['choose']),
    wordBand: t.wordBand,
    ...pick(t, ['wordBandLearning']),
    minSubmitWords: t.minSubmitWords,
  });
}

function speakingEntry(t, level, owner) {
  return withHash({
    level,
    ...owner,
    lane: t.lane,
    template: t.template,
    examKey: LANE_EXAM_KEY[t.lane] || null,
    mode: t.mode,
    profile: t.profile,
    prepMinutes: t.prepMinutes,
    instructionsDe: t.instructionsDe,
    ...pick(t, ['situationDe', 'cards', 'slides']),
    moves: t.moves,
    ...pick(t, ['planningRound']),
    aiRole: t.aiRole,
    openingLine: t.openingLine,
    hintWords: t.hintWords,
  });
}

function microEntry(m, level, owner) {
  return withHash({
    level,
    ...owner,
    lane: null,
    profile: m.profile,
    mode: m.mode,
    register: m.register,
    ...pick(m, ['situationDe']),
    promptDe: m.promptDe,
    ...(m.mode === 'spoken' ? pick(m, ['planSeconds', 'seconds']) : pick(m, ['words'])),
    targets: m.targets,
  });
}

/** Every bankable task of an authored document, classified. */
function collectBankTasks(doc) {
  const out = [];
  eachNode(doc, (x) => {
    if (typeof x.bankKey !== 'string') return;
    if (typeof x.taskDe === 'string') out.push({ kind: 'writing', task: x });
    else if (isObj(x.aiRole)) out.push({ kind: 'speaking', task: x });
    else if (x.mode === 'written' || x.mode === 'spoken') out.push({ kind: x.mode === 'written' ? 'micro-writing' : 'micro-speaking', task: x });
  });
  return out;
}

// ── labels ──────────────────────────────────────────────────────────────────────────────
function teilLabel(templateId, lanes) {
  const [laneId, teil] = templateId.split('.');
  const lane = lanes.get(laneId);
  const t = lane && lane.teile ? lane.teile[teil] : null;
  if (!t || !MODULE_LABEL[t.module]) return templateId;
  const order = lane.modules && lane.modules[t.module] && Array.isArray(lane.modules[t.module].teile) ? lane.modules[t.module].teile : [];
  const idx = order.indexOf(teil);
  const nr = idx >= 0 ? idx + 1 : Number((teil.match(/\d+/) || [])[0]) || null;
  return nr ? `${MODULE_LABEL[t.module]} Teil ${nr}` : MODULE_LABEL[t.module];
}

// ── review cards (SCHEMA §2 keys) ───────────────────────────────────────────────────────
function reviewCardsOf(u) {
  const cards = [];
  for (const b of u.spec?.lexiconBlocks || []) for (const lx of b.lemmas || []) cards.push(`word:${lx}`);
  for (const g of u.spec?.grammar?.new || []) cards.push(`pattern:${g}:${u.id}`);
  for (const rm of u.redemittel || []) cards.push(`sentence:${rm.id}`);
  return cards;
}

// ── minutes (design values until the time model / minutesMeasured exist) ────────────────
function minutesOf(u, profile) {
  if (!profile) return null;
  const kinds = Array.isArray(u.steps) ? u.steps.map((s) => s.kind) : profile.steps;
  const byStep = {};
  let total = 0;
  kinds.forEach((kind, i) => {
    const m = Number.isInteger(profile.minutes[kind]) ? profile.minutes[kind] : 0;
    total += m;
    if (Array.isArray(u.steps)) byStep[u.steps[i].id] = m;
  });
  return { total, byStep: Array.isArray(u.steps) ? byStep : null, source: 'level-profile design minutes per step kind' };
}

// ── the level ───────────────────────────────────────────────────────────────────────────
/**
 * Compile one level. Returns { outputs: [{ file, text }], syncDirs: [dir], errors: [str], warnings: [str] }.
 * Nothing is written; see writeOutputs().
 */
export function compileLevel(level, { contentRoot, exclude = [], outRoot = DEFAULT_OUT, banksRoot = DEFAULT_BANKS, refs = true } = {}) {
  const errors = [];
  const warnings = [];
  const tree = loadTree(contentRoot, { exclude });
  const index = buildIndex(tree.filter((t) => !t.error));
  for (const t of tree) {
    const lv = levelOfDoc(t);
    if (!t.error && lv !== null && lv !== level) continue; // another level's content: indexed, not compiled
    for (const e of checkLoaded(t, index, { refs })) errors.push(formatError(rel(t.file), e));
  }
  if (errors.length) return { outputs: [], syncDirs: [], errors, warnings };

  const docs = (kind) => tree.filter((t) => t.kind === kind);
  const mine = (kind) => docs(kind).filter((t) => levelOfDoc(t) === level);
  const courses = mine('course');
  if (courses.length !== 1) {
    errors.push(courses.length ? `${level}: ${courses.length} course.json files (${courses.map((c) => rel(c.file)).join(', ')})` : `${level}: no course.json (course-v2/course@1) found`);
    return { outputs: [], syncDirs: [], errors, warnings };
  }
  const course = courses[0].doc;
  const prefix = prefixOfLevel(level);
  const profile = docs('levels').flatMap((t) => t.doc.levels).find((l) => l.level === level) || null;
  if (!profile) warnings.push(`${level}: no level profile — minutesPlanned is null`);
  const lexicon = mine('lexicon')[0]?.doc || null;
  const ruleCards = mine('rulecards')[0]?.doc || null;
  const candoText = new Map(docs('cando').flatMap((t) => t.doc.items.map((i) => [i.id, i.de])));
  const spineLabel = new Map(docs('spine').flatMap((t) => t.doc.points.map((p) => [p.id, p.label])));
  const lanes = new Map(docs('lane').map((t) => [t.doc.id, t.doc]));
  const live = new Set(course.lanes.live);

  const units = mine('unit').sort((a, b) => a.doc.nr - b.doc.nr);
  const seenNr = new Map();
  for (const u of units) {
    if (seenNr.has(u.doc.nr)) errors.push(`${rel(u.file)}: unit nr ${u.doc.nr} also in ${rel(seenNr.get(u.doc.nr))}`);
    seenNr.set(u.doc.nr, u.file);
    if (!course.units.includes(u.doc.id)) errors.push(`${rel(u.file)}: unit ${u.doc.id} is not listed in ${level}/course.json`);
  }
  const packsByUnit = new Map();
  for (const p of mine('lanepack')) {
    if (!packsByUnit.has(p.doc.unit)) packsByUnit.set(p.doc.unit, []);
    packsByUnit.get(p.doc.unit).push(p);
  }

  const outputs = [];
  const levelOut = path.join(outRoot, level);
  const ids = new Map();
  const bank = { writing: new Map(), speaking: new Map() };
  const addBank = (tasks, owner, file) => {
    for (const { kind, task } of tasks) {
      if (!task.bankKey.startsWith(`${prefix}-`)) {
        errors.push(`${rel(file)}: KEY-01 bank key "${task.bankKey}" does not belong to course prefix "${prefix}"`);
        continue;
      }
      const target = kind === 'writing' || kind === 'micro-writing' ? bank.writing : bank.speaking;
      if (bank.writing.has(task.bankKey) || bank.speaking.has(task.bankKey)) {
        errors.push(`${rel(file)}: KEY-01 duplicate bank key "${task.bankKey}"`);
        continue;
      }
      const entry =
        kind === 'writing' ? writingEntry(task, level, owner)
          : kind === 'speaking' ? speakingEntry(task, level, owner)
            : microEntry(task, level, owner);
      target.set(task.bankKey, entry);
    }
  };

  const rows = [];
  const unitHashes = {};
  const totals = { lernschritte: 0, items: 0, generatedItems: 0, examBlocks: 0, writingTasks: 0, speakingTasks: 0, microOutputs: 0, redemittel: 0, audioLines: 0, reviewCards: 0 };
  const rowById = new Map();

  for (const { file, doc: u } of units) {
    const hash = contentHash(u);
    unitHashes[u.id] = hash;
    const chunk = learnerCopy(u);
    const generated = [];
    if (Array.isArray(chunk.steps)) for (const s of chunk.steps) generated.push(...assignGeneratedIds(s));
    collectIds({ ...u, steps: chunk.steps || u.steps }, ids, errors, rel(file));

    const poolItems = [];
    eachNode(u, (x) => {
      if (isItem(x)) poolItems.push(toPoolItem(x, u.nr));
    });
    const lines = [];
    eachNode(u, (x) => {
      if (isLine(x)) lines.push(x);
    });
    const tasks = collectBankTasks(u);
    addBank(tasks, { unit: u.id }, file);

    const packs = (packsByUnit.get(u.id) || []).filter((p) => live.has(p.doc.lane)).sort((a, b) => a.doc.lane.localeCompare(b.doc.lane));
    for (const p of packs) {
      addBank(collectBankTasks(p.doc), { unit: u.id }, p.file);
      collectIds(p.doc, ids, errors, rel(p.file));
      eachNode(p.doc, (x) => {
        if (isItem(x)) poolItems.push(toPoolItem(x, u.nr));
      });
    }

    const minutesPlanned = minutesOf(u, profile);
    const reviewCards = reviewCardsOf(u);
    const hasContent = Array.isArray(u.steps);
    const counts = {
      lernschritte: hasContent ? u.steps.length : 0,
      items: poolItems.length,
      generatedItems: generated.length,
      examBlocks: hasContent ? u.steps.filter((s) => s.kind === 'pruefung').reduce((n, s) => n + s.blocks.length, 0) : 0,
      writingTasks: tasks.filter((t) => t.kind === 'writing').length,
      speakingTasks: tasks.filter((t) => t.kind === 'speaking').length,
      microOutputs: tasks.filter((t) => t.kind.startsWith('micro')).length,
      newWords: (u.spec.lexiconBlocks || []).reduce((n, b) => n + b.lemmas.length, 0),
      redemittel: Array.isArray(u.redemittel) ? u.redemittel.length : 0,
      audioLines: lines.length,
      reviewCards: reviewCards.length,
    };
    for (const k of Object.keys(totals)) totals[k] += counts[k];

    if (hasContent) {
      const out = { $generated: GENERATED_MARK, ...chunk };
      if (packs.length) out.lanePacks = Object.fromEntries(packs.map((p) => [p.doc.lane, learnerCopy(p.doc).slots]));
      out.poolItems = poolItems;
      out.minutesPlanned = minutesPlanned;
      out.reviewCards = reviewCards;
      out.estimates = { lineSeconds: `words / ${WORDS_PER_SECOND} per second until the audio run measures each line` };
      out.contentHash = hash;
      outputs.push({ file: path.join(levelOut, 'units', `u${pad2(u.nr)}.json`), text: json(out) });
    }

    const pf = {};
    for (const laneId of course.lanes.live) {
      const templates = laneId === u.spec.lanes.primary
        ? u.spec.lanes.pruefungsfokus.map((p) => p.template)
        : (u.spec.lanes.spur && u.spec.lanes.spur[laneId]) || [];
      if (templates.length) pf[laneId] = templates.map((t) => teilLabel(t, lanes));
    }
    const row = {
      unit: u.id,
      nr: u.nr,
      etappe: u.etappe,
      title: u.title.de,
      canDoTitle: u.title.canDo,
      handlungsfeld: u.spec.handlungsfeld,
      canDos: u.spec.canDos.map((id) => {
        if (!candoText.has(id)) warnings.push(`${u.id}: can-do ${id} has no registry text`);
        return candoText.get(id) || id;
      }),
      grammar: u.spec.grammar.new.map((g) => spineLabel.get(g) || g),
      pruefungsfokus: pf,
      minutesPlanned: minutesPlanned ? minutesPlanned.total : null,
      minutesMeasured: null,
      status: u.status,
      canDoIds: u.spec.canDos,
      chunk: hasContent ? `units/u${pad2(u.nr)}.json` : null,
      counts,
    };
    rows.push(row);
    rowById.set(u.id, row);
  }

  // Plateaus and closing blocks: learner copies, their items and tasks.
  const extraHashes = {};
  for (const kind of ['plateau', 'closing']) {
    for (const { file, doc } of mine(kind).sort((a, b) => a.doc.id.localeCompare(b.doc.id))) {
      extraHashes[doc.id] = contentHash(doc);
      collectIds(doc, ids, errors, rel(file));
      addBank(collectBankTasks(doc), { source: doc.id }, file);
      const after = kind === 'plateau' ? Number((doc.after.match(/-u(\d{2})$/) || [])[1]) : 12;
      const poolItems = [];
      eachNode(doc, (x) => {
        if (isItem(x)) poolItems.push(toPoolItem(x, after));
      });
      const out = { $generated: GENERATED_MARK, ...learnerCopy(doc), poolItems, contentHash: extraHashes[doc.id] };
      const name = kind === 'plateau' ? `${doc.id.split('-').pop()}.json` : `${doc.id}.json`;
      outputs.push({ file: path.join(levelOut, kind === 'plateau' ? 'plateaus' : 'closing', name), text: json(out) });
    }
  }
  if (errors.length) return { outputs: [], syncDirs: [], errors, warnings };

  // Manifest (the syllabus rows plus the course-level fields the player and copy read).
  const etappeOf = (id) => (course.etappen.find((e) => e.units.includes(id)) || {}).nr || null;
  const rowsInOrder = course.units.map((id) => rowById.get(id) || {
    unit: id, nr: Number(id.slice(-2)), etappe: etappeOf(id), title: null, canDoTitle: null, handlungsfeld: [], canDos: [],
    grammar: [], pruefungsfokus: {}, minutesPlanned: null, minutesMeasured: null, status: 'missing', canDoIds: [], chunk: null, counts: null,
  });
  const lexEntries = lexicon ? lexicon.entries : [];
  const counts = {
    units: course.units.length,
    unitsWithSpec: rows.length,
    unitsAuthored: rows.filter((r) => r.chunk).length,
    ...totals,
    newWords: lexicon ? lexEntries.length : rows.reduce((n, r) => n + r.counts.newWords, 0),
    productiveWords: lexEntries.filter((e) => e.role === 'productive').length,
    receptiveWords: lexEntries.filter((e) => e.role === 'receptive').length,
    ruleCards: ruleCards ? ruleCards.cards.length : 0,
    canDos: new Set(rows.flatMap((r) => r.canDoIds)).size,
    plateaus: mine('plateau').length,
    closingBlocks: mine('closing').length,
  };
  const minutesByUnit = Object.fromEntries(rows.map((r) => [r.unit, r.minutesPlanned]));
  const plannedTotal = rows.reduce((n, r) => n + (r.minutesPlanned || 0), 0);
  const cardsPerUnit = rows.length ? totals.reviewCards / rows.length : 0;
  const reviewMinutesByPace = {
    model: 'compile-v0 upper bound: every review card reaches every ladder rung within the course (SRS-01 replaces it)',
    cardsPerUnit: round1(cardsPerUnit),
  };
  for (const [pace, p] of Object.entries(course.pace)) {
    const perDay = (cardsPerUnit * p.unitsPerWeek * course.review.ladderDays.length) / p.learningDays;
    reviewMinutesByPace[pace] = round1((perDay * course.review.secondsPerReview) / 60);
  }
  const levelHash = contentHash({
    course,
    units: unitHashes,
    lexicon: lexicon ? contentHash(lexicon) : null,
    ruleCards: ruleCards ? contentHash(ruleCards) : null,
    extra: extraHashes,
  });
  const manifest = {
    $generated: GENERATED_MARK,
    level,
    kind: course.kind,
    priceKey: course.priceKey,
    title: course.title,
    ...pick(course, ['honestyLineDe']),
    lanes: course.lanes,
    units: rowsInOrder,
    etappen: course.etappen,
    plateaus: course.plateaus,
    closing: course.closing,
    completion: course.completion,
    review: course.review,
    pace: course.pace,
    targets: course.targets,
    minutesPlanned: { units: plannedTotal, byUnit: minutesByUnit, source: 'level-profile design minutes; minutesMeasured replaces them (LGL-09)' },
    reviewMinutesByPace,
    minutesMeasured: null,
    counts,
    contentHash: levelHash,
  };
  outputs.push({ file: path.join(levelOut, 'manifest.json'), text: json(manifest) });

  // Banks: grader input, keyed by bankKey (sorted for stable diffs).
  const sortedObj = (m) => Object.fromEntries([...m.entries()].sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0)));
  outputs.push({
    file: path.join(banksRoot, `${level}.banks.json`),
    text: json({ $generated: GENERATED_MARK, level, prefix, scope: `${prefix}-`, writing: sortedObj(bank.writing), speaking: sortedObj(bank.speaking) }),
  });

  // Ids ledger (ID-01): live ids of this level; ids that were live before and are gone now become
  // tombstones; a tombstoned id may never come back.
  const ledgerFile = path.join(levelOut, 'ids.ledger.json');
  let prev = { ids: {}, tombstones: {} };
  if (fs.existsSync(ledgerFile)) {
    try {
      prev = JSON.parse(fs.readFileSync(ledgerFile, 'utf8'));
    } catch {
      errors.push(`${rel(ledgerFile)}: unreadable ledger — restore it from version control before compiling`);
    }
  }
  for (const k of bank.writing.keys()) ids.set(k, { kind: 'bank' });
  for (const k of bank.speaking.keys()) ids.set(k, { kind: 'bank' });
  const tombstones = { ...(prev.tombstones || {}) };
  for (const id of ids.keys()) {
    if (tombstones[id]) errors.push(`${level}: ID-01 id "${id}" was removed earlier (tombstoned) and may not be reused — give the item a new id`);
  }
  for (const [id, kind] of Object.entries(prev.ids || {})) {
    if (!ids.has(id) && !tombstones[id]) tombstones[id] = { kind, removedWhen: levelHash };
  }
  if (errors.length) return { outputs: [], syncDirs: [], errors, warnings };
  const liveIds = Object.fromEntries([...ids.entries()].sort(([a], [b]) => (a < b ? -1 : 1)).map(([id, v]) => [id, v.kind]));
  const tomb = Object.fromEntries(Object.entries(tombstones).sort(([a], [b]) => (a < b ? -1 : 1)));
  outputs.push({ file: ledgerFile, text: json({ $generated: GENERATED_MARK, level, ids: liveIds, tombstones: tomb }) });

  return { outputs, syncDirs: [path.join(levelOut, 'units'), path.join(levelOut, 'plateaus'), path.join(levelOut, 'closing')], errors, warnings };
}

/**
 * Write outputs, delete generated files in syncDirs that are no longer produced.
 * With check: true nothing is written; returns the files that would change.
 */
export function writeOutputs({ outputs, syncDirs }, { check = false } = {}) {
  const changed = [];
  const produced = new Set(outputs.map((o) => path.resolve(o.file)));
  for (const o of outputs) {
    const cur = fs.existsSync(o.file) ? fs.readFileSync(o.file, 'utf8') : null;
    if (cur === o.text) continue;
    changed.push(o.file);
    if (!check) {
      fs.mkdirSync(path.dirname(o.file), { recursive: true });
      fs.writeFileSync(o.file, o.text);
    }
  }
  for (const dir of syncDirs) {
    if (!fs.existsSync(dir)) continue;
    for (const name of fs.readdirSync(dir).sort()) {
      const p = path.resolve(dir, name);
      if (!name.endsWith('.json') || produced.has(p)) continue;
      changed.push(p);
      if (!check) fs.unlinkSync(p);
    }
  }
  return changed;
}

/** Levels that have a course.json under a content root. */
export function levelsIn(contentRoot, { exclude = [] } = {}) {
  return [...new Set(loadTree(contentRoot, { exclude }).filter((t) => t.kind === 'course' && typeof t.doc.level === 'string').map((t) => t.doc.level))].sort();
}
