// Course v2 compiler v0 — deterministic, idempotent (SCHEMA §13).
//
// For one level it reads content/course-v2/** (registries shared, the level's own files) and
// produces, after a clean SCH-01/REF-01/KEY-01 check:
//
//   <out>/<level>/units/uNN.json      the unit chunk the player lazy-loads (units at stage T only):
//                                     learner-invisible fields stripped, generated fields added
//                                     (poolItems in the live lessonPools shape, generated-item ids,
//                                     line seconds, minutesPlanned, reviewCards, contentHash)
//   <out>/<level>/reserve.json        the reserve index (SCHEMA §13): every Lernschritt's reserve items
//                                     in the pool shape, by unit, step, topic and error tag — read by
//                                     requeue, earlierDraw, Plateau review sets, Mehr üben, repair cards
//   <out>/<level>/plateaus/pN.json, closing/<id>.json   the same treatment for Plateau/closing files;
//                                     a Plateau's `review.items` is its review set, DRAWN here from the
//                                     unit reserves (banks: ['plateau'], seeded by the Plateau id:
//                                     currentShare from the units since the previous Plateau, the rest
//                                     from the earlier ones); a .1 Halbtest gets `comesNext` — the first
//                                     unit of the .2 level whose Prüfungsfokus names each Teil (the
//                                     Teil-Karte), from that level's unit files or specs.json
//   <out>/<level>/manifest.json       course manifest: units with titles, can-dos, grammar, Prüfungsfokus,
//                                     minutes and counts (syllabus rows), Etappen, completion, review,
//                                     pace, counts for copy, contentHash
//   <out>/<level>/ids.ledger.json     every live id of the level + tombstones of removed ids (ID-01)
//   <out>/<level>/rule-cards.json     the level's rule cards (when authored)
//   <out>/<level>/words.json          the level's word list for the Kapitel „Wortschatz" page (when a lexicon exists)
//   <out>/<level>/lines.json          every spoken line with its cast voice — the audio run's input
//   <banks>/<level>.banks.json        grader input only, every entry keyed by bankKey:
//                                       writing  = WritingTasks (Leitpunkt cues and `choose` included,
//                                                  SCHEMA §15.5) + written MicroOutputs
//                                       speaking = SpeakingTasks + spoken MicroOutputs
//                                       micro    = every MicroOutput, with its `mode` (the lookup
//                                                  table of _shared/rubrics/data.mjs bankEntry(…, 'micro', key))
//
// PARTIAL LEVELS (compile mode). A level compiles from the units that exist: a unit course.json lists
// but no file holds yet is a manifest row with status 'coming' (title, can-dos, Prüfungsfokus and
// planned minutes from the level's specs.json bundle when it has one) and no chunk; a unit whose own
// check fails (SCH-01, REF-01, KEY-01 — its lane packs included) is SKIPPED with its errors returned,
// never half-written, and is listed as 'coming' too. References to a planned-but-missing unit (and to
// ids under it) resolve in compile mode only; the checker and the validator keep REF-01 as it is.
// Ids of a unit that is not compiled in a run stay live in the ledger — only a unit that compiles can
// tombstone its removed ids. Errors in any other file of the level or in a shared registry, and the
// compile-stage integrity errors (ID-01 duplicates and tombstones, KEY-01 prefix/duplicates) still
// refuse the whole level.
//
// Nothing here reads a clock, the environment or the network: the same content gives the same bytes.
import fs from 'node:fs';
import path from 'node:path';
import { loadTree, rel, REPO_ROOT } from './tree.mjs';
import { buildIndex } from './refindex.mjs';
import { checkLoaded } from './checker.mjs';
import { formatError } from './schema.mjs';
import { contentHash } from './hash.mjs';
import { PATTERNS, LANE_EXAM_KEY, prefixOfLevel, levelOfPrefix, parseBankKey } from './ids.mjs';

export const GENERATED_MARK = 'generated by scripts/course-v2/compile.mjs from content/course-v2 — do not edit';
export const DEFAULT_OUT = path.join(REPO_ROOT, 'src/data/course-v2');
export const DEFAULT_BANKS = path.join(REPO_ROOT, 'netlify/functions/_shared/course-v2');

const MODULE_LABEL = { hoeren: 'Hören', lesen: 'Lesen', sprachbausteine: 'Sprachbausteine', schreiben: 'Schreiben', sprechen: 'Sprechen' };
// Fields no learner sees: reviewer rationale, authoring provenance, validator flags.
const STRIP_ITEM_KEYS = ['origin', 'reviewerConfirmed', 'acceptedWhy', 'intentionalError', 'perceptionOnly'];
const STRIP_SPEC_KEYS = ['lehrwerk', 'deviation', 'source', 'fokusPlan'];
const STRIP_TOP_KEYS = ['$schema', 'version', 'status', 'reviewedIn', 'stage'];
const WORDS_PER_SECOND = 2.5; // line-length estimate (150 words/min) until the audio run measures it

// Compiled output is minified (the authored content under content/course-v2 stays readable): one line
// per file, keys in the compiler's fixed insertion order, so an unchanged unit gives identical bytes.
const json = (x) => `${JSON.stringify(x)}\n`;
const round1 = (x) => Math.round(x * 10) / 10;
const pad2 = (n) => String(n).padStart(2, '0');
const isObj = (x) => x !== null && typeof x === 'object' && !Array.isArray(x);
const isItem = (x) => isObj(x) && typeof x.id === 'string' && typeof x.type === 'string' && typeof x.role === 'string' && PATTERNS.item.test(x.id);
const isLine = (x) => isObj(x) && typeof x.id === 'string' && typeof x.speaker === 'string' && PATTERNS.line.test(x.id);

function levelOfDoc({ doc, kind }) {
  if (!doc) return null;
  switch (kind) {
    case 'course':
    case 'unit':
    case 'lexicon':
    case 'rulecards':
    case 'plateau':
    case 'closing':
    case 'mockmodule':
      return typeof doc.level === 'string' ? doc.level : null;
    case 'lanepack':
      return typeof doc.unit === 'string' ? doc.unit.split('-')[0] : null;
    case 'plateaulanepack':
      return typeof doc.plateau === 'string' ? doc.plateau.split('-')[0] : null;
    default:
      return null; // registries, casts, stubs: shared by every level
  }
}

// ── partial levels: file ownership, planned units, spec bundles ─────────────────────────
const UNIT_OF_ID = /^((?:a1|a2|b1|b2)\.[12]-u(?:0[1-9]|1[0-2]))(?:-|$)/;
/** The unit an id lives under ('a1.1-u04-ls1-p03' → 'a1.1-u04'; bank key 'a11-u04-w' → 'a1.1-u04'), or null. */
export function unitOfId(id) {
  if (typeof id !== 'string') return null;
  const m = id.match(UNIT_OF_ID);
  if (m) return m[1];
  const b = parseBankKey(id);
  return b && /^u\d{2}$/.test(b.slot) ? `${levelOfPrefix(b.prefix)}-${b.slot}` : null;
}

/** The level directory a file sits in (`<root>/<level>/…`), or null. */
function levelOfFile(file, contentRoot) {
  const first = path.relative(contentRoot, file).split(path.sep)[0];
  return PATTERNS.LEVEL.test(first) ? first : null;
}

/**
 * The unit a file belongs to: a unit file or one of its lane packs, by the document's own id or
 * — when it cannot be parsed or has no valid id — by its path `<level>/units/uNN[.lane-x].json`.
 */
function unitOfFile(t, contentRoot) {
  if (!t.error && t.kind === 'unit' && typeof t.doc.id === 'string' && PATTERNS.UNIT.test(t.doc.id)) return t.doc.id;
  if (!t.error && t.kind === 'lanepack' && typeof t.doc.unit === 'string' && PATTERNS.UNIT.test(t.doc.unit)) return t.doc.unit;
  const m = path.relative(contentRoot, t.file).split(path.sep).join('/').match(/^((?:a1|a2|b1|b2)\.[12])\/units\/u(0[1-9]|1[0-2])(?:\.lane-[a-z0-9]+)?\.json$/);
  return m && (t.error || t.kind === 'unit' || t.kind === 'lanepack') ? `${m[1]}-u${m[2]}` : null;
}

/**
 * `<level>/specs.json` — the curriculum agents' spec bundle (an array of spec units, not a SCHEMA
 * file; RAILS §8). The checker reports it; the compiler reads it only as syllabus input for units
 * that have no file of their own yet.
 */
function isSpecBundle(t, contentRoot) {
  const r = path.relative(contentRoot, t.file).split(path.sep);
  return r.length === 2 && r[1] === 'specs.json' && PATTERNS.LEVEL.test(r[0]) && Array.isArray(t.doc);
}

/** The index a compile run checks against: references to planned-but-missing units resolve. */
function withPlannedUnits(index, missing) {
  if (!index || missing.size === 0) return index;
  return {
    ...index,
    has(kind, id) {
      const found = index.has(kind, id);
      if (found !== false) return found;
      const owner = kind === 'unit' ? id : ['step', 'item', 'line', 'text', 'asset', 'fact', 'fokus', 'bank'].includes(kind) ? unitOfId(id) : null;
      return owner && missing.has(owner) ? true : found;
    },
  };
}

const strs = (x) => (Array.isArray(x) ? x.filter((v) => typeof v === 'string') : []);
const str = (x) => (typeof x === 'string' && x ? x : null);

/** Visit every object/array in document order. */
function eachNode(root, fn) {
  const visit = (x, parent) => {
    if (Array.isArray(x)) {
      x.forEach((y) => visit(y, x));
      return;
    }
    if (!isObj(x)) return;
    fn(x, parent);
    for (const v of Object.values(x)) visit(v, x);
  };
  visit(root, null);
}

// ── pool shape (SCHEMA §3.1, last paragraph) ────────────────────────────────────────────
/** An authored Item in the live lessonPools shape read by check.js, requeue.js, mastery.js, reviewGrading. */
export function toPoolItem(item, minLektion) {
  const questionDe =
    item.type === 'sentence_building' && Array.isArray(item.tiles)
      ? `${item.promptDe.replace(/\.$/, ':')} [${item.tiles.join(' / ')}]`
      : item.promptDe;
  const out = {
    id: item.id,
    topic: item.topic,
    type: item.type,
    questionDe,
    questionEn: item.promptEn ?? null,
    options: item.options ?? null,
    answer: item.answer,
    accepted: item.accepted,
    caseSensitive: item.caseSensitive === true,
    explanationDe: item.explanation.de,
    explanationEn: item.explanation.en,
    hint: item.hint ? item.hint.de : null,
    minLektion,
  };
  if (item.exact) out.exact = item.exact; // passed to checkAnswer() by checkOptionsFor() once E1 extends it
  // renderer inputs of the new item types, carried only when the item has them
  for (const k of ['pairs', 'audioLineRef', 'textRef', 'noMatch']) if (item[k] !== undefined) out[k] = item[k];
  return out;
}

/** A reserve item in the pool shape plus what the reserve index draws by (SCHEMA §3.1 banks/errorTags). */
function toReserveItem(item, minLektion, step) {
  const out = toPoolItem(item, minLektion);
  out.step = step;
  const tags = [...(item.errorTag ? [item.errorTag] : []), ...(Array.isArray(item.errorTags) ? item.errorTags : [])];
  out.errorTags = [...new Set(tags)];
  out.banks = Array.isArray(item.banks) ? item.banks : [];
  if (Number.isInteger(item.difficulty)) out.difficulty = item.difficulty;
  return out;
}

// ── plural variants (SCHEMA §6 pluralVariants, 2026-09-28) ──────────────────────────────
/**
 * Every correct plural of a lexicon noun that has more than one (lx.balkon: Balkone, Balkons),
 * lower-case plural → all its plurals. Read from every level's lexicon: a plural is a fact about
 * the word, not about the level that allocates it.
 */
function pluralTwinsOf(lexicons) {
  const twins = new Map();
  for (const lex of lexicons) {
    for (const e of Array.isArray(lex && lex.entries) ? lex.entries : []) {
      const variants = strs(e && e.pluralVariants);
      if (!variants.length || typeof e.plural !== 'string') continue;
      const all = [...new Set([e.plural, ...variants].map((p) => p.replace(/^die\s+/i, '').trim()).filter(Boolean))];
      for (const p of all) twins.set(p.toLowerCase(), all);
    }
  }
  return twins;
}

/** Item types the learner TYPES an answer into (a choice or tile item offers its forms instead). */
const TYPED_TYPES = new Set(['fill_blank', 'error_correction', 'dictation', 'notes']);
const isTyped = (x) => TYPED_TYPES.has(x.type) || (x.type === 'cloze' && !(Array.isArray(x.options) && x.options.length));

/**
 * The item with every plural twin of its key accepted too: an accepted form that types „Balkone"
 * also accepts „Balkons" (the checker grades against `accepted`). Returns the item itself when
 * nothing changes; never touches a choice or tile item.
 */
function withPluralTwins(item, twins) {
  if (!twins.size || !isItem(item) || !isTyped(item)) return item;
  const base = strs(item.accepted).length ? strs(item.accepted) : [item.answer].filter((a) => typeof a === 'string');
  const out = [...base];
  for (const form of base) {
    for (const m of form.matchAll(/\p{L}+/gu)) {
      const all = twins.get(m[0].toLowerCase());
      if (!all) continue;
      for (const v of all) {
        const cased = /^\p{Lu}/u.test(m[0]) ? v.charAt(0).toUpperCase() + v.slice(1) : v.charAt(0).toLowerCase() + v.slice(1);
        const variant = form.slice(0, m.index) + cased + form.slice(m.index + m[0].length);
        if (!out.includes(variant)) out.push(variant);
      }
    }
  }
  return out.length === base.length ? item : { ...item, accepted: out };
}

// ── generated ids, stripping, line seconds ──────────────────────────────────────────────
/** Give every GeneratorSpec of a step its compiler-assigned item ids (STEP-gNN, in document order). */
function assignGeneratedIds(step) {
  let n = 0;
  const assigned = [];
  eachNode(step, (x) => {
    if (typeof x.generator === 'string' && Number.isInteger(x.count)) {
      x.ids = [];
      for (let i = 0; i < x.count; i++) x.ids.push(`${step.id}-g${pad2(++n)}`);
      assigned.push(...x.ids);
    }
  });
  return assigned;
}

function estimateSeconds(line) {
  const words = String(line.say || line.de).trim().split(/\s+/).filter(Boolean).length;
  return round1(words / WORDS_PER_SECOND);
}

/**
 * Learner-facing copy of an authored file (deep clone; the input is not touched). Reserves leave
 * the chunk: they are never served in their Lernschritt and live in the reserve index instead.
 */
// ── the chapter outline (owner decision 2026-09-29) ─────────────────────────────────────
// The course must read like a Lehrwerk: every Kapitel shows what it teaches — Wortschatz,
// Hören or Lesen, Grammatik, Übungen, Sprechen or Schreiben, Aussprache, Prüfungstraining,
// the Kapiteltest. The outline is DERIVED from the unit's own steps (never authored twice),
// and rides on the manifest row so the course home can show it without loading the unit.

/** A grammar point's short name: its spine label up to the first „ (", „:", „;" or „ – ". */
export function shortGrammarLabel(label) {
  const s = String(label || '');
  const cut = [' (', ':', ';', ' – '].map((m) => s.indexOf(m)).filter((i) => i > 0);
  return (cut.length ? s.slice(0, Math.min(...cut)) : s).trim();
}

const INPUT_SKILLS = { dialog: ['hoeren'], text: ['lesen'], mixed: ['hoeren', 'lesen'] };

/** One entry per step: { nr, id, kind, title, skills, grammar, input, teile, items }. */
export function outlineOf(u, spineLabel = new Map()) {
  return (Array.isArray(u.steps) ? u.steps : []).map((s, i) => {
    const skills = [];
    const add = (k) => { if (!skills.includes(k)) skills.push(k); };
    const poolSize = Array.isArray(s.pool?.items) ? s.pool.items.length : 0;
    if (['situation', 'text', 'sprache'].includes(s.kind)) {
      add('wortschatz');
      for (const k of INPUT_SKILLS[s.input?.kind] || []) add(k);
      if (s.structure) add('grammatik');
      if (poolSize) add('ueben');
      if (s.microOutput?.mode === 'spoken') add('sprechen');
      if (s.microOutput?.mode === 'written') add('schreiben');
      if (s.aussprache) add('aussprache');
    } else if (s.kind === 'pruefung') add('pruefung');
    else if (s.kind === 'sprechen') add('sprechen');
    else if (s.kind === 'schreiben' || s.kind === 'ueberarbeiten') add('schreiben');
    else if (s.kind === 'check') add('test');
    const label = s.structure ? spineLabel.get(s.structure) || s.structure : null;
    const teile = [
      ...(Array.isArray(s.blocks) ? s.blocks.map((b) => b && b.template) : []),
      ...(Array.isArray(s.task?.parts) ? s.task.parts.map((p) => p && p.template) : []),
      s.task?.template,
    ].filter((t) => typeof t === 'string');
    return {
      nr: i + 1,
      id: s.id,
      kind: s.kind,
      title: typeof s.title === 'string' ? s.title : null,
      skills,
      grammar: s.structure ? { id: s.structure, short: shortGrammarLabel(label), label } : null,
      ruleCard: typeof s.ruleCard === 'string' ? s.ruleCard : null,
      input: s.input ? { kind: s.input.kind || null, title: s.input.title || null } : null,
      teile: [...new Set(teile)],
      items: poolSize,
    };
  });
}

function learnerCopy(doc) {
  const c = structuredClone(doc);
  for (const k of STRIP_TOP_KEYS) delete c[k];
  if (isObj(c.spec)) for (const k of STRIP_SPEC_KEYS) delete c.spec[k];
  if (Array.isArray(c.steps)) for (const st of c.steps) if (isObj(st)) delete st.reserve;
  eachNode(c, (x) => {
    if (isItem(x)) for (const k of STRIP_ITEM_KEYS) delete x[k];
    if (isLine(x) && x.seconds === undefined) x.seconds = estimateSeconds(x);
    if (typeof x.claimDe === 'string' && PATTERNS.fact.test(x.id || '')) delete x.notes;
  });
  return c;
}

// ── ids (ID-01 ledger) ──────────────────────────────────────────────────────────────────
// order matters where SCHEMA §2 patterns overlap: a lane-infixed exam text (…-ls4-ta2-t3) also has
// the shape of a block id, so `text` is tried first
const ID_KINDS = ['UNIT', 'STEP', 'item', 'line', 'text', 'asset', 'block', 'mo', 'rm', 'fact', 'fokus', 'plateau'];
function collectIds(doc, into, errors, where) {
  const add = (id, kind) => {
    if (into.has(id)) errors.push(`${where}: ID-01 duplicate id "${id}" (also ${into.get(id).where})`);
    else into.set(id, { kind, where });
  };
  eachNode(doc, (x) => {
    if (typeof x.id === 'string') {
      const kind = ID_KINDS.find((k) => PATTERNS[k].test(x.id));
      if (kind) add(x.id, kind === 'UNIT' ? 'unit' : kind === 'STEP' ? 'step' : kind);
    }
    if (Array.isArray(x.ids) && typeof x.generator === 'string') x.ids.forEach((id) => add(id, 'item-generated'));
  });
}

// ── banks ───────────────────────────────────────────────────────────────────────────────
function withHash(entry) {
  return { ...entry, contentHash: contentHash(entry) };
}
const pick = (src, keys) => {
  const o = {};
  for (const k of keys) if (src[k] !== undefined) o[k] = src[k];
  return o;
};

function writingEntry(t, level, owner, textTypeLabels = null) {
  return withHash({
    level,
    ...owner,
    lane: t.lane,
    template: t.template,
    examKey: t.examKey,
    profile: t.profile,
    register: t.register,
    address: t.address,
    situationDe: t.situationDe,
    taskDe: t.taskDe,
    // cues and `choose` feed the server twin of the pre-check (advisory cue coverage, never the score)
    leitpunkte: t.leitpunkte.map((lp) => ({ id: lp.id, de: lp.de, cues: lp.cues })),
    choose: t.choose ?? null,
    // form tasks (method deterministic): the fields and their keys are scored in code
    ...(t.form ? { form: { fields: t.form.fields } } : {}),
    ...pick(t, ['wordBand', 'wordBandLearning', 'minSubmitWords']),
    // what the learner writes (SCHEMA §8 WritingTask.textType, 2026-09-28): the grader names the genre,
    // so a post is not read as a letter without Betreff and Gruß
    ...(t.textType ? { textType: t.textType, textTypeLabel: (textTypeLabels && textTypeLabels.get(t.textType)) || null } : {}),
  });
}

// SpeakingPart fields the speaking functions read (SCHEMA §12: parts, stimulus, partnerData,
// keyPoints, seconds/turns); modelTurns stay in the unit chunk (shown after the attempt only)
const SPEAKING_PART_KEYS = ['template', 'mode', 'profile', 'prepMinutes', 'prepAtHome', 'instructionsDe', 'situationDe', 'cards', 'photos', 'slides',
  'stimulus', 'partnerData', 'topicChoice', 'keyPoints', 'seconds', 'turns', 'moves', 'planningRound'];

/**
 * The Prüfungsfokus length of each speaking Teil of a unit (SCHEMA §8 UnitSpec.lanes.pruefungsfokus,
 * slot 'sprechen'): template → 'reduced' | 'mini'. Only shortened Teile are listed; a Teil the
 * Prüfungsfokus does not name, or names 'full', is played at full length.
 */
function shortenedSpeakingTeile(spec) {
  const out = new Map();
  const list = isObj(spec) && isObj(spec.lanes) && Array.isArray(spec.lanes.pruefungsfokus) ? spec.lanes.pruefungsfokus : [];
  for (const p of list) {
    if (isObj(p) && p.slot === 'sprechen' && typeof p.template === 'string' && (p.length === 'reduced' || p.length === 'mini')) out.set(p.template, p.length);
  }
  return out;
}

const SHORTENED_LENGTHS = ['reduced', 'mini'];

/**
 * One SpeakingPart as the speaking functions read it. `length` is carried when the Teil is
 * shortened: the grader then scores only the criteria a shortened Teil elicits (rubric
 * `appliesIf: 'full'`; review a1.1-u01 r1–r3 F01). The part's own `length` wins (the form EXM-04
 * and grade.mjs read — the only source a Plateau or closing part has, since those carry no
 * Prüfungsfokus); else the unit's Prüfungsfokus entry for its template.
 */
export function speakingPart(p, shortened) {
  const out = pick(p, SPEAKING_PART_KEYS);
  const own = SHORTENED_LENGTHS.includes(p.length) ? p.length : null;
  const length = own || (shortened && shortened.get(p.template));
  return length ? { ...out, length } : out;
}

function speakingEntry(t, level, owner, shortened = null) {
  const parts = Array.isArray(t.parts) ? t.parts : null;
  return withHash({
    level,
    ...owner,
    lane: t.lane,
    examKey: LANE_EXAM_KEY[t.lane] || null,
    // a one-Teil task carries its part fields at the top (as normalizeSpeakingTask reads them);
    // a multi-Teil round carries `parts` — each with its own template, mode and rubric profile, and
    // each graded on that profile — plus the first part's template/mode/profile for the session row
    ...(parts
      ? { ...pick(parts[0], ['template', 'mode', 'profile', 'prepMinutes']), parts: parts.map((p) => speakingPart(p, shortened)) }
      : speakingPart(t, shortened)),
    aiRole: t.aiRole,
    openingLine: t.openingLine,
    hintWords: t.hintWords,
  });
}

function microEntry(m, level, owner) {
  return withHash({
    level,
    ...owner,
    lane: null,
    profile: m.profile,
    mode: m.mode,
    register: m.register,
    ...pick(m, ['situationDe']),
    promptDe: m.promptDe,
    ...(m.mode === 'spoken' ? pick(m, ['planSeconds', 'seconds']) : pick(m, ['words'])),
    targets: m.targets,
  });
}

/** Every bankable task of an authored document, classified. */
function collectBankTasks(doc) {
  const out = [];
  eachNode(doc, (x) => {
    if (typeof x.bankKey !== 'string') return;
    if (typeof x.taskDe === 'string') out.push({ kind: 'writing', task: x });
    else if (isObj(x.aiRole)) out.push({ kind: 'speaking', task: x });
    else if (x.mode === 'written' || x.mode === 'spoken') out.push({ kind: x.mode === 'written' ? 'micro-writing' : 'micro-speaking', task: x });
  });
  return out;
}

// ── Plateau review sets (SCHEMA §10 `review`, §13; BLUEPRINT §5.2) ──────────────────────
/** FNV-1a of a string → a 32-bit seed (no clock, no environment: the same key, the same draw). */
function seedOf(key) {
  let h = 2166136261 >>> 0;
  for (let i = 0; i < key.length; i += 1) {
    h ^= key.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

/** mulberry32 — the PRNG of the live course's draws (src/lib/lesson/buildLesson.js). */
function prng(seed) {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function shuffled(list, rand) {
  const out = [...list];
  for (let i = out.length - 1; i > 0; i -= 1) {
    const j = Math.floor(rand() * (i + 1));
    [out[i], out[j]] = [out[j], out[i]];
  }
  return out;
}

/** Round-robin over groups (each already in its draw order) until every group is empty. */
function roundRobin(groups) {
  const out = [];
  const queues = groups.map((g) => [...g]);
  while (queues.some((q) => q.length)) for (const q of queues) if (q.length) out.push(q.shift());
  return out;
}

/**
 * The candidates of one share in the order they are drawn: spread over the units (in unit order)
 * and, inside a unit, over its Lernschritte (seeded order), so a review set of ≈ 20 maps back to
 * every Lernschritt it can reach; items not drawn by an earlier Plateau come first.
 */
function spreadOrder(cands, units, rand, exclude) {
  const seq = (list) => roundRobin(units.map((u) => {
    const mine = list.filter((c) => c.unit === u);
    const steps = shuffled([...new Set(mine.map((c) => c.step))].sort(), rand);
    return roundRobin(steps.map((s) => shuffled(mine.filter((c) => c.step === s), rand)));
  }));
  return [...seq(cands.filter((c) => !exclude.has(c.id))), ...seq(cands.filter((c) => exclude.has(c.id)))];
}

/**
 * Draw the review set of one Plateau from the unit reserves (SCHEMA §10: `review: { draw,
 * currentShare, from: 'reserve' }`; BLUEPRINT §5.2: ≈ 65 % from the units since the previous
 * Plateau, the rest from the earlier units). Deterministic: seeded by the Plateau id, no clock.
 *
 *   candidates  [{ id, unit, step }]  reserve items that carry banks: ['plateau'] (unit at stage T)
 *   current     unit ids since the previous Plateau, in order
 *   earlier     unit ids before them, in order
 *   exclude     ids an earlier Plateau of the level drew — they go to the back of their share
 *
 * A share with too few candidates hands its rest to the other (P1 has no earlier units: all 20
 * from U1–U3). Returns { current: [cand], earlier: [cand], items: [cand] } — `items` is the
 * whole set in its seeded serving order.
 */
export function drawPlateauReview(candidates, { id, draw = 20, currentShare = 0.65, current = [], earlier = [], exclude = new Set() }) {
  const rand = prng(seedOf(`${id}|review`));
  const inCurrent = (candidates || []).filter((c) => current.includes(c.unit));
  const inEarlier = (candidates || []).filter((c) => earlier.includes(c.unit));
  const total = Math.max(0, Math.floor(Number(draw) || 0));
  let wantCurrent = Math.round(total * (Number(currentShare) || 0));
  let wantEarlier = total - wantCurrent;
  if (inEarlier.length < wantEarlier) { wantCurrent += wantEarlier - inEarlier.length; wantEarlier = inEarlier.length; }
  if (inCurrent.length < wantCurrent) { wantEarlier = Math.min(inEarlier.length, wantEarlier + wantCurrent - inCurrent.length); wantCurrent = inCurrent.length; }
  const cur = spreadOrder(inCurrent, current, rand, exclude).slice(0, wantCurrent);
  const ear = spreadOrder(inEarlier, earlier, rand, exclude).slice(0, wantEarlier);
  return { current: cur, earlier: ear, items: shuffled([...cur, ...ear], rand) };
}

/**
 * Where each Teil of a .1 closing block comes next (BLUEPRINT §5.3 Teil-Karte, „kommt in A1.2,
 * Lektion 2"): the first unit of the paired .2 level whose Prüfungsfokus names the template in
 * the closing's lane. Read from the .2 level's unit files where they exist, else its specs.json
 * bundle. { level, byTemplate: { [template]: { unit, nr, title } } } — an empty byTemplate when
 * the .2 level has no specs yet (the player then says „in A1.2").
 */
function comesNextOf(level, lane, templates, { unitDocs, bundleEntries }) {
  const next = /\.1$/.test(level) ? level.replace(/\.1$/, '.2') : null;
  if (!next) return null;
  const byNr = new Map();
  for (const e of bundleEntries) if (isObj(e) && typeof e.id === 'string' && PATTERNS.UNIT.test(e.id) && e.id.startsWith(`${next}-`) && !byNr.has(e.id)) byNr.set(e.id, e);
  for (const u of unitDocs) if (isObj(u) && u.level === next && typeof u.id === 'string') byNr.set(u.id, u);
  const rows = [...byNr.values()].sort((a, b) => (a.id < b.id ? -1 : 1));
  const byTemplate = {};
  for (const template of templates) {
    const hit = rows.find((r) => {
      const l = isObj(r.spec) && isObj(r.spec.lanes) ? r.spec.lanes : {};
      const list = Array.isArray(l.pruefungsfokus) ? l.pruefungsfokus : [];
      return (l.primary === lane || l.primary === undefined) && list.some((p) => isObj(p) && p.template === template);
    });
    if (hit) byTemplate[template] = { unit: hit.id, nr: Number(hit.id.slice(-2)), title: isObj(hit.title) ? str(hit.title.de) : null };
  }
  return { level: next, byTemplate };
}

/** Kind of one Plateau/closing Teil: an ExamBlock, a WritingTask or a SpeakingTask. */
const partKindOf = (p) => (!isObj(p) ? null : Array.isArray(p.items) && typeof p.template === 'string' ? 'block'
  : typeof p.taskDe === 'string' ? 'writing' : isObj(p.aiRole) ? 'speaking' : null);

// ── labels ──────────────────────────────────────────────────────────────────────────────
function teilLabel(templateId, lanes) {
  const [laneId, teil] = templateId.split('.');
  const lane = lanes.get(laneId);
  const t = lane && lane.teile ? lane.teile[teil] : null;
  if (!t || !MODULE_LABEL[t.module]) return templateId;
  const order = lane.modules && lane.modules[t.module] && Array.isArray(lane.modules[t.module].teile) ? lane.modules[t.module].teile : [];
  const idx = order.indexOf(teil);
  const nr = idx >= 0 ? idx + 1 : Number((teil.match(/\d+/) || [])[0]) || null;
  return nr ? `${MODULE_LABEL[t.module]} Teil ${nr}` : MODULE_LABEL[t.module];
}

// ── review cards (SCHEMA §2 keys) ───────────────────────────────────────────────────────
function reviewCardsOf(u) {
  const cards = [];
  for (const b of u.spec?.lexiconBlocks || []) for (const lx of b.lemmas || []) cards.push(`word:${lx}`);
  for (const g of u.spec?.grammar?.new || []) cards.push(`pattern:${g}:${u.id}`);
  for (const rm of u.redemittel || []) cards.push(`sentence:${rm.id}`);
  return cards;
}

// ── minutes (design values until the time model / minutesMeasured exist) ────────────────
function minutesOf(u, profile) {
  if (!profile) return null;
  const kinds = Array.isArray(u.steps) ? u.steps.map((s) => s.kind) : profile.steps;
  const byStep = {};
  let total = 0;
  kinds.forEach((kind, i) => {
    const m = Number.isInteger(profile.minutes[kind]) ? profile.minutes[kind] : 0;
    total += m;
    if (Array.isArray(u.steps)) byStep[u.steps[i].id] = m;
  });
  return { total, byStep: Array.isArray(u.steps) ? byStep : null, source: 'level-profile design minutes per step kind' };
}

// ── the level ───────────────────────────────────────────────────────────────────────────
/**
 * Compile one level. Returns { outputs: [{ file, text }], syncDirs: [dir], optionalFiles: [file], errors: [str], warnings: [str] }.
 * Nothing is written; see writeOutputs().
 */
export function compileLevel(level, { contentRoot, exclude = [], outRoot = DEFAULT_OUT, banksRoot = DEFAULT_BANKS, refs = true } = {}) {
  const errors = [];
  const warnings = [];
  const loaded = loadTree(contentRoot, { exclude });
  const bundles = loaded.filter((t) => isSpecBundle(t, contentRoot));
  const tree = loaded.filter((t) => !bundles.includes(t));
  const baseIndex = buildIndex(tree.filter((t) => !t.error));
  // Units some course.json plans but no file holds: references to them resolve in compile mode.
  const present = new Set(tree.filter((t) => !t.error && t.kind === 'unit' && typeof t.doc.id === 'string').map((t) => t.doc.id));
  const planned = new Set(tree.filter((t) => !t.error && t.kind === 'course' && Array.isArray(t.doc.units)).flatMap((t) => strs(t.doc.units)));
  const missing = new Set([...planned].filter((id) => !present.has(id)));
  const index = withPlannedUnits(baseIndex, missing);

  // A unit (with its lane packs) that fails its own check is skipped; any other error refuses the level.
  const failed = new Map(); // unit id → { file, errors }
  for (const t of tree) {
    const lv = t.error ? levelOfFile(t.file, contentRoot) : levelOfDoc(t);
    if (lv !== null && lv !== level) continue; // another level's content: indexed, not compiled
    const found = checkLoaded(t, index, { refs }).map((e) => formatError(rel(t.file), e));
    if (!found.length) continue;
    const owner = lv === level ? unitOfFile(t, contentRoot) : null;
    if (owner) {
      if (!failed.has(owner)) failed.set(owner, { unit: owner, file: rel(t.file), errors: [] });
      failed.get(owner).errors.push(...found);
    } else errors.push(...found);
  }
  if (errors.length) return { outputs: [], syncDirs: [], errors, warnings, skipped: [] };
  const skipped = [...failed.values()].sort((a, b) => (a.unit < b.unit ? -1 : 1));

  const docs = (kind) => tree.filter((t) => !t.error && t.kind === kind);
  const mine = (kind) => docs(kind).filter((t) => levelOfDoc(t) === level);
  const courses = mine('course');
  if (courses.length !== 1) {
    errors.push(courses.length ? `${level}: ${courses.length} course.json files (${courses.map((c) => rel(c.file)).join(', ')})` : `${level}: no course.json (course-v2/course@1) found`);
    return { outputs: [], syncDirs: [], errors, warnings, skipped };
  }
  const course = courses[0].doc;
  const prefix = prefixOfLevel(level);
  const profile = docs('levels').flatMap((t) => t.doc.levels).find((l) => l.level === level) || null;
  if (!profile) warnings.push(`${level}: no level profile — minutesPlanned is null`);
  const lexicon = mine('lexicon')[0]?.doc || null;
  const pluralTwins = pluralTwinsOf(docs('lexicon').map((t) => t.doc));
  const textTypeLabels = new Map(docs('texttypes').flatMap((t) => (Array.isArray(t.doc.types) ? t.doc.types : []).map((x) => [x.id, x.label])));
  const ruleCards = mine('rulecards')[0]?.doc || null;
  const candoText = new Map(docs('cando').flatMap((t) => t.doc.items.map((i) => [i.id, (typeof i.learnerDe === 'string' && i.learnerDe.trim()) || i.de])));
  const spineLabel = new Map(docs('spine').flatMap((t) => t.doc.points.map((p) => [p.id, p.label])));
  const lanes = new Map(docs('lane').map((t) => [t.doc.id, t.doc]));
  const live = new Set(course.lanes.live);
  // the level's spec bundle: syllabus data for units without a file (first entry per id wins)
  const specById = new Map();
  for (const b of bundles.filter((t) => levelOfFile(t.file, contentRoot) === level)) {
    for (const e of b.doc) if (isObj(e) && typeof e.id === 'string' && !specById.has(e.id)) specById.set(e.id, e);
  }

  const units = mine('unit').filter((u) => !failed.has(u.doc.id)).sort((a, b) => a.doc.nr - b.doc.nr);
  const seenNr = new Map();
  for (const u of units) {
    if (seenNr.has(u.doc.nr)) errors.push(`${rel(u.file)}: unit nr ${u.doc.nr} also in ${rel(seenNr.get(u.doc.nr))}`);
    seenNr.set(u.doc.nr, u.file);
    if (!course.units.includes(u.doc.id)) errors.push(`${rel(u.file)}: unit ${u.doc.id} is not listed in ${level}/course.json`);
  }
  const packsByUnit = new Map();
  for (const p of mine('lanepack').filter((x) => !failed.has(x.doc.unit))) {
    if (!packsByUnit.has(p.doc.unit)) packsByUnit.set(p.doc.unit, []);
    packsByUnit.get(p.doc.unit).push(p);
  }

  const outputs = [];
  const levelOut = path.join(outRoot, level);
  const ids = new Map();
  const bank = { writing: new Map(), speaking: new Map(), micro: new Map() };
  const addBank = (tasks, owner, file, shortened = null) => {
    for (const { kind, task } of tasks) {
      if (!task.bankKey.startsWith(`${prefix}-`)) {
        errors.push(`${rel(file)}: KEY-01 bank key "${task.bankKey}" does not belong to course prefix "${prefix}"`);
        continue;
      }
      const target = kind === 'writing' || kind === 'micro-writing' ? bank.writing : bank.speaking;
      if (bank.writing.has(task.bankKey) || bank.speaking.has(task.bankKey)) {
        errors.push(`${rel(file)}: KEY-01 duplicate bank key "${task.bankKey}"`);
        continue;
      }
      const entry =
        kind === 'writing' ? writingEntry(task, level, owner, textTypeLabels)
          : kind === 'speaking' ? speakingEntry(task, level, owner, shortened)
            : microEntry(task, level, owner);
      target.set(task.bankKey, entry);
      if (kind.startsWith('micro')) bank.micro.set(task.bankKey, entry);
    }
  };

  // the syllabus label of each live lane's Prüfungsfokus Teile (unit files and spec bundles alike)
  const pruefungsfokusOf = (spLanes) => {
    const pf = {};
    if (!isObj(spLanes)) return pf;
    for (const laneId of course.lanes.live) {
      const list = laneId === spLanes.primary
        ? (Array.isArray(spLanes.pruefungsfokus) ? spLanes.pruefungsfokus : []).map((p) => p && p.template)
        : (isObj(spLanes.spur) && spLanes.spur[laneId]) || [];
      const templates = strs(list);
      if (templates.length) pf[laneId] = templates.map((t) => teilLabel(t, lanes));
    }
    return pf;
  };
  // the learner line of a can-do (`learnerDe`, SCHEMA §4.1) where the registry has one; `de` stays the
  // descriptor wording (ich-Form + source) and is the fallback (review a1.1-u06 r2/r3 F01, u11 r3 F02)
  const canDoTexts = (unitId, ids) => ids.map((id) => {
    if (!candoText.has(id)) warnings.push(`${unitId}: can-do ${id} has no registry text`);
    return candoText.get(id) || id;
  });

  const rows = [];
  const unitHashes = {};
  const totals = { lernschritte: 0, items: 0, reserveItems: 0, generatedItems: 0, examBlocks: 0, writingTasks: 0, speakingTasks: 0, microOutputs: 0, redemittel: 0, audioLines: 0, reviewCards: 0 };
  const rowById = new Map();

  const reserveIndex = [];
  // reserve items a Plateau may draw (banks: ['plateau']), as the learner sees them (SCHEMA §3.1)
  const plateauCandidates = [];
  for (const { file, doc: u } of units) {
    const hash = contentHash(u);
    unitHashes[u.id] = hash;
    const chunk = learnerCopy(u);
    // every correct plural of a noun is accepted where an item's key types one (SCHEMA §6 pluralVariants)
    if (pluralTwins.size) {
      eachNode(chunk, (x) => {
        const twin = withPluralTwins(x, pluralTwins);
        if (twin !== x) x.accepted = twin.accepted;
      });
    }
    const generated = [];
    if (Array.isArray(chunk.steps)) for (const s of chunk.steps) generated.push(...assignGeneratedIds(s));
    collectIds({ ...u, steps: (chunk.steps || u.steps || []).map((s, i) => ({ ...s, reserve: u.steps[i]?.reserve })) }, ids, errors, rel(file));

    // pool items: every authored item except the reserves (the reserve index carries those)
    const reserveIds = new Set();
    for (const st of Array.isArray(u.steps) ? u.steps : []) {
      for (const it of Array.isArray(st.reserve) ? st.reserve : []) {
        if (!isItem(it)) continue;
        reserveIds.add(it.id);
        reserveIndex.push({ unit: u.id, ...toReserveItem(withPluralTwins(it, pluralTwins), u.nr, st.id) });
        if (u.stage === 'T' && strs(it.banks).includes('plateau')) {
          const item = structuredClone(withPluralTwins(it, pluralTwins));
          for (const k of STRIP_ITEM_KEYS) delete item[k];
          plateauCandidates.push({ id: it.id, unit: u.id, step: st.id, item });
        }
      }
    }
    const poolItems = [];
    eachNode(u, (x) => {
      if (isItem(x) && !reserveIds.has(x.id)) poolItems.push(toPoolItem(withPluralTwins(x, pluralTwins), u.nr));
    });
    const lines = [];
    eachNode(u, (x) => {
      if (isLine(x)) lines.push(x);
    });
    const tasks = collectBankTasks(u);
    addBank(tasks, { unit: u.id }, file, shortenedSpeakingTeile(u.spec));

    const packs = (packsByUnit.get(u.id) || []).filter((p) => live.has(p.doc.lane)).sort((a, b) => a.doc.lane.localeCompare(b.doc.lane));
    for (const p of packs) {
      addBank(collectBankTasks(p.doc), { unit: u.id }, p.file);
      collectIds(p.doc, ids, errors, rel(p.file));
      eachNode(p.doc, (x) => {
        if (isItem(x)) poolItems.push(toPoolItem(x, u.nr));
      });
    }

    const minutesPlanned = minutesOf(u, profile);
    const reviewCards = reviewCardsOf(u);
    // Only a unit at stage T is complete enough to play (SCHEMA §8.1); earlier stages get a
    // syllabus row only, and their items are not counted as served content yet.
    const hasContent = u.stage === 'T' && Array.isArray(u.steps);
    const counts = {
      lernschritte: hasContent ? u.steps.length : 0,
      items: hasContent ? poolItems.length : 0,
      reserveItems: hasContent ? reserveIds.size : 0,
      generatedItems: hasContent ? generated.length : 0,
      examBlocks: hasContent
        ? u.steps.reduce((n, s) => n + (Array.isArray(s.blocks) ? s.blocks.length : 0) + (isObj(s.examBlock) ? 1 : 0), 0)
        : 0,
      writingTasks: tasks.filter((t) => t.kind === 'writing').length,
      speakingTasks: tasks.filter((t) => t.kind === 'speaking').length,
      microOutputs: tasks.filter((t) => t.kind.startsWith('micro')).length,
      newWords: (u.spec.lexiconBlocks || []).reduce((n, b) => n + b.lemmas.length, 0),
      redemittel: Array.isArray(u.redemittel) ? u.redemittel.length : 0,
      audioLines: lines.length,
      reviewCards: reviewCards.length,
    };
    for (const k of Object.keys(totals)) totals[k] += counts[k];

    if (hasContent) {
      const out = { $generated: GENERATED_MARK, ...chunk };
      if (packs.length) out.lanePacks = Object.fromEntries(packs.map((p) => [p.doc.lane, learnerCopy(p.doc).slots]));
      out.poolItems = poolItems;
      out.minutesPlanned = minutesPlanned;
      out.reviewCards = reviewCards;
      out.estimates = { lineSeconds: `words / ${WORDS_PER_SECOND} per second until the audio run measures each line` };
      out.contentHash = hash;
      outputs.push({ file: path.join(levelOut, 'units', `u${pad2(u.nr)}.json`), text: json(out) });
    }

    const pf = pruefungsfokusOf(u.spec.lanes);
    const row = {
      unit: u.id,
      nr: u.nr,
      etappe: u.etappe,
      title: u.title.de,
      canDoTitle: u.title.canDo,
      handlungsfeld: u.spec.handlungsfeld,
      canDos: canDoTexts(u.id, u.spec.canDos),
      grammar: u.spec.grammar.new.map((g) => spineLabel.get(g) || g),
      pruefungsfokus: pf,
      minutesPlanned: minutesPlanned ? minutesPlanned.total : null,
      minutesMeasured: null,
      status: u.status,
      stage: u.stage ?? null,
      canDoIds: u.spec.canDos,
      chunk: hasContent ? `units/u${pad2(u.nr)}.json` : null,
      counts,
      outline: hasContent ? outlineOf(u, spineLabel) : null,
    };
    rows.push(row);
    rowById.set(u.id, row);
  }

  // Plateaus and closing blocks: learner copies, their items and tasks; a Plateau's review set is
  // drawn here from the unit reserves (SCHEMA §10, §13), a .1 closing block learns where each of
  // its Teile comes next in the .2 level (the Teil-Karte, BLUEPRINT §5.3).
  const extraHashes = {};
  const assessmentCounts = {
    plateau: { examBlocks: 0, writingTasks: 0, speakingTasks: 0, microOutputs: 0, items: 0, reviewItems: 0 },
    closing: { examBlocks: 0, writingTasks: 0, speakingTasks: 0, microOutputs: 0, items: 0 },
  };
  const unitNrOf = (id) => Number((String(id).match(/-u(\d{2})$/) || [])[1]) || 0;
  const unitOrder = course.units.filter((id) => typeof id === 'string').sort((a, b) => unitNrOf(a) - unitNrOf(b));
  const plateauAfters = mine('plateau').map((t) => unitNrOf(t.doc.after)).filter(Boolean).sort((a, b) => a - b);
  const drawnBefore = new Set(); // review items an earlier Plateau of the level drew
  for (const kind of ['plateau', 'closing']) {
    for (const { file, doc } of mine(kind).sort((a, b) => a.doc.id.localeCompare(b.doc.id))) {
      extraHashes[doc.id] = contentHash(doc);
      collectIds(doc, ids, errors, rel(file));
      const tasks = collectBankTasks(doc);
      addBank(tasks, { source: doc.id }, file);
      const after = kind === 'plateau' ? unitNrOf(doc.after) : 12;
      const poolItems = [];
      eachNode(doc, (x) => {
        if (isItem(x)) poolItems.push(toPoolItem(withPluralTwins(x, pluralTwins), after));
      });
      const copy = learnerCopy(doc);
      if (pluralTwins.size) {
        eachNode(copy, (x) => {
          const twin = withPluralTwins(x, pluralTwins);
          if (twin !== x) x.accepted = twin.accepted;
        });
      }
      const parts = kind === 'plateau' ? (Array.isArray(doc.examTeile) ? doc.examTeile : []) : Array.isArray(doc.parts) ? doc.parts : [];
      const c = assessmentCounts[kind];
      c.examBlocks += parts.filter((p) => partKindOf(p) === 'block').length;
      c.writingTasks += tasks.filter((t) => t.kind === 'writing').length;
      c.speakingTasks += tasks.filter((t) => t.kind === 'speaking').length;
      c.microOutputs += tasks.filter((t) => t.kind.startsWith('micro')).length;
      c.items += poolItems.length;

      if (kind === 'plateau' && isObj(doc.review)) {
        const previous = plateauAfters.filter((n) => n < after).pop() || 0;
        const current = unitOrder.filter((id) => unitNrOf(id) > previous && unitNrOf(id) <= after);
        const earlier = unitOrder.filter((id) => unitNrOf(id) <= previous);
        const drawn = drawPlateauReview(plateauCandidates, {
          id: doc.id, draw: doc.review.draw, currentShare: doc.review.currentShare, current, earlier, exclude: drawnBefore,
        });
        for (const d of drawn.items) drawnBefore.add(d.id);
        if (drawn.items.length < doc.review.draw) {
          warnings.push(`${doc.id}: review set drew ${drawn.items.length} of ${doc.review.draw} items (too few reserve items with banks ['plateau'] in ${[...earlier, ...current].join(', ') || 'no compiled unit'})`);
        }
        c.reviewItems += drawn.items.length;
        copy.review = {
          ...copy.review,
          units: { current, earlier },
          drawn: { current: drawn.current.length, earlier: drawn.earlier.length },
          items: drawn.items.map((d) => ({ ...d.item, unit: d.unit, step: d.step })),
        };
      }
      if (kind === 'closing' && doc.kind === 'halbtest') {
        const templates = [...new Set(parts.map((p) => p && p.template).filter((t) => typeof t === 'string'))];
        copy.comesNext = comesNextOf(level, doc.lane, templates, {
          unitDocs: docs('unit').map((t) => t.doc),
          bundleEntries: bundles.flatMap((b) => b.doc),
        });
      }
      const out = { $generated: GENERATED_MARK, ...copy, poolItems, contentHash: extraHashes[doc.id] };
      const name = kind === 'plateau' ? `${doc.id.split('-').pop()}.json` : `${doc.id}.json`;
      outputs.push({ file: path.join(levelOut, kind === 'plateau' ? 'plateaus' : 'closing', name), text: json(out) });
    }
  }
  if (errors.length) return { outputs: [], syncDirs: [], errors, warnings, skipped };

  // Manifest (the syllabus rows plus the course-level fields the player and copy read). A unit with
  // no compiled file (not written yet, or skipped) is 'coming': its row comes from the spec bundle.
  const etappeOf = (id) => (course.etappen.find((e) => e.units.includes(id)) || {}).nr || null;
  const comingRow = (id) => {
    const e = specById.get(id);
    const sp = e && isObj(e.spec) ? e.spec : {};
    const title = e && isObj(e.title) ? e.title : {};
    const grammar = isObj(sp.grammar) ? strs(sp.grammar.new) : [];
    const canDoIds = strs(sp.canDos);
    const minutes = e ? minutesOf({}, profile) : null;
    return {
      unit: id,
      nr: Number(id.slice(-2)),
      etappe: etappeOf(id),
      title: str(title.de),
      canDoTitle: str(title.canDo),
      handlungsfeld: strs(sp.handlungsfeld),
      canDos: canDoTexts(id, canDoIds),
      grammar: grammar.map((g) => spineLabel.get(g) || g),
      pruefungsfokus: pruefungsfokusOf(sp.lanes),
      minutesPlanned: minutes ? minutes.total : null,
      minutesMeasured: null,
      status: 'coming',
      stage: null,
      canDoIds,
      chunk: null,
      counts: null,
      outline: null,
    };
  };
  const rowsInOrder = course.units.map((id) => rowById.get(id) || comingRow(id));
  const lexEntries = lexicon ? lexicon.entries : [];
  const counts = {
    units: course.units.length,
    unitsWithSpec: rows.length,
    unitsAuthored: rows.filter((r) => r.chunk).length,
    unitsComing: rowsInOrder.filter((r) => r.status === 'coming').length,
    ...totals,
    newWords: lexicon ? lexEntries.length : rows.reduce((n, r) => n + r.counts.newWords, 0),
    productiveWords: lexEntries.filter((e) => e.role === 'productive').length,
    receptiveWords: lexEntries.filter((e) => e.role === 'receptive').length,
    ruleCards: ruleCards ? ruleCards.cards.length : 0,
    canDos: new Set(rows.flatMap((r) => r.canDoIds)).size,
    plateaus: mine('plateau').length,
    closingBlocks: mine('closing').length,
    // examBlocks / writingTasks / speakingTasks / microOutputs above count the UNITS only (the
    // syllabus rows' sums, as the course pages read them). The Plateaus' and the closing block's
    // own Teile are counted apart, and `inCourse` is everything a learner of the level meets.
    inPlateaus: assessmentCounts.plateau,
    inClosing: assessmentCounts.closing,
    inCourse: Object.fromEntries(['examBlocks', 'writingTasks', 'speakingTasks', 'microOutputs'].map((k) => [
      k, totals[k] + assessmentCounts.plateau[k] + assessmentCounts.closing[k],
    ])),
  };
  const minutesByUnit = Object.fromEntries(rows.map((r) => [r.unit, r.minutesPlanned]));
  const plannedTotal = rows.reduce((n, r) => n + (r.minutesPlanned || 0), 0);
  const cardsPerUnit = rows.length ? totals.reviewCards / rows.length : 0;
  const reviewMinutesByPace = {
    model: 'compile-v0 upper bound: every review card reaches every ladder rung within the course (SRS-01 replaces it)',
    cardsPerUnit: round1(cardsPerUnit),
  };
  for (const [pace, p] of Object.entries(course.pace)) {
    const perDay = (cardsPerUnit * p.unitsPerWeek * course.review.ladderDays.length) / p.learningDays;
    reviewMinutesByPace[pace] = round1((perDay * course.review.secondsPerReview) / 60);
  }
  const levelHash = contentHash({
    course,
    units: unitHashes,
    lexicon: lexicon ? contentHash(lexicon) : null,
    ruleCards: ruleCards ? contentHash(ruleCards) : null,
    extra: extraHashes,
  });
  const manifest = {
    $generated: GENERATED_MARK,
    level,
    kind: course.kind,
    priceKey: course.priceKey,
    title: course.title,
    ...pick(course, ['honestyLineDe', 'showcase']),
    lanes: course.lanes,
    units: rowsInOrder,
    etappen: course.etappen,
    plateaus: course.plateaus,
    closing: course.closing,
    completion: course.completion,
    review: course.review,
    pace: course.pace,
    targets: course.targets,
    minutesPlanned: { units: plannedTotal, byUnit: minutesByUnit, source: 'level-profile design minutes; minutesMeasured replaces them (LGL-09)' },
    reviewMinutesByPace,
    minutesMeasured: null,
    counts,
    contentHash: levelHash,
  };
  outputs.push({ file: path.join(levelOut, 'manifest.json'), text: json(manifest) });

  // Rule cards (Form segment, repair cards) and the audio line list (input of generate-course-audio:
  // voice from the cast bible, text from `say` when present, else `de`).
  if (ruleCards) outputs.push({ file: path.join(levelOut, 'rule-cards.json'), text: json({ $generated: GENERATED_MARK, level, cards: ruleCards.cards }) });
  // The level's word list (the Kapitel's „Wortschatz" page): the lexicon as the learner reads it.
  if (lexicon) {
    const WORD_KEYS = ['id', 'lemma', 'pos', 'article', 'plural', 'plural_kind', 'role', 'unit', 'example', 'exampleEn'];
    const words = lexicon.entries.map((e) => ({
      ...Object.fromEntries(WORD_KEYS.filter((k) => e[k] !== undefined && e[k] !== null).map((k) => [k, e[k]])),
      gloss: e.gloss && e.gloss.en ? e.gloss.en : null,
    }));
    outputs.push({ file: path.join(levelOut, 'words.json'), text: json({ $generated: GENERATED_MARK, level, words }) });
  }
  // The reserve index (SCHEMA §13 `reserve.js`, JSON here like every v0 output): by unit, step, topic
  // and error tag. Only units at stage T contribute — an earlier stage has no finished reserve.
  const servable = new Set(units.filter((u) => u.doc.stage === 'T').map((u) => u.doc.id));
  const reserve = reserveIndex.filter((r) => servable.has(r.unit));
  const byKey = (key) => {
    const o = {};
    for (const r of reserve) for (const k of [].concat(r[key])) (o[k] ||= []).push(r.id);
    return Object.fromEntries(Object.entries(o).sort(([a], [b]) => (a < b ? -1 : 1)));
  };
  outputs.push({
    file: path.join(levelOut, 'reserve.json'),
    text: json({ $generated: GENERATED_MARK, level, items: reserve, byUnit: byKey('unit'), byTopic: byKey('topic'), byErrorTag: byKey('errorTags') }),
  });
  const voices = new Map(docs('casts').flatMap((t) => Object.entries(t.doc.members)));
  const audio = [];
  // voice: the cast bible for cast members, the file's own `extras` for one-off speakers (SCHEMA §3.3);
  // anonymous speakers (ansage, radio, durchsage, pruefer) get their voice in the audio run
  const addLines = (doc) => eachNode(doc, (x) => {
    if (!isLine(x)) return;
    const member = voices.get(x.speaker);
    const extra = isObj(doc.extras) ? doc.extras[x.speaker] : undefined;
    const voice = member ? member.voice.azure : extra ? extra.voice : null;
    const rate = member ? member.voice.rate : extra ? extra.rate ?? null : null;
    audio.push({ id: x.id, speaker: x.speaker, voice, rate, text: x.say || x.de });
  });
  units.forEach((u) => addLines(u.doc));
  for (const kind of ['plateau', 'closing']) mine(kind).sort((a, b) => a.doc.id.localeCompare(b.doc.id)).forEach((t) => addLines(t.doc));
  outputs.push({ file: path.join(levelOut, 'lines.json'), text: json(audio) });

  // Banks: grader input, keyed by bankKey (sorted for stable diffs).
  const sortedObj = (m) => Object.fromEntries([...m.entries()].sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0)));
  outputs.push({
    file: path.join(banksRoot, `${level}.banks.json`),
    text: json({
      $generated: GENERATED_MARK,
      level,
      prefix,
      scope: `${prefix}-`,
      writing: sortedObj(bank.writing),
      speaking: sortedObj(bank.speaking),
      micro: sortedObj(bank.micro),
    }),
  });

  // Ids ledger (ID-01): live ids of this level; ids that were live before and are gone now become
  // tombstones; a tombstoned id may never come back.
  const ledgerFile = path.join(levelOut, 'ids.ledger.json');
  let prev = { ids: {}, tombstones: {} };
  if (fs.existsSync(ledgerFile)) {
    try {
      prev = JSON.parse(fs.readFileSync(ledgerFile, 'utf8'));
    } catch {
      errors.push(`${rel(ledgerFile)}: unreadable ledger — restore it from version control before compiling`);
    }
  }
  for (const k of bank.writing.keys()) ids.set(k, { kind: 'bank' });
  for (const k of bank.speaking.keys()) ids.set(k, { kind: 'bank' });
  const tombstones = { ...(prev.tombstones || {}) };
  for (const id of ids.keys()) {
    if (tombstones[id]) errors.push(`${level}: ID-01 id "${id}" was removed earlier (tombstoned) and may not be reused — give the item a new id`);
  }
  // A unit that is not compiled in this run (not written yet, or skipped) keeps its ids live: only a
  // unit that compiles can remove an id, so a unit that fails its check for a while loses nothing.
  const processed = new Set(units.map((u) => u.doc.id));
  for (const [id, kind] of Object.entries(prev.ids || {})) {
    if (ids.has(id) || tombstones[id]) continue;
    const owner = unitOfId(id);
    if (owner && !processed.has(owner) && course.units.includes(owner)) ids.set(id, { kind });
    else tombstones[id] = { kind, removedWhen: levelHash };
  }
  if (errors.length) return { outputs: [], syncDirs: [], errors, warnings, skipped };
  const liveIds = Object.fromEntries([...ids.entries()].sort(([a], [b]) => (a < b ? -1 : 1)).map(([id, v]) => [id, v.kind]));
  const tomb = Object.fromEntries(Object.entries(tombstones).sort(([a], [b]) => (a < b ? -1 : 1)));
  outputs.push({ file: ledgerFile, text: json({ $generated: GENERATED_MARK, level, ids: liveIds, tombstones: tomb }) });

  return {
    outputs,
    syncDirs: [path.join(levelOut, 'units'), path.join(levelOut, 'plateaus'), path.join(levelOut, 'closing')],
    optionalFiles: [path.join(levelOut, 'rule-cards.json'), path.join(levelOut, 'words.json')],
    errors,
    warnings,
    skipped,
    summary: {
      units: course.units.length,
      compiled: rowsInOrder.filter((r) => r.chunk).map((r) => r.unit),
      syllabusOnly: rowsInOrder.filter((r) => !r.chunk && r.status !== 'coming').map((r) => r.unit),
      coming: rowsInOrder.filter((r) => r.status === 'coming').map((r) => r.unit),
    },
  };
}

/**
 * Write outputs; delete generated files in syncDirs, and optionalFiles, that are no longer produced.
 * With check: true nothing is written; returns the files that would change.
 */
export function writeOutputs({ outputs, syncDirs = [], optionalFiles = [] }, { check = false } = {}) {
  const changed = [];
  const produced = new Set(outputs.map((o) => path.resolve(o.file)));
  for (const o of outputs) {
    const cur = fs.existsSync(o.file) ? fs.readFileSync(o.file, 'utf8') : null;
    if (cur === o.text) continue;
    changed.push(o.file);
    if (!check) {
      fs.mkdirSync(path.dirname(o.file), { recursive: true });
      fs.writeFileSync(o.file, o.text);
    }
  }
  for (const f of optionalFiles) {
    const p = path.resolve(f);
    if (produced.has(p) || !fs.existsSync(p)) continue;
    changed.push(p);
    if (!check) fs.unlinkSync(p);
  }
  for (const dir of syncDirs) {
    if (!fs.existsSync(dir)) continue;
    for (const name of fs.readdirSync(dir).sort()) {
      const p = path.resolve(dir, name);
      if (!name.endsWith('.json') || produced.has(p)) continue;
      changed.push(p);
      if (!check) fs.unlinkSync(p);
    }
  }
  return changed;
}

/** Levels that have a course.json under a content root. */
export function levelsIn(contentRoot, { exclude = [] } = {}) {
  return [...new Set(loadTree(contentRoot, { exclude }).filter((t) => t.kind === 'course' && typeof t.doc.level === 'string').map((t) => t.doc.level))].sort();
}
