// Datenquelle für alle Shorts/Reels aus der Videobibliothek.
//
// Eine Zeile pro Clip. Titel, Text und Hashtags stehen hier, nirgends sonst —
// `texte-erzeugen.mjs` schreibt daraus die Dateien in `texte/`, `schneiden.sh`
// liest `anker` und `dauer` für den Schnitt.
//
// anker = Position im Originalvideo in Prozent der Gesamtlänge (0–100).
// Die Länge der Videos ist von hier aus nicht messbar (Supabase ist vom
// Agenten-Proxy blockiert), deshalb relative Anker statt fester Zeitstempel.
// Nach dem Schnitt einmal durchsehen und bei Bedarf den Anker anpassen.

export const KAMPAGNE = 'shorts_01';
export const BASIS = 'https://deutsch-meister.de/video-library';

export const VIDEOS = [
  {
    nr: 1,
    id: '7551ef9a-b5f0-43c0-816b-b112e38df1de',
    slug: 'german-alphabet-pronunciation-rules',
    titel: 'German Alphabet & Pronunciation Rules',
    thema: 'Alphabet',
    clips: [
      {
        anker: 8,
        titel: 'Ä, Ö, Ü — die drei Buchstaben, die es im Englischen nicht gibt',
        hook: 'Drei Punkte über dem Buchstaben ändern das ganze Wort.',
        de: 'Ä, Ö und Ü sind keine Verzierung. schon / schön sind zwei verschiedene Wörter. Wer die Umlaute überhört, hört den Unterschied nie.',
        en: 'Ä, Ö, Ü are not decoration — schon and schön are different words.',
        tags: ['DeutschLernen', 'GermanA1', 'Umlaute', 'DeutscheAussprache'],
      },
      {
        anker: 26,
        titel: 'Das ß — wann es statt ss steht',
        hook: 'Ein Buchstabe, eine Regel, und du machst den Fehler nie wieder.',
        de: 'Nach langem Vokal und nach Diphthong steht ß: Straße, weiß. Nach kurzem Vokal steht ss: Fluss, muss.',
        en: 'ß after a long vowel or diphthong, ss after a short one. One rule, no exceptions worth memorising at A1.',
        tags: ['DeutschLernen', 'GermanA1', 'Rechtschreibung'],
      },
      {
        anker: 44,
        titel: 'Das deutsche R kommt aus dem Hals, nicht von der Zunge',
        hook: 'Der häufigste Akzent-Verräter bei Anfängern.',
        de: 'Das deutsche R wird hinten im Rachen gebildet. Wer es wie im Englischen oder Arabischen rollt, klingt sofort fremd.',
        en: 'The German R is made in the throat. Rolling it is the fastest way to sound foreign.',
        tags: ['DeutschLernen', 'DeutscheAussprache', 'GermanA1'],
      },
      {
        anker: 62,
        titel: 'V und W sind im Deutschen vertauscht',
        hook: 'Wasser klingt wie "Vasser". Vater klingt wie "Fater".',
        de: 'Deutsches W = englisches V. Deutsches V = englisches F. Zwei Buchstaben, die fast jeder Anfänger falsch herum liest.',
        en: 'German W sounds like English V. German V sounds like English F.',
        tags: ['DeutschLernen', 'DeutscheAussprache', 'GermanA1'],
      },
      {
        anker: 80,
        titel: 'Z klingt nie wie Z',
        hook: 'Zahl, Zeit, zehn — alle beginnen mit "ts".',
        de: 'Das deutsche Z ist immer ts. Nie das weiche Z aus dem Englischen. Zehn spricht man "tsehn".',
        en: 'German Z is always "ts" — never the soft English Z.',
        tags: ['DeutschLernen', 'DeutscheAussprache', 'GermanA1'],
      },
    ],
  },
  {
    nr: 2,
    id: '69a66686-663b-4c0a-b408-2f66b72dba69',
    slug: 'german-letter-combinations-mastering-pronunciation',
    titel: 'German Letter Combinations: Mastering Pronunciation',
    thema: 'Buchstabenkombinationen',
    clips: [
      {
        anker: 8,
        titel: 'SCH — drei Buchstaben, ein Laut',
        hook: 'Schule, Schnee, schön — immer derselbe Anfang.',
        de: 'SCH ist im Deutschen ein einziger Laut, wie das englische "sh". Nicht s-c-h einzeln sprechen.',
        en: 'SCH is one sound, like English "sh". Never three separate letters.',
        tags: ['DeutschLernen', 'DeutscheAussprache', 'GermanA1'],
      },
      {
        anker: 26,
        titel: 'CH hat zwei Klänge — und der Vokal davor entscheidet',
        hook: 'ich und ach klingen komplett verschieden.',
        de: 'Nach i, e, ä, ö, ü: weiches ch (ich, echt). Nach a, o, u: hartes ch aus dem Rachen (ach, Buch).',
        en: 'Soft ch after i/e/ä/ö/ü, hard ch after a/o/u. The vowel before decides.',
        tags: ['DeutschLernen', 'DeutscheAussprache', 'GermanA1'],
      },
      {
        anker: 44,
        titel: 'EI und IE — die Regel, die nie versagt',
        hook: 'Du sprichst den zweiten Buchstaben.',
        de: 'EI klingt wie "ai" (mein, Zeit). IE klingt wie langes "ii" (Liebe, sieben). Immer der zweite Buchstabe gewinnt.',
        en: 'In EI and IE, you pronounce the second letter. Always.',
        tags: ['DeutschLernen', 'DeutscheAussprache', 'GermanA1'],
      },
      {
        anker: 62,
        titel: 'SP und ST am Wortanfang werden zu "schp" und "scht"',
        hook: 'Sport heißt "Schport". Stadt heißt "Schtadt".',
        de: 'Steht SP oder ST am Wortanfang, spricht man sch: spielen, Stunde, Straße. In der Wortmitte bleibt es s.',
        en: 'SP and ST at the start of a word become "schp" and "scht".',
        tags: ['DeutschLernen', 'DeutscheAussprache', 'GermanA1'],
      },
      {
        anker: 80,
        titel: 'EU und ÄU klingen beide wie "oi"',
        hook: 'Zwei Schreibweisen, ein Laut.',
        de: 'heute, neun, Häuser, Bäume — EU und ÄU klingen identisch, wie das englische "oy" in boy.',
        en: 'EU and ÄU sound identical — like "oy" in boy.',
        tags: ['DeutschLernen', 'DeutscheAussprache', 'GermanA1'],
      },
    ],
  },
  {
    nr: 3,
    id: '55353665-adb7-4222-a82d-cf5fb7b712d7',
    slug: 'mastering-der-die-das-german-articles-explained',
    titel: 'Mastering Der, Die, Das: German Articles Explained',
    thema: 'Artikel',
    clips: [
      {
        anker: 8,
        titel: 'Warum Deutsch drei Artikel hat — und Englisch nur einen',
        hook: 'the wird zu der, die oder das. Und es gibt kein System dahinter.',
        de: 'Jedes deutsche Substantiv hat ein Geschlecht: maskulin, feminin oder neutral. Das Geschlecht hat nichts mit der Bedeutung zu tun — Mädchen ist neutral.',
        en: 'Every German noun carries a gender, and it rarely matches meaning. Mädchen (girl) is neuter.',
        tags: ['DeutschLernen', 'GermanA1', 'DerDieDas', 'DeutscheGrammatik'],
      },
      {
        anker: 26,
        titel: 'Diese Endungen sind IMMER die',
        hook: '-ung, -heit, -keit, -schaft, -ion — ohne Ausnahme.',
        de: 'Wortendungen verraten das Geschlecht. -ung, -heit, -keit, -schaft, -tion, -tät sind immer feminin: die Zeitung, die Freiheit, die Universität.',
        en: 'Words ending in -ung, -heit, -keit, -schaft, -tion, -tät are always feminine.',
        tags: ['DeutschLernen', 'DerDieDas', 'DeutscheGrammatik', 'GermanA1'],
      },
      {
        anker: 44,
        titel: '-chen und -lein sind immer das',
        hook: 'Deshalb ist das Mädchen neutral.',
        de: 'Jede Verkleinerungsform auf -chen oder -lein ist neutral — egal was das Wort bedeutet. das Mädchen, das Brötchen, das Häuschen.',
        en: 'Every diminutive in -chen or -lein is neuter, whatever the word means.',
        tags: ['DeutschLernen', 'DerDieDas', 'DeutscheGrammatik', 'GermanA1'],
      },
      {
        anker: 62,
        titel: 'Tage, Monate, Jahreszeiten — alle der',
        hook: 'der Montag, der Januar, der Sommer.',
        de: 'Alle Wochentage, Monate und Jahreszeiten sind maskulin. Dazu Himmelsrichtungen und Wetter: der Norden, der Regen, der Wind.',
        en: 'Days, months, seasons, directions and weather are all masculine.',
        tags: ['DeutschLernen', 'DerDieDas', 'DeutscheGrammatik', 'GermanA1'],
      },
      {
        anker: 80,
        titel: 'Lern den Artikel MIT dem Wort — nie danach',
        hook: 'Der häufigste Fehler beim Vokabellernen.',
        de: 'Schreib nie "Tisch" in deine Liste. Schreib "der Tisch". Den Artikel später nachzulernen kostet dich dreimal so viel Zeit.',
        en: 'Never write "Tisch" in your vocab list. Write "der Tisch". Adding the article later costs three times the effort.',
        tags: ['DeutschLernen', 'DerDieDas', 'Lerntipp', 'GermanA1'],
      },
    ],
  },
  {
    nr: 4,
    id: '9e043ea2-56ce-4c6f-bb5a-f5125bbd0d74',
    slug: 'german-indefinite-articles-ein-eine-explained',
    titel: 'German Indefinite Articles: Ein & Eine Explained',
    thema: 'Unbestimmte Artikel',
    clips: [
      {
        anker: 8,
        titel: 'ein oder eine? Der bestimmte Artikel verrät es',
        hook: 'Wenn du der/die/das kennst, kennst du auch ein/eine.',
        de: 'der → ein, das → ein, die → eine. Mehr Formen gibt es im Nominativ nicht.',
        en: 'der → ein, das → ein, die → eine. That is the whole nominative table.',
        tags: ['DeutschLernen', 'GermanA1', 'DeutscheGrammatik'],
      },
      {
        anker: 26,
        titel: 'Wann "ein Mann" und wann "der Mann"?',
        hook: 'Irgendeiner oder genau dieser.',
        de: 'ein = irgendeiner, zum ersten Mal erwähnt. der = genau dieser, beide wissen welcher. Ich sehe einen Mann. Der Mann ist groß.',
        en: 'ein = one of many, first mention. der = that specific one you both already know.',
        tags: ['DeutschLernen', 'GermanA1', 'DeutscheGrammatik'],
      },
      {
        anker: 44,
        titel: 'kein — so verneint man ein Substantiv',
        hook: 'Nicht "nicht ein". Immer kein.',
        de: 'kein ist ein + Verneinung: Ich habe kein Auto. Ich habe keine Zeit. Die Endungen folgen ein/eine exakt.',
        en: 'To negate a noun, use kein — never "nicht ein". Endings follow ein/eine exactly.',
        tags: ['DeutschLernen', 'GermanA1', 'DeutscheGrammatik'],
      },
      {
        anker: 62,
        titel: 'ein hat keinen Plural — kein schon',
        hook: 'Ein Auto. Autos. Keine Autos.',
        de: 'Im Plural fällt ein einfach weg: ein Buch → Bücher. Die Verneinung bleibt aber: keine Bücher.',
        en: 'ein simply disappears in the plural — but keine stays.',
        tags: ['DeutschLernen', 'GermanA1', 'DeutscheGrammatik'],
      },
      {
        anker: 80,
        titel: 'Drei Sätze, die den Unterschied zeigen',
        hook: 'Einmal gehört, nie wieder verwechselt.',
        de: 'Ich kaufe ein Buch. — irgendeins. Ich kaufe das Buch. — genau dieses. Ich kaufe kein Buch. — gar keins.',
        en: 'A book / the book / no book — three sentences, three meanings.',
        tags: ['DeutschLernen', 'GermanA1', 'DeutscheGrammatik'],
      },
    ],
  },
  {
    nr: 5,
    id: 'c22ee1dd-4a8f-489d-806e-ce9fade3146c',
    slug: 'german-personal-pronouns-the-complete-guide',
    titel: 'German Personal Pronouns: The Complete Guide',
    thema: 'Personalpronomen',
    clips: [
      {
        anker: 8,
        titel: 'Alle acht Personalpronomen in 45 Sekunden',
        hook: 'ich, du, er, sie, es, wir, ihr, sie.',
        de: 'Das ist die komplette Liste im Nominativ. Jeder deutsche Satz mit einer Person beginnt mit einem dieser Wörter.',
        en: 'ich, du, er, sie, es, wir, ihr, sie — the complete nominative list.',
        tags: ['DeutschLernen', 'GermanA1', 'DeutscheGrammatik'],
      },
      {
        anker: 26,
        titel: 'du oder Sie? Die Entscheidung in einem Satz',
        hook: 'Falsch gewählt und du wirkst unhöflich — oder distanziert.',
        de: 'Sie für Fremde, Vorgesetzte, Behörden, Ärzte. du für Familie, Freunde, Kinder, Kommilitonen. Im Zweifel Sie — und warten, bis das du angeboten wird.',
        en: 'Sie for strangers and authority. du for family and friends. When unsure: Sie, and wait to be offered du.',
        tags: ['DeutschLernen', 'GermanA1', 'DeutschInDeutschland'],
      },
      {
        anker: 44,
        titel: 'sie, sie und Sie — drei Wörter, die gleich klingen',
        hook: 'Sie hat drei Bedeutungen. Das Verb sagt dir welche.',
        de: 'sie ist = she is. sie sind = they are. Sie sind = you are (höflich). Das Verb entscheidet, nicht das Pronomen.',
        en: 'sie ist = she. sie sind = they. Sie sind = you (formal). The verb tells you which.',
        tags: ['DeutschLernen', 'GermanA1', 'DeutscheGrammatik'],
      },
      {
        anker: 62,
        titel: 'Für Dinge sagt man nicht immer "es"',
        hook: 'Der Tisch ist er. Die Tür ist sie.',
        de: 'Das Pronomen folgt dem Artikel, nicht der Bedeutung. der Tisch → er ist neu. die Tür → sie ist offen. das Buch → es ist dick.',
        en: 'The pronoun follows the article, not the meaning. der Tisch → er. die Tür → sie.',
        tags: ['DeutschLernen', 'GermanA1', 'DeutscheGrammatik'],
      },
      {
        anker: 80,
        titel: 'ihr oder Sie, wenn du mit mehreren sprichst',
        hook: 'Die Mehrzahl von du ist nicht Sie.',
        de: 'ihr = mehrere Menschen, die du duzt. Sie = mehrere Menschen, die du siezt. Ihr kommt morgen. Sie kommen morgen.',
        en: 'ihr = several people you address informally. Sie = several you address formally.',
        tags: ['DeutschLernen', 'GermanA1', 'DeutscheGrammatik'],
      },
    ],
  },
  {
    nr: 6,
    id: 'a2c76a90-e9f7-43f5-be97-64e5f93b4ece',
    slug: 'german-pronoun-cases-nominative-accusative-dative',
    titel: 'German Pronoun Cases: Nominative, Accusative & Dative',
    thema: 'Pronomen im Fall',
    clips: [
      {
        anker: 8,
        titel: 'ich → mich → mir',
        hook: 'Ein Pronomen, drei Formen, drei Rollen.',
        de: 'ich bin der Handelnde. mich ist das direkte Ziel: Er sieht mich. mir ist der Empfänger: Er gibt mir das Buch.',
        en: 'ich (I) → mich (me, direct) → mir (to me).',
        tags: ['DeutschLernen', 'GermanA1', 'DeutscheGrammatik', 'Akkusativ'],
      },
      {
        anker: 26,
        titel: 'du → dich → dir',
        hook: 'Dieselbe Logik, andere Person.',
        de: 'Ich sehe dich. Ich gebe dir das Buch. Wer die Rolle im Satz erkennt, wählt die Form automatisch.',
        en: 'du → dich → dir. Same logic, second person.',
        tags: ['DeutschLernen', 'GermanA1', 'DeutscheGrammatik'],
      },
      {
        anker: 44,
        titel: 'er → ihn → ihm',
        hook: 'Das ihn, das alle vergessen.',
        de: 'Nur die maskuline Form ändert sich sichtbar: er → ihn im Akkusativ, ihm im Dativ. sie und es bleiben im Akkusativ gleich.',
        en: 'Only the masculine changes visibly: er → ihn → ihm. sie and es stay the same in the accusative.',
        tags: ['DeutschLernen', 'GermanA1', 'DeutscheGrammatik', 'Akkusativ'],
      },
      {
        anker: 62,
        titel: 'wir, ihr, sie im Akkusativ und Dativ',
        hook: 'uns, euch, ihnen — fertig.',
        de: 'wir → uns → uns. ihr → euch → euch. sie → sie → ihnen. Die Plurale sind die einfachsten im ganzen System.',
        en: 'wir → uns. ihr → euch. sie → sie → ihnen. The plurals are the easy part.',
        tags: ['DeutschLernen', 'GermanA1', 'DeutscheGrammatik'],
      },
      {
        anker: 80,
        titel: 'Die ganze Tabelle in einem Clip',
        hook: 'Speichern und einmal am Tag ansehen.',
        de: 'mich dich ihn sie es uns euch sie — Akkusativ. mir dir ihm ihr ihm uns euch ihnen — Dativ. Zwei Reihen, mehr braucht A1 nicht.',
        en: 'Two rows cover the whole A1 pronoun system. Save this one.',
        tags: ['DeutschLernen', 'GermanA1', 'DeutscheGrammatik'],
      },
    ],
  },
  {
    nr: 7,
    id: '8846a19f-c76b-4b20-9c3b-5728563a1a9c',
    slug: 'german-verb-sein-how-to-say-to-be',
    titel: 'German Verb Sein: How to Say "To Be"',
    thema: 'sein',
    clips: [
      {
        anker: 8,
        titel: 'ich bin, du bist, er ist',
        hook: 'Das erste Verb, das du wirklich können musst.',
        de: 'sein ist das häufigste Verb im Deutschen. Die Singularformen sehen dem Infinitiv nicht ähnlich — auswendig lernen, nicht ableiten.',
        en: 'ich bin, du bist, er ist. The singular forms look nothing like the infinitive — memorise them.',
        tags: ['DeutschLernen', 'GermanA1', 'DeutscheVerben'],
      },
      {
        anker: 26,
        titel: 'wir sind, ihr seid, sie sind',
        hook: 'seid mit d — nicht seit mit t.',
        de: 'ihr seid (Verb) und seit (Zeitangabe) klingen identisch. Der Schreibfehler ist einer der häufigsten überhaupt — auch bei Muttersprachlern.',
        en: 'ihr seid (verb) vs seit (since) sound identical. Germans get this wrong too.',
        tags: ['DeutschLernen', 'GermanA1', 'DeutscheVerben', 'Rechtschreibung'],
      },
      {
        anker: 44,
        titel: 'Warum sein so unregelmäßig ist',
        hook: 'Es ist nicht kaputt — es ist alt.',
        de: 'Die häufigsten Verben einer Sprache sind fast immer unregelmäßig. Sie werden so oft benutzt, dass sie sich nie angeglichen haben.',
        en: 'The most-used verbs in any language stay irregular — they are used too often to level out.',
        tags: ['DeutschLernen', 'GermanA1', 'DeutscheVerben'],
      },
      {
        anker: 62,
        titel: 'Fragen mit sein — Verb nach vorn',
        hook: 'Bist du müde? Ist das richtig?',
        de: 'Für eine Ja/Nein-Frage stellst du einfach das Verb an den Anfang. Du bist müde → Bist du müde?',
        en: 'For a yes/no question, move the verb to the front. That is the whole rule.',
        tags: ['DeutschLernen', 'GermanA1', 'DeutscheVerben'],
      },
      {
        anker: 80,
        titel: 'Fünf Sätze mit sein, die du täglich brauchst',
        hook: 'Ich bin müde. Das ist gut. Wo ist …?',
        de: 'Ich bin müde. Ich bin fertig. Das ist gut. Wo ist der Bahnhof? Wie spät ist es? Fünf Sätze, jeden Tag benutzbar.',
        en: 'Five sentences with sein you will use every single day.',
        tags: ['DeutschLernen', 'GermanA1', 'DeutscheVerben'],
      },
    ],
  },
  {
    nr: 8,
    id: '64c72eff-d01f-48bb-84e4-397545cb7532',
    slug: 'german-verb-haben-how-to-say-to-have',
    titel: 'German Verb Haben: How to Say "To Have"',
    thema: 'haben',
    clips: [
      {
        anker: 8,
        titel: 'ich habe, du hast, er hat',
        hook: 'Das zweitwichtigste Verb nach sein.',
        de: 'Im Singular fällt das b weg: habe, hast, hat. Im Plural kommt es zurück: haben, habt, haben.',
        en: 'The b drops in the singular — habe, hast, hat — and returns in the plural.',
        tags: ['DeutschLernen', 'GermanA1', 'DeutscheVerben'],
      },
      {
        anker: 26,
        titel: 'wir haben, ihr habt, sie haben',
        hook: 'Zwei von drei Pluralformen sind identisch.',
        de: 'wir haben und sie haben sind gleich. Nur ihr habt fällt heraus. Das gilt für fast jedes deutsche Verb.',
        en: 'wir haben and sie haben are identical — only ihr habt differs. True for almost every German verb.',
        tags: ['DeutschLernen', 'GermanA1', 'DeutscheVerben'],
      },
      {
        anker: 44,
        titel: 'Nach haben kommt immer der Akkusativ',
        hook: 'Ich habe einen Bruder — nicht ein Bruder.',
        de: 'haben verlangt ein direktes Objekt im Akkusativ. Deshalb wird ein zu einen: Ich habe einen Hund, einen Termin, einen Plan.',
        en: 'haben always takes the accusative — that is why ein becomes einen.',
        tags: ['DeutschLernen', 'GermanA1', 'Akkusativ', 'DeutscheVerben'],
      },
      {
        anker: 62,
        titel: 'Ich habe Hunger — nicht "ich bin hungrig"',
        hook: 'Deutsch hat man Hunger, Durst, Angst und Zeit.',
        de: 'Wo das Englische "to be" nimmt, nimmt das Deutsche haben: Ich habe Hunger. Ich habe Angst. Ich habe Zeit. Ohne Artikel.',
        en: 'German "has" hunger, thirst, fear and time — where English "is". And without an article.',
        tags: ['DeutschLernen', 'GermanA1', 'DeutscheVerben'],
      },
      {
        anker: 80,
        titel: 'haben in Frage und Verneinung',
        hook: 'Hast du Zeit? Ich habe keine Zeit.',
        de: 'Frage: Verb nach vorn — Hast du …? Verneinung mit Substantiv: kein — Ich habe kein Geld, keine Zeit, keinen Termin.',
        en: 'Question: verb first. Negation of a noun: kein, never nicht ein.',
        tags: ['DeutschLernen', 'GermanA1', 'DeutscheVerben'],
      },
    ],
  },
  {
    nr: 9,
    id: '31a0c195-7cd6-4454-915e-d45937cee18b',
    slug: 'the-nominative-case-subjects-in-german',
    titel: 'The Nominative Case: Subjects in German',
    thema: 'Nominativ',
    clips: [
      {
        anker: 8,
        titel: 'Was der Nominativ überhaupt ist',
        hook: 'Der Fall, in dem jedes Wort im Wörterbuch steht.',
        de: 'Der Nominativ markiert das Subjekt — wer oder was die Handlung ausführt. Er ist die Grundform: der Mann, die Frau, das Kind.',
        en: 'The nominative marks the subject — who is doing the action. It is the dictionary form.',
        tags: ['DeutschLernen', 'GermanA1', 'Nominativ', 'DeutscheGrammatik'],
      },
      {
        anker: 26,
        titel: 'Wer oder was? — die Testfrage',
        hook: 'Drei Sekunden, und du weißt es.',
        de: 'Frag „Wer oder was macht das?" Die Antwort steht im Nominativ. Der Hund beißt den Mann. Wer beißt? Der Hund.',
        en: 'Ask "who or what is doing it?" — the answer is your nominative.',
        tags: ['DeutschLernen', 'GermanA1', 'Nominativ', 'DeutscheGrammatik'],
      },
      {
        anker: 44,
        titel: 'der, die, das — und im Plural immer die',
        hook: 'Die einfachste Zeile der ganzen Tabelle.',
        de: 'Nominativ: der Mann, die Frau, das Kind, die Kinder. Nichts verändert sich. Deshalb lernt man diesen Fall zuerst.',
        en: 'der, die, das and die in the plural. Nothing changes — which is why you learn this case first.',
        tags: ['DeutschLernen', 'GermanA1', 'Nominativ', 'DerDieDas'],
      },
      {
        anker: 62,
        titel: 'Nach sein steht wieder der Nominativ',
        hook: 'Der einzige Fall, in dem zwei Nominative im Satz stehen.',
        de: 'Das ist der Lehrer. Er ist mein Bruder. Nach sein, werden und bleiben folgt kein Objekt, sondern ein zweiter Nominativ.',
        en: 'After sein, werden and bleiben there is no object — a second nominative follows.',
        tags: ['DeutschLernen', 'GermanA1', 'Nominativ', 'DeutscheGrammatik'],
      },
      {
        anker: 80,
        titel: 'Subjekt finden, ohne nachzudenken',
        hook: 'Nicht das erste Wort. Das handelnde Wort.',
        de: 'Den Mann beißt der Hund — das Subjekt ist der Hund, obwohl es hinten steht. Der Artikel entscheidet, nicht die Position.',
        en: 'Word order does not decide the subject — the article does.',
        tags: ['DeutschLernen', 'GermanA1', 'Nominativ', 'DeutscheGrammatik'],
      },
    ],
  },
  {
    nr: 10,
    id: 'ecb2c540-8469-4e29-8a61-bbc8833e99b5',
    slug: 'asking-questions-in-the-nominative-case',
    titel: 'Asking Questions in the Nominative Case',
    thema: 'Fragen im Nominativ',
    clips: [
      {
        anker: 8,
        titel: 'Wer? für Menschen, Was? für Dinge',
        hook: 'Zwei Fragewörter decken den halben Alltag ab.',
        de: 'Wer ist das? — bei Personen. Was ist das? — bei Dingen. Beide fragen nach dem Subjekt, beide stehen im Nominativ.',
        en: 'Wer? for people, Was? for things. Both ask for the subject.',
        tags: ['DeutschLernen', 'GermanA1', 'Nominativ', 'DeutscheGrammatik'],
      },
      {
        anker: 26,
        titel: 'Welcher, welche, welches',
        hook: 'Wenn du aus mehreren auswählst.',
        de: 'Welcher folgt dem Artikel: welcher Mann, welche Frau, welches Kind. Wer der/die/das kennt, kennt auch diese Formen.',
        en: 'welcher follows der/die/das exactly — welcher Mann, welche Frau, welches Kind.',
        tags: ['DeutschLernen', 'GermanA1', 'DeutscheGrammatik'],
      },
      {
        anker: 44,
        titel: 'Ja/Nein-Fragen — Verb an Position eins',
        hook: 'Kein do, kein does. Nur umstellen.',
        de: 'Das Englische braucht ein Hilfsverb, das Deutsche nicht. Du hast Zeit → Hast du Zeit? Mehr passiert nicht.',
        en: 'No "do" needed. Just move the verb to the front.',
        tags: ['DeutschLernen', 'GermanA1', 'DeutscheGrammatik'],
      },
      {
        anker: 62,
        titel: 'Die W-Fragen auf einen Blick',
        hook: 'Wer, was, wo, wann, wie, warum.',
        de: 'Sechs Wörter, mit denen du jede Grundfrage stellst. Das Verb steht immer direkt dahinter: Wo wohnst du? Wann kommst du?',
        en: 'Six question words cover every basic question — and the verb always comes straight after.',
        tags: ['DeutschLernen', 'GermanA1', 'DeutscheGrammatik'],
      },
      {
        anker: 80,
        titel: '„Wer ist das?" — dein erster echter Dialog',
        hook: 'Eine Frage, eine Antwort, fertig.',
        de: 'Wer ist das? — Das ist mein Bruder. Was ist das? — Das ist ein Buch. Zwei Muster, die in jedem Gespräch vorkommen.',
        en: 'Two patterns that show up in every single conversation.',
        tags: ['DeutschLernen', 'GermanA1', 'DeutschSprechen'],
      },
    ],
  },
  {
    nr: 11,
    id: '1799188c-86ee-42c3-8552-bd08abcc0290',
    slug: 'the-accusative-case-direct-objects-in-german',
    titel: 'The Accusative Case: Direct Objects in German',
    thema: 'Akkusativ',
    clips: [
      {
        anker: 8,
        titel: 'der wird zu den. Das ist der ganze Akkusativ.',
        hook: 'Ein einziger Artikel ändert sich. Einer.',
        de: 'Im Akkusativ wird aus der ein den. die bleibt die, das bleibt das, die (Plural) bleibt die. Wer das weiß, kann den Fall.',
        en: 'In the accusative only der changes — to den. Everything else stays.',
        tags: ['DeutschLernen', 'GermanA1', 'Akkusativ', 'DeutscheGrammatik'],
      },
      {
        anker: 26,
        titel: 'Wen oder was? — die Testfrage',
        hook: 'Wer handelt, wen trifft es.',
        de: 'Ich sehe den Mann. Wen sehe ich? Den Mann. Die Antwort auf „wen oder was" steht immer im Akkusativ.',
        en: 'Ask "whom or what?" — the answer is your accusative object.',
        tags: ['DeutschLernen', 'GermanA1', 'Akkusativ', 'DeutscheGrammatik'],
      },
      {
        anker: 44,
        titel: 'die und das ändern sich nicht — wirklich nicht',
        hook: 'Die Hälfte der Arbeit fällt einfach weg.',
        de: 'Ich sehe die Frau. Ich sehe das Kind. Ich sehe die Kinder. Identisch mit dem Nominativ. Nur der maskuline Artikel bewegt sich.',
        en: 'die and das are identical in the nominative and accusative. Only the masculine moves.',
        tags: ['DeutschLernen', 'GermanA1', 'Akkusativ'],
      },
      {
        anker: 62,
        titel: 'Diese Verben verlangen immer den Akkusativ',
        hook: 'haben, sehen, kaufen, brauchen, essen.',
        de: 'Die häufigsten Alltagsverben nehmen ein direktes Objekt: Ich habe einen Termin. Ich brauche den Schlüssel. Ich kaufe das Brot.',
        en: 'haben, sehen, kaufen, brauchen, essen — the everyday verbs all take a direct object.',
        tags: ['DeutschLernen', 'GermanA1', 'Akkusativ', 'DeutscheVerben'],
      },
      {
        anker: 80,
        titel: 'Subjekt oder Objekt? Der Artikel verrät es',
        hook: 'Der Mann sieht den Hund. Den Mann sieht der Hund.',
        de: 'Beide Sätze sind korrekt und bedeuten das Gegenteil. Im Deutschen entscheidet der Fall, nicht die Reihenfolge — anders als im Englischen.',
        en: 'Both sentences are correct and mean opposite things. In German the case decides, not the word order.',
        tags: ['DeutschLernen', 'GermanA1', 'Akkusativ', 'DeutscheGrammatik'],
      },
    ],
  },
];

export function link(video, clipIndex, plattform) {
  const quelle = { yt: 'youtube', ig: 'instagram', fb: 'facebook' }[plattform];
  const inhalt = `dm-s-${video.nr}-${clipIndex + 1}-${plattform}`;
  return `${BASIS}/${video.id}?utm_source=${quelle}&utm_medium=organic_short&utm_campaign=${KAMPAGNE}&utm_content=${inhalt}`;
}

export function clipName(video, clipIndex) {
  return `${String(video.nr).padStart(2, '0')}-${video.slug}--clip-${clipIndex + 1}`;
}
