#!/usr/bin/env python3
"""Build words-a2.1-additions.json. Data-only; the validator does the checking."""
import json, os

S = os.path.dirname(os.path.abspath(__file__))

# (german, english, article, plural, example_sentence)
DATA = {
"Health & Body": [
 ("Gesundheit", "health", "die", None, "Meine Gesundheit ist mir sehr wichtig."),
 ("Krankheit", "illness, disease", "die", "Krankheiten", "Die Krankheit dauert meistens eine Woche."),
 ("Verletzung", "injury", "die", "Verletzungen", "Der Arzt untersucht die Verletzung am Knie."),
 ("Wunde", "wound", "die", "Wunden", "Die Wunde am Finger tut noch weh."),
 ("Pflaster", "plaster, band-aid", "das", "Pflaster", "Ich klebe ein Pflaster auf die Wunde."),
 ("Notfall", "emergency", "der", "Notfälle", "Im Notfall wählst du die Nummer 112."),
 ("Patient", "patient (male)", "der", "Patienten", "Der Patient wartet schon eine Stunde."),
 ("Kinderarzt", "pediatrician", "der", "Kinderärzte", "Wir gehen mit dem Baby zum Kinderarzt."),
 ("Blut", "blood", "das", None, "Der Arzt nimmt mir heute etwas Blut ab."),
 ("Operation", "operation, surgery", "die", "Operationen", "Die Operation dauert ungefähr zwei Stunden."),
 ("Zahnschmerzen", "toothache (Pl.)", None, None, "Ich habe seit gestern Zahnschmerzen."),
 ("Rückenschmerzen", "back pain (Pl.)", None, None, "Mein Vater hat oft Rückenschmerzen."),
 ("Tropfen", "drop, drops (medicine)", "der", "Tropfen", "Der Arzt gibt mir Tropfen für die Nase."),
 ("Bewegung", "exercise, movement", "die", "Bewegungen", "Bewegung ist gut für den Rücken."),
 ("behandeln", "to treat", None, None, "Die Ärztin behandelt meine Erkältung."),
 ("heilen", "to heal", None, None, "Die Wunde heilt in ein paar Tagen."),
 ("atmen", "to breathe", None, None, "Der Patient atmet ruhig und langsam."),
 ("schwitzen", "to sweat", None, None, "Bei Fieber schwitzt man oft in der Nacht."),
 ("messen", "to measure (misst)", None, None, "Wir messen das Fieber jeden Morgen."),
 ("schwach", "weak", None, None, "Nach der Grippe bin ich noch schwach."),
 ("verletzt", "injured, hurt", None, None, "Mein Bruder ist am Arm verletzt."),
 ("ungesund", "unhealthy", None, None, "Zu viel Zucker ist sehr ungesund."),
],
"Home & Moving": [
 ("Erdgeschoss", "ground floor", "das", "Erdgeschosse", "Unsere Wohnung liegt im Erdgeschoss."),
 ("Dachboden", "attic", "der", "Dachböden", "Die alten Kartons stehen auf dem Dachboden."),
 ("Strom", "electricity", "der", None, "Der Strom ist bei uns sehr teuer."),
 ("Umzugskarton", "moving box", "der", "Umzugskartons", "Wir brauchen noch zehn Umzugskartons."),
 ("Hausordnung", "house rules", "die", "Hausordnungen", "Die Hausordnung hängt neben dem Briefkasten."),
 ("Klingel", "doorbell", "die", "Klingeln", "Die Klingel an der Haustür geht nicht."),
 ("Briefkasten", "mailbox, letterbox", "der", "Briefkästen", "Mein Name steht unten am Briefkasten."),
 ("Treppenhaus", "stairwell", "das", "Treppenhäuser", "Im Treppenhaus darf man nicht rauchen."),
 ("Mülltonne", "rubbish bin", "die", "Mülltonnen", "Die Mülltonne steht hinter dem Haus."),
 ("Schlüssel", "key", "der", "Schlüssel", "Der Vermieter gibt mir zwei Schlüssel."),
 ("Kündigung", "notice, termination", "die", "Kündigungen", "Die Kündigung für die Wohnung ist fertig."),
 ("Haustür", "front door", "die", "Haustüren", "Bitte mach die Haustür wieder zu."),
 ("Nachbarschaft", "neighbourhood", "die", "Nachbarschaften", "Unsere Nachbarschaft ist ruhig und freundlich."),
 ("Wäsche", "laundry, washing", "die", None, "Die Wäsche hängt schon auf dem Balkon."),
 ("mieten", "to rent (from someone)", None, None, "Wir mieten ab Mai eine neue Wohnung."),
 ("vermieten", "to rent out", None, None, "Meine Tante vermietet zwei Zimmer an Studenten."),
 ("streichen", "to paint (a wall) (hat gestrichen)", None, None, "Wir streichen die Wand im Schlafzimmer weiß."),
 ("einrichten", "to furnish, to set up", None, None, "Wir richten das Kinderzimmer neu ein."),
 ("putzen", "to clean", None, None, "Am Samstag putze ich das Bad."),
 ("gemütlich", "cosy, comfortable", None, None, "Das Wohnzimmer bei euch ist sehr gemütlich."),
 ("schmutzig", "dirty", None, None, "Die Fenster sind nach dem Winter schmutzig."),
 ("eng", "narrow, tight", None, None, "Der Flur in der Wohnung ist eng."),
],
"Offices & Forms": [
 ("Amt", "public office, authority", "das", "Ämter", "Das Amt ist heute bis sechzehn Uhr geöffnet."),
 ("Behörde", "authority, public agency", "die", "Behörden", "Die Behörde schickt mir einen Brief."),
 ("Bürgeramt", "citizens' office", "das", "Bürgerämter", "Im Bürgeramt bekommst du deinen Ausweis."),
 ("Anmeldung", "registration", "die", "Anmeldungen", "Die Anmeldung für die Wohnung dauert zehn Minuten."),
 ("Abmeldung", "deregistration", "die", "Abmeldungen", "Für die Abmeldung brauchst du den Ausweis."),
 ("Antrag", "application (form)", "der", "Anträge", "Ich gebe den Antrag morgen im Amt ab."),
 ("Stempel", "stamp (official)", "der", "Stempel", "Auf dem Formular fehlt noch der Stempel."),
 ("Bescheinigung", "certificate, confirmation", "die", "Bescheinigungen", "Die Bescheinigung vom Arzt bringe ich mit."),
 ("Ausweis", "ID card", "der", "Ausweise", "Zeigen Sie mir bitte Ihren Ausweis."),
 ("Geburtsurkunde", "birth certificate", "die", "Geburtsurkunden", "Die Geburtsurkunde liegt zu Hause im Ordner."),
 ("Steuernummer", "tax number", "die", "Steuernummern", "Meine Steuernummer steht auf diesem Brief."),
 ("Schalter", "counter, service desk", "der", "Schalter", "Bitte gehen Sie zum Schalter drei."),
 ("Kopie", "copy", "die", "Kopien", "Ich mache eine Kopie von meinem Ausweis."),
 ("Öffnungszeit", "opening hours", "die", "Öffnungszeiten", "Die Öffnungszeiten stehen an der Tür."),
 ("Beratung", "advice, consultation", "die", "Beratungen", "Die Beratung im Amt war sehr gut."),
 ("abgeben", "to hand in (hat abgegeben)", None, None, "Du musst das Formular am Schalter abgeben."),
 ("anmelden", "to register (something)", None, None, "Ich melde mein Auto morgen beim Amt an."),
 ("kopieren", "to copy", None, None, "Bitte kopieren Sie den Ausweis für uns."),
 ("prüfen", "to check, to examine", None, None, "Die Behörde prüft meinen Antrag noch."),
 ("gültig", "valid", None, None, "Mein Ausweis ist noch zwei Jahre gültig."),
 ("nötig", "necessary", None, None, "Für den Antrag ist ein Foto nötig."),
 ("persönlich", "in person, personal", None, None, "Sie müssen persönlich zum Amt kommen."),
],
"Travel & Holidays": [
 ("Ferienwohnung", "holiday flat", "die", "Ferienwohnungen", "Wir haben eine Ferienwohnung am Meer gebucht."),
 ("Halbpension", "half board", "die", None, "Im Hotel nehmen wir immer Halbpension."),
 ("Sonnencreme", "sunscreen", "die", "Sonnencremes", "Die Sonnencreme liegt in meiner Tasche."),
 ("Postkarte", "postcard", "die", "Postkarten", "Ich schreibe meiner Mutter eine Postkarte."),
 ("Souvenir", "souvenir", "das", "Souvenirs", "Aus Wien bringe ich dir ein Souvenir mit."),
 ("Rundfahrt", "sightseeing tour", "die", "Rundfahrten", "Die Rundfahrt durch die Stadt dauert zwei Stunden."),
 ("Wanderung", "hike", "die", "Wanderungen", "Am Sonntag machen wir eine kleine Wanderung."),
 ("Zelt", "tent", "das", "Zelte", "Unser Zelt steht direkt neben dem See."),
 ("Campingplatz", "campsite", "der", "Campingplätze", "Der Campingplatz liegt in der Nähe vom Strand."),
 ("Grenze", "border", "die", "Grenzen", "An der Grenze zeigen wir unsere Ausweise."),
 ("Ausland", "abroad", "das", None, "Meine Schwester arbeitet seit Mai im Ausland."),
 ("Flug", "flight", "der", "Flüge", "Der Flug nach Rom dauert zwei Stunden."),
 ("Bordkarte", "boarding pass", "die", "Bordkarten", "Die Bordkarte habe ich auf dem Handy."),
 ("Aussicht", "view", "die", "Aussichten", "Vom Balkon haben wir eine schöne Aussicht."),
 ("packen", "to pack", None, None, "Ich packe heute Abend meinen Koffer."),
 ("verreisen", "to go away, to travel (ist verreist)", None, None, "Im August verreisen wir für zwei Wochen."),
 ("abfliegen", "to depart (by plane) (ist abgeflogen)", None, None, "Wir fliegen am Montag um sechs Uhr ab."),
 ("landen", "to land (ist gelandet)", None, None, "Das Flugzeug landet in zwanzig Minuten."),
 ("mitnehmen", "to take along (hat mitgenommen)", None, None, "Nimm bitte deine Bordkarte mit."),
 ("erholsam", "relaxing", None, None, "Der Urlaub am Meer war sehr erholsam."),
 ("international", "international", None, None, "Der Flughafen in Frankfurt ist international."),
 ("weit", "far", None, None, "Der Weg zum Hotel ist nicht weit."),
],
"Clothing & Appearance": [
 ("Anzug", "suit", "der", "Anzüge", "Zur Hochzeit trägt mein Bruder einen Anzug."),
 ("Krawatte", "tie", "die", "Krawatten", "Die Krawatte passt gut zum Hemd."),
 ("Sandale", "sandal", "die", "Sandalen", "Im Sommer trage ich gerne Sandalen."),
 ("Unterwäsche", "underwear", "die", None, "Die Unterwäsche liegt in der oberen Schublade."),
 ("Schmuck", "jewellery", "der", None, "Meine Mutter trägt fast nie Schmuck."),
 ("Ring", "ring", "der", "Ringe", "Der Ring von meiner Oma ist alt."),
 ("Ohrring", "earring", "der", "Ohrringe", "Ich schenke ihr Ohrringe zum Geburtstag."),
 ("Brille", "glasses", "die", "Brillen", "Ohne Brille kann ich nicht gut lesen."),
 ("Frisur", "hairstyle", "die", "Frisuren", "Deine neue Frisur gefällt mir sehr gut."),
 ("Bart", "beard", "der", "Bärte", "Mein Kollege hat seit Januar einen Bart."),
 ("Kleidung", "clothing", "die", None, "Die Kleidung für den Urlaub liegt bereit."),
 ("Stoff", "fabric, material", "der", "Stoffe", "Der Stoff vom Kleid ist sehr weich."),
 ("Handtasche", "handbag", "die", "Handtaschen", "Der Schlüssel ist in meiner Handtasche."),
 ("Knopf", "button", "der", "Knöpfe", "An der Jacke fehlt ein Knopf."),
 ("bügeln", "to iron", None, None, "Am Abend bügele ich meine Hemden."),
 ("nähen", "to sew", None, None, "Meine Oma näht mir einen Rock."),
 ("aussuchen", "to pick out, to choose", None, None, "Suchen Sie bitte eine Jacke aus."),
 ("aussehen", "to look, to appear (sieht aus)", None, None, "Im blauen Kleid siehst du gut aus."),
 ("elegant", "elegant", None, None, "Der schwarze Anzug ist sehr elegant."),
 ("sportlich", "sporty, casual", None, None, "Meine neuen Schuhe sind sehr sportlich."),
 ("hübsch", "pretty", None, None, "Deine neue Bluse ist wirklich hübsch."),
 ("blond", "blond", None, None, "Meine kleine Schwester ist blond."),
],
"Family & Relationships": [
 ("Großeltern", "grandparents (Pl.)", None, None, "Meine Großeltern wohnen in einem kleinen Dorf."),
 ("Enkelkind", "grandchild", "das", "Enkelkinder", "Meine Oma hat schon vier Enkelkinder."),
 ("Schwiegertochter", "daughter-in-law", "die", "Schwiegertöchter", "Seine Schwiegertochter kommt aus Polen."),
 ("Schwiegereltern", "parents-in-law (Pl.)", None, None, "Meine Schwiegereltern besuchen uns am Wochenende."),
 ("Ehepaar", "married couple", "das", "Ehepaare", "Das Ehepaar wohnt seit zwanzig Jahren hier."),
 ("Liebe", "love", "die", None, "Die Liebe zu meiner Familie ist groß."),
 ("Scheidung", "divorce", "die", "Scheidungen", "Nach der Scheidung lebt er allein."),
 ("Rentner", "pensioner (male)", "der", "Rentner", "Mein Nachbar ist seit Januar Rentner."),
 ("Hochzeitstag", "wedding anniversary", "der", "Hochzeitstage", "Meine Eltern haben morgen Hochzeitstag."),
 ("Kindheit", "childhood", "die", None, "Meine Kindheit war sehr schön."),
 ("Partnerin", "partner (female)", "die", "Partnerinnen", "Er kommt heute mit seiner Partnerin."),
 ("Familienfeier", "family celebration", "die", "Familienfeiern", "Am Samstag ist eine große Familienfeier."),
 ("Braut", "bride", "die", "Bräute", "Die Braut trägt ein weißes Kleid."),
 ("heiraten", "to marry", None, None, "Meine Schwester heiratet im nächsten Sommer."),
 ("streiten", "to argue (hat gestritten)", None, None, "Die Kinder streiten oft über das Spielzeug."),
 ("aufwachsen", "to grow up (ist aufgewachsen)", None, None, "Ich bin in einem kleinen Dorf aufgewachsen."),
 ("sorgen", "to take care of (sorgen für + Akk)", None, None, "Meine Großeltern sorgen oft für die Enkelkinder."),
 ("aufpassen", "to look after, to watch (hat aufgepasst)", None, None, "Meine Mutter passt am Nachmittag auf die Kinder auf."),
 ("verwandt", "related", None, None, "Wir sind mit dieser Familie verwandt."),
 ("geschieden", "divorced", None, None, "Mein Onkel ist seit drei Jahren geschieden."),
 ("schwanger", "pregnant", None, None, "Meine Kollegin ist im vierten Monat schwanger."),
],
"Media & Communication": [
 ("Anruf", "phone call", "der", "Anrufe", "Ich bekomme jeden Tag viele Anrufe."),
 ("Zeitung", "newspaper", "die", "Zeitungen", "Mein Vater liest jeden Morgen die Zeitung."),
 ("Brief", "letter", "der", "Briefe", "Der Brief von der Bank kommt heute."),
 ("Briefmarke", "stamp (postage)", "die", "Briefmarken", "Für die Postkarte brauche ich eine Briefmarke."),
 ("Umschlag", "envelope", "der", "Umschläge", "Der Umschlag liegt neben dem Drucker."),
 ("Paket", "parcel, package", "das", "Pakete", "Das Paket kommt morgen mit der Post."),
 ("Serie", "series, TV show", "die", "Serien", "Diese Serie gefällt meiner Frau sehr."),
 ("Radio", "radio", "das", "Radios", "Wir hören im Auto immer Radio."),
 ("SMS", "text message", "die", "SMS", "Ich schicke dir gleich eine SMS."),
 ("Video", "video", "das", "Videos", "Mein Sohn schaut ein Video auf dem Handy."),
 ("Kamera", "camera", "die", "Kameras", "Die Kamera von meinem Handy ist gut."),
 ("Absender", "sender", "der", "Absender", "Auf dem Brief fehlt der Absender."),
 ("Empfänger", "recipient", "der", "Empfänger", "Der Empfänger wohnt nicht mehr hier."),
 ("Lautsprecher", "loudspeaker", "der", "Lautsprecher", "Der Lautsprecher im Zimmer ist sehr laut."),
 ("tippen", "to type", None, None, "Ich tippe die Nummer in mein Handy."),
 ("löschen", "to delete", None, None, "Bitte lösch die alten Fotos vom Handy."),
 ("drucken", "to print", None, None, "Kannst du mir das Formular drucken?"),
 ("senden", "to send (hat gesendet)", None, None, "Ich sende Ihnen die Rechnung per Mail."),
 ("zurückrufen", "to call back (hat zurückgerufen)", None, None, "Der Chef ruft dich später zurück."),
 ("digital", "digital", None, None, "Meine Fahrkarte ist nur digital."),
 ("kostenlos", "free of charge", None, None, "Das Internet im Hotel ist kostenlos."),
 ("telefonisch", "by phone", None, None, "Sie erreichen uns telefonisch ab acht Uhr."),
],
"Celebrations & Invitations": [
 ("Weihnachten", "Christmas (usually without article)", None, None, "An Weihnachten sind wir bei meinen Eltern."),
 ("Ostern", "Easter (usually without article)", None, None, "Zu Ostern besuchen wir meine Großeltern."),
 ("Silvester", "New Year's Eve (usually without article)", None, None, "An Silvester feiern wir bei Freunden."),
 ("Geschenk", "present, gift", "das", "Geschenke", "Das Geschenk für Oma liegt im Auto."),
 ("Torte", "cake, gateau", "die", "Torten", "Meine Mutter backt eine Torte für dich."),
 ("Kerze", "candle", "die", "Kerzen", "Auf der Torte stehen dreißig Kerzen."),
 ("Luftballon", "balloon", "der", "Luftballons", "Die Kinder bekommen alle einen Luftballon."),
 ("Blumenstrauß", "bunch of flowers", "der", "Blumensträuße", "Ich bringe der Gastgeberin einen Blumenstrauß mit."),
 ("Glückwunsch", "congratulation", "der", "Glückwünsche", "Herzlichen Glückwunsch zum Geburtstag!"),
 ("Zusage", "acceptance (of an invitation)", "die", "Zusagen", "Wir haben schon zwanzig Zusagen bekommen."),
 ("Absage", "cancellation, refusal", "die", "Absagen", "Leider bekomme ich viele Absagen."),
 ("Sekt", "sparkling wine", "der", None, "Um Mitternacht trinken wir alle Sekt."),
 ("Gastgeberin", "hostess", "die", "Gastgeberinnen", "Die Gastgeberin begrüßt alle Gäste an der Tür."),
 ("Einladungskarte", "invitation card", "die", "Einladungskarten", "Die Einladungskarte kommt morgen mit der Post."),
 ("schenken", "to give (a present)", None, None, "Ich schenke meinem Bruder ein Buch."),
 ("dekorieren", "to decorate", None, None, "Wir dekorieren das Zimmer für die Party."),
 ("einpacken", "to wrap up (hat eingepackt)", None, None, "Ich packe das Geschenk noch schnell ein."),
 ("auspacken", "to unwrap (hat ausgepackt)", None, None, "Die Kinder packen die Geschenke sofort aus."),
 ("begrüßen", "to greet, to welcome", None, None, "Der Gastgeber begrüßt uns sehr herzlich."),
 ("fröhlich", "cheerful, happy", None, None, "Auf der Feier waren alle sehr fröhlich."),
 ("herzlich", "warm, cordial", None, None, "Wir danken dir herzlich für die Einladung."),
 ("lustig", "funny, fun", None, None, "Der Abend bei euch war sehr lustig."),
],
}

rows = []
for cat, items in DATA.items():
    for german, english, article, plural, ex in items:
        rows.append({
            "german": german,
            "english": english,
            "article": article,
            "plural": plural,
            "category": cat,
            "example_sentence": ex,
            "level": "a2.1",
        })

with open(os.path.join(S, "words-a2.1-additions.json"), "w", encoding="utf-8") as fh:
    json.dump(rows, fh, ensure_ascii=False, indent=2)
    fh.write("\n")
print(len(rows), "rows")
for cat, items in DATA.items():
    print(f"  {cat}: {len(items)}")
