#!/usr/bin/env node
// Course v2 rubric compiler — the server copy of the rubric profiles (SCHEMA §4.5, §12, §13).
//
//   node scripts/course-v2/compile-rubrics.mjs            write netlify/functions/_shared/course-v2/rubrics.json
//   node scripts/course-v2/compile-rubrics.mjs --check    write nothing; exit 1 when the file is out of date
//   options:
//     --content <dir>   content root (default content/course-v2; the fixture tree is content/course-v2/fixtures)
//     --out <file>      output file (default netlify/functions/_shared/course-v2/rubrics.json)
//
// Reads every profile under <content>/registries/rubrics/{writing,speaking}/*.json and the spine
// labels of <content>/registries/grammar-spine.json, and writes ONE deterministic JSON file:
//   { $generated, profiles: { <id>: <profile as authored> }, spineLabels: { <spineId>: <label> } }
// The graders (evaluate-writing, evaluate-speaking, via netlify/functions/_shared/rubrics/data.mjs)
// read only this file; netlify.toml ships the directory with every function (included_files).
//
// Refuses (exit 1, nothing written) when a profile fails the schema check (SCH-01), its id is not
// its file name, its kind is not its directory, it names a zero/cap rule that
// netlify/functions/_shared/rubrics/rules.mjs does not define (EXM-08), or its modelId is neither
// 'deterministic', a known 'config:' alias nor a literal model id.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { checkFiles, formatResults } from './lib/checker.mjs';
import { RULES } from '../../netlify/functions/_shared/rubrics/rules.mjs';
import { MODEL_CONFIG } from '../../netlify/functions/_shared/rubrics/defaults.mjs';

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
export const GENERATED_MARK = 'generated by scripts/course-v2/compile-rubrics.mjs from content/course-v2/registries — do not edit';
export const DEFAULT_OUT = path.join(REPO_ROOT, 'netlify/functions/_shared/course-v2/rubrics.json');
const rel = (p) => path.relative(REPO_ROOT, p) || '.';

/** Compile the rubric registry under `contentRoot`. → { text, errors, count } */
export function compileRubrics(contentRoot = path.join(REPO_ROOT, 'content/course-v2')) {
  const errors = [];
  const profiles = {};
  const base = path.join(contentRoot, 'registries/rubrics');
  const files = [];
  for (const kind of ['writing', 'speaking']) {
    const dir = path.join(base, kind);
    if (!fs.existsSync(dir)) continue;
    for (const name of fs.readdirSync(dir).sort()) if (name.endsWith('.json')) files.push({ kind, file: path.join(dir, name) });
  }
  if (!files.length) errors.push(`${rel(base)}: no rubric profiles found`);

  const schema = checkFiles(files.map((f) => f.file));
  errors.push(...formatResults(schema));

  for (const { kind, file } of files) {
    let doc;
    try {
      doc = JSON.parse(fs.readFileSync(file, 'utf8'));
    } catch (e) {
      errors.push(`${rel(file)}: invalid JSON: ${e.message}`);
      continue;
    }
    const where = rel(file);
    const id = path.basename(file, '.json');
    if (doc.id !== id) errors.push(`${where}: id '${doc.id}' is not the file name '${id}'`);
    if (doc.kind !== kind) errors.push(`${where}: kind '${doc.kind}' but the file is under rubrics/${kind}/`);
    for (const r of [...(doc.zeroRules || []), ...(doc.capRules || [])]) {
      if (!RULES[r]) errors.push(`${where}: rule '${r}' is not defined in netlify/functions/_shared/rubrics/rules.mjs (EXM-08)`);
    }
    for (const r of doc.zeroRules || []) if (RULES[r] && RULES[r].kind !== 'zero') errors.push(`${where}: '${r}' is a ${RULES[r].kind} rule, listed under zeroRules`);
    for (const r of doc.capRules || []) if (RULES[r] && RULES[r].kind !== 'cap') errors.push(`${where}: '${r}' is a ${RULES[r].kind} rule, listed under capRules`);
    const m = doc.modelId;
    const deterministic = doc.method === 'deterministic';
    if (deterministic ? !(m === null || m === 'deterministic') : (typeof m !== 'string' || (m !== 'deterministic' && (m.startsWith('config:') ? !MODEL_CONFIG[m] : !/^claude-[a-z0-9-]+$/.test(m))))) {
      errors.push(`${where}: modelId '${m}' is not ${deterministic ? "null or 'deterministic' (method: deterministic)" : `'deterministic', a known config alias (${Object.keys(MODEL_CONFIG).join(', ')}) or a literal model id`}`);
    }
    if (doc.method === 'ai' && m === 'deterministic') errors.push(`${where}: method 'ai' with modelId 'deterministic'`);
    if (Number.isFinite(doc.examMax) && Number.isFinite(doc.max) && doc.examMax < doc.max) errors.push(`${where}: examMax ${doc.examMax} is below max ${doc.max}`);
    if (profiles[doc.id]) errors.push(`${where}: duplicate profile id '${doc.id}'`);
    profiles[doc.id] = doc;
  }

  const spineLabels = {};
  const spineFile = path.join(contentRoot, 'registries/grammar-spine.json');
  if (fs.existsSync(spineFile)) {
    try {
      const spine = JSON.parse(fs.readFileSync(spineFile, 'utf8'));
      for (const p of [...(spine.points || [])].sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0))) {
        if (typeof p?.id === 'string' && typeof p?.label === 'string') spineLabels[p.id] = p.label;
      }
    } catch (e) {
      errors.push(`${rel(spineFile)}: invalid JSON: ${e.message}`);
    }
  }

  const sorted = Object.fromEntries(Object.keys(profiles).sort().map((k) => [k, profiles[k]]));
  const text = `${JSON.stringify({ $generated: GENERATED_MARK, profiles: sorted, spineLabels }, null, 2)}\n`;
  return { text, errors, count: Object.keys(sorted).length };
}

function main(argv) {
  let check = false;
  let content = null;
  let out = DEFAULT_OUT;
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--check') check = true;
    else if (a === '--content' || a === '--out') {
      const v = argv[++i];
      if (!v) return usage(`${a} needs a value`);
      if (a === '--content') content = path.resolve(v);
      else out = path.resolve(v);
    } else return usage(`unknown argument ${a}`);
  }
  const { text, errors, count } = compileRubrics(content || undefined);
  if (errors.length) {
    for (const e of errors) console.log(e);
    console.log(`course-v2 compile-rubrics: ${errors.length} error(s) — nothing written`);
    return 1;
  }
  const cur = fs.existsSync(out) ? fs.readFileSync(out, 'utf8') : null;
  if (check) {
    if (cur !== text) {
      console.log(`${rel(out)}: out of date — run node scripts/course-v2/compile-rubrics.mjs`);
      return 1;
    }
    console.log(`course-v2 compile-rubrics --check: ${count} profile(s), up to date`);
    return 0;
  }
  if (cur !== text) {
    fs.mkdirSync(path.dirname(out), { recursive: true });
    fs.writeFileSync(out, text);
  }
  console.log(`course-v2 compile-rubrics: ${count} profile(s) → ${rel(out)}${cur === text ? ' (unchanged)' : ''}`);
  return 0;
}

function usage(msg) {
  if (msg) console.error(msg);
  console.error('usage: node scripts/course-v2/compile-rubrics.mjs [--check] [--content <dir>] [--out <file>]');
  return 2;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  process.exitCode = main(process.argv.slice(2));
}
