// GENERATED by scripts/build-lesson-pool.mjs — do not edit by hand.
// Source: grammar-content-cache.json (dumpedAt 2026-08-24), sub_level A1.1.
// One card per grammar topic: the course's own rule text, used by
// netlify/functions/explain-answer.mjs to ground the "Erklär mir das" answer.
// Re-run `node scripts/build-lesson-pool.mjs a1.1` after refreshing the cache.

export const RULE_CARDS = {
  "alphabet-pronunciation": {
    "titleDe": "Buchstaben die anders klingen",
    "content": "Diese Buchstaben gibt es im Englischen, aber sie klingen anders auf Deutsch.\nGerman Letter | German Sound | English Example | German Example\nW | sounds like English V | vine | Wasser (water)\nV | sounds like English F | fun | Vater (father)\nJ | sounds like English Y | yes | ja (yes)\nZ | sounds like English ts | cats | zehn (ten)\nS (before vowel) | sounds like English Z | zoo | Sonne (sun)\nR | rolled/throaty R | no English match | rot (red)\nCh | soft hissing sound | no English match | ich (I)",
    "commonMistakes": [
      {
        "wrong": "Saying W like English W",
        "correct": "Say W like English V",
        "explanationDe": "Deutsches W klingt immer wie englisches V."
      },
      {
        "wrong": "Saying Z like English Z",
        "correct": "Say Z like English ts",
        "explanationDe": "Deutsches Z klingt wie ts."
      }
    ]
  },
  "definite-articles": {
    "titleDe": "Bestimmte Artikel auf einen Blick",
    "content": "Gender | Singular | Plural | Example Singular → Plural\nMasculine | der | die | der Tisch → die Tische\nFeminine | die | die | die Lampe → die Lampen\nNeuter | das | die | das Buch → die Bücher",
    "commonMistakes": []
  },
  "indefinite-articles": {
    "titleDe": "Unbestimmte Artikel",
    "content": "ein oder eine. Maskulin und Neutrum sind gleich!\nGender | German | English | Example\nMasculine | ein | a / an | ein Mann (a man)\nFeminine | eine | a / an | eine Frau (a woman)\nNeuter | ein | a / an | ein Kind (a child)\nPlural | — (nothing) | some / — | Kinder (children)",
    "commonMistakes": [
      {
        "wrong": "Eine Mann ist hier.",
        "correct": "Ein Mann ist hier.",
        "explanationDe": "Mann = maskulin → ein."
      },
      {
        "wrong": "Ich habe ein Katze.",
        "correct": "Ich habe eine Katze.",
        "explanationDe": "Katze = feminin → eine."
      }
    ]
  },
  "nouns-gender": {
    "titleDe": "Schnelle Genus-Übersicht",
    "content": "Gender | Article | Example | Approx. % of Nouns\nMasculine | der | der Mann, der Tisch | ~40%\nFeminine | die | die Frau, die Lampe | ~35%\nNeuter | das | das Kind, das Buch | ~25%\nPlural (all) | die | die Männer, die Frauen, die Kinder | 100%",
    "commonMistakes": []
  },
  "personal-pronouns": {
    "titleDe": "Personalpronomen",
    "content": "9 Pronomen. Achtung: sie = sie (she), sie (they), Sie (formal you)!\nGerman | English | When to use\nich | I | talking about yourself\ndu | you (informal) | friends, family, children\ner | he | masculine nouns and male people\nsie | she | feminine nouns and female people\nes | it | neuter nouns\nwir | we | talking about your group\nihr | you all (informal) | group of friends/family\nsie | they | more than one person/thing\nSie | you (formal) | strangers, bosses, teachers — always capitalized!",
    "commonMistakes": [
      {
        "wrong": "Using du with your teacher",
        "correct": "Use Sie with your teacher",
        "explanationDe": "Lehrer, Chef, Fremde = immer Sie."
      },
      {
        "wrong": "Writing sie for formal you",
        "correct": "Always capitalize: Sie",
        "explanationDe": "Formelles Sie wird immer großgeschrieben."
      }
    ]
  },
  "possessive-articles": {
    "titleDe": "Possessivartikel: Alle Formen",
    "content": "Possessivartikel bekommen die gleichen Endungen wie ein: keine Endung bei der/das-Wörtern, -e bei die-Wörtern und im Plural.\nOwner | maskulin (der) | feminin (die) | neutral (das) | Plural\nich (I) | mein | meine | mein | meine\ndu (you) | dein | deine | dein | deine\ner (he) | sein | seine | sein | seine\nsie (she) | ihr | ihre | ihr | ihre\nes (it) | sein | seine | sein | seine\nwir (we) | unser | unsere | unser | unsere\nihr (you all) | euer | eure | euer | eure\nsie (they) | ihr | ihre | ihr | ihre\nSie (you, formal) | Ihr | Ihre | Ihr | Ihre",
    "commonMistakes": [
      {
        "wrong": "Das ist sein Schwester.",
        "correct": "Das ist seine Schwester.",
        "explanationDe": "Schwester ist feminin → seine. Das Geschlecht des Besitzers (er) spielt keine Rolle."
      },
      {
        "wrong": "Das ist meine Bruder.",
        "correct": "Das ist mein Bruder.",
        "explanationDe": "Bruder ist maskulin → mein, nicht meine."
      },
      {
        "wrong": "Wie ist ihr Name?",
        "correct": "Wie ist Ihr Name?",
        "explanationDe": "Zu einem Fremden: Ihr groß. Kleines ihr bedeutet her oder their."
      }
    ]
  },
  "present-tense-regular": {
    "titleDe": "Regelmäßige Verbendungen",
    "content": "Schritt 1: Infinitiv (spielen). Schritt 2: -en entfernen → spiel-. Schritt 3: Endung anhängen.\nPronoun | Ending | spielen (to play) | wohnen (to live)\nich | -e | ich spiele | ich wohne\ndu | -st | du spielst | du wohnst\ner/sie/es | -t | er spielt | er wohnt\nwir | -en | wir spielen | wir wohnen\nihr | -t | ihr spielt | ihr wohnt\nsie/Sie | -en | sie spielen | sie wohnen",
    "commonMistakes": [
      {
        "wrong": "Ich spielen Fußball.",
        "correct": "Ich spiele Fußball.",
        "explanationDe": "ich + -e. spielen ist der Infinitiv."
      },
      {
        "wrong": "Er spiele Gitarre.",
        "correct": "Er spielt Gitarre.",
        "explanationDe": "er/sie/es + -t. -e ist für ich!"
      }
    ]
  },
  "separable-verbs-intro": {
    "titleDe": "Die Satzklammer",
    "content": "Der konjugierte Stamm steht auf Position 2, das Präfix wandert ans Satzende. In einer Ja/Nein-Frage steht das konjugierte Verb an erster Stelle (kein Subjekt in Position 1), aber das Präfix bleibt trotzdem am Ende.\nPosition 1 | Konjugiertes Verb | Mitte | Präfix (Ende)\nIch | stehe | um 7 Uhr | auf\nDu | rufst | deine Mutter | an\nWir | kaufen | heute | ein\nIhr | kommt | um 8 Uhr | mit\nEr | räumt | sein Zimmer | auf\n— | Stehst | du um 7 Uhr | auf",
    "commonMistakes": [
      {
        "wrong": "Ich aufstehe um 7 Uhr.",
        "correct": "Ich stehe um 7 Uhr auf.",
        "explanationDe": "Der Infinitiv bleibt im Satz nicht zusammen — konjugiere den Stamm und schicke das Präfix ans Ende."
      },
      {
        "wrong": "Ich stehe auf um 7 Uhr.",
        "correct": "Ich stehe um 7 Uhr auf.",
        "explanationDe": "Das Präfix muss das letzte Wort sein, nach der Zeitangabe."
      },
      {
        "wrong": "Er anruft seine Mutter.",
        "correct": "Er ruft seine Mutter an.",
        "explanationDe": "Nur der Stamm wird konjugiert (ruft); das Präfix an bleibt getrennt und steht am Ende."
      }
    ]
  },
  "time-and-dates": {
    "titleDe": "Wiederholung: Zahlen 1–12 und Zehnerzahlen",
    "content": "Du kennst diese Zahlen schon — du brauchst sie jetzt für die Uhrzeit und das Datum.\nZahl | Deutsch\n1 | eins\n2 | zwei\n3 | drei\n4 | vier\n5 | fünf\n6 | sechs\n7 | sieben\n8 | acht\n9 | neun\n10 | zehn\n11 | elf\n12 | zwölf\n20 | zwanzig\n30 | dreißig\n40 | vierzig\n50 | fünfzig\n60 | sechzig\n70 | siebzig\n80 | achtzig\n90 | neunzig\n100 | hundert",
    "commonMistakes": [
      {
        "wrong": "Es ist halb drei Uhr. (gemeint: 3:30)",
        "correct": "Es ist halb drei. (= 2:30)",
        "explanationDe": "halb drei bedeutet 2:30, nicht 3:30 — halb + die NÄCHSTE Stunde."
      },
      {
        "wrong": "Der Kurs ist um Montag.",
        "correct": "Der Kurs ist am Montag.",
        "explanationDe": "Wochentage benutzen am. um ist nur für Uhrzeiten."
      },
      {
        "wrong": "Mein Geburtstag ist am fünf Mai.",
        "correct": "Mein Geburtstag ist am fünften Mai.",
        "explanationDe": "Nach am braucht das Datum die Ordnungszahl mit -en: am fünften."
      }
    ]
  },
  "verb-haben": {
    "titleDe": "Konjugation von haben",
    "content": "ich habe, wir haben, sie haben = hab-. du hast, er hat = ohne b!\nPronoun | haben | English | Example\nich | habe | have | Ich habe ein Auto.\ndu | hast | have | Du hast Recht. (You are right.)\ner/sie/es | hat | has | Er hat Hunger. (He is hungry.)\nwir | haben | have | Wir haben Zeit.\nihr | habt | have | Ihr habt Glück! (You all are lucky!)\nsie/Sie | haben | have | Sie haben zwei Kinder.",
    "commonMistakes": [
      {
        "wrong": "Ich hat einen Hund.",
        "correct": "Ich habe einen Hund.",
        "explanationDe": "ich + habe. hat = er/sie/es."
      },
      {
        "wrong": "Er habe Hunger.",
        "correct": "Er hat Hunger.",
        "explanationDe": "er + hat. habe = ich."
      }
    ]
  },
  "verb-sein": {
    "titleDe": "Konjugation von sein",
    "content": "6 verschiedene Formen. Jede Form ist anders!\nPronoun | sein | English | Example\nich | bin | am | Ich bin müde. (I am tired.)\ndu | bist | are | Du bist nett. (You are nice.)\ner/sie/es | ist | is | Er ist groß. (He is tall.)\nwir | sind | are | Wir sind hier. (We are here.)\nihr | seid | are | Ihr seid lustig. (You all are funny.)\nsie/Sie | sind | are | Sie sind freundlich. (They/You are friendly.)",
    "commonMistakes": [
      {
        "wrong": "Ich ist müde.",
        "correct": "Ich bin müde.",
        "explanationDe": "ich + bin. ist = er/sie/es."
      },
      {
        "wrong": "Du sind nett.",
        "correct": "Du bist nett.",
        "explanationDe": "du + bist. sind = wir/sie/Sie."
      }
    ]
  },
  "yes-no-questions": {
    "titleDe": "Aussage → Frage",
    "content": "Verb an Position 1, Subjekt an Position 2 — der Rest bleibt gleich.\nAussage | Ja/Nein-Frage | English\nDu bist müde. | Bist du müde? | Are you tired?\nDu hast Zeit. | Hast du Zeit? | Do you have time?\nDu kommst aus Italien. | Kommst du aus Italien? | Do you come from Italy?\nDu arbeitest viel. | Arbeitest du viel? | Do you work a lot?\nDu stehst früh auf. | Stehst du früh auf? | Do you get up early?\nSie wohnen in Berlin. | Wohnen Sie in Berlin? | Do you live in Berlin? (formal)",
    "commonMistakes": [
      {
        "wrong": "Du kommst aus Italien?",
        "correct": "Kommst du aus Italien?",
        "explanationDe": "Bei geschriebenen Fragen steht das Verb an Position 1 — nicht nur ein Fragezeichen am Satzende."
      },
      {
        "wrong": "Kommst aus Italien du?",
        "correct": "Kommst du aus Italien?",
        "explanationDe": "Das Subjekt steht direkt nach dem Verb (Position 2), nicht am Satzende."
      },
      {
        "wrong": "Sind Sie Frau Meier? — Ja, ich bin.",
        "correct": "Ja, ich bin Frau Meier.",
        "explanationDe": "Die Kurzantwort wiederholt die ganze Aussage, nicht nur Ja/Nein + Verb."
      }
    ]
  }
};

/** The card for a topic slug, or null when the topic has none. */
export function ruleCard(slug) {
  return RULE_CARDS[String(slug || '').toLowerCase()] || null;
}

/** The card as the plain text block the prompt carries. */
export function ruleCardText(slug) {
  const card = ruleCard(slug);
  if (!card) return '';
  const mistakes = (card.commonMistakes || [])
    .map((m) => `Falsch: ${m.wrong} — Richtig: ${m.correct}. ${m.explanationDe}`)
    .join('\n');
  return [`Regel: ${card.titleDe}`, card.content, mistakes].filter(Boolean).join('\n');
}
