// GENERATED by scripts/build-lesson-pool.mjs — do not edit by hand.
// Source: grammar-content-cache.json (dumpedAt 2026-08-24), sub_level(s) A1.1, A1.2.
// One card per grammar topic: the course's own rule text, used by
// netlify/functions/explain-answer.mjs to ground the "Erklär mir das" answer.
// One map for every level — a slug belongs to one sub_level, so the builder
// merges the level it runs for over the committed cards and writes both back.
// Re-run `node scripts/build-lesson-pool.mjs <level>` (a1.1, a1.2) after refreshing the cache.

export const RULE_CARDS = {
  "accusative-intro": {
    "titleDe": "Der Akkusativ: den, einen, keinen",
    "content": "Viele Verben verlangen ein Objekt im Akkusativ: brauchen, kaufen, bezahlen.\nNur maskuline Nomen ändern die Form:\nder Markt → den Markt. ein Supermarkt → einen Supermarkt. kein Park → keinen Park.\nFeminin, neutral und Plural bleiben gleich: die Quittung, das Geld, die Geschäfte.\nBeispiele: Ich brauche einen Supermarkt im Zentrum.\nIch bezahle das Kilo Brot an der Kasse. Ana kauft ein Stück Kuchen.\nDas Subjekt bleibt im Nominativ: Der Markt ist im Zentrum.\nEnglish: only masculine words change in the accusative — der becomes den, ein becomes einen.",
    "commonMistakes": [
      {
        "wrong": "Ich brauche ein Supermarkt.",
        "correct": "Ich brauche einen Supermarkt.",
        "explanationDe": "Nach brauchen steht der Akkusativ. Maskulin wird ein zu einen."
      },
      {
        "wrong": "Ana bezahlt der Kuchen.",
        "correct": "Ana bezahlt den Kuchen.",
        "explanationDe": "bezahlen verlangt den Akkusativ: der Kuchen wird den Kuchen."
      },
      {
        "wrong": "Im Zentrum brauche ich keine Park.",
        "correct": "Im Zentrum brauche ich keinen Park.",
        "explanationDe": "Auch kein bekommt im Akkusativ maskulin die Endung -en: keinen Park."
      }
    ]
  },
  "alphabet-pronunciation": {
    "titleDe": "Die Buchstabennamen und das Buchstabieren",
    "content": "Beim Buchstabieren sagt man jeden Buchstaben einzeln.\nJeder Buchstabe hat einen Namen:\nA a, B be, C ce, D de, E e, F ef, G ge, H ha, I i, J Jot, K ka, L el, M em,\nN en, O o, P pe, Q ku, R er, S es, T te, U u, V Vau, W we, X ix, Y Ypsilon, Z Zett.\nÄ a-Umlaut, Ö o-Umlaut, Ü u-Umlaut, ß Eszett.\nVorsicht: E und I, G und J, V und W haben ähnliche Namen.\nFrage: Wie schreibt man das? Antwort: A-N-A.\nBeispiele: Buchstabieren Sie bitte Chakiri. Wie buchstabiert man Ana?\nWie schreibt man Tschüss? Buchstabieren Sie Entschuldigung.\nEnglish: every German letter has its own name — say the names one by one when you spell.",
    "commonMistakes": [
      {
        "wrong": "Wie heißt der Buchstabe Z? — Zed.",
        "correct": "Wie heißt der Buchstabe Z? — Zett.",
        "explanationDe": "Der Buchstabe Z heißt Zett."
      },
      {
        "wrong": "V und W haben denselben Namen.",
        "correct": "V heißt Vau, W heißt We.",
        "explanationDe": "Zwei Buchstaben, zwei Namen. Beim Buchstabieren ist das der häufigste Fehler."
      },
      {
        "wrong": "Ich buchstabiere Tschüss: T-S-C-H-U-S-S.",
        "correct": "Ich buchstabiere Tschüss: T-S-C-H-Ü-S-S.",
        "explanationDe": "Ü ist ein eigener Buchstabe. Man sagt u-Umlaut."
      }
    ]
  },
  "basic-sentence-structure": {
    "titleDe": "Der Satz: das Verb steht auf Position 2",
    "content": "Im Aussagesatz steht das Verb auf Position 2: Sie gehen geradeaus.\nBeginnt der Satz mit einem anderen Wort, steht das Subjekt hinter dem Verb:\nDann gehen Sie links. Zuerst gehen Sie geradeaus bis zur Kirche.\nAuch in der W-Frage steht das Verb auf Position 2: Wie komme ich zum Rathaus?\nWeitere Beispiele: Die Apotheke ist rechts. Neben der Apotheke ist die Bank.\nAm Platz ist die Haltestelle. Danach kommt die Brücke.\nFeste Wendungen für den Weg: zum Rathaus, zur Kirche, an der Ecke.\nDie Regel dahinter kommt in Lektion 11.\nEnglish: the verb is the second element — if anything else opens the sentence, the subject moves behind the verb.",
    "commonMistakes": [
      {
        "wrong": "Dann Sie gehen links.",
        "correct": "Dann gehen Sie links.",
        "explanationDe": "Das Verb bleibt auf Position 2. Das Subjekt steht dahinter."
      },
      {
        "wrong": "Wie ich komme zum Rathaus?",
        "correct": "Wie komme ich zum Rathaus?",
        "explanationDe": "In der W-Frage steht das Verb direkt nach dem Fragewort."
      },
      {
        "wrong": "Die Bank neben der Apotheke ist.",
        "correct": "Die Bank ist neben der Apotheke.",
        "explanationDe": "Das Verb steht nicht am Satzende. Im Aussagesatz steht es auf Position 2."
      }
    ]
  },
  "dative-prepositions-intro": {
    "titleDe": "Präpositionen mit Dativ",
    "content": "Nach mit, nach, bei, seit, von, zu und aus steht der Dativ:\nmit dem Bus, nach dem Regen, bei der Sonne, seit einer Woche.\nMaskulin und neutral bekommen dem, feminin bekommt der: mit dem Wind, aus der Stadt.\nOft verschmelzen Präposition und Artikel:\nin dem → im Sommer. an dem → am Abend. zu der → zur Kirche. zu dem → zum Bahnhof.\nDamit sind auch die Wendungen aus Lektion 1 klar: zum Rathaus, zur Kirche.\nBeim Wetter: Seit einer Woche regnet es. Nach dem Regen ist die Sonne da.\nEnglish: these seven prepositions always take the dative, and several of them merge with the article.",
    "commonMistakes": [
      {
        "wrong": "Ich fahre mit den Bus.",
        "correct": "Ich fahre mit dem Bus.",
        "explanationDe": "Nach mit steht der Dativ: mit dem Bus, mit der Straßenbahn."
      },
      {
        "wrong": "Seit eine Woche regnet es.",
        "correct": "Seit einer Woche regnet es.",
        "explanationDe": "seit verlangt den Dativ. Feminin heißt es einer: seit einer Woche."
      },
      {
        "wrong": "Wir gehen zu dem Bahnhof.",
        "correct": "Wir gehen zum Bahnhof.",
        "explanationDe": "zu dem wird zum, zu der wird zur: zum Bahnhof, zur Kirche."
      }
    ]
  },
  "definite-articles": {
    "titleDe": "der, die, das: die Sache ist schon bekannt",
    "content": "ein und eine stehen bei einer neuen Sache.\nder, die und das zeigen: Beide wissen, welche Sache gemeint ist.\nNeu: ein Heft, eine Schere, ein Lineal.\nSchon bekannt: das Heft, die Schere, das Lineal.\nder (maskulin), die (feminin), das (neutral). Im Plural steht immer die: die Hefte, die Stifte.\nMan zeigt mit hier und da: Das Wörterbuch ist hier. Der Stift ist da.\nIst das ein Heft? — Ja, und das Heft ist grün.\nWo ist die Schere? — Die Schere ist hier.\nHier lernen Sie nur den Artikel. Die Pluralformen lernt man Wort für Wort.\nEnglish: ein/eine introduces something new; der/die/das points at the thing both speakers already mean.",
    "commonMistakes": [
      {
        "wrong": "Das ist eine Schere. Eine Schere ist hier.",
        "correct": "Das ist eine Schere. Die Schere ist hier.",
        "explanationDe": "Die Schere ist jetzt bekannt. Dann steht der bestimmte Artikel: die Schere."
      },
      {
        "wrong": "Die Stift ist blau.",
        "correct": "Der Stift ist blau.",
        "explanationDe": "der Stift ist maskulin. die steht bei femininen Nomen und im Plural."
      },
      {
        "wrong": "Wo ist Wörterbuch?",
        "correct": "Wo ist das Wörterbuch?",
        "explanationDe": "Der Artikel fällt nicht weg. Vor dem Nomen steht der, die oder das."
      }
    ]
  },
  "imperative": {
    "titleDe": "Der Imperativ: bitten und auffordern",
    "content": "Der Imperativ steht auf Position 1.\nBei Sie bleibt das Pronomen stehen: Helfen Sie bitte! Warten Sie bitte!\nDie zweite Form: ich komme, du kommst → Komm! ich warte, du wartest → Warte!\nich helfe, du hilfst → Hilf! Das Pronomen fällt weg, die Endung -st fällt mit.\nTrennbare Verben schicken die Vorsilbe ans Ende: Machen Sie den Fernseher aus!\nDas Wort bitte macht den Satz höflich.\nIm Haushalt: Holen Sie bitte den Teppich! Warten Sie kurz!\nEnglish: the imperative opens the sentence; the polite form keeps Sie, the familiar one drops the pronoun.",
    "commonMistakes": [
      {
        "wrong": "Sie helfen bitte!",
        "correct": "Helfen Sie bitte!",
        "explanationDe": "Im Imperativ steht das Verb auf Position 1, Sie direkt dahinter."
      },
      {
        "wrong": "Kommst jetzt!",
        "correct": "Komm jetzt!",
        "explanationDe": "In dieser Form fällt die Endung -st weg: Komm! Warte! Hilf!"
      },
      {
        "wrong": "Mach aus den Fernseher!",
        "correct": "Mach den Fernseher aus!",
        "explanationDe": "Die Vorsilbe aus steht ganz am Ende."
      }
    ]
  },
  "indefinite-articles": {
    "titleDe": "ein, eine, einen – und der Beruf ohne Artikel",
    "content": "Neu oder unbekannt? Dann steht ein oder eine:\nein Computer (der), ein Telefon (das), eine Pause (die).\nNach brauchen, haben und kaufen wird maskulin ein zu einen:\nIch brauche einen Computer. Die Regel dahinter (Akkusativ) kommt in A1.2.\nDer Beruf steht ohne Artikel: Ich bin Ingenieurin. Herr Weber ist Ingenieur.\nAuch in der Frage: Was sind Sie von Beruf? — Ich bin Verkäufer.\nDie Verneinung ist kein: Wir haben kein Handy. Ich habe keine Nummer.\nEnglish: German uses no article before a job — Ich bin Ingenieurin, never eine Ingenieurin.",
    "commonMistakes": [
      {
        "wrong": "Ich bin eine Verkäuferin.",
        "correct": "Ich bin Verkäuferin.",
        "explanationDe": "Nach sein steht der Beruf ohne Artikel. Richtig: Ich bin Verkäuferin."
      },
      {
        "wrong": "Ich brauche ein Computer.",
        "correct": "Ich brauche einen Computer.",
        "explanationDe": "Nach brauchen wird maskulin ein zu einen: einen Computer, einen Stuhl."
      },
      {
        "wrong": "Das ist ein Pause.",
        "correct": "Das ist eine Pause.",
        "explanationDe": "die Pause ist feminin, also eine Pause. ein steht bei der und das."
      }
    ]
  },
  "modal-verbs-intro": {
    "titleDe": "Modalverben: können, müssen, dürfen, wollen, sollen",
    "content": "Das Modalverb steht auf Position 2, das zweite Verb im Infinitiv ganz am Ende:\nHier dürfen Sie nicht fahren. Den Müll müssen Sie nach Hause nehmen.\nkönnen heißt: etwas ist möglich. müssen heißt: es ist nötig. dürfen heißt: es ist erlaubt.\nwollen und möchten heißen: man will es. sollen heißt: eine andere Person sagt es.\nIn der ich-Form und in der er-Form fehlt die Endung: ich kann, du kannst, er kann.\nAuch: ich muss, er muss. ich darf, sie darf.\nAm Bahnhof: Ich möchte ein Ticket. Wo soll ich einsteigen?\nEnglish: the modal verb is second and the plain infinitive goes to the very end.",
    "commonMistakes": [
      {
        "wrong": "Sie müssen nehmen den Müll nach Hause.",
        "correct": "Sie müssen den Müll nach Hause nehmen.",
        "explanationDe": "Der Infinitiv steht ganz am Ende des Satzes."
      },
      {
        "wrong": "Ich kann langsam fahre.",
        "correct": "Ich kann langsam fahren.",
        "explanationDe": "Nach dem Modalverb steht der Infinitiv: fahren, nehmen, laufen."
      },
      {
        "wrong": "Ich kanne nicht laufen.",
        "correct": "Ich kann nicht laufen.",
        "explanationDe": "In der ich-Form und in der er-Form fehlt die Endung: ich kann, er kann."
      }
    ]
  },
  "negation": {
    "titleDe": "nicht oder kein?",
    "content": "kein verneint ein Nomen mit unbestimmtem Artikel oder ohne Artikel:\neine Lampe → keine Lampe. ein Spiegel → kein Spiegel. Im Akkusativ: keinen Rabatt.\nnicht verneint alles andere: ein Verb, ein Adjektiv oder ein Nomen mit bestimmtem Artikel.\nDie Steckdose funktioniert nicht. Die Wand ist nicht schön.\nnicht steht am Satzende oder direkt vor dem Wort.\nIm Hotel: Im Flur ist keine Lampe und kein Spiegel.\nDie Rechnung bezahlen Sie nicht.\nEnglish: kein negates a noun that has ein or no article; nicht negates everything else.",
    "commonMistakes": [
      {
        "wrong": "Im Flur ist nicht eine Lampe.",
        "correct": "Im Flur ist keine Lampe.",
        "explanationDe": "Ein Nomen mit unbestimmtem Artikel verneint man mit kein: keine Lampe."
      },
      {
        "wrong": "Die Steckdose funktioniert kein.",
        "correct": "Die Steckdose funktioniert nicht.",
        "explanationDe": "Ein Verb verneint man immer mit nicht."
      },
      {
        "wrong": "Ich habe nicht einen Rabatt.",
        "correct": "Ich habe keinen Rabatt.",
        "explanationDe": "Im Akkusativ heißt es keinen Rabatt: maskulin bekommt die Endung -en."
      }
    ]
  },
  "nominative-case": {
    "titleDe": "Der Nominativ: wer oder was?",
    "content": "Das Subjekt eines Satzes steht im Nominativ.\nMan findet es mit wer (Person) oder was (Sache):\nWer ist das? — Mein Onkel ist groß. Was ist das? — Das Bild ist alt.\nNach sein steht das zweite Nomen auch im Nominativ: Das ist mein Bruder.\nDie Artikel im Nominativ: der Opa, die Oma, das Kind, im Plural die Kinder.\nSein Bein ist lang. Ihre Nase ist klein.\nMeine Tante ist glücklich. Die Frau da hat lange Haare.\nEnglish: the subject stands in the nominative, and so does the noun after sein.",
    "commonMistakes": [
      {
        "wrong": "Das ist meinen Bruder.",
        "correct": "Das ist mein Bruder.",
        "explanationDe": "Nach sein steht der Nominativ: Das ist mein Bruder."
      },
      {
        "wrong": "Was ist die Frau da?",
        "correct": "Wer ist die Frau da?",
        "explanationDe": "wer fragt nach einer Person, was nach einer Sache."
      },
      {
        "wrong": "Mein Oma ist alt.",
        "correct": "Meine Oma ist alt.",
        "explanationDe": "die Oma ist feminin. Im Nominativ heißt es meine Oma."
      }
    ]
  },
  "nouns-gender": {
    "titleDe": "Genus: der, die, das — und die Endungen, die helfen",
    "content": "Jedes Nomen hat ein Genus: der, die oder das. Im Plural steht immer die.\nDiese Endungen zeigen das Genus:\n-ung, -heit, -keit, -schaft → die: die Entschuldigung, die Freiheit, die Möglichkeit, die Freundschaft.\n-chen, -lein → das: das Mädchen, das Brötchen.\n-er bei männlichen Berufsnamen → der: der Lehrer. Vorsicht: die Mutter, die Schwester, die Tochter.\nHat ein Nomen keine dieser Endungen, dann lernt man den Artikel einfach mit.\nLernen Sie jedes Nomen mit dem Artikel: nicht Tisch, sondern der Tisch.\nEnglish: learn every noun together with its article; the endings above are reliable groups, not a complete system.",
    "commonMistakes": [
      {
        "wrong": "das Entschuldigung",
        "correct": "die Entschuldigung",
        "explanationDe": "Nomen auf -ung sind die-Wörter."
      },
      {
        "wrong": "die Mädchen ist jung.",
        "correct": "Das Mädchen ist jung.",
        "explanationDe": "Nomen auf -chen sind das-Wörter, auch bei Personen."
      },
      {
        "wrong": "die Lehrer kauft den Stuhl.",
        "correct": "Der Lehrer kauft den Stuhl.",
        "explanationDe": "Männliche Berufsnamen auf -er sind der-Wörter. Die Frau ist die Lehrerin. In der Familie gilt das nicht: die Mutter, die Schwester."
      }
    ]
  },
  "numbers-counting": {
    "titleDe": "Zahlen ab 20 und die Ordnungszahlen",
    "content": "Zahlen über 20 liest man von hinten nach vorn:\n21 ist einundzwanzig, 48 ist achtundvierzig, 65 ist fünfundsechzig.\nZwischen beiden steht und. Man schreibt alles in einem Wort.\n480 ist vierhundertachtzig: zuerst 400, dann 80.\nDie Ordnungszahl bekommt bis 19 die Endung -te: das dritte Stockwerk, die erste Wohnung.\nAb 20 heißt die Endung -ste: der zwanzigste Mai.\nIn der Anzeige: Die Miete ist 480 Euro im Monat. Der Keller kostet 20 Euro.\nEnglish: numbers above twenty are read back to front — einundzwanzig is one-and-twenty.",
    "commonMistakes": [
      {
        "wrong": "Die Wohnung kostet achtvierzig Euro.",
        "correct": "Die Wohnung kostet achtundvierzig Euro.",
        "explanationDe": "Zwischen beiden steht und: achtundvierzig, einundzwanzig."
      },
      {
        "wrong": "Das drei Stockwerk ist frei.",
        "correct": "Das dritte Stockwerk ist frei.",
        "explanationDe": "Die Ordnungszahl bekommt die Endung -te: das dritte Stockwerk, die erste Wohnung."
      },
      {
        "wrong": "der zwanzigte Mai",
        "correct": "der zwanzigste Mai",
        "explanationDe": "Ab 20 heißt die Endung -ste: der zwanzigste Mai."
      }
    ]
  },
  "perfekt-intro": {
    "titleDe": "Das Perfekt: haben und Partizip II",
    "content": "Was gestern war, steht im Perfekt: haben steht auf Position 2, das Partizip II ganz am Ende.\nRegelmäßig entsteht das Partizip mit ge- und -t:\nfeiern → gefeiert. kaufen → gekauft. kochen → gekocht. machen → gemacht.\nUnregelmäßig endet es auf -en: essen → gegessen, trinken → getrunken.\nDiese Formen lernt man Wort für Wort.\nBeim Fest: Wir haben gestern gefeiert. Ich habe Milch getrunken.\nAna hat den Kuchen gekauft. Tim hat den Fisch gekocht.\nwar ist die einzige einfache Vergangenheitsform in diesem Kurs: Der Käse war lecker.\nEnglish: haben in second position, and the participle at the very end of the sentence.",
    "commonMistakes": [
      {
        "wrong": "Ich habe gegessen Kuchen.",
        "correct": "Ich habe Kuchen gegessen.",
        "explanationDe": "Das Partizip II steht ganz am Ende des Satzes."
      },
      {
        "wrong": "Ana hat den Fisch kocht.",
        "correct": "Ana hat den Fisch gekocht.",
        "explanationDe": "Das regelmäßige Partizip beginnt mit ge-: gekocht, gekauft, gefeiert."
      },
      {
        "wrong": "Ich bin Kuchen gegessen.",
        "correct": "Ich habe Kuchen gegessen.",
        "explanationDe": "Das Perfekt in diesem Kurs steht immer mit haben."
      }
    ]
  },
  "personal-pronouns": {
    "titleDe": "er, sie, es – und die Formen für mehrere Personen",
    "content": "Das Pronomen richtet sich nach dem Artikel des Nomens, nicht nach der Bedeutung.\nder Vater → er. der Bruder → er.\ndie Mutter → sie. die Schwester → sie.\ndas Kind → es. das Baby → es.\nMehrere Personen: wir (meine Familie und ich), ihr (mehrere Personen zusammen), sie (die Eltern).\nSie mit großem S ist die höfliche Form: Woher kommen Sie, Frau Chakiri?\nBeispiele: Wie alt ist er? — Er ist zwanzig. Meine Schwester ist jung. Sie spricht Arabisch.\nEnglish: the pronoun follows the article of the noun — das Kind is always es.",
    "commonMistakes": [
      {
        "wrong": "Das Kind ist jung. Er ist zwei.",
        "correct": "Das Kind ist jung. Es ist zwei.",
        "explanationDe": "das Kind → es. Das Genus entscheidet, nicht die Person."
      },
      {
        "wrong": "Die Mutter kommt aus Marokko. Es spricht Arabisch.",
        "correct": "Die Mutter kommt aus Marokko. Sie spricht Arabisch.",
        "explanationDe": "die Mutter → sie. Auch die Schwester und die Tochter bekommen sie."
      },
      {
        "wrong": "Woher kommen sie, Frau Weber?",
        "correct": "Woher kommen Sie, Frau Weber?",
        "explanationDe": "Die höfliche Anrede schreibt man immer mit großem S."
      }
    ]
  },
  "possessive-articles": {
    "titleDe": "Possessivartikel: mein, sein, ihr und Ihr",
    "content": "Der Possessivartikel zeigt, wem etwas gehört.\nBeispiele: mein Geschenk (ich), dein Bruder (du), sein Handy (er), ihr Buch (sie).\nFür Gruppen: unser Fest (wir), euer Fest (ihr).\nVor femininen Nomen und im Plural kommt -e dazu: meine Mama, unsere Gäste, eure Karten.\nDie höfliche Form ist Ihr und steht immer mit großem I: Ist das Ihr Geschenk, Frau Kaya?\nBeim Fest: Meine Mama kommt. Mein Papa bringt Kuchen mit. Unsere Party ist am Freitag.\nEnglish: the polite form Ihr always takes a capital I, also inside a sentence.",
    "commonMistakes": [
      {
        "wrong": "Das ist mein Mama.",
        "correct": "Das ist meine Mama.",
        "explanationDe": "Vor femininen Nomen kommt -e dazu: meine Mama, meine Schwester, meine Karte."
      },
      {
        "wrong": "Ist das ihr Geschenk, Frau Kaya?",
        "correct": "Ist das Ihr Geschenk, Frau Kaya?",
        "explanationDe": "Die höfliche Form schreibt man immer mit großem I: Ihr Geschenk, Ihr Büro."
      },
      {
        "wrong": "Wir feiern unsere Fest.",
        "correct": "Wir feiern unser Fest.",
        "explanationDe": "das Fest ist neutral, also unser Fest. Das -e steht nur vor femininen Nomen und im Plural."
      }
    ]
  },
  "prepositions-accusative": {
    "titleDe": "Präpositionen mit Akkusativ",
    "content": "Nach für, ohne, gegen, um und durch steht immer der Akkusativ.\nNur maskulin ändert die Form: der Mantel → für den Mantel.\nein Pullover → für einen Pullover. der Schal → ohne den Schal.\nFeminin, neutral und Plural bleiben gleich: für die Mütze, ohne das Hemd, für die Schuhe.\nWeitere Beispiele: Ich gehe durch das Kaufhaus. Der Bus fährt um den Platz.\nBeim Vergleich hilft als: Die Mütze ist billiger als der Schal.\nDas Kleid ist teurer. Unregelmäßig: groß → größer, gut → besser.\nEnglish: für, ohne, gegen, um and durch always take the accusative.",
    "commonMistakes": [
      {
        "wrong": "Der Mantel ist für mein Bruder.",
        "correct": "Der Mantel ist für meinen Bruder.",
        "explanationDe": "Nach für steht der Akkusativ: für meinen Bruder, für einen Bruder."
      },
      {
        "wrong": "Ich gehe ohne der Schal.",
        "correct": "Ich gehe ohne den Schal.",
        "explanationDe": "ohne verlangt den Akkusativ: der Schal wird den Schal."
      },
      {
        "wrong": "Die Mütze ist billiger wie der Schal.",
        "correct": "Die Mütze ist billiger als der Schal.",
        "explanationDe": "Beim Vergleich steht als: billiger als der Schal, größer als das Kleid."
      }
    ]
  },
  "present-tense-regular": {
    "titleDe": "Präsens: die Endungen und zwei Sonderfälle",
    "content": "Regelmäßige Verben: Stamm plus Endung. spielen ohne -en ergibt den Stamm spiel-.\nich spiele, du spielst, er/sie/es spielt, wir spielen, ihr spielt, sie/Sie spielen.\nSo auch: hören, kochen, tanzen, lernen, wohnen, schwimmen.\nEndet der Stamm auf -t oder -d, kommt ein e dazu: ich arbeite, du arbeitest, er arbeitet.\nZwei Verben wechseln den Vokal: ich spreche, du sprichst, er spricht.\nUnd: ich fahre, du fährst, er fährt.\ngern steht nach dem Verb: Ich höre gern Musik. Ich spiele gern Fußball.\nEnglish: add the ending to the stem; stems on -t or -d take an extra e (arbeitest).",
    "commonMistakes": [
      {
        "wrong": "Ich spielen Fußball.",
        "correct": "Ich spiele Fußball.",
        "explanationDe": "Nach ich steht die Endung -e. spielen ist der Infinitiv."
      },
      {
        "wrong": "Er arbeitt im Büro.",
        "correct": "Er arbeitet im Büro.",
        "explanationDe": "Der Stamm arbeit- endet auf -t. Dann kommt ein e dazu: er arbeitet."
      },
      {
        "wrong": "Er sprecht Arabisch.",
        "correct": "Er spricht Arabisch.",
        "explanationDe": "sprechen wechselt den Vokal: er spricht. Genauso: er fährt."
      }
    ]
  },
  "question-words": {
    "titleDe": "W-Fragen: das Fragewort steht vorn",
    "content": "In der W-Frage steht das Fragewort auf Position 1, das Verb direkt dahinter:\nWann fährt der Zug? Wohin fahren wir? Wie oft kommt der Bus?\nwer fragt nach der Person, was nach der Sache, wo nach dem Ort,\nwohin nach der Richtung, warum nach dem Grund, wie lange nach der Dauer.\nWeitere Beispiele: Wann ist das Konzert? Wie lange dauert der Ausflug?\nDie Antwort ist ein ganzer Satz: Der Zug fährt um acht Uhr.\nEnglish: the question word comes first and the verb second — Wann fährt der Zug?",
    "commonMistakes": [
      {
        "wrong": "Wann der Zug fährt?",
        "correct": "Wann fährt der Zug?",
        "explanationDe": "Nach dem Fragewort steht sofort das Verb, danach das Subjekt."
      },
      {
        "wrong": "Wo fahren wir am Wochenende?",
        "correct": "Wohin fahren wir am Wochenende?",
        "explanationDe": "wo fragt nach dem Ort, wohin nach der Richtung."
      },
      {
        "wrong": "Was fährt der Bus?",
        "correct": "Wie oft fährt der Bus?",
        "explanationDe": "was fragt nach der Sache. Nach dem Fahrplan fragt man mit wie oft."
      }
    ]
  },
  "separable-verbs-intro": {
    "titleDe": "Trennbare Verben: die Satzklammer",
    "content": "Trennbare Verben teilen sich im Satz: das Verb steht auf Position 2, die Vorsilbe ganz am Ende.\nein|kaufen: Ich kaufe am Freitag ein.\nauf|stehen: Ich stehe um sechs auf.\nan|rufen: Ich rufe meine Mutter an.\nmit|bringen: Ich bringe Kuchen mit.\nab|holen: Ich hole meine Kollegin ab.\nIn der Frage steht das Verb vorn, die Vorsilbe bleibt am Ende: Kaufen Sie heute ein?\nEnglish: a separable verb splits — the finite part comes second, the prefix goes last.",
    "commonMistakes": [
      {
        "wrong": "Ich einkaufe am Freitag.",
        "correct": "Ich kaufe am Freitag ein.",
        "explanationDe": "Die Vorsilbe ein bleibt nicht am Verb. Sie steht am Satzende."
      },
      {
        "wrong": "Ich stehe auf um sechs.",
        "correct": "Ich stehe um sechs auf.",
        "explanationDe": "Die Vorsilbe auf steht ganz am Ende, nach der Uhrzeit."
      },
      {
        "wrong": "Rufen Sie mich morgen?",
        "correct": "Rufen Sie mich morgen an?",
        "explanationDe": "Ohne die Vorsilbe an fehlt das halbe Verb: anrufen braucht an am Ende."
      }
    ]
  },
  "stem-changing-verbs": {
    "titleDe": "Verben mit Vokalwechsel",
    "content": "Einige Verben ändern im Präsens den Stammvokal.\nDer Wechsel steht nur in zwei Formen: ich nehme, du nimmst, er nimmt, wir nehmen.\nSo auch: helfen → sie hilft. sehen → er sieht.\nschlafen → er schläft. essen → sie isst. sprechen → er spricht.\nBei ich, wir, ihr und Sie bleibt der Vokal: ich helfe, wir helfen, Sie schlafen.\nIn der Praxis: Die Tablette hilft gegen Kopfschmerzen.\nAna nimmt die Tablette am Abend. Ihr Auge sieht gut.\nEnglish: the vowel changes in exactly two forms of the present tense, nowhere else.",
    "commonMistakes": [
      {
        "wrong": "Er nehmt eine Tablette.",
        "correct": "Er nimmt eine Tablette.",
        "explanationDe": "nehmen wechselt den Vokal: er nimmt, sie nimmt."
      },
      {
        "wrong": "Ich nimme die Tablette am Morgen.",
        "correct": "Ich nehme die Tablette am Morgen.",
        "explanationDe": "Bei ich bleibt der Vokal: ich nehme, wir nehmen."
      },
      {
        "wrong": "Die Tablette helft gegen Fieber.",
        "correct": "Die Tablette hilft gegen Fieber.",
        "explanationDe": "helfen wechselt zu hilft. Genauso: er sieht, er schläft."
      }
    ]
  },
  "time-and-dates": {
    "titleDe": "Die Uhrzeit: offiziell und im Alltag",
    "content": "Offiziell sagt man die Stunde und die Minuten: 8:30 ist acht Uhr dreißig, 14:15 ist vierzehn Uhr fünfzehn.\nUmgangssprachlich sagt man: halb neun ist 8:30, Viertel nach acht ist 8:15, Viertel vor neun ist 8:45.\nhalb nimmt die nächste Stunde. halb neun liegt also vor neun Uhr.\num steht vor der Uhrzeit: Der Termin ist um acht Uhr.\nam steht vor Tagen und Tageszeiten: am Montag, am Morgen, am Abend.\nim steht vor Monaten: im Mai.\nDas Datum mit Ordnungszahlen kommt erst in A1.2. Hier lernen Sie nur die Uhrzeit und die Tage.\nEnglish: um for clock times, am for days and parts of the day, im for months.",
    "commonMistakes": [
      {
        "wrong": "halb neun ist 9:30.",
        "correct": "halb neun = 8:30, nicht 9:30.",
        "explanationDe": "halb nimmt die nächste Stunde: halb neun liegt eine halbe Stunde vor neun Uhr."
      },
      {
        "wrong": "Der Termin ist um Montag.",
        "correct": "Der Termin ist am Montag.",
        "explanationDe": "um Montag → am Montag. um steht nur vor der Uhrzeit, am vor Tagen und Tageszeiten."
      },
      {
        "wrong": "Der Termin ist am Mai.",
        "correct": "Der Termin ist im Mai.",
        "explanationDe": "Monate bekommen im, Tage bekommen am."
      }
    ]
  },
  "verb-haben": {
    "titleDe": "haben: Hunger, Durst und Zeit",
    "content": "haben ist unregelmäßig. Diese sechs Formen sind fest:\nich habe, du hast, er/sie/es hat, wir haben, ihr habt, sie/Sie haben.\nMit haben sagt man Hunger, Durst und Zeit — und zwar ohne Artikel:\nIch habe Hunger. Ich habe Durst. Haben Sie Zeit?\nIm Café: Wir haben Suppe, Salat und Kuchen. Die Kellnerin hat Zeit.\nIn der Frage steht haben vorn: Haben Sie auch Hunger? — Ja, ich habe Hunger.\nMan bestellt so: Ich möchte einen Kaffee, bitte.\nEnglish: German has hunger and thirst rather than being hungry — Ich habe Hunger.",
    "commonMistakes": [
      {
        "wrong": "Ich bin Hunger.",
        "correct": "Ich habe Hunger.",
        "explanationDe": "Hunger, Durst und Zeit kommen mit haben, nicht mit sein."
      },
      {
        "wrong": "Er habe Durst.",
        "correct": "Er hat Durst.",
        "explanationDe": "er, sie und es bekommen hat. habe gehört zu ich."
      },
      {
        "wrong": "Ich habe einen Hunger.",
        "correct": "Ich habe Hunger.",
        "explanationDe": "Nach haben stehen Hunger, Durst und Zeit ohne Artikel."
      }
    ]
  },
  "verb-sein": {
    "titleDe": "sein: ich bin, du bist, Sie sind",
    "content": "sein ist unregelmäßig. Man lernt die sechs Formen auswendig:\nich bin, du bist, er/sie/es ist, wir sind, ihr seid, sie/Sie sind.\nDer Beruf: Was sind Sie von Beruf? — Ich bin Studentin. Herr Weber ist Lehrer.\nNach sein steht der Beruf ohne Artikel: Ich bin Lehrerin. Nicht: Ich bin eine Lehrerin.\nWoher sind Sie? — Ich bin aus Marokko. Wir sind aus Marokko.\nDer Wohnort: Ich bin in Bremen. Ana ist in Bremen.\nIn der Frage steht sein vorn: Sind Sie Frau Chakiri? — Ja, ich bin Frau Chakiri.\nEnglish: sein is irregular — learn the six forms as whole words, not from a stem.",
    "commonMistakes": [
      {
        "wrong": "Ich bin ein Lehrer.",
        "correct": "Ich bin Lehrer.",
        "explanationDe": "Nach sein steht der Beruf ohne Artikel. Richtig: Ich bin Lehrer."
      },
      {
        "wrong": "Ana bin Studentin.",
        "correct": "Ana ist Studentin.",
        "explanationDe": "bin gehört zu ich. Für eine Person steht ist: Ana ist Studentin."
      },
      {
        "wrong": "Wie sind Sie von Beruf?",
        "correct": "Was sind Sie von Beruf?",
        "explanationDe": "Die feste Frage lautet: Was sind Sie von Beruf?"
      }
    ]
  },
  "yes-no-questions": {
    "titleDe": "Aussage → Ja/Nein-Frage",
    "content": "In der geschriebenen Ja/Nein-Frage steht das Verb auf Platz 1, das Subjekt direkt danach. Alles andere bleibt gleich.\nDer Zug fährt pünktlich. → Fährt der Zug pünktlich?\nSie haben eine Fahrkarte. → Haben Sie eine Fahrkarte?\nSie kommen aus Österreich. → Kommen Sie aus Österreich?\nDer Bus fährt in die Schweiz. → Fährt der Bus in die Schweiz?\nSie stehen früh auf. → Stehen Sie früh auf? Die Vorsilbe bleibt am Ende.\nAntworten Sie mit einem ganzen Satz: Ja, ich bin pünktlich. Nein, ich habe keine Zeit.\nEnglish: in a written yes/no question the verb comes first and the subject second.",
    "commonMistakes": [
      {
        "wrong": "Sie kommen aus Österreich?",
        "correct": "Kommen Sie aus Österreich?",
        "explanationDe": "In der geschriebenen Frage steht das Verb auf Platz 1. Gesprochen gibt es auch die Frage mit gleicher Wortfolge und steigender Stimme; in Übungen schreibt man die Frage mit dem Verb auf Platz 1."
      },
      {
        "wrong": "Kommen aus Österreich Sie?",
        "correct": "Kommen Sie aus Österreich?",
        "explanationDe": "Das Subjekt steht direkt nach dem Verb, nicht am Satzende."
      },
      {
        "wrong": "Sind Sie Frau Meier? — Ja, ich bin.",
        "correct": "Ja, ich bin Frau Meier.",
        "explanationDe": "Die Kurzantwort wiederholt die ganze Aussage, nicht nur Ja plus Verb."
      }
    ]
  }
};

/** The levels whose topics have been generated into the map above. */
export const RULE_CARD_LEVELS = ["a1.1","a1.2"];

/** The card for a topic slug, or null when the topic has none. */
export function ruleCard(slug) {
  return RULE_CARDS[String(slug || '').toLowerCase()] || null;
}

/** The card as the plain text block the prompt carries. */
export function ruleCardText(slug) {
  const card = ruleCard(slug);
  if (!card) return '';
  const mistakes = (card.commonMistakes || [])
    .map((m) => `Falsch: ${m.wrong} — Richtig: ${m.correct}. ${m.explanationDe}`)
    .join('\n');
  return [`Regel: ${card.titleDe}`, card.content, mistakes].filter(Boolean).join('\n');
}
